### ISSUE TITLE
add TMOUT=600 ? 

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#1011]
per RHEL-07-040160  SRG-OS-000163-GPOS-00072

**Comment by redhatrises** [comment]
Looks like this XCCDF/OVAL exists. Closing.

**Comment by aradcliff** [comment]
I downloaded/applied scap-security-guide 0.1.31 to my CentOS 7 (7.2.1511) system.  The "accounts_tmout" rule adds the following to /etc/profile:

      `TMOUT = 600`

This throws an error and does not actually set $TMOUT.  Should this perhaps be changed to:

      `export TMOUT=600`

?

**Comment by shawndwells** [comment]
@aradcliff - yes

from the remediation script I'm not sure where the space is being added:
(RHEL/7/templates/static/bash/accounts_tmout.sh)

`````
# platform = Red Hat Enterprise Linux 7
. /usr/share/scap-security-guide/remediation_functions
populate var_accounts_tmout

if grep --silent ^TMOUT /etc/profile ; then
        sed -i "s/^TMOUT.*/TMOUT=$var_accounts_tmout/g" /etc/profile
else
        echo -e "\n# Set TMOUT to $var_accounts_tmout per security requirements" >> /etc/profile
        echo "TMOUT=$var_accounts_tmout" >> /etc/profile
fi
`````

**Comment by redhatrises** [comment]
Actually, there is no need to have the export. This was already fixed in master. See https://github.com/OpenSCAP/scap-security-guide/commit/8c15c9ded7af82b275bccf3861b02a5e4ad6b161

The issue was the spaces in between the equals sign. So setting `TMOUT = 600` to `TMOUT=600` will work.
