### ISSUE TITLE
create DDoS  --limit-burst  rule? 

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#1018]
per RHEL-07-040250  SRG-OS-000420-GPOS-00186

**Comment by redhatrises** [comment]
`RHEL-07-040250` has been removed from the latest STIG iteration. Closing.

**Comment by redhatrises** [comment]
Re-opening. This is actually now `RHEL-07-040510`

**Comment by redhatrises** [comment]
Closing in favor of #1854
