### ISSUE TITLE
audit use of "write" command? 

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#1021]
per RHEL-07-030600	SRG-OS-000471-GPOS-00215

Configure the host to generate audit records for terminal communications. Add or update the following rules in /etc/audit/audit.rules: -a always,exit -F path=/usr/libexec/pt_chown -F perm=x -F auid>=500 -F auid!=4294967295 -k privileged_terminal -a always,exit -F path=/usr/bin/write -F perm=x -F auid>=500 -F auid!=4294967295 -k privileged-terminal-write The audit daemon must be restarted for the changes to take effect.

**Comment by redhatrises** [comment]
Current STIG draft no longer has this rule to audit `/usr/bin/write`. Closing.
