### ISSUE TITLE
False positive with bootloader_password

### ISSUE THREAD

**Issue by pkbarbiedoll** [OpenSCAP/scap-security-guide#1024]
**Summary**:
Bootloader password is set and works when attempting to edit kernel paremeters on boot. Entering the incorrect password disallows access to edit options.

**OS**: 

```
cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.2 (Maipo)
(minimal install)
```

**OpenSCAP**:

```
Name        : openscap
Arch        : x86_64
Version     : 1.2.5
Release     : 3.el7
Size        : 49 M
Repo        : installed
From repo   : rhel-7-server-rpms
```

**SCAP Security Guide**:

```
Name        : scap-security-guide
Arch        : noarch
Version     : 0.1.25
Release     : 3.el7
Size        : 11 M
Repo        : installed
From repo   : rhel-7-server-rpms

```

**grub2.cfg:**

```
### BEGIN /etc/grub.d/01_users ###
if [ -f ${prefix}/user.cfg ]; then
  source ${prefix}/user.cfg
  if [ -n "${GRUB2_PASSWORD}" ]; then
    set superusers="root"
    export superusers
    password_pbkdf2 root ${GRUB2_PASSWORD}
  fi
fi
set superusers="someuser"
password_pbkdf2 someuser grub.pbkdf2.sha512.10000.5733A57BDE228186691A6F856A1E99C7C69583BB8A49DF86EB312BD030749D9F1BCD64E52267C1A4D0D0C22A11B31DDFAD5B114BE6D871DDC89AC51A090FF58A.EBA411FBCF950049FC752185F6DC62F0E85E97F697FFFF1A241099D259C87E1956809FB0083CD62DEC1526F340865A44F99A834C5A629F4C3B7F54B1FD616341
### END /etc/grub.d/01_users ###

### BEGIN /etc/grub.d/40_custom ###
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry 'Linux password protected' --users someuser {
set root=(hd0,msdos1)
linux   /vmlinuz
}
### END /etc/grub.d/40_custom ###

```

**Command used to generate report:**
`oscap oval eval --results $file_xml --report $file_html /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml`

**Results:**

> oval:ssg:def:475  **false**   compliance  [20140909], [**bootloader_password**]   **Set Boot Loader Password

**Expected Result:**

> oval:ssg:def:475  **true**    compliance  [20140909], [**bootloader_password**]   **Set Boot Loader Password

**Comment by iankko** [comment]
Ditto. Will try to reproduce this one too. Thanks!

**Comment by alsifius** [comment]
I am currently running into this problem on RHEL 7.2, version 0.1.30 of the scap-security-guide. Has there been any moment on this?

**Comment by redhatrises** [comment]
This is most likely because `superuser="root"` exists. The OVAL checks that root, admin, or administrator are not used as bootloader users.

**Comment by iankko** [comment]
Just to clarify, the report is right in the sense scanning of this rule will return ```false``` in the default configuration of ```/boot/grub2/grub.cfg```configuration file on Red Hat Enterprise Linux 7 Update 2 (verified by testing).

But regarding the ```false positive``` point - the result isn't false positive. It's actual finding (see ```Set Boot Loader Password``` rule description e.g. in:
* http://static.open-scap.org/ssg-guides/ssg-rhel7-guide-C2S.html
for further details), there's written:

```To meet FISMA Moderate, the bootloader superuser account and password MUST differ from the root account and password. ```

Thus like Gabe suggests above, one of the pre-requisities for this rule to pass is to remove the entries for the ```root``` user from the snippet of configuration file above. Though the change would help, it might not be sufficient by itself (wasn't at least AFAICT from quick testing).

Rather to change / modify the OVAL check, the proper solution here IMHO is to provide a remediation script (doesn't seem to be available yet AFAICT) which would correct the not-compliant default configuration, so subsequent check would pass.

HTH, Jan

**Comment by redhatrises** [comment]
@pkbarbiedoll is this still an issue for you?

**Comment by redhatrises** [comment]
Closing as there has been no movement on this for a while.
