### ISSUE TITLE
False positive with audit_rules_file_deletion_events

### ISSUE THREAD

**Issue by pkbarbiedoll** [OpenSCAP/scap-security-guide#1029]
**Summary**:
Deletion events are configured in `/etc/audit/rules.d/audit.rules`

**OS**: 

```
cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.2 (Maipo)
(minimal install)
```

**OpenSCAP**:

```
Name        : openscap
Arch        : x86_64
Version     : 1.2.5
Release     : 3.el7
Size        : 49 M
Repo        : installed
From repo   : rhel-7-server-rpms
```

**SCAP Security Guide**:

```
Name        : scap-security-guide
Arch        : noarch
Version     : 0.1.25
Release     : 3.el7
Size        : 11 M
Repo        : installed
From repo   : rhel-7-server-rpms

```

**included in /etc/audit/rules.d/audit.rules:**

```
# audit_rules_file_deletion_events
-a always,exit -F arch=b32 -S rmdir -S unlink -S unlinkat -S rename -S renameat -F auid>=1000 -F auid!=4294967295 -k delete
-a always,exit -F arch=b64 -S rmdir -S unlink -S unlinkat -S rename -S renameat -F auid>=1000 -F auid!=4294967295 -k delete
```

**Command used to generate report:**
`oscap oval eval --results $file_xml --report $file_html /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml`

**Results:**

> oval:ssg:def:188  **false**   compliance  [RHEL7_20150326], [FEDORA20_20150326], [**audit_rules_file_deletion_events**]   **Audit File Deletion Even**

**Expected Results:**

> oval:ssg:def:188  **true**    compliance  [RHEL7_20150326], [FEDORA20_20150326], [audit_rules_file_deletion_events]   Audit File Deletion Even

**Comment by shawndwells** [comment]
resolved around 66f76d61
