### ISSUE TITLE
False positive with auditd_data_retention_num_logs

### ISSUE THREAD

**Issue by pkbarbiedoll** [OpenSCAP/scap-security-guide#1030]
**Summary**:
num_logs is set to 6 in `/etc/audit/auditd.conf` (auditd restarted before re-running oscap)

**OS**: 

```
cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.2 (Maipo)
(minimal install)
```

**OpenSCAP**:

```
Name        : openscap
Arch        : x86_64
Version     : 1.2.5
Release     : 3.el7
Size        : 49 M
Repo        : installed
From repo   : rhel-7-server-rpms
```

**SCAP Security Guide**:

```
Name        : scap-security-guide
Arch        : noarch
Version     : 0.1.25
Release     : 3.el7
Size        : 11 M
Repo        : installed
From repo   : rhel-7-server-rpms

```

**/etc/audit/auditd.conf**

```
num_logs = 6
```

**Command used to generate report:**
`oscap oval eval --results $file_xml --report $file_html /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml`

**Results:**

> oval:ssg:def:738  **error**   compliance  [RHEL6_20150812], [RHEL7_20150812], [FEDORA22_20150812], [**auditd_data_retention_num_logs**]   Auditd Maximum Number of Logs to Retain

**Expected Results:**

> oval:ssg:def:738  **true**    compliance  [RHEL6_20150812], [RHEL7_20150812], [FEDORA22_20150812], [auditd_data_retention_num_logs]   Auditd Maximum Number of Logs to Ret

**Comment by iankko** [comment]
Ditto for this one.

**Comment by redhatrises** [comment]
@pkbarbiedoll is this still an issue for you?

**Comment by redhatrises** [comment]
Closing as there has been no movement on this for a while.
