### ISSUE TITLE
[RHEL/6] Numerous "xccdf_org.ssgproject.content_rule_partition_for_tmp - Only OVAL and OCIL are supported check systems" errors reported by NIST SCAP content validation testsuite

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-security-guide#1037]
Example (https://jlieskov.fedorapeople.org/scap-scapversion-1.2-validation-result.html):

```
351-1 	1
(of 294) 	ERROR 	SCHEMATRON 	xccdf_org.ssgproject.content_rule_partition_for_tmp - Only OVAL and OCIL are supported 
```

There are 294 instances of the very same error.

**Comment by shawndwells** [comment]
@iankko - Since https://github.com/OpenSCAP/scap-security-guide/pull/1050 was merged, can we close this issue? (same as before)

**Comment by iankko** [comment]
@shawndwells 
Right, good catch (looks PR needs to explicitly have "Fixes: Issue_ID" to get closed automatically).
