### ISSUE TITLE
Convert current "JBossEAP5" benchmark into the form of common SSG product to simplify contributions and enhancements / updates

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-security-guide#1046]
We currently ship security checklist for the `JBossEAP5` product in the form of final XCCDF and OVAL files:
- [EAP5 XCCDF](https://github.com/OpenSCAP/scap-security-guide/blob/master/JBossEAP5/eap5-xccdf.xml),
- [EAP5 OVAL](https://github.com/OpenSCAP/scap-security-guide/blob/master/JBossEAP5/eap5-oval.xml)
- [EAP5 CPE Dictionary](https://github.com/OpenSCAP/scap-security-guide/blob/master/JBossEAP5/eap5-cpe-dictionary.xml)
- [EAP5 OCIL](https://github.com/OpenSCAP/scap-security-guide/blob/master/JBossEAP5/eap5-ocil.xml)

The current form of `JBossEAP5` benchmark is placing the following barrier WRT to open-source contributions model --  couple of final big (XCCDF, OVAL, OCIL ...) XML files don't allow cooperation on content development (due to many possible conflicts when providing patches). This results into state when SCAP content for `JBossEAP5` is:
- not used as much as it could be,
- getting more and more outdated due to missing content updates,
- not suitable for more recent versions of the `JBossEAP / WildFly` products.

Therefore -- we need:
- split those standalone XCCDF, OVAL, and OCIL files into the tree structure, as seen by other SSG products.

**Comment by mpreisler** [comment]
This is not a blocker, probably marked as blocker by accident.

**Comment by redhatrises** [comment]
This has been fixed with the lastest JBoss EAP 6 content and the removal of the EAP 5 content.
