### ISSUE TITLE
Enhance the current "JBossEAP5" SCAP content to add support for newer JBossEAP versions

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-security-guide#1047]
Right now SSG provides SCAP content for `JBossEAP5` product:
&nbsp; &nbsp; [1] https://github.com/OpenSCAP/scap-security-guide/tree/master/JBossEAP5

But there are more recent versions of JBossEAP product available:
- [v6](http://www.redhat.com/en/about/press-releases/red-hat-launches-jboss-enterprise-application-platform-6), 
- [v7 Beta](https://www.redhat.com/en/about/blog/red-hat-announces-availability-red-hat-jboss-enterprise-application-platform-7-beta)

We should enhance the SCAP content currently provided for `JBossEAP5` product to be applicable (and possibly enhanced with newly introduced features) also to `JBossEAP6` and upcoming `JBossEAP7` versions.

This issue is blocked by the previous issue:
&nbsp; &nbsp; [2] https://github.com/OpenSCAP/scap-security-guide/issues/1046

**Comment by redhatrises** [comment]
JBoss EAP 6 was added and JBoss EAP 5 was removed.
