### ISSUE TITLE
Rule ensure_gpgcheck_globally_activated does not check for DNF

### ISSUE THREAD

**Issue by ybznek** [OpenSCAP/scap-security-guide#1056]
My docker container fedora23 don't pass
the rule:
xccdf_org.ssgproject.content_rule_ensure_gpgcheck_globally_activated"

As I see, it check **/etc/yum.conf**. On my personal fedora23 (upgraded from fedora22) I have the file, but I don't see it in container.

Maybe we need to use ```/etc/dnf/dnf.conf```

Used command (probably not important)
```
sudo oscap-docker container fedora:23  xccdf eval --oval-results --profile xccdf_org.ssgproject.content_profile_standard --report /tmp/report.html ssg-fedora-ds.xml 
```

**Comment by iankko** [comment]
@ybznek 
> As I see, it check /etc/yum.conf. On my personal fedora23 (upgraded from fedora22) I have the file, but I don't see it in container.
> 
Maybe we need to use /etc/dnf/dnf.conf

Right, great catch. Thanks Zbynek.

@redhatrises 

Gabe any chance you already working on the fix for this? (just curious since you updated the title of this ticket).

**Comment by redhatrises** [comment]
> Gabe any chance you already working on the fix for this? (just curious since you updated the title of this ticket).

@iankko I was not working already on one, but I will take this ticket and create a fix.

**Comment by iankko** [comment]
@redhatrises 
> @iankko I was not working already on one, but I will take this ticket and create a fix.

Brilliant. Thanks!
