### ISSUE TITLE
RHEL7 STIG: CCI-000803 The operating system must use mechanisms meeting the requirements of applicable federal laws, Executive Orders, directives, policies, regulations, standards, and guidance for authentication to a cryptographic module.

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#108]
IA-7	CCI-000803	SRG-OS-000120		The operating system must use mechanisms meeting the requirements of applicable federal laws, Executive Orders, directives, policies, regulations, standards, and guidance for authentication to a cryptographic module.	"Unapproved mechanisms that are used for authentication to the cryptographic module are not verified, and therefore cannot be relied upon to provide confidentiality or integrity and DoD data may be compromised.

Operating systems utilizing encryption are required to use FIPS compliant mechanisms for authenticating to cryptographic modules.

FIPS 140-2 is the current standard for validating that mechanisms used to access cryptographic modules utilize authentication that meets DoD requirements."

**Comment by ghelleks** [comment]
It would be great if this check included verification of the FIPS certification status of the installed packages, as well. That would mean checking not just RPM versions, but (because of backports) the actual libraries installed.
