### ISSUE TITLE
[BugFix] [RHEL/6] One instance of 'The @use-case attribute in the <ds:data-stream> element MUST be set to "CONFIGURATION", "VULNERABILITY", "INVENTORY" or "OVAL_ONLY"' error

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-security-guide#1094]
Performing validation of current RHEL-6 SSG ```master``` with NIST SCAP content validation testsuite (https://jlieskov.fedorapeople.org/2016-03-18-scap-validation-result.html) returns one instance of the following error:
```
324-1 	1(of 1)
ERROR 	SCHEMATRON

scap_org.open-scap_datastream_from_xccdf_ssg-rhel6-xccdf-1.2.xml -
The @use-case attribute in the <ds:data-stream> element MUST be set
to "CONFIGURATION", "VULNERABILITY",  INVENTORY" or "OVAL_ONLY"

/*:data-stream-collection[namespace-uri()='http://scap.nist.gov/schema/scap/source/1.2'][1]
*:data-stream[namespace-uri()='http://scap.nist.gov/schema/scap/source/1.2'][1]
matches(@use-case,'^(CONFIGURATION|VULNERABILITY|INVENTORY|OVAL_ONLY)$')
```

This issue has been previously investigated within the following openscap ticket:
&nbsp; &nbsp; [1] https://github.com/OpenSCAP/openscap/issues/330

and the conclusion there was the 'OTHER" @use-case is valid attribute value. The NIST testsuite will be updated to allow the "OTHER" attribute value in future release.

Thus this is a not a bug for SSG content. Just tracking this so it would be covered (should someone need in the future explanation why old testsuite is failing).

**Comment by mpreisler** [comment]
Closing as this was confirmed to be invalid.
