### ISSUE TITLE
[BugFix] [RHEL/6] One instance of "@update on <xccdf:version> SHOULD be specified" error

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-security-guide#1096]
Performing the validation of current (2016-03-18) SSG RHEL-6 master content against NIST SCAP content validation testsuite (https://jlieskov.fedorapeople.org/2016-03-18-scap-validation-result.html) returns ones instance of the following error:
```
341-1 	1(of 1)
ERROR 	SCHEMATRON

@update on <xccdf:version> SHOULD be specified

/*:data-stream-collection[namespace-uri()='http://scap.nist.gov/schema/scap/source/1.2']
1]/*:component[namespace-uri()='http://scap.nist.gov/schema/scap/source/1.2']
[2]/*:Benchmark[namespace-uri()='http://checklists.nist.gov/xccdf/1.2'][1]/*:version
[namespace-uri()='http://checklists.nist.gov/xccdf/1.2'][1]

exists(@update)
```

**Comment by mpreisler** [comment]
Crap, didn't mean to take over this ticket. Just wanted to say that I have fixed the version_time and version_update serialization in https://github.com/OpenSCAP/openscap/commit/1f05cc104a34f49e34e27f616280837e5c68388d

If you use OpenSCAP from git it will no longer drop the 2 attributes from <version> in Benchmark.

**Comment by iankko** [comment]
> If you use OpenSCAP from git it will no longer drop the 2 attributes from in Benchmark.
Great. Thanks for that! (that's big help)
