### ISSUE TITLE
Create RHEL7 rule for idle_activation_enabled

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#1130]
![image](https://cloud.githubusercontent.com/assets/5713754/14085102/f24f2a3a-f4eb-11e5-8974-4234f7ab6a84.png)

**Comment by redhatrises** [comment]
- See https://github.com/OpenSCAP/scap-security-guide/blob/master/RHEL/7/input/profiles/stig-rhel7-server-gui-upstream.xml for profile enablement.
- See https://github.com/OpenSCAP/scap-security-guide/blob/master/RHEL/7/input/xccdf/system/software/gnome.xml for XCCDF content.
