### ISSUE TITLE
need new rule: GDM TimedLoginEnable=false

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#1161]
![image](https://cloud.githubusercontent.com/assets/5713754/14188982/109a15f8-f759-11e5-851f-f4bd4ce59ba7.png)

**Comment by bcon** [comment]
Could you sneak in a fix to this? The SPAWAR SCC, DISA STIG, and Tenable Nessus look for the false to be lowercase. The implementation of this in the SCAP content was "False" which makes a false positive result in Tenable Nessus and SCC scans.

Looking at GDM docs, the lowercase is probably technically correct (e.g. https://wiki.gnome.org/Projects/GDM/2.22/Configuration)
