### ISSUE TITLE
[DISA FSO]  disable inactive accounts using pam_lastlog.so in system_auth_ac

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#12]
SRG-OS-000118 CCI-000795 The operating system must manage information
system identifiers for users and devices by disabling the user
identifier after an organization-defined time period of inactivity.

Basically, it uses the following format:

auth    required    pam_lastlog.so inactive=35

It's a much cleaner way to do this rather than modifying the useradd
command. I plan to use that since RHEL is really starting to take off
here and RHEL 6.4 is going to be my standard if possible.

**Comment by redhatrises** [comment]
@shawndwells with RHEL7 this can be changed in ```/etc/default/useradd``` seems like that would be much cleaner than adding ```pam_lastlog.so``` to ```system-auth-ac```. Was this requested because of RHEL6?

**Comment by shawndwells** [comment]
No longer an issue. Resolving.
