### ISSUE TITLE
New sysctl rule:  net.ipv4.conf.default.proxy_arp=0

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#1215]
DISA requested new sysctl rule:

AC–4	CCI–000366	SRG–OS–000480–GPOS–00227	RHEL–07–040400	Proxy Address Resolution Protocol (Proxy ARP) must not be enabled on the system.	Proxy ARP allows a system to respond to ARP requests on one interface on behalf of hosts connected to another interface.  If this function is enabled when not required, addressing information may be leaked between the attached network segments.	Applicable – Configurable	"Verify that Proxy Address Resolution Protocol (Proxy ARP) is not enabled on the system.

Check the value of the “proxy_arp” variable with the following command:

# /sbin/sysctl –a | grep  net.ipv4.conf.default.proxy_arp
net.ipv4.conf.default.proxy_arp=0

If net.ipv4.conf.default.proxy_arp does not have a value of “0”, a line is not returned, or the retuned line is commented out, this is a finding."	"Set the system to the required kernel parameter by adding the following line to /etc/sysctl.conf (or modify the line to have the required value):

net.ipv4.conf.default.proxy_arp=0"	Cat II

**Comment by redhatrises** [comment]
DISA dropped rule. @shawndwells reopen if you disagree.
