### ISSUE TITLE
[BugFix] [scap-security-guide-nightly-oval510-zip] and [scap-security-guide-nightly-zip] Jenkins jobs are currently failing due to missing 'unlinked-rhel-osp7-ocil.xml' file

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-security-guide#1231]
See e.g.:
- https://jenkins.open-scap.org/job/scap-security-guide-nightly-oval510-zip/248/console
- https://jenkins.open-scap.org/job/scap-security-guide-nightly-zip/247/console

**Comment by yuumasato** [comment]
The builds referenced don't exist any more.
After PR #1529 a small fix on the zip path in the job configuration solved the last failure.
The job seems to be running smoothly. I'll wait a few runs before closing this issue.

**Comment by yuumasato** [comment]
There was just one unrelated fail caused by disk space on run https://jenkins.open-scap.org/job/scap-security-guide-nightly-oval510-zip/441/, but next run was successful.

Closing this issue.
