### ISSUE TITLE
[RHEL/7] false positive (fail) on content_rule_rpm_verify_permissions

### ISSUE THREAD

**Issue by openprivacy** [OpenSCAP/scap-security-guide#1250]
#### On machine performing scan:
*oscap:*
OpenSCAP command line tool (oscap) 1.2.9

*SCAP Security guide:*
ea13b91|master (current 13 May 2016) "make rhel7"

*Command run:*
oscap-ssh sudo oscap-user@staging 22 xccdf eval --profile xccdf_org.ssgproject.content_profile_stig-rhel7-server-upstream --results-arf scans/results-arf.xml --results scans/results.xml --report scans/results.html scap/ssg-rhel7-ds.xml

#### On staging (server being remotely scanned):

*OpenSCAP version:*
OpenSCAP command line tool (oscap) 1.2.8

*OS version:*
Red Hat Enterprise Linux Server release 7.2 (Maipo)

#### Result:
```
Title  Verify and Correct File Permissions with RPM
Rule   xccdf_org.ssgproject.content_rule_rpm_verify_permissions
Ident  CCE-27209-6
Result fail
```
Note: the `gdm` package is not installed.

#### Test command returns empty:
```
[oscap-user@staging ~]$ sudo rpm -Va | grep '^.M'
[oscap-user@staging ~]$
```

**Comment by shawndwells** [comment]
On 5/13/16 2:04 PM, Fen Labalme wrote:
>
>
>         On machine performing scan:
>
> /oscap:/
> OpenSCAP command line tool (oscap) 1.2.9
>
> /SCAP Security guide:/
> ea13b91 
> <https://github.com/OpenSCAP/scap-security-guide/commit/ea13b910c6594a56f74374e0908ad0e2dab9bd67>|master 
> (current 13 May 2016) "make rhel7"
>
> /Command run:/
> oscap-ssh sudo oscap-user@staging 22 xccdf eval --profile 
> xccdf_org.ssgproject.content_profile_stig-rhel7-server-upstream 
> --results-arf scans/results-arf.xml --results scans/results.xml 
> --report scans/results.html scap/ssg-rhel7-ds.xml
>
>
>         On staging (server being remotely scanned):
>
> /OpenSCAP version:/
> OpenSCAP command line tool (oscap) 1.2.8
>
> /OS version:/
> Red Hat Enterprise Linux Server release 7.2 (Maipo)
>
>
>         Result:
>
> |Title Verify and Correct File Permissions with RPM Rule 
> xccdf_org.ssgproject.content_rule_rpm_verify_permissions Ident 
> CCE-27209-6 Result fail |
>
> Note: the |gdm| package is not installed.
>
>
>         Test command returns empty:
>
> |[oscap-user@staging ~]$ sudo rpm -Va | grep '^.M' [oscap-user@staging 
> ~]$ |
>
> —
>

Can you generate and share your OVAL results file? e.g.:
$ sudo oscap oval eval --id oval:ssg-rpm_verify_permissions:def:1 
--results /tmp/results.xml output/ssg-rhel7-oval.xml

Scroll to the bottom of /tmp/results.xml and you should find what files 
are triggering the failure.


-- 
Shawn Wells
Chief Security Strategist
U.S. Public Sector
shawn@redhat.com | 443.534.0130

**Comment by openprivacy** [comment]
Super useful hint as to how to find details on a fail - is this documented somewhere?
Ran:
```
$ sudo oscap oval eval --id oval:ssg-rpm_verify_permissions:def:1 --results /tmp/results.xml  ssg-rhel7-oval.xml 
Definition oval:ssg-rpm_verify_permissions:def:1: false
Evaluation done.
```
Bottom of results.xml:
```
        <system_data>
          <lin-sys:rpmverifyfile_item id="1093221" status="exists">
            <lin-sys:name>httpd</lin-sys:name>
            <lin-sys:epoch>(none)</lin-sys:epoch>
            <lin-sys:version>2.4.6</lin-sys:version>
            <lin-sys:release>40.el7</lin-sys:release>
            <lin-sys:arch>x86_64</lin-sys:arch>
            <lin-sys:filepath>/var/log/httpd</lin-sys:filepath>
            <lin-sys:extended_name>httpd-0:2.4.6-40.el7.x86_64</lin-sys:extended_name>
            <lin-sys:size_differs>pass</lin-sys:size_differs>
            <lin-sys:mode_differs>pass</lin-sys:mode_differs>
            <lin-sys:md5_differs>not performed</lin-sys:md5_differs>
            <lin-sys:device_differs>pass</lin-sys:device_differs>
            <lin-sys:link_mismatch>pass</lin-sys:link_mismatch>
            <lin-sys:ownership_differs>pass</lin-sys:ownership_differs>
            <lin-sys:group_differs>fail</lin-sys:group_differs>
            <lin-sys:mtime_differs>pass</lin-sys:mtime_differs>
            <lin-sys:capabilities_differ>pass</lin-sys:capabilities_differ>
            <lin-sys:configuration_file datatype="boolean">false</lin-sys:configuration_file>
            <lin-sys:documentation_file datatype="boolean">false</lin-sys:documentation_file>
            <lin-sys:ghost_file datatype="boolean">false</lin-sys:ghost_file>
            <lin-sys:license_file datatype="boolean">false</lin-sys:license_file>
            <lin-sys:readme_file datatype="boolean">false</lin-sys:readme_file>
          </lin-sys:rpmverifyfile_item>
        </system_data>
      </oval_system_characteristics>
    </system>
  </results>
</oval_results>
```
The fail of `/var/log/httpd` is `group_differs>fail` but this appears correct to me:
```
$ ls -ldZ /var/log/httpd
drwx------. root apache unconfined_u:object_r:httpd_log_t:s0 /var/log/httpd
$ sudo rpm -Va | grep '^.M'
$
```
What is my next step?

A related (but slightly off topic, if you'll forgive me) question: I'd like to `chown 705 /var/log/apache` to allow non-root users to see the apache logs. If I set the SELinux policy to allow this, will OpenSCAP follow the policy? Or perhaps is there a better way to accomplish what I want?

**Comment by redhatrises** [comment]
> The fail of `/var/log/httpd` is `group_differs>fail` but this appears correct to me:
```
$ ls -ldZ /var/log/httpd
drwx------. root apache unconfined_u:object_r:httpd_log_t:s0 /var/log/httpd
$ sudo rpm -Va | grep '^.M'
$
```
What is my next step?

@openprivacy will you change the group for `/var/log/httpd` from `apache` to `root`, re-run the oval scan, and report back if that fixed the fail?

**Comment by openprivacy** [comment]
Changing group from apache to root fixed things. So the test used by OVAL/XCCDF is different than the test offered to the user for checking. But resolved now, so I'll close this. Thanks!
