### ISSUE TITLE
All profiles from SSG 0.1.31 are documented on open-scap.org/security-policies/choosing-policy/

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-security-guide#1259]
The purpose of the open-scap.org's portal [choosing policy page](https://www.open-scap.org/security-policies/choosing-policy/) is to provide guidance for SSG users how to choose the most appropriate profile for their use case.

Section `Security policies available in the SCAP Security Guide` provides a list of currently available profiles across the various SSG products. Each link from the list points to corresponding http://static.open-scap.org/ssg-guides record, where the users can obtain further information about the specific profile (profile name, description, list of selected rules etc.)

Since from time to time in SSG when making new release happens a new profile is introduced to specific product, when making SSG-0.1.30 release we need to ensure the list of profiles at:
  [1] https://www.open-scap.org/security-policies/choosing-policy/

is synchronized with the list of profiles available in SCAP-Security-Guide-0.1.30 tarballs / Zip archives.

This issue is intended mainly as a note for myself not to forget update the list of profiles on [1] page when making 0.1.30 release.

**Comment by yuumasato** [comment]
Build of missing guides were fixed by #1586, #1587 and #1588.
Only thing left is to update https://www.open-scap.org/security-policies/choosing-policy/ page.

**Comment by yuumasato** [comment]
Profiles in open-scap.org portal updated
Added `docker-host` profile for RHEL7.
Added `desktop`, `fisma-medium-rhel6-server` and `ftp-server` profiles for RHEL6.
