### ISSUE TITLE
[RFE] [Infrastructure] Turn innocent xsltproc warnings about failure to load external file into SSG make exit(1) errors

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-security-guide#1290]
xsltproc is widely used within SSG infrastructure. The issue being each time when xsltproc fails to load referenced external entity XML file it issues an (innocent) warning like the following:

```
xsltproc --stringparam ssg_version "0.1.29" -o output/xccdf-unlinked-unresolved.xml 
transforms/shorthand2xccdf.xslt output/shorthand.xml
warning: failed to load external entity "../../shared/output/contributors.xml"
```

Though in some use-cases this xsltproc behavior (issue a warning, result with exit 0 code rather than issue an error, result with exit 1 code) might be appropriate, in SSG when this happens it often means:
- the final benchmark will be either incomplete (some required part wasn't properly included as should be),
- the build process will exit with error (due to missing definition of variables etc.)

The latter scenario is actually the better (because by failing make it's possible immediately to notice what get wrong and correct the issue). The former scenario is a bit more sneaky - the build succeeded, thus it might seem everything is OK. Even when it is not the case (some part of the benchmark is missing due to unsuccessful attempt to load external entity file).

Therefore the proposal is to change / update the SSG build system to treat xsltproc warnings in the form of:

```
warning: failed to load external entity: ...
```

as critical errors, and abort the make process immediately with exit code 1 (failure).

This could be implemented via some wrapper around xsltproc call parsing it's output / stderr, to identify if some external entity file failed to load. Or via python lxml xslt functionality to check first if the URI resolves properly. Or even some other way.

Regardless of the method used to implement this, this issue will be considered as fixed, when if during SSG build some XML files failed to be loaded, SSG build will exit with failure (exit code 1), rather than with success and silent xsltproc warning, like it's doing now.

**Comment by iankko** [comment]
This has beaten us once again -- most recent manifestation of this is https://github.com/OpenSCAP/scap-security-guide/pull/1373

**Comment by mpreisler** [comment]
This has been fixed by #1394

**Comment by redhatrises** [comment]
@mpreisler are you sure? I thought this ticket was for any XSLT warnings that might show themselves.

**Comment by mpreisler** [comment]
Yeah, you are right. Thx for watching this. I only fixed this for the remediations.xml. We need to do the same thing for all included documents.

**Comment by radzy** [comment]
@mpreisler , @redhatrises : I have a sh script that does something along those lines.  I didn't upload it because I didn't see any other sh scripts and because I was concerned about how it would fit in with the new cmake work.  Let me know if  you'd like to look at it, and I'll upload a PR for discussion.

**Comment by redhatrises** [comment]
Preferably it would be with either python or xslt. I think that #1394 is the desired method.

**Comment by radzy** [comment]
Thanks @redhatrises .  That's what I expected.  :-)

**Comment by redhatrises** [comment]
Believe that we are moving away from xslt and xml files. Closing.
