### ISSUE TITLE
[RFE] [Infrastructure] Generate $(OUT)/remediation_functions.xml dynamically from shared/remediations/bash/templates/remediation_functions

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-security-guide#1291]
See:
- https://github.com/OpenSCAP/scap-security-guide/pull/1270#issuecomment-222984282

[Thanks to a recent change](https://github.com/OpenSCAP/scap-security-guide/pull/1270) the remediation scripts are now part of final benchmark itself (no need to rely on external `/usr/share/scap-security-guide/remediation_functions` sh library).

But in the current form `shared/xccdf/remediation_functions.xml` has been generated manually only once (it's not regenerated during the build process). The issue here is each time a new function got added into `shared/remediations/bash/templates/remediation_functions` the `shared/xccdf/remediation_functions.xml` will need to be created again.

To get rid of this need, the above proposal mentions creation of `$(OUT)/remediation_functions.xml` file during each build from `shared/remediations/bash/templates/remediation_functions`.

We need to implement this.

**Comment by mpreisler** [comment]
Maybe I am missing something but can't we just remove the old file? It doesn't seem to be used anywhere...

**Comment by yuumasato** [comment]
Fixed by #2035

**Comment by yuumasato** [comment]
Fixed by #2035
