### ISSUE TITLE
[PROJECT IDEA] Create a YAML to XCCDF generator using Jekyll

### ISSUE THREAD

**Issue by JJediny** [OpenSCAP/scap-security-guide#1294]
> Just sharing some crude notes and a nascent idea...
## Issue

Generating XCCDF profiles that are actionable seems to require an inherit understanding of how/which macros are available. I've been toying with the idea of translating some raw tests in [docker-security-workbench into XCCDF](https://github.com/OpenSCAP/container-compliance/issues/11) and had an idea that I'm looking for feedback on its potential utility and/or concerns or comments on such an approach. 
- **As a developer** I would like to quickly and more importantly iteratively develop a XCCDF profile for each component in my stack. 
- **As a project manager** I want the ability to contribute to procedures/policies/controls and map them to a system component. YAML offers me an ability to do this over creating/editing XML directly 
- **As a operations manager** I want a single/dynamic endpoint to pull each XCCDF file for each component so I can use my CI/CD process and docker to isolate and test each component against each matching profile and automate remediation and the generation of the reports. 
## Idea

Using Jekyll/Github Pages (YAML/MD) native pages and/or _data folder I would develop a XML output to serialize the YAML using jekyll's templates and filters to generate an XML output with various logic and conditions to properly generate inline xml/xml wrapping/field injection? I'll likely be doing this regardless, but I'd be great to get any heads up or comments on a few day notetaking/mapping exercise in how to structure yaml and yet handle variation within the concepts of macros most notably.

Similar to https://github.com/jekyll/jekyll-feed or/like other JSON outputs that generate a single file based on multiple entires either in .md files and/or yaml nesting

```
Group:
  id:
  title:
  description:
  Value:
    id:
    type: number
    operator: equals
    interactive: 0
    title:
    description:
    Values:
    - selector:
      value:
    - selector:
      value:
  Rule:
    id:   #This id is used to match a rule to a remediation script, OVAL ref, or Policy reference
    severity: medium #low, medium, high
    weight:
    title:
    description:
    warning:
    Macros: # Tests NOTE logic using xsl to validate results of multiple macros using (xsl: if test, xsl: template match)
      - type: package # service, partion, sysctl, fileperms, fileowner, filegroupowner, mount, module, audit, sshd, xinetd, chkconfig, yum, iptables, socket, systemd
        actions:
          - enable # install, check, disable, enable, desc, syscall, service, remove, socket
          - check
        tests:
        - key: # either a filepath, setting name, option/part
          value:  # EXAMPLES - 0, 1, 5000 or name match to service/package/setting (auditd, ntpd, crond. audit, firewalld)
          boolean: # See default and allow below - could use a generic boolean attribute in place?
          #default: no/yes - sshd test adds a default option
          #allow: true/false - firwalld type requires an allow attribute
        rationale:
        ocil: false #ocil is a specific type of test = true wraps this rule with an ocil xml tag
    References:
      oval:   # OVAL vulnerability id
      cce:    # CCE vulnerablity id
      nist:   # NIST-800 Control id
      disa:   # DOD-DSIA STIG id
      cis:    # Center for Internet Security id
      ossrg:  #General Purpose Operating System SRG

```

**Comment by iankko** [comment]
@JJediny 
Hello John,
  thank you for the proposal.
...
>  had an idea that I'm looking for feedback on its potential utility and/or concerns or comments on such an approach. 
...

Though being an interesting idea, one concern here - who would be expected to ensure the grammar of the output XCCDF / XML file is correct? (IOW who should ensure it won't be possible to create XCCDF file containing e.g. ```<xccdf:Group>``` within an ```<xccdf:Rule>``` ?)

Having the ability to generate XCCDFs quickly is one thing. Having the ability to generate well-formed XCCDFs quickly might not be that straightforward.

On the other hand in general I wouldn't mind availability of simple script in SSG being able to translate "well-formed" XCCDF expressed in YAML / JSON format into corresponding XCCDF form (of a profile, group etc.)

**Comment by shawndwells** [comment]
Project never took off. Resolving. Feel free to re-open if there is interest! :)
