### ISSUE TITLE
[Infrastructure] [Enhancement] Start producing SSG remediation scripts in the form of Ansible Playbooks

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-security-guide#1308]
[OpenSCAP since 1.2.7](https://www.redhat.com/archives/open-scap-list/2015-December/msg00000.html) allows the xccdf:fix element to be [implemented in the form of Ansible Playbook](https://github.com/OpenSCAP/openscap/commit/53c2a65de4ef06bcefbc88df5682226ba7aa0280)

We should enhance the SSG build system to be able to produce remediations for the benchmarks covered within SSG in the form of Ansible Playbooks too.

The expectation of this RFE is to have some transformation available, that would automatically convert the already available remediation scripts in bash form, into the form as expected by `ansible-playbook`.  (AP) Once the remediations are exported into the form expected by AP, we would enhance the benchmarks with another `<xccdf:fix>` elements using `xccdf:fix:script:ansible"` and include their form into the resulting benchmark.

To speak even in more detail like we currently have `combineremediations.py` Python helper. we would have `combineplaybooks.py` helper that would produce `$(OUT)/ansible-playbook-remediations.xml` (besides / on top of `$(OUT)/bash-remediations.xml` like done by `combineremediations.py` helper currently). And during the benchmark build for the product, content of `$(OUT)/ansible-playbook-remediations.xml` would be inserted at appropriate places into both:
- the XCCDF, and
- the DataStream format of the benchmarks.

**Comment by chagara** [comment]
@geerlingguy you are the master in doing work in ansible and your guidance would be awesome in completing this. I would also be interested in helping but, I just started learning about ansible.

**Comment by ybznek** [comment]
Hi @iankko,

Sorry, it is quite difficult to handle the issue from the description without better knowledge of ssg & without practical experience with Ansible.

*that would automatically convert the already available remediation scripts in bash form* - how do you imagine **automatic** convert? Write manually playbook variant for every `remediations/*.sh` and then automatically generate merged xml file?

**Comment by iankko** [comment]
@ybznek 
Hi Zbynek,

> that would automatically convert the already available remediation scripts in bash form - how do you imagine automatic convert? Write manually playbook variant for every remediations/*.sh and then automatically generate merged xml file?

My idea was to create ```ansible templates``` for possible ```categories of remediations```, and then use these templates to create the remediaton scripts automa{t,g}ically (possibly also modify existing ```combineremediations.py``` helper to understand these new ansible templates).

Will give you some more explanatory example in next comment (couple of mins).

**Comment by iankko** [comment]
If you have a look at ```scap-security-guide/RHEL/6/input/remediations/bash/templates``` there's template used to create RHEL-6 remediation for ```service_*_enabled``` kind of rule (IOW calling ```make services``` from ```scap-security-guide/RHEL/6/input/remediations/bash/templates``` directory will produce the following remediations in the ```scap-security-guide/RHEL/6/input/remediations/bash/templates/output``` directory:
```

$ ls output/*.sh
output/service_abrtd_disabled.sh         output/service_haldaemon_disabled.sh   output/service_oddjobd_disabled.sh      output/service_rsyslog_enabled.sh
output/service_acpid_disabled.sh         output/service_httpd_disabled.sh       output/service_pcscd_enabled.sh         output/service_saslauthd_disabled.sh
output/service_atd_disabled.sh           output/service_iptables_enabled.sh     output/service_portreserve_disabled.sh  output/service_smartd_disabled.sh
output/service_auditd_enabled.sh         output/service_ip6tables_enabled.sh    output/service_postfix_enabled.sh       output/service_smb_disabled.sh
output/service_autofs_disabled.sh        output/service_irqbalance_enabled.sh   output/service_psacct_enabled.sh        output/service_snmpd_disabled.sh
output/service_avahi-daemon_disabled.sh  output/service_kdump_disabled.sh       output/service_qpidd_disabled.sh        output/service_squid_disabled.sh
output/service_bluetooth_disabled.sh     output/service_mdmonitor_disabled.sh   output/service_quota_nld_disabled.sh    output/service_sshd_disabled.sh
output/service_certmonger_disabled.sh    output/service_messagebus_disabled.sh  output/service_rdisc_disabled.sh        output/service_sysstat_disabled.sh
output/service_cgconfig_disabled.sh      output/service_named_disabled.sh       output/service_restorecond_enabled.sh   output/service_tftp_disabled.sh
output/service_cgred_disabled.sh         output/service_netconsole_disabled.sh  output/service_rhnsd_disabled.sh        output/service_vsftpd_disabled.sh
output/service_cpuspeed_disabled.sh      output/service_netfs_disabled.sh       output/service_rhsmcertd_disabled.sh    output/service_xinetd_disabled.sh
output/service_crond_enabled.sh          output/service_nfs_disabled.sh         output/service_rpcbind_disabled.sh      output/service_ypbind_disabled.sh
output/service_cups_disabled.sh          output/service_nfslock_disabled.sh     output/service_rpcgssd_disabled.sh
output/service_dhcpd_disabled.sh         output/service_ntpdate_disabled.sh     output/service_rpcidmapd_disabled.sh
output/service_dovecot_disabled.sh       output/service_ntpd_enabled.sh         output/service_rpcsvcgssd_disabled.sh
```

These *.sh files are valid remediation scripts already, that can be manually copied under ```shared/remediations/bash``` directory (after review each of them), and when RHEL-6 benchmark is built these remediations will get included (thanks to ```shared/transforms/combineremediations.py``` helper).

Thus to project this to ansible playbook use case -- my idea was to create ```RHEL/6/remediations/ansible/templates/template_package_installed``` template, a Makefile and CSV file, which after calling ```make packages``` would create form of ansible playbook that would check if a RPM package_X is installed.

For further details have a look at current form of ```template_service_enabled and Makefile``` in the ```scap- security-guide/RHEL/6/input/remediations/bash/templates``` directory.

Once we are able to create first such ansible-playbook *.sh (or whatever suffix) remediation script, we can proceed further to identify what needs to be modified in ```shared/transforms/combineremediations.py``` helper in order these ansible playbooks remediations to be inserted into produced bechmarks (at appropriate <fix> element places too).

Does the above makes sense?

**Comment by ybznek** [comment]
Thank you.

It makes sense. I currently don't see any blocker, I will go work on it.

**Comment by ybznek** [comment]
*For record:*
 ansible-review could help us, need more investigation -  https://github.com/willthames/ansible-review

**Comment by iankko** [comment]
@ybznek 
>  For record:
ansible-review could help us, need more investigation - https://github.com/willthames/ansible-review

Maybe once SSG playbooks are available we could use ansible-review for regular inspection of produced playbooks? (something like we do right now with shellcheck for remediation scripts)

**Comment by mpreisler** [comment]
This ticket is outdated and no longer reflects the Ansible implementation.
