### ISSUE TITLE
[BugFix] [RHEL/6] [RHEL/7] Smooth down the "/usr/share/doc/audit-*/stig.rules" to SSG RHEL-6 / RHEL-7 STIG profile audit rules expectations

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-security-guide#1311]
Many SSG users are accustomed to apply `stig.rules` as provided by the audit package (`/usr/share/doc/audit-*/stig.rules` location on RHEL-6 system) instead of applying direct SSG remediation.

The recommendations in this file are functionally equivalent to those expressed in various audit rules present in `RHEL/6` and `RHEL/7` STIG profiles (basically the only thing that differs is the suggested audit rule key, that will be subsequently used to search / locate the specific audit log entries).

We should smooth the transition from `/usr/share/doc/audit-*/stig.rules` to officially expected `RHEL/6` and `RHEL/7` STIG profiles audit rules settings as much as possible (the corresponding OVAL checks to be as much as tolerant to the form used in `/usr/share/doc/audit-*/stig.rules` file as possible. Though simultaneously with preserving the recommendations / requirements of SSG STIG profiles of course).

AFAICT some effort has been done in the past to have these two settings being alternative. But we should perform a verification, and fix the remaining issues in audit rules OVALs where applicable.

Taking as action item for me (since I have written majority of those OVAL checks).

**Comment by shawndwells** [comment]
Instead of modifying our OVAL to what stig.rules may have, should we patch stig.rules to match SSG?

**Comment by redhatrises** [comment]
Agree with @shawndwells. As more STIG auditing rules are added and fixed, `stig.rules` will need to be updated to match SSG.

**Comment by redhatrises** [comment]
Closing as `stig.rules` should comply with what rules SSH is providing not the other way around.
