### ISSUE TITLE
[Feature request] Port RHEL-6 testing kickstarts to RHEL-7

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-security-guide#1317]
For RHEL-6 system there are currently available two kickstart files, that can be / are used for testing:
- [test-usgcb-subcompliance-ks.cfg](https://github.com/OpenSCAP/scap-security-guide/blob/master/RHEL/6/tests/kickstart/test-usgcb-subcompliance-ks.cfg)
- [test-usgcb-supercompliance-ks.cfg](https://github.com/OpenSCAP/scap-security-guide/blob/master/RHEL/6/tests/kickstart/test-usgcb-supercompliance-ks.cfg)

The first one is handy for testing of remediations (install non-compliant system from scratch, perform remediations && verify they system is corrected / in passing state),

The second one is handing for testing of OVALs (install compliant system from scratch, verify if all rules return the "PASS" state).

To be able to perform the same set of tests on RHEL-7 system, we need to have these kickstarts ported (to work properly) with RHEL-7 product too.

Contributions welcome.

Thanks, Jan

**Comment by redhatrises** [comment]
Closing as there is a new test suite and testing kickstarts are no longer really required or used.
