### ISSUE TITLE
scap-security-guide-nist-testsuite Jenkins CI test job fails starting from 2016-07-11

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-security-guide#1344]
See https://jenkins.open-scap.org/job/scap-security-guide-nist-testsuite/183/
The issue isn't in CI job itself, since there are two errors reported with the testsuite:
  https://jenkins.open-scap.org/job/scap-security-guide-nist-testsuite/183/consoleFull

(both for RHEL-6 and RHEL-7 content)

I will inspect the failure. Stay tuned.

**Comment by redhatrises** [comment]
@iankko I wonder if we should add the NIST SCAP validator tool as part of the Jenkins make target so that when there is a new pull request the new PR is validated by the NIST tool, no?

**Comment by mpreisler** [comment]
@redhatrises We probably shouldn't do that. The validator is quite heavy and requires a java runtime. I am not sure it's worth it. It's probably better to watch the jenkins job occasionally and fix issues as they crop up.

**Comment by iankko** [comment]
@redhatrises 
Discussed this previously with Martin, and as a result I agree with him. While the enhancement would be useful (we not to regress WRT to ScapVal requirements), this contradicts with current effort to speed up Jenkins ```scap-security-guide-pull-requests``` CI job RTT time as much as possible.

The conclusion was should be enough to check status of ```scap-security-guide-nist-testsuite``` Jenkins CI job once per month (prior making the release). It's part of SSG release process guide.

**Comment by mpreisler** [comment]
https://jenkins.open-scap.org/job/scap-security-guide-nist-testsuite/333/
