### ISSUE TITLE
oscap-docker should check if docker-storage-setup is configured

### ISSUE THREAD

**Issue by thetuxracer** [OpenSCAP/scap-security-guide#1346]
For using docker in production, the device mapper storage driver, with loopback devices is [discouraged]. There are various ways of configuring the devicemapper storage driver, and suggested ones are aufs, direct-lvm. Choosing the right storage driver and backing filesystem is crucial to stability and performance. 

We can display the configured storage driver in the report file.

[discouraged]: https://docs.docker.com/engine/userguide/storagedriver/selectadriver/

**Comment by jan-cerny** [comment]
@thetuxracer 

I have studied this today. If I understand it well, using the devicemapper with loopback devices is the default value. User has to change the configuration explicitly.
 (see https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/)

To check whether the requirement not to use loopback devices is satisfied, we actually have to check that something else was configured. In other words, we need to verify whether custom storage options were set. Specifficaly, the configuration files should contain `--storage-opt=dm.thinpooldev=`

A challenge that I see here is that Docker is managed by systemd and has multiple configuration files, including `docker.json` file.

I suggest this way of checking the proper configuration:
1) identify all the configurations file that could affect the docker storage settings. We will  have to list all environmentfiles and unit file and add the config.json and default conf files in /usr/lib/docker-storage-setup/docker-storage-setup
2) scan each file for storage options. Specify a regular expression that would match it correctly. The json config file would most likely require a special approach.
3) verify whether dm.thinpooldev option was correctly specified and that it points to a reasonable device

Am I correct or am I missing something here?

**Comment by thetuxracer** [comment]
@jan-cerny You are correct, thats how we have to check this. The docker-storage config files in /etc/sysconfig/ and /usr/lib/docker-storage-setup.

We probably would need to check for existence of the device pointed to by the config files. Is that somehow possible?

**Comment by jan-cerny** [comment]
@thetuxracer Thank you for your confirmation. Checking for existence of device pointed by the config files is possible, and I think it is quite easy - parse the value from the config file, store that into a variable and use it in OVAL file_test.

**Comment by jan-cerny** [comment]
Fixed in https://github.com/OpenSCAP/scap-security-guide/commit/3659aac2117a9e7076e5d5eee22fbb4f688a9857 

Sorry for delay on closing this.
