### ISSUE TITLE
[BugFix] [Infrastructure] combineovals.py / combineremediations.py - Refactor / simplify cooperation of "add_platforms()" and "check_is_applicable_for_product()" routines

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-security-guide#1354]
Discussed the following with @ybznek yesterday (current form of `check_is_applicable_for_product()` routine isn't straightforward for SSG newcomers since it assumes some knowledge of SSG internals).

The concern / issue Zbynek was concerned with was the combination of `and` operation with `multi_platform_all` `<platform>` definition:
- https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/transforms/combineovals.py#L115

My reasoning / motivation behind using the `and` operator was / is the following:
- We want the `multi_platform_all` platform element to represent RHEL-5, RHEL-6, RHEL-7, Fedora, RHEL-OSP-7, and Debian products -- for the `combineovals.py` case (but don't include also JRE, Chromium, whatever else products)
- The usage of `multi_platform_all`` in this combination is confusing (`multi_platform_all``` suggests the OVAL would be truly included everywhere, not just on selected Linux distributions)

Therefore:
- We should select more appropriate name for this combination of platforms,
- Replace `multi_platform_all` with the new name

Besides the above the `check_is_applicable_for_platform` doesn't parse the config (`config/oval.config`) file to determine list of platforms, that should belong under `multi_platform_all` identifier. Instead of that the logic is embedded in routine itself.

Moreover there's separate `add_platforms()` routine, which is responsible for expanding `multi_platform_rhel` elements into:
- `<platform>Red Hat Enterprise Linux 6</platform>`,
- `<platform>Red Hat Enterprise Linux 7</platform>`

combination of platforms. Also responsible for expanding `multi_platform_fedora` into:
- `<platform>Fedora 23</platform>`,
- `<platform>Fedora 24</platform>`, and
- `<platform>Fedora 25<platform>`
  combination of platforms etc.

Thus to remove this duplicity (`check_is_applicable_for_product()` routine first to filter out OVALs for `<platform>multi_platform_rhel</platform>` or `<platform>multi_platform_fedora</platform>`, later `add_platforms()` routine expand these pseudo-platforms into true / final platforms as mentioned above), the proposal is to refactor the cooperation of `check_is_applicable_for_product()` and `add_platforms()` routines to perform the following:
- Call add_platforms() to parse `config/oval.config` file. Have `multi_platform_all` (or more suitable name) defined in that config, so it's explicitly listed in the config that `multi_platform_all` corresponds to RHEL-5, RHEL-6, RHEL-7, Fedora-23, Fedora-24, Fedora-25, RHEL-OSP-7, and Debian-8 platforms currently,
- Modify `check_is_applicable_for_product()` routine to remote the confusing `and` statement (`check_is_applicable_for_product()` routine should be able to operate solely on `multi_platform_all` definition without the need to explicitly to list the platforms, that should be considered as valid representatives of `all` platform).

The same refactoring should be applied also to `shared/transforms/combineremediations.py` helper (since the logic of affected code is derived from the form present in `combineovals.py` helper).

**Comment by radzy** [comment]
> We want the multi_platform_all platform element to represent
> RHEL-5, RHEL-6, RHEL-7, Fedora, RHEL-OSP-7, and Debian products --
> for the combineovals.py case (but don't include also JRE, Chromium,
> whatever else products)

Perhaps we can separate platforms into two categories: OSs and
applications.  In that case, we could rephrase the goal as:

  We want the multi_platform_os_all platform element to represent
  all platforms that are OSs, but exclude applications.

In that case, it would automatically include SUSE & WRLinux,
but exclude Chromium, Firefox, and so on.

A corresponding multi_platform_app_all might (or might not)
be useful to group the non-OS platforms.  (I'm not suggesting
we create this now, but only that if it is ever appropriate,
it would match the "multi_platform_os_all" name.)

**Comment by shawndwells** [comment]
considering this resolved.
