### ISSUE TITLE
Make kernel_module_* remediation scripts idempotent

### ISSUE THREAD

**Issue by ybznek** [OpenSCAP/scap-security-guide#1369]
These script were created from templates and are not idempotent (they may have different path, later).
- bash/kernel_module_bluetooth_disabled.sh
- bash/kernel_module_usb-storage_disabled.sh

Fix mainly templates

**Comment by shawndwells** [comment]
This appears resolved by https://github.com/OpenSCAP/scap-security-guide/pull/1368. @ybznek can we resolve this issue?

**Comment by yuumasato** [comment]
I think this issue came out of #1368, not really fixing it.

**Comment by redhatrises** [comment]
That's correct. This issue is not yet fixed.
