### ISSUE TITLE
sed -i command not found

### ISSUE THREAD

**Issue by hooksie1** [OpenSCAP/scap-security-guide#1420]
Running on RHEL 7.2, I get sed -i: command not found for these following CCEs:

CCE-27471-2
CCE-27314-4
CCE-27363-1
CCE-27295-5

Removing $sed_command and just using sed -i works.

Using the same if statement in a test script, $sed_command works. Not sure what's going on.

**Comment by shawndwells** [comment]
does not appear to be an issue any longer. resolving. thank you for reporting @hooksie1 !

**Comment by yuumasato** [comment]
I'm hitting this issue. :)
