### ISSUE TITLE
RHEL 7.3 beta: no remediation for xccdf_org.ssgproject.content_rule_sysctl_net_ipv6_conf_all_accept_source_route

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#1442]
Title   Configure Kernel Parameter for Accepting Source-Routed Packets for All Interfaces
Rule    xccdf_org.ssgproject.content_rule_sysctl_net_ipv6_conf_all_accept_source_route
Ident   CCE-80179-5
Result  fail

**Comment by iankko** [comment]
Fixed by: https://github.com/OpenSCAP/scap-security-guide/pull/1393
