### ISSUE TITLE
RHEL 7.3 beta: no OVAL for xccdf_org.ssgproject.content_rule_wireless_disable_in_bios

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#1443]
Title   Disable WiFi or Bluetooth in BIOS
Rule    xccdf_org.ssgproject.content_rule_wireless_disable_in_bios
Ident   CCE-27397-9
Result  notchecked

**Comment by redhatrises** [comment]
@shawndwells I think that we should close this as I don't think that we can OVAL check this.

**Comment by shawndwells** [comment]
right now the report shows this:
![image](https://cloud.githubusercontent.com/assets/5713754/20087372/de327006-a545-11e6-8848-9613eec746ab.png)


Still getting questions on why this comes back as notchecked. Should we make the language stronger, identifying this control can't be automated?

**Comment by redhatrises** [comment]
Yes. Let's make the language stronger to say that it cannot be automated. There is another check like this one that we should do the same to as well.

**Comment by shawndwells** [comment]
i haven't gone through each notchecked (yet), but here's the complete list from rhel 7.3:

![image](https://cloud.githubusercontent.com/assets/5713754/20087460/a5779ac4-a546-11e6-83a5-80d81b27ecfb.png)

**Comment by shawndwells** [comment]
Removed physical hardware checks in core profiles, left remaining in DISA STIG (where they're free to include any craziness they mandate).
