### ISSUE TITLE
RHEl 7.3 beta: no remediation for xccdf_org.ssgproject.content_rule_accounts_tmout

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#1445]
Title   Set Interactive Session Timeout
Rule    xccdf_org.ssgproject.content_rule_accounts_tmout
Ident   CCE-27557-8
Result  fail

**Comment by iankko** [comment]
Fixed by: https://github.com/OpenSCAP/scap-security-guide/pull/1393
