### ISSUE TITLE
RHEL 7.3 beta: no remediation for xccdf_org.ssgproject.content_rule_accounts_password_pam_maxclassrepeat

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#1446]
Title   Set Password to Maximum of Consecutive Repeating Characters from Same Character Class
Rule    xccdf_org.ssgproject.content_rule_accounts_password_pam_maxclassrepeat
Ident   CCE-27512-3
Result  fail

**Comment by iankko** [comment]
Fixed by: https://github.com/OpenSCAP/scap-security-guide/pull/1393
