### ISSUE TITLE
RHEL 7.3 beta: no remediation for xccdf_org.ssgproject.content_rule_aide_periodic_cron_checking

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#1448]
Title   Configure Periodic Execution of AIDE
Rule    xccdf_org.ssgproject.content_rule_aide_periodic_cron_checking
Ident   CCE-26952-2
Result  fail

**Comment by redhatrises** [comment]
Closing as this works with the latest build.
