### ISSUE TITLE
RHEL 7.3 beta: no remediation for xccdf_org.ssgproject.content_rule_package_aide_installed

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#1450]
Title   Install AIDE
Rule    xccdf_org.ssgproject.content_rule_package_aide_installed
Ident   CCE-27096-7
Result  fail

**Comment by shawndwells** [comment]
Our remediation attempts to use YUM to install the packages, however a system may not be associated to a yum repo or RHN during install time. Is there another way we can install this package through remediation scripts during install?

**Comment by ybznek** [comment]
If somewhere is available (installation media?), we could install .rpm directly. But I don't think that generally working & clean solution exists.

**Comment by redhatrises** [comment]
Closing as this works with the latest build. 

The one problem that we would have for using .rpm directly would be handling any dependencies that may be associated with installing a package which I am not sure that that is something we want to tackle. If it is something that should be tackled, let's open a separate issue to track installing just rpms as an option for all remediation scripts.
