### ISSUE TITLE
Scientific Linux 6/Centos & other derivates empty <ident />

### ISSUE THREAD

**Issue by ybznek** [OpenSCAP/scap-security-guide#1452]
I have tried SL6, centos6/7

```
oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_common  /usr/share/xml/scap/ssg/content/ssg-centos6-ds.xml
```

**Result:**
```
Title   Ensure /var/log/audit Located On Separate Partition
Rule    xccdf_org.ssgproject.content_rule_partition_for_var_log_audit
Ident
          
Ident
          
Result  notapplicable
```

**Rhel6 result(different rule):**
```
Title   Require Client SMB Packet Signing, if using smbclient
Rule    xccdf_org.ssgproject.content_rule_require_smb_client_signing
Ident   CCE-26328-5
Ident   DISA FSO RHEL-06-000272
Result  notapplicable

```

**Xml:**
```
...
 <ns10:ident system="https://nvd.nist.gov/cce/index.cfm" />
...
```

**Expected result:**
Valid identifier / Or no empty "Ident" line

**Question:**

- Do we want have CCE/... identifiers for derivates or we rather want to remove them completely?
- Shall we fix it in opensca base to not print empty "Ident"?

**Comment by redhatrises** [comment]
@ybznek this is by design as the RHEL CCE numbers do not apply to CentOS and Scientific Linux. CentOS and Scientific Linux would get their own CCE numbers. However, agree that openscap base should not print an empty Ident.

**Comment by mpreisler** [comment]
I think we should just rip out the entire element and not keep an empty ident in SSG. OpenSCAP is doing the right thing by printing the empty ident. Let's fix this in SSG.
