### ISSUE TITLE
CCE-27127-0 Randomized Layout of Virtual address Space

### ISSUE THREAD

**Issue by hooksie1** [OpenSCAP/scap-security-guide#1454]
In the RHEL 7.2 STIG upstream the remediation script strips out the period and unerscores for the line in the /etc/sysctl.conf file.

Actual output:
kernelrandomizevaspace = 2

Expected output:
kernel.randomize_va_space = 2

**Comment by mpreisler** [comment]
The referenced PR doesn't touch the remediation in question. I think this was mistakedly marked as fixed by @redhatrises 

Reported by xmtrcv via IRC.

**Comment by xmtrcv** [comment]
Just a note: shared/remediations/bash/templates/remediation_functions contains the updated $stripped_key, but shared/xccdf/remediation_functions.xml lists the old one.

**Comment by shawndwells** [comment]
This maps to downstream RHEL BugZilla https://bugzilla.redhat.com/show_bug.cgi?id=1372060

**Comment by redhatrises** [comment]
Argh... If #1291 was fixed, this wouldn't have been a problem.
