### ISSUE TITLE
SSHD empty passwords - always pass

### ISSUE THREAD

**Issue by ybznek** [OpenSCAP/scap-security-guide#1475]
Fedora 24 (I haven't checked other systems)
```
$ sudo grep PermitEmptyPasswords /etc/ssh/sshd_config 
PermitEmptyPasswords yes
```
And rule xccdf_org.ssgproject.content_rule_sshd_disable_empty_passwords always pass

(I have used scap-workbench and tailored content, but it should not be related.)

**Comment by redhatrises** [comment]
@ybznek is the sshd service enabled or disabled?

**Comment by ybznek** [comment]
@redhatrises 
Disabled. I've tested it on personal computer when I run this service manually when I need.

With enabled service it works as expected. I can understand this behavior.

As user, I would like to get different result in such scenario than "pass". But we probably don't have better xccdf result value for that.

Maybe we can close this as "not a bug"

**Comment by radzy** [comment]
@ybznek, @redhatrises : I think the expectation is valid.  We could change the logic to check for installed instead of enabled.  That might make the results conform to expectations better

**Comment by redhatrises** [comment]
> With enabled service it works as expected. I can understand this behavior.

I believe that this is by design. I believe that the logic was that if a service is in use that it should be configured; otherwise, why configure the service if it is disabled by design. I vaguely remember some discussion on this several years back with @shawndwells. 

@shawndwells what are your thoughts here? Check if service is enabled or if package is installed? I believe that you had some reasoning to this for high security environments. I just don't remember what that was.

**Comment by mpreisler** [comment]
In my opinion this is not a bug.

**Comment by redhatrises** [comment]
> In my opinion this is not a bug.

Concur. Closing.

**Comment by shawndwells** [comment]
Classic DoD STIG baselines would check configuration options for services that were not installed or running. For example, having to PKI httpd.conf when Apache wasn't even installed!

To enhance usability, SSG OVAL checks were written to pass/fail only when the associated service is installed + running. For example, the OVAL code for this check:

`````
    <criteria comment="SSH is not being used or conditions are met"
    operator="OR">
      <extend_definition comment="sshd service is disabled"
      definition_ref="service_sshd_disabled" />
      <criterion comment="Check PermitEmptyPasswords in /etc/ssh/sshd_config"
      negate="true" test_ref="test_sshd_permitemptypasswords_no" />
    </criteria>
`````

An acknowledged loophole is that a SysAdmin may turn off the SSH daemon, run the scan, and show this rule as passing. But we can't protect from malicious insiders. 

There may be inconsistency between packages checking for service installation vs service enablement. IIRC, the service enablement is conditional of service installation... so `````service_sshd_disabled````` was chosen.
