### ISSUE TITLE
Update makefiles to change constant paths to macros for easier cross compilation

### ISSUE THREAD

**Issue by radzy** [OpenSCAP/scap-security-guide#1488]
The current makefiles specify paths such as /usr/share directly in the Makefile as a constant value.  For cross compilation, these need to be set to something else, such as $(SYSROOT)/usr/share.  And in general, at least in some programming circles, it is considered best to use macros for such things.

I'm opening this issue for discussion, at this time.  I would be happy to make the changes, if this kind of change is acceptable to the maintainers.  I would be happy to make the changes either everywhere (my preference), or just in the WRLinux subdirectory, at the discretion of the maintainers.

**Comment by mpreisler** [comment]
This is going to be fixed by https://github.com/OpenSCAP/scap-security-guide/pull/1377

**Comment by radzy** [comment]
Great.  Thanks @mpreisler .  I'll close this, then.  :-)

**Comment by mpreisler** [comment]
Nah, let's keep this open until it's actually fixed :-) I have referenced it in the PR so we'll close it when that gets merged.

Thx for reporting this!

**Comment by yuumasato** [comment]
This has been fixed by the new cmake build system.
