### ISSUE TITLE
Trouble with dangling references

### ISSUE THREAD

**Issue by radzy** [OpenSCAP/scap-security-guide#1489]
I may have found the reason for the original treatment of dangling references.

In the new code, I'm getting the message about dangling references in the command, "xsltproc --stringparam reverse_DNS org.$(VENDOR).content ..."  And the subsequent "oscap ds sds-compose" command generates an error due to the inserted strings.

At that time, the references really are dangling.  They exist in the oval file, but not in the $(OUT)/$(ID)-$(PROD)-xccdf.xml file used as input to xsltproc.  But if the error strings are removed, then the subsequent oscap ds sds-compose resolves them, but not correctly.

Sigh.  I'm using a heavily modified version of scap-security-guide, and it would be difficult to create a test case.  :-(

**Comment by mpreisler** [comment]
The XSLT that converts XCCDF 1.1 to 1.2 really only does that, it converts 1.1 to 1.2 and only the XCCDF file. The OVAL file shouldn't affect it in any way.

Make sure you really don't have dangling references in the XCCDF 1.1 file you are generating.

**Comment by radzy** [comment]
Thanks, @mpreisler .  Yes, I know it's definitely something I'm doing, since other OSs/apps work.   The rules that are omitted are located in shared, and I have updated the platform list for those rules.  But they don't show up in my xccdf file, and I haven't been able to figure out why not.

**Comment by radzy** [comment]
Hmmm.  Turns out this is, in some way, a dup of #1290.  The relevant input file had a typo that made it incorrect syntax.  (An extra "</Group>" directive.)
