### ISSUE TITLE
OVAL 5.10 definitions referencing OVAL 5.11 definition

### ISSUE THREAD

**Issue by yuumasato** [OpenSCAP/scap-security-guide#1526]
The OVAL 5.10 definitions of `sssd_memcache_timeout`, `sssd_ssh_know_hosts_timeout` and `sssd_offline_cred_expiration` in RHEL/7 reference an OVAL 5.11 definition: `service_sssd_disabled`.

Problem:
When building content for RHEL/7 with OVAL 5.10 the `service_sssd_disabled` definition is not included and the references to it in `sssd_memcache_timeout`, `sssd_ssh_know_hosts_timeout` and `sssd_offline_cred_expiration` are left unmatched.

How to reproduce:
$ cd RHEL/7 && make content OVAL_5_11=1

Errors reported by make:
`oscap ds sds-compose output/ssg-rhel7-xccdf-1.2.xml output/ssg-rhel7-ds.xml
File 'RHEL/7/output/ssg-rhel7-ds.xml' line 532: Element '{http://oval.mitre.org/XMLSchema/oval-definitions-5}extend_definition': No match found for key-sequence ['oval:ssg-service_sssd_disabled:def:1'] of keyref '{http://oval.mitre.org/XMLSchema/oval-definitions-5}extendKeyRef'.
File 'RHEL/7/output/ssg-rhel7-ds.xml' line 548: Element '{http://oval.mitre.org/XMLSchema/oval-definitions-5}extend_definition': No match found for key-sequence ['oval:ssg-service_sssd_disabled:def:1'] of keyref '{http://oval.mitre.org/XMLSchema/oval-definitions-5}extendKeyRef'.
File 'RHEL/7/output/ssg-rhel7-ds.xml' line 564: Element '{http://oval.mitre.org/XMLSchema/oval-definitions-5}extend_definition': No match found for key-sequence ['oval:ssg-service_sssd_disabled:def:1'] of keyref '{http://oval.mitre.org/XMLSchema/oval-definitions-5}extendKeyRef'.
OpenSCAP Error: Invalid SCAP Source Datastream (1.2) content in /home/wsato/scap-security-guide/RHEL/7/output/ssg-rhel7-ds.xml. [oscap_source.c:319]
Makefile:55: recipe for target 'content' failed
make: *** [content] Error 1`

One of the causes of #1344

**Comment by redhatrises** [comment]
Not a blocker as OVAL version 5.11 is recommended/desired over 5.10.

**Comment by mpreisler** [comment]
> Not a blocker as OVAL version 5.11 is recommended/desired over 5.10. PR shortly.

I believe @yuumasato correctly marked this as a blocker because without this fixed the 5.10 content would be released in an invalid state. That definitely is a blocker for the release.
