### ISSUE TITLE
CCE-27351-6: screen not installed during system load

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#1549]
downstream BZ https://bugzilla.redhat.com/show_bug.cgi?id=1372066

**Comment by redhatrises** [comment]
@shawndwells can you re-test this with the latest master? Anaconda remediation scripts was merged.

**Comment by shawndwells** [comment]
Would have to generate installation media to test. Can tinker with that over the holiday.

**Comment by mpreisler** [comment]
This has been fixed by the Anaconda remediation script merges. See bugzilla for more details.

Reopen if necessary.
