### ISSUE TITLE
Kernel nousb Option Disabling Physical Keyboards

### ISSUE THREAD

**Issue by fcaviggia** [OpenSCAP/scap-security-guide#1608]
The `nousb` kernel option introduced with scap-security-guide-0.1.31 is preventing physical keyboards from working.

**Comment by lkkevin** [comment]
Hi Frank, i tried scap-security-guide-0.1.30 but it still disabled my USB mouse and keyboard

**Comment by lkkevin** [comment]
I tried multiple ways reinstall the USB-storage device without success.  Finally i had to use scap-security-guide-0.1.25-3.el7.noarch.rpm because i needed usb mouse and keyboard.

**Comment by fcaviggia** [comment]
Let me check into it some more.

**Comment by johnclendenen** [comment]
Hello, I'm pretty new to OpenSCAP but am experimenting with it in CentOS.

I believe I am having the same issue in CentOS 7.3. I see the following messages:

usbserial: usb_serial_init - usb_register failed
usbserial: usb_serial_init - returning with error -19

This prevents me from being able to enter the LUKS password. The unusual thing is that it prevents any keyboard entry, even over IPMI KVM and IPMI SOL. Maybe that's expected if the USB driver is disabled. My understanding of the inner workings of IPMI is limited.

This issue occurs after initial install with the server stig selected under security policy.

**Comment by fcaviggia** [comment]
I ended up creating a 'workaround' in my hardening scripts (https://github.com/RedHatGov/ssg-el7-kickstart/) - usbguard is now included as part of RHEL 7.4, so I don't think adding the 'nousb' option to the kernel is a good policy because it makes a system 'secure' but also 'unusable'.

**Comment by shawndwells** [comment]
On 8/8/17 3:33 PM, johnclendenen wrote:
>
> Hello, I'm pretty new to OpenSCAP but am experimenting with it in CentOS.
>
> I believe I am having the same issue in CentOS 7.3. I see the
> following messages:
>
> usbserial: usb_serial_init - usb_register failed
> usbserial: usb_serial_init - returning with error -19
>
> This prevents me from being able to enter the LUKS password. The
> unusual thing is that it prevents any keyboard entry, even over IPMI
> KVM and IPMI SOL. Maybe that's expected if the USB driver is disabled.
> My understanding of the inner workings of IPMI is limited.
>
> This issue occurs after initial install with the server stig selected
> under security policy.
>

If using downstream releases (e.g. scap-security-guide in RHEL or
CentOS), consider upgrading the RPM. The profiles were updated to block
usb-storage, vs all of USB, specifically for this issue.

In (upstream) code:
https://github.com/OpenSCAP/scap-security-guide/blob/master/RHEL/7/input/profiles/ospp-rhel7.xml#L265#L268

SCAP Security Guide content should work on all RHEL 7.x versions....
should be able to pull the RHEL 7.4 RPM and run on 7.3 if you need to.

**Comment by johnclendenen** [comment]
Sorry, I didn't realize that RHEL 7.4 had come out. I'll just check back when CentOS 7.4 is released. I'm only just starting to look into OpenSCAP, so no rush here.

Thanks

**Comment by shawndwells** [comment]
Current content uses ``bootloader_nousb_argument`` to prevent booting from USB devices, then ``kernel_module_usb-storage_disabled`` to block usb storage. Resolving ticket.
