### ISSUE TITLE
Submit Vendor STIG intent form for OpenShift v3

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#1627]

**Comment by shawndwells** [comment]
Ref: http://iase.disa.mil/stigs/Pages/vendor-process.aspx

http://iasecontent.disa.mil/stigs/doc/U_Vendor_STIG_Intent_Form.docx

**Comment by shawndwells** [comment]
Internal gdocs URL : https://docs.google.com/document/d/1IhiglKdDfhfuoH0Ah2ESaDe1BT_9uxSXCugQi9OS_Y4/edit

Will open once formally completed

**Comment by KedneckInc** [comment]
The project I'm working on is being pushed to move onto OpenShift, and requires STIGing of our nodes.  Can you give me any update on the status of this issue?

**Comment by shawndwells** [comment]
Creating a NIST National Checklist vs DISA STIG. Closing.
