### ISSUE TITLE
	xccdf_org.ssgproject.content_rule_firewalld_sshd_disabled should pass when sshd installed

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#1632]

**Comment by redhatrises** [comment]
@shawndwells does this make sense? If a rule is enabled to make sure that the firewall does not allow ssh access, why should this pass if the `openssh-server` rpm is installed?

**Comment by shawndwells** [comment]
So, the XCCDF:

``
<Rule id="firewalld_sshd_disabled" prodtype="rhel7">
<title>Remove SSH Server <tt>firewalld</tt> Firewall exception (Unusual)</title>
<description>By default, inbound connections to SSH's port are allowed. If
the SSH server is not being used, this exception should be removed from the
firewall configuration.
``

I was originally reading as "if SSH is installed, this exception should not be removed, and the rule should pass."

But you're right.... there certainly could be use cases where SSH server is installed and port 22 is supposed to be closed (e.g., SSH port knocking or using alternative listening ports).

**Comment by shawndwells** [comment]
resolving this issue, noting this use case as above, and someone can re-open if they feel strongly.

looking at you, @aapuch
