### ISSUE TITLE
Failure Validate OVAL.XML

### ISSUE THREAD

**Issue by fearturtle03** [OpenSCAP/scap-security-guide#1643]
I am having an issue with running a scan so went to try and validate the OVAL and XCCDF files. The XCCDF validates but the OVAL does not. 

On my Oracle Linux 6 I have installed:  -openscap.1.0.10-3.0.2.e16.x86_64.rpm &  openscap-scanner & scap-security-guide-0.1.28-2.0.2.e16.noarch. 

When I run:  oscap info /usr/share/xml/scap/ssg/content/ssg-rhel6-oval.xml  I get the following:
_Document type: OVAL Definitions
OVAL version: 5.11
Generated: 2016-04-26T22:56:03
Imported: 2016-04-26T22:56:48
Segmentation fault (core dumped)_

I do not get that for info on the XCCDF.xml so is that oval.xml my problem? 

Also when I try and validate the oval.xml per the Oracle Security guide I get the following:
_# oscap oval validate /usr/share/xml/scap/ssg/content/ssg-rhel6-oval.xml && echo "ok" || echo "exit code = $? not ok"
OpenSCAP Error: Schema file not found when trying to validate '/usr/share/xml/scap/ssg/content/ssg-rhel6-oval.xml' [oscapxml.c:332]
exit code = 1 not ok_

Where is the error log and what should I be looking for? 

Thank You

**Comment by mpreisler** [comment]
Hi @fearturtle03 

You are using `openscap 1.0.x` which is an old version that doesn't support OVAL 5.11. I find it bizarre that Oracle packages old openscap but very recent scap-security-guide with OVAL 5.11. I recommend submitting a bug to Oracle about this.

In the meantime you can download the OVAL 5.10 version of SSG and use that, check out https://github.com/OpenSCAP/scap-security-guide/releases/tag/v0.1.31 and look for the ZIP file with oval-5.10 suffix. There are such zip files for all recent SSG releases. For your SSG 0.1.28 the 5.10 zip file is https://github.com/OpenSCAP/scap-security-guide/releases/download/v0.1.28/scap-security-guide-0.1.28-oval-5.10.zip

Hope this helps.

I will keep this open to investigate the segfault when running `oscap info` against an unsupported version of OVAL.

**Comment by fearturtle03** [comment]
Thank You!

What version of openscap supports OVAL 5.11?

So to use the OVAL 5.10 I would use the RHEL6-ds.xml in place of the RHEL-oval.xml correct?

**Comment by mpreisler** [comment]
> What version of openscap supports OVAL 5.11?

`openscap 1.2.x`, the latest release is 1.2.13, see https://github.com/OpenSCAP/openscap/releases/tag/1.2.13



> So to use the OVAL 5.10 I would use the RHEL6-ds.xml in place of the RHEL-oval.xml correct?

No, it will still be called ssg-rhel6-ds.xml or ssg-rhel6-oval.xml but if it's coming from the oval-5.10 ZIP it will only be using OVAL 5.10.

**Comment by fearturtle03** [comment]
Ok the .zip files downloaded from the links   0.1.28-OVAL-5.10  only contained -ds.xml files, I did not see any OVAL-xml files in the download.

**Comment by mpreisler** [comment]
@fearturtle03 I recommend using the DS files, they contain everything you need. If you really need the separate OVAL and XCCDF files you can always do:

```
oscap ds sds-split ssg-rhel6-ds.xml $TARGET_DIR
```

**Comment by fearturtle03** [comment]
Ok thanks. So I am trying to follow the Oracle Security Guide and it says to do the following:

# oscap xccdf eval --profile server \
  --results /tmp/`hostname`-ssg-results.xml \
  --report /var/www/html/`hostname`-ssg-results.html \
  --cpe /usr/share/xml/scap/ssg/content/ssg-rhel6-cpe-dictionary.xml \
        /usr/share/xml/scap/ssg/content/ssg-rhel6-xccdf.xml

Should I be using the ds-xml file in place of the xccdf.xml then?

**Comment by fearturtle03** [comment]
Also am I to assume the ds-xml file when used requires access to the internet?

**Comment by mpreisler** [comment]
You can drop the --cpe argument and use `ssg-rhel6-ds.xml`. Let's close this, please ask Oracle for support.
