### ISSUE TITLE
Suggested fix for xccdf_org.ssgproject.content_rule_gconf_gnome_disable_ctrlaltdel_reboot results in continued violation

### ISSUE THREAD

**Issue by biddster** [OpenSCAP/scap-security-guide#1650]
My Centos6 and RHEL6 boxes are flagging up `xccdf_org.ssgproject.content_rule_gconf_gnome_disable_ctrlaltdel_reboot`. I've followed the guideline and applied:

```
sudo gconftool-2 --direct \
  --config-source xml:readwrite:/etc/gconf/gconf.xml.mandatory \
  --type string \
  --set /apps/gnome_settings_daemon/keybindings/power ""
```

However, I'm still seeing a violation on subsequent scans.

I've had a look at the def here:

https://github.com/OpenSCAP/scap-security-guide/blob/master/RHEL/6/input/oval/gconf_gnome_disable_ctrlaltdel_reboot.xml

I'm wondering if it's the second test for `/etc/gconf/gconf.xml.mandatory/%gconf-tree.xml` as that file doesn't appear to exist?

However, `/etc/gconf/gconf.xml.defaults/%gconf-tree.xml` does exist?

**Comment by shawndwells** [comment]
Inside the oval, the "operator="OR"" will evaluate against both test_gnome_disable_ctrlaltdel_reboot and test_gconf_tree_gnome_disable_ctrlaltdel_reboot .... so I don't believe it's the 2nd test:

`````
    <criteria operator="OR">
      <extend_definition comment="GConf2 installed" definition_ref="package_GConf2_installed" negate="true" />
      <criterion comment="set Ctrl-Alt-Del key sequence to nothing" test_ref="test_gnome_disable_ctrlaltdel_reboot" />
      <criterion comment="set Ctrl-Alt-Del key sequence to nothing" test_ref="test_gconf_tree_gnome_disable_ctrlaltdel_reboot" />
    </criteria>
`````

Once you ran the gconftool-2 command, does neither of the following files+settings exist? I don't have a RHEL6 machine to quickly test.

`````   <ind:filepath>/etc/gconf/gconf.xml.mandatory/apps/gnome_settings_daemon/keybindings/%gconf.xml</ind:filepath>
    <ind:xpath>/gconf/entry[@name='power']/stringvalue[1]/text()</ind:xpath>
`````

or 
`````
    <ind:filepath>/etc/gconf/gconf.xml.mandatory/%gconf-tree.xml</ind:filepath>
    <ind:xpath>/gconf/dir/dir/dir/entry[@name='power']/stringvalue[1]/text()</ind:xpath>
`````

**Comment by redhatrises** [comment]
The issue is that `<ind:value_of>` cannot process an empty element. A fix is coming shortly.

**Comment by biddster** [comment]
Thanks for the in progress fix.

However, I still haven't found a RHEL box where `/etc/gconf/gconf.xml.mandatory/%gconf-tree.xml` actually exists.

I've only ever found it under `/etc/gconf/gconf.xml.defaults/%gconf-tree.xml`.

**Comment by redhatrises** [comment]
@biddster `/etc/gconf/gconf.xml.mandatory/%gconf-tree.xml` doesn't exist by default. However if you use `gconf-editor`, it will create `%gconf-tree.xml`. You can also create it yourself and deploy that instead of having to run `gconftool-2` on every system. Also if `%gconf-tree.xml` sits at the top of the precedence tree, so if `/etc/gconf/gconf.xml.mandatory/%gconf-tree.xml` exists, any other settings under `/etc/gconf/gconf.xml.mandatory` will be ignored.

**Comment by biddster** [comment]
@redhatrises Thanks for the clarification, that makes sense now. I presume that `/etc/gconf/gconf.xml.defaults/%gconf-tree.xml` is used as the template when it's created?
