### ISSUE TITLE
non-existent selector error

### ISSUE THREAD

**Issue by autonomicpilot** [OpenSCAP/scap-security-guide#1654]
Running this command:
----------
oscap xccdf eval --fetch-remote-resources --profile xccdf_org.ssgproject.content_profile_stig-rhel6-server-upstream --report /root/output_before.html ssg-centos6-ds.xml

Results in this output:
----------
OpenSCAP Error: Attempt to get non-existent selector "15" from variable "xccdf_org.ssgproject.content_value_var_accounts_password_minlen_login_defs" [xccdf_policy.c:463]
Invalid selector '15' for xccdf:value/@id='xccdf_org.ssgproject.content_value_var_accounts_password_minlen_login_defs'. Using null value instead. [xccdf_policy.c:2137]

The fix:
----------
Add "\<value selector="15">15</value>" under "\<Value id="var_accounts_password_minlen_login_defs" type="number" >" in file: "/root/scap-security-guide/RHEL/6/input/xccdf/system/accounts/restrictions/password_expiration.xml"

**Comment by redhatrises** [comment]
Thanks @autonomicpilot. Fix is pending approval.
