### ISSUE TITLE
Add ChangeLog file in the repository

### ISSUE THREAD

**Issue by pthierry38** [OpenSCAP/scap-security-guide#1660]
Hi all,

I'm currently packaging the scap-security-guide project in Debian. For this work, I need an upstream changelog in the repository to be able to deploy it through the ssg packages.

Is it possible to keep the Release Notes of the last tagged version in the repository so that I can deploy it in the package ? This file could be updated at each new tag.

**Comment by redhatrises** [comment]
@pthierry38 not knowing what the Debian project requires can you say something like "Rebased to upstream release v1.2.3. See <release notes link>"?

It seems as if a lot of projects are moving away from Changelog and pointing to a release notes web page.

**Comment by pthierry38** [comment]
@redhatrises Ok I will check how to use a release note link instead
