### ISSUE TITLE
We don't build JBoss/EAP/5

### ISSUE THREAD

**Issue by ybznek** [OpenSCAP/scap-security-guide#1683]
Maybe I am wrong,
but I don't see EAP in https://raw.githubusercontent.com/OpenSCAP/scap-security-guide/master/Makefile 

Release notes:
```[Enhancement] JBoss EAP 5 XCCDF and OVAL updates```
```[Enhancement][EAP/5] Add build capability and cleanup```
But I don't see it in archive https://github.com/OpenSCAP/scap-security-guide/releases/tag/v0.1.31

What is difference between https://github.com/OpenSCAP/scap-security-guide/tree/master/JBossEAP5 and https://github.com/OpenSCAP/scap-security-guide/tree/master/JBoss/EAP/5 ?

And I am not able to build JBoss/EAP/5

Maybe we really don't want to release it, but we should investigate it.

**Comment by redhatrises** [comment]
Not a blocker. `JBoss/EAP/5` is still in the process of being converted over to SSG. 
`JBossEAP5` (which is the official version for now) is being converted over to `JBoss/EAP/5`. I just don't have the cycles right now to finish the conversion. See #1046.

**Comment by ybznek** [comment]
Ok. I will remove label.
