### ISSUE TITLE
Update sshd approved cipher and MAC checks

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#1686]
Right now OVAL checks for the enablement of *all* FIPS ciphers and MACs. A system that is configured to only enable a single cipher, while properly configured, would fail the OVAL. Need to update OVAL to allow any combination of approved ciphers.

**Comment by yuumasato** [comment]
I think https://github.com/OpenSCAP/scap-security-guide/pull/1767 and https://github.com/OpenSCAP/scap-security-guide/pull/1908 have fixed this.
