### ISSUE TITLE
Verify User Who Owns /etc/cron.allow file

### ISSUE THREAD

**Issue by cpellitt** [OpenSCAP/scap-security-guide#1689]
CCE-80378-3 Verify User Who Owns /etc/cron.allow file states:
If /etc/cron.allow exists, it must be owned by root.

However, the OVAL requires that /etc/cron.allow exists.

**Comment by shawndwells** [comment]
ref: https://github.com/OpenSCAP/scap-security-guide/blob/master/RHEL/7/input/oval/file_owner_cron_allow.xml
