### ISSUE TITLE
Set the GNOME3 Login Warning Banner Text

### ISSUE THREAD

**Issue by cpellitt** [OpenSCAP/scap-security-guide#1691]
CCE-26892-0 Set the GNOME3 Login Warning Banner Text seems to always fail the scan when \n is included as part of banner-message-text.

I think the "login_banner_text" variable is using a regex that matches a new line, but not a literal \n.

This is the dconf file being checked:
```
[org/gnome/login-screen]
banner-message-text=string 'You are accessing a U.S. Government (USG) Information System (IS) that is provided for USG-authorized use only. By using this IS (which includes any device attached to this IS), you consent to the following conditions:\n-The USG routinely intercepts and monitors communications on this IS for purposes including, but not limited to, penetration testing, COMSEC monitoring, network operations and defense, personnel misconduct (PM), law enforcement (LE), and counterintelligence (CI) investigations.\n-At any time, the USG may inspect and seize data stored on this IS.\n-Communications using, or data stored on, this IS are not private, are subject to routine monitoring, interception, and search, and may be disclosed or used for any USG-authorized purpose.\n-This IS includes security measures (e.g., authentication and access controls) to protect USG interests -- not for your personal benefit or privacy.\n-Notwithstanding the above, using this IS does not constitute consent to PM, LE or CI investigative searching or monitoring of the content of privileged communications, or work product, related to personal representation or services by attorneys, psychotherapists, or clergy, and their assistants. Such communications and work product are private and confidential. See User Agreement for details.'
```

**Comment by ajd394** [comment]
i think the issue may be that the word 'string' should not appear after the '=' . When i run 'dconf update' it throws and error on this line.

**Comment by ajd394** [comment]
The following documentation shows that the current check/fix text has an error.

[https://help.gnome.org/admin/system-admin-guide/stable/login-banner.html.en](https://help.gnome.org/admin/system-admin-guide/stable/login-banner.html.en)

**Comment by cipherboy** [comment]
@ajd394 Good catch! Do you want to fix this? Looks like this occurs in a few other places as well.

- This issue: [here](https://github.com/OpenSCAP/scap-security-guide/blob/master/linux_os/guide/system/accounts/accounts-banners/gui_login_banner/dconf_gnome_login_banner_text.rule#L16) and [here](https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/checks/oval/dconf_gnome_login_banner_text.xml#L44).
- Similarly in the ctrl-alt-delete reboot rules [here](https://github.com/OpenSCAP/scap-security-guide/blob/master/linux_os/guide/system/software/gnome/gnome_system_settings/dconf_gnome_disable_ctrlaltdel_reboot.rule#L7) and [here](https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/checks/oval/dconf_gnome_disable_ctrlaltdel_reboot.xml#L30)
- And in the screensaver: [here](https://github.com/OpenSCAP/scap-security-guide/blob/master/linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_mode_blank.rule#L12), and [here](https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/checks/oval/dconf_gnome_screensaver_mode_blank.xml#L33)

**Comment by ajd394** [comment]
@cipherboy Ay dios mio! errors everywhere! I can fix it! However, I haven't made a contribution before so can you look over my changes before I submit a PR?

**Comment by cipherboy** [comment]
@ajd394 Happy to! Drop a link when you have the fix. :)
