### ISSUE TITLE
Options for Removable Media Partitions

### ISSUE THREAD

**Issue by cpellitt** [OpenSCAP/scap-security-guide#1692]
For the following rules:
CCE-80146-4 Add nodev Option to Removable Media Partitions
CCE-80147-2 Add noexec Option to Removable Media Partitions
CCE-80148-0 Add nosuid Option to Removable Media Partitions

I think there is a problem with the OVAL for these rules. The only way I could get them to pass is to create an entry for the cdrom in /etc/fstab and to have it actively mounted. It doesn't make sense for either of these conditions to be required, but it always seems to fail otherwise.

**Comment by redhatrises** [comment]
This should be fixed by #1776. Please re-open if not.
