### ISSUE TITLE
Login.defs umask check results in error

### ISSUE THREAD

**Issue by cpellitt** [OpenSCAP/scap-security-guide#1699]
CCE-80205-8 Ensure the Default Umask is Set Correctly in login.defs

This check gets a result of "error" using RHEL 7.

```
# grep -i umask /etc/login.defs
UMASK           077
```

[https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/oval/accounts_umask_etc_login_defs.xml](https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/oval/accounts_umask_etc_login_defs.xml)

**Comment by redhatrises** [comment]
When fixing this, we should verify and/or fix https://bugzilla.redhat.com/show_bug.cgi?id=1404398 as well.

**Comment by redhatrises** [comment]
@yuumasato did #1945 fix the first part of this PR (except for the BZ)?

**Comment by yuumasato** [comment]
@redhatrises The rule does not error anymore.
Added two tests to check it in https://github.com/OpenSCAP/scap-security-guide/pull/2485.

**Comment by redhatrises** [comment]
Thanks @yuumasato. Closing this ticket as the issue has been fixed, and there is already a BZ for the other one. Fixing the BZ is not a huge priority right now.
