### ISSUE TITLE
RHEL Desktop is not a supported platform

### ISSUE THREAD

**Issue by cpellitt** [OpenSCAP/scap-security-guide#1700]
[https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/oval/installed_OS_is_rhel7.xml](https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/oval/installed_OS_is_rhel7.xml)
[https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/oval/installed_OS_is_rhel6.xml](https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/oval/installed_OS_is_rhel6.xml)

RHEL Desktop is not detected as a RHEL 6/7 system. Only server, workstation, and computenode pass the OVAL check.

```
# rpm -qa | grep redhat-release
redhat-release-client-7.3-4.el7.x86_64
```

**Comment by redhatrises** [comment]
Corresponding bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1402363
