### ISSUE TITLE
Auditd Kernel Module Arch

### ISSUE THREAD

**Issue by cpellitt** [OpenSCAP/scap-security-guide#1714]
When testing these rules on RHEL 7 64-bit:
xccdf_org.ssgproject.content_rule_audit_rules_kernel_module_loading (CCE-80415-3)
xccdf_org.ssgproject.content_rule_audit_rules_kernel_module_loading_init (CCE-80414-6)
xccdf_org.ssgproject.content_rule_audit_rules_kernel_module_loading_delete (CCE-80415-3)

Using only this audit rule returns fail:
`-a always,exit -F arch=b64 -S init_module -S delete_module -k modules`

Using these audit rules returns pass:
```
-a always,exit -F arch=b32 -S init_module -S delete_module -k modules
-a always,exit -F arch=b64 -S init_module -S delete_module -k modules
```

According to the description, arch=b32 is not required on 64-bit systems, but the check fails if it is not included.

**Comment by konstruktoid** [comment]
Have a look at https://github.com/OpenSCAP/scap-security-guide/issues/1999

**Comment by cpellitt** [comment]
The explanation from [#1999](https://github.com/OpenSCAP/scap-security-guide/issues/1999) confirms that only one architecture should be checked.

> In some cases it makes sense to audit just syscalls specific for that specific architecture. For example for kernel module loading system calls it's enough to check the 64-bit versions of those syscalls on 64-bit system, since it's not possible to load 64-bit kernel module on 32-bit system for example.

**Comment by redhatrises** [comment]
Closing. System should check for both 32bit and 64bit kernel instances until 32bit kernels are no longer around. See https://github.com/GovReady/govready/issues/65#issuecomment-68658479 for the reasoning.
