### ISSUE TITLE
Update scap-security-content for official RHEL 7 STIG

### ISSUE THREAD

**Issue by dsirrine** [OpenSCAP/scap-security-guide#1758]
STIG version 1 release 1 was released 3/13/2017 at http://iase.disa.mil/stigs/os/unix-linux/Pages/index.aspx

**Comment by shawndwells** [comment]
threw an HTML edition of the DISA content here:

http://people.redhat.com/swells/U_Red_Hat_Enterprise_Linux_7_V1R1_Manual_STIG/stig.html#V-71951

**Comment by shawndwells** [comment]
work in progress - https://github.com/OpenSCAP/scap-security-guide/pull/1773

**Comment by shawndwells** [comment]
done
