### ISSUE TITLE
needs mapping/rule: SRG-OS-000480-GPOS-00227, SV-86673r1_rule, RHEL-07-021040 (umask 077)

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#1843]

**Comment by shawndwells** [comment]
<Group id="V-72049"><title>SRG-OS-000480-GPOS-00227</title><description>&lt;GroupDescription&gt;&lt;/GroupDescription&gt;</description><Rule id="SV-86673r1_rule" severity="medium" weight="10.0"><version>RHEL-07-021040</version><title>The umask must be set to 077 for all local interactive user accounts.</title><description>&lt;VulnDiscussion&gt;The umask controls the default access mode assigned to newly created files. A umask of 077 limits new files to mode 700 or less permissive. Although umask can be represented as a four-digit number, the first digit representing special access modes is typically ignored or required to be "0". This requirement applies to the globally configured system defaults and the local interactive user defaults for each account on the system.&lt;/VulnDiscussion&gt;&lt;FalsePositives&gt;&lt;/FalsePositives&gt;&lt;FalseNegatives&gt;&lt;/FalseNegatives&gt;&lt;Documentable&gt;false&lt;/Documentable&gt;&lt;Mitigations&gt;&lt;/Mitigations&gt;&lt;SeverityOverrideGuidance&gt;&lt;/SeverityOverrideGuidance&gt;&lt;PotentialImpacts&gt;&lt;/PotentialImpacts&gt;&lt;ThirdPartyTools&gt;&lt;/ThirdPartyTools&gt;&lt;MitigationControl&gt;&lt;/MitigationControl&gt;&lt;Responsibility&gt;&lt;/Responsibility&gt;&lt;IAControls&gt;&lt;/IAControls&gt;</description><reference><dc:title>DPMS Target Red Hat 7</dc:title><dc:publisher>DISA</dc:publisher><dc:type>DPMS Target</dc:type><dc:subject>Red Hat 7</dc:subject><dc:identifier>2777</dc:identifier></reference><ident system="http://iase.disa.mil/cci">CCI-000318</ident><ident system="http://iase.disa.mil/cci">CCI-000368</ident><ident system="http://iase.disa.mil/cci">CCI-001812</ident><ident system="http://iase.disa.mil/cci">CCI-001813</ident><ident system="http://iase.disa.mil/cci">CCI-001814</ident><fixtext fixref="F-78401r1_fix">Remove the umask statement from all local interactive users’ initialization files. ^M
^M
If the account is for an application, the requirement for a umask less restrictive than "077" can be documented with the Information System Security Officer, but the user agreement for access to the account must specify that the local interactive user must log on to their account first and then switch the user to the application account with the correct option to gain the account’s environment variables.</fixtext><fix id="F-78401r1_fix" /><check system="C-72281r1_chk"><check-content-ref name="M" href="DPMS_XCCDF_Benchmark_RHEL_7_STIG.xml" /><check-content>Verify that the default umask for all local interactive users is "077".^M
^M
Identify the locations of all local interactive user home directories by looking at the "/etc/passwd" file.^M
^M
Check all local interactive user initialization files for interactive users with the following command:^M
^M
Note: The example is for a system that is configured to create users home directories in the "/home" directory.^M
^M
# grep -i umask /home/*/.*^M
^M
If any local interactive user initialization files are found to have a umask statement that has a value less restrictive than "077", this is a finding.</check-content></check></Rule></Group>

**Comment by trevor-vaughan** [comment]
So, we set this up in `/etc/profile.d` so that it applies evenly to all users that log into the system.

Checking home directories can only be done if the home directories are locally mounted.

Does anyone know if `auditd` picks up a `umask` change at login time? It *should* and, if it does, then I would like to propose that as the appropriate resolution when combined with setting the `umask` in `/etc/profile.d` since it's effectively the same as me typing `umask` at the command line.

As an aside, how serious is changing your `umask` at runtime? Should we be booting users off of the system, changing it back, or what?

**Comment by shawndwells** [comment]
previously mapped:

https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/guide/system/accounts/accounts-session/user_umask/accounts_umask_interactive_users.rule#L26
