### ISSUE TITLE
needs mapping/rule: SRG-OS-000364-GPOS-00151, SV-86699r1_rule, RHEL-07-021700 (grub bootloader on removable media)

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#1844]

**Comment by shawndwells** [comment]
<Group id="V-72075"><title>SRG-OS-000364-GPOS-00151</title><description>&lt;GroupDescription&gt;&lt;/GroupDescription&gt;</description><Rule id="SV-86699r1_rule" severity="medium" weight="10.0"><version>RHEL-07-021700</version><title>The system must not allow removable media to be used as the boot loader unless approved.</title><description>&lt;VulnDiscussion&gt;Malicious users with removable boot media can gain access to a system configured to use removable media as the boot loader. If removable media is designed to be used as the boot loader, the requirement must be documented with the Information System Security Officer (ISSO).&lt;/VulnDiscussion&gt;&lt;FalsePositives&gt;&lt;/FalsePositives&gt;&lt;FalseNegatives&gt;&lt;/FalseNegatives&gt;&lt;Documentable&gt;false&lt;/Documentable&gt;&lt;Mitigations&gt;&lt;/Mitigations&gt;&lt;SeverityOverrideGuidance&gt;&lt;/SeverityOverrideGuidance&gt;&lt;PotentialImpacts&gt;&lt;/PotentialImpacts&gt;&lt;ThirdPartyTools&gt;&lt;/ThirdPartyTools&gt;&lt;MitigationControl&gt;&lt;/MitigationControl&gt;&lt;Responsibility&gt;&lt;/Responsibility&gt;&lt;IAControls&gt;&lt;/IAControls&gt;</description><reference><dc:title>DPMS Target Red Hat 7</dc:title><dc:publisher>DISA</dc:publisher><dc:type>DPMS Target</dc:type><dc:subject>Red Hat 7</dc:subject><dc:identifier>2777</dc:identifier></reference><ident system="http://iase.disa.mil/cci">CCI-000318</ident><ident system="http://iase.disa.mil/cci">CCI-000368</ident><ident system="http://iase.disa.mil/cci">CCI-001812</ident><ident system="http://iase.disa.mil/cci">CCI-001813</ident><ident system="http://iase.disa.mil/cci">CCI-001814</ident><fixtext fixref="F-78427r1_fix">Remove alternate methods of booting the system from removable media or document the configuration to boot from removable media with the ISSO.</fixtext><fix id="F-78427r1_fix" /><check system="C-72307r1_chk"><check-content-ref name="M" href="DPMS_XCCDF_Benchmark_RHEL_7_STIG.xml" /><check-content>Verify the system is not configured to use a boot loader on removable media.^M
^M
Note: GRUB 2 reads its configuration from the "/boot/grub2/grub.cfg" file on traditional BIOS-based machines and from the "/boot/efi/EFI/redhat/grub.cfg" file on UEFI machines.^M
^M
Check for the existence of alternate boot loader configuration files with the following command:^M
^M
# find / -name grub.cfg^M
/boot/grub2/grub.cfg^M
^M
If a "grub.cfg" is found in any subdirectories other than "/boot/grub2" and "/boot/efi/EFI/redhat", ask the System Administrator if there is documentation signed by the ISSO to approve the use of removable media as a boot loader. ^M
^M
Check that the grub configuration file has the set root command in each menu entry with the following commands:^M
^M
# grep -c menuentry /boot/grub2/grub.cfg^M
1^M
# grep ‘set root’ /boot/grub2/grub.cfg^M
set root=(hd0,1)^M
^M
If the system is using an alternate boot loader on removable media, and documentation does not exist approving the alternate configuration, this is a finding.</check-content></check></Rule></Group>

**Comment by trevor-vaughan** [comment]
I'm looking at this and I just realized something. There needs to be a standardized location and format for admins to document *on the system* how something doesn't apply. Then the scanner could just pick up that justification and auto-report it. It would save a LOT of time for a lot of people.

**Comment by shawndwells** [comment]
On 6/21/17 10:27 PM, Trevor Vaughan wrote:
> I'm looking at this and I just realized something. There needs to be a
> standardized location and format for admins to document /on the
> system/ how something doesn't apply. Then the scanner could just pick
> up that justification and auto-report it. It would save a LOT of time
> for a lot of people.

Could a tailoring file be used for this?

**Comment by trevor-vaughan** [comment]
Sorry...I should have said "normal humans" AKA "not XML wizards"

**Comment by trevor-vaughan** [comment]
Something like `/etc/scap/justifications/INSANE-ID-NUMBER.txt` would do it for me.

**Comment by shawndwells** [comment]
Previously added:

https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/guide/system/accounts/accounts-physical/bootloader/bootloader_no_removeable_media.rule#L27
