### ISSUE TITLE
needs mapping/rule: SRG-OS-000250-GPOS-00093, SV-86853r2_rule, RHEL-07-040190 (USELDAPAUTH=yes)

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#1851]

**Comment by shawndwells** [comment]
<Group id="V-72229"><title>SRG-OS-000250-GPOS-00093</title><description>&lt;GroupDescription&gt;&lt;/GroupDescription&gt;</description><Rule id="SV-86853r2_rule" severity="medium" weight="10.0"><version>RHEL-07-040190</version><title>The operating system must implement cryptography to protect the integrity of Lightweight Directory Access Protocol (LDAP) communications.</title><description>&lt;VulnDiscussion&gt;Without cryptographic integrity protections, information can be altered by unauthorized users without detection.^M
^M
Cryptographic mechanisms used for protecting the integrity of information include, for example, signed hash functions using asymmetric cryptography enabling distribution of the public key to verify the hash information while maintaining the confidentiality of the key used to generate the hash.&lt;/VulnDiscussion&gt;&lt;FalsePositives&gt;&lt;/FalsePositives&gt;&lt;FalseNegatives&gt;&lt;/FalseNegatives&gt;&lt;Documentable&gt;false&lt;/Documentable&gt;&lt;Mitigations&gt;&lt;/Mitigations&gt;&lt;SeverityOverrideGuidance&gt;&lt;/SeverityOverrideGuidance&gt;&lt;PotentialImpacts&gt;&lt;/PotentialImpacts&gt;&lt;ThirdPartyTools&gt;&lt;/ThirdPartyTools&gt;&lt;MitigationControl&gt;&lt;/MitigationControl&gt;&lt;Responsibility&gt;&lt;/Responsibility&gt;&lt;IAControls&gt;&lt;/IAControls&gt;</description><reference><dc:title>DPMS Target Red Hat 7</dc:title><dc:publisher>DISA</dc:publisher><dc:type>DPMS Target</dc:type><dc:subject>Red Hat 7</dc:subject><dc:identifier>2777</dc:identifier></reference><ident system="http://iase.disa.mil/cci">CCI-001453</ident><fixtext fixref="F-78583r1_fix">Configure the operating system to implement cryptography to protect the integrity of LDAP remote access sessions.^M
^M
Set the "tls_cacertdir" option in "/etc/pam_ldap.conf" to point to the directory that will contain the X.509 certificates for peer authentication.^M
^M
Set the "tls_cacertfile" option in "/etc/pam_ldap.conf" to point to the path for the X.509 certificates used for peer authentication.</fixtext><fix id="F-78583r1_fix" /><check system="C-72463r1_chk"><check-content-ref name="M" href="DPMS_XCCDF_Benchmark_RHEL_7_STIG.xml" /><check-content>Verify the operating system implements cryptography to protect the integrity of remote LDAP access sessions.^M
^M
To determine if LDAP is being used for authentication, use the following command:^M
^M
# grep -i useldapauth /etc/sysconfig/authconfig^M
USELDAPAUTH=yes^M
^M
If USELDAPAUTH=yes, then LDAP is being used. ^M
^M
Check for the directory containing X.509 certificates for peer authentication with the following command:^M
^M
# grep -i cacertdir /etc/pam_ldap.conf^M
tls_cacertdir /etc/openldap/certs^M
^M
Verify the directory set with the "tls_cacertdir" option exists.^M
^M
If the directory does not exist or the option is commented out, this is a finding.</check-content></check></Rule></Group>

**Comment by trevor-vaughan** [comment]
IIRC the settings in `/etc/pam_ldap.conf` have no effect if you're using `sssd` for all LDAP connections.
