### ISSUE TITLE
needs mapping/rule: SRG-OS-000420-GPOS-00186, SV-86895r1_rule, RHEL-07-040510 (firewalld rate limit)

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#1854]

**Comment by shawndwells** [comment]
<Group id="V-72271"><title>SRG-OS-000420-GPOS-00186</title><description>&lt;GroupDescription&gt;&lt;/GroupDescription&gt;</description><Rule id="SV-86895r1_rule" severity="medium" weight="10.0"><version>RHEL-07-040510</version><title>The operating system must protect against or limit the effects of Denial of Service (DoS) attacks by validating the operating system is implementing rate-limiting measures on impacted network interfaces.</title><description>&lt;VulnDiscussion&gt;DoS is a condition when a resource is not available for legitimate users. When this occurs, the organization either cannot accomplish its mission or must operate at degraded capacity.^M
^M
This requirement addresses the configuration of the operating system to mitigate the impact of DoS attacks that have occurred or are ongoing on system availability. For each system, known and potential DoS attacks must be identified and solutions for each type implemented. A variety of technologies exist to limit or, in some cases, eliminate the effects of DoS attacks (e.g., limiting processes or establishing memory partitions). Employing increased capacity and bandwidth, combined with service redundancy, may reduce the susceptibility to some DoS attacks.&lt;/VulnDiscussion&gt;&lt;FalsePositives&gt;&lt;/FalsePositives&gt;&lt;FalseNegatives&gt;&lt;/FalseNegatives&gt;&lt;Documentable&gt;false&lt;/Documentable&gt;&lt;Mitigations&gt;&lt;/Mitigations&gt;&lt;SeverityOverrideGuidance&gt;&lt;/SeverityOverrideGuidance&gt;&lt;PotentialImpacts&gt;&lt;/PotentialImpacts&gt;&lt;ThirdPartyTools&gt;&lt;/ThirdPartyTools&gt;&lt;MitigationControl&gt;&lt;/MitigationControl&gt;&lt;Responsibility&gt;&lt;/Responsibility&gt;&lt;IAControls&gt;&lt;/IAControls&gt;</description><reference><dc:title>DPMS Target Red Hat 7</dc:title><dc:publisher>DISA</dc:publisher><dc:type>DPMS Target</dc:type><dc:subject>Red Hat 7</dc:subject><dc:identifier>2777</dc:identifier></reference><ident system="http://iase.disa.mil/cci">CCI-002385</ident><fixtext fixref="F-78625r1_fix">Create a direct firewall rule to protect against DoS attacks with the following command:^M
^M
Note: The command is to add a rule to the public zone.^M
^M
# firewall-cmd --direct --add-rule ipv4 filter IN_public_allow 0 -p tcp -m limit --limit 25/minute --limit-burst 100  -j ACCEPT</fixtext><fix id="F-78625r1_fix" /><check system="C-72505r1_chk"><check-content-ref name="M" href="DPMS_XCCDF_Benchmark_RHEL_7_STIG.xml" /><check-content>Verify the operating system protects against or limits the effects of DoS attacks by ensuring the operating system is implementing rate-limiting measures on impacted network interfaces.^M
^M
Check the firewall configuration with the following command:^M
^M
Note: The command is to query rules for the public zone.^M
^M
# firewall-cmd --direct --get-rule ipv4 filter IN_public_allow^M
rule ipv4 filter IN_public_allow 0 -p tcp -m limit --limit 25/minute --limit-burst 100  -j ACCEPT^M
^M
If a rule with both the limit and limit-burst arguments parameters does not exist, this is a finding.</check-content></check></Rule></Group>

**Comment by trevor-vaughan** [comment]
You might want this as well https://github.com/simp/pupmod-simp-iptables/blob/master/manifests/rules/scanblock.pp

**Comment by shawndwells** [comment]
Mapping previously completed. Ref:

https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/guide/system/network/network-firewalld/ruleset_modifications/configure_firewalld_rate_limiting.rule#L35
