### ISSUE TITLE
needs mapping/rule: SRG-OS-000029-GPOS-00010, SV-87809r2_rule, RHEL-07-010082 (GNOME idle-delay)

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#1865]

**Comment by shawndwells** [comment]
<Group id="V-73157"><title>SRG-OS-000029-GPOS-00010</title><description>&lt;GroupDescription&gt;&lt;/GroupDescription&gt;</description><Rule id="SV-87809r2_rule" severity="medium" weight="10.0"><version>RHEL-07-010082</version><title>The operating system must set the session idle delay setting for all connection types.</title><description>&lt;VulnDiscussion&gt;A session time-out lock is a temporary action taken when a user stops work and moves away from the immediate physical vicinity of the information system but does not log out because of the temporary nature of the absence. Rather than relying on the user to manually lock their operating system session prior to vacating the vicinity, operating systems need to be able to identify when a user's session has idled and take action to initiate the session lock.^M
^M
The session lock is implemented at the point where session activity can be determined and/or controlled.&lt;/VulnDiscussion&gt;&lt;FalsePositives&gt;&lt;/FalsePositives&gt;&lt;FalseNegatives&gt;&lt;/FalseNegatives&gt;&lt;Documentable&gt;false&lt;/Documentable&gt;&lt;Mitigations&gt;&lt;/Mitigations&gt;&lt;SeverityOverrideGuidance&gt;&lt;/SeverityOverrideGuidance&gt;&lt;PotentialImpacts&gt;&lt;/PotentialImpacts&gt;&lt;ThirdPartyTools&gt;&lt;/ThirdPartyTools&gt;&lt;MitigationControl&gt;&lt;/MitigationControl&gt;&lt;Responsibility&gt;&lt;/Responsibility&gt;&lt;IAControls&gt;&lt;/IAControls&gt;</description><reference><dc:title>DPMS Target Red Hat 7</dc:title><dc:publisher>DISA</dc:publisher><dc:type>DPMS Target</dc:type><dc:subject>Red Hat 7</dc:subject><dc:identifier>2777</dc:identifier></reference><ident system="http://iase.disa.mil/cci">CCI-000057</ident><fixtext fixref="F-79603r1_fix">Configure the operating system to prevent a user from overriding a session lock after a 15-minute period of inactivity for graphical user interfaces.^M
^M
Create a database to contain the system-wide screensaver settings (if it does not already exist) with the following command: ^M
^M
Note: The example below is using the database "local" for the system, so if the system is using another database in /etc/dconf/profile/user, the file should be created under the appropriate subdirectory.^M
^M
# touch /etc/dconf/db/local.d/locks/session^M
^M
Add the setting to lock the session idle delay:^M
^M
/org/gnome/desktop/session/idle-delay</fixtext><fix id="F-79603r1_fix" /><check system="C-73281r2_chk"><check-content-ref name="M" href="DPMS_XCCDF_Benchmark_RHEL_7_STIG.xml" /><check-content>Verify the operating system prevents a user from overriding session idle delay after a 15-minute period of inactivity for graphical user interfaces. The screen program must be installed to lock sessions on the console.^M
^M
Note: If the system does not have GNOME installed, this requirement is Not Applicable. ^M
^M
Determine which profile the system database is using with the following command:^M
# grep system-db /etc/dconf/profile/user^M
^M
system-db:local^M
^M
Check for the session idle delay setting with the following command:^M
^M
Note: The example below is using the database "local" for the system, so the path is "/etc/dconf/db/local.d". This path must be modified if a database other than "local" is being used.^M
^M
# grep -i idle-delay /etc/dconf/db/local.d/locks/*^M
^M
/org/gnome/desktop/session/idle-delay^M

**Comment by shawndwells** [comment]
Note: The example below is using the database "local" for the system, so the path is "/etc/dconf/db/local.d". This path must be modified if a database other than "local" is being used.^M
^M
# grep -i idle-delay /etc/dconf/db/local.d/locks/*^M
^M
/org/gnome/desktop/session/idle-delay^M
^M
If the command does not return a result, this is a finding.

**Comment by ptitoliv** [comment]
Hello,

Maybe a naive question but is that DISA rule isn't already covered by dconf_gnome_session_idle_user_locks.xml oval check ?

**Comment by shawndwells** [comment]
Previously completed. Ref:

https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_session_idle_user_locks.rule#L33
