### ISSUE TITLE
needs mapping/rule: SRG-OS-000424-GPOS-00188, SV-87829r1_rule, RHEL-07-041010 (disable wireless)

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#1872]

**Comment by shawndwells** [comment]
Wireless network adapters must be disabled.rule

<VulnDiscussion>The use of wireless networking can introduce many different attack vectors into the organization's network. Common attack vectors such as malicious association and ad hoc networks will allow an attacker to spoof a wireless access point (AP), allowing validated systems to connect to the malicious AP and enabling the attacker to monitor and record network traffic. These malicious APs can also serve to create a man-in-the-middle attack or be used to create a denial of service to valid network resources.</VulnDiscussion><FalsePositives></FalsePositives><FalseNegatives></FalseNegatives><Documentable>false</Documentable><Mitigations></Mitigations><SeverityOverrideGuidance></SeverityOverrideGuidance><PotentialImpacts></PotentialImpacts><ThirdPartyTools></ThirdPartyTools><MitigationControl></MitigationControl><Responsibility></Responsibility><IAControls></IAControls>

identifiers:  CCI-001443, CCI-001444, CCI-002418

references: 

Remediation description:
Configure the system to disable all wireless network interfaces with the following command: #nmcli radio wifi off

**Comment by shawndwells** [comment]
usgcb selection: https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/xccdf/system/network/wireless.xml#L42

**Comment by shawndwells** [comment]
and oval: shared/templates/static/oval/wireless_disable_interfaces.xml

**Comment by trevor-vaughan** [comment]
Shouldn't this be "disable all network interfaces that are not required"?

Scan: All must be justified, always a finding. No idea how to automate this well. There are perfectly good reasons to have wireless turned on and it would seem that a proper mitigation would be to require PKI authentication on all wireless interfaces.

Also, is `NetworkManager` now required? We usually disable it so that we have better control over our interface management.

**Comment by shawndwells** [comment]
Previously completed. Reference:

https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/guide/system/network/network-wireless/wireless_software/wireless_disable_interfaces.rule#L35
