### ISSUE TITLE
needs remediation: xccdf_org.ssgproject.content_rule_rsyslog_remote_loghost

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#1886]

**Comment by jan-cerny** [comment]
The rule `rsyslog_remote_loghost` requires user to specify a remote host to which he wishes to send logs from his system. The name of the remote host is obviously up to the user. How can we make a remediation script for that? Any thoughts?

**Comment by mpreisler** [comment]
We could use an xccdf:Value so user can set it using tailoring.

**Comment by redhatrises** [comment]
It should not remediate anything if xccdf:Value is blank. Another option is add a warning in the XCCDF with something like:

<warning category="general">
To prevent hard-coded hosts and IPs, automatic remediation of this control is not available. Remediation
must be automated as a component of machine provisioning, or followed manually as outlined above.
</warning>

as all sites and implementations are different.

**Comment by jan-cerny** [comment]
Fixed in https://github.com/OpenSCAP/scap-security-guide/pull/1918
