### ISSUE TITLE
[DISA] RHEL-07-010180: Maxrepeat should be 2 or 4?

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#1891]
DISA requirement text:
``When passwords are changed the number of repeating consecutive characters must not be more than four characters.rule``

Check text:
``Configure the operating system to require the change of the number of repeating consecutive characters when passwords are changed by setting the "maxrepeat" option. Add the following line to "/etc/security/pwquality.conf conf" (or modify the line to have the required value): maxrepeat = 2``

**Comment by shawndwells** [comment]
Hey @tbrunell , can you ping DISA on this?

**Comment by jamescassell** [comment]
I'd recommend closing this.  In V1R4 this is maxrepeat=3 in both the title and the check.

**Comment by redhatrises** [comment]
This should automatically be closed when the PR referencing this issue is merged.

**Comment by shawndwells** [comment]
thanks @redhatrises

**Comment by jmackani** [comment]
It should be 3 characters.
