### ISSUE TITLE
Create a template for file ownership and permissions remediation scripts

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/scap-security-guide#1911]
We have a lot of rules in SSG requiring that a given file must be owned by root, or must have permissions 0644, etc.

We have also a lot of remediation scripts for those rules, for example:
https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/templates/static/bash/file_owner_etc_group.sh
https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/templates/static/bash/file_permissions_etc_group.sh

All those scripts are very similar.

@mpreisler suggested that those files should be transformed to templates, so that we don't create a lot of copies, instead the scripts would be generated automatically.

**Comment by redhatrises** [comment]
@jan-cerny isn't this handled in #3146?

**Comment by yuumasato** [comment]
Fixed in #3146
