### ISSUE TITLE
Prelinking needs to be disabled in fips mode

### ISSUE THREAD

**Issue by MollyJoBault** [OpenSCAP/scap-security-guide#1915]
grub2_enable_fips_mode.sh remediation script currently enables prelinking.  In FIPs mode, prelinking must be disabled for reliable behavior: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Security_Guide/chap-Federal_Standards_and_Regulations.html#sec-Enabling-FIPS-Mode

**Comment by MollyJoBault** [comment]
Thank you!  You guys rock!

**Comment by mpreisler** [comment]
> Thank you! You guys rock!

Thanks for reporting this! You rock too! :-)
