### ISSUE TITLE
OVAL error: accounts_logon_fail_delay generates "Conversion of the string" error

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#1928]
OVAL generates the following error:
`````
OpenSCAP Error: Conversion of the string "$var_accounts_fail_delay" to an integer (64 bits) failed: Invalid argument [oval_cmp.c:110]
`````

Stared at the OVAL code for awhile and don't see what's causing this. Tried comparing against accounts_tmout.xml, which uses similar integer operations, but not seeing it.

**Comment by yuumasato** [comment]
@shawndwells I cannot reproduce this. Could you share more details about environment in which this happent?

**Comment by shawndwells** [comment]
getting this off a fresh clone and oscap scan against stig-upstream. will try on a clean VM tomorrow

**Comment by shawndwells** [comment]
cloned off master and this check still errors.

**Comment by yuumasato** [comment]
Found a bug that might be related.
@shawndwells could you check if this fixes the problem for you?

**Comment by shawndwells** [comment]
Thanks @yuumasato, all gone.
