### ISSUE TITLE
"personnel" is spelled wrong in "Warning" banner

### ISSUE THREAD

**Issue by aisingh2** [OpenSCAP/scap-security-guide#1929]
Please correct the spellings for "personnel" (which are given as 'personal') in Line no. 25 of following doc:
scap-security-guide/RHEL/6/input/xccdf/system/accounts/banners.xml

**Comment by shawndwells** [comment]
Thanks for reporting @aisingh2. Created a PR that fixes the typo: https://github.com/OpenSCAP/scap-security-guide/pull/1931

**Comment by shawndwells** [comment]
@aisingh2 - patch merged upstream and will be picked up in next release
