### ISSUE TITLE
RHEL7 STIG: CCI-000172 The operating system must generate audit records when successful/unsuccessful accesses to objects occur.

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#193]
AU-12 c	CCI-000172	SRG-OS-000474		The operating system must generate audit records when successful/unsuccessful accesses to objects occur.	"Without generating audit records that are specific to the security and mission needs of the organization, it would be difficult to establish, correlate, and investigate the events relating to an incident, or identify those responsible for one. 

Audit records can be generated from various components within the information system (e.g., module or policy filter). "

**Comment by shawndwells** [comment]
Sent the following to DISA FSO to request clarification of requirement:

````
Hello,

    In attempting to create the RHEL7 STIG, we're evaluating the meaning of CCI-000172. The language is:

"The operating system must generate audit records when successful/unsuccessful accesses to objects occur. "Without generating audit records that are specific to the security and mission needs of the organization, it would be difficult to establish, correlate, and investigate the events relating to an incident, or identify those responsible for one.

Audit records can be generated from various components within the information system (e.g., module or policy filter). "

    Does this mean FSO wants to audit every file access? It is likely this would generate an excessive amount of audit events per day. Can you clarify?

    By comparison, the prior version of the OS SRG only required auditing unauthorized access attempts.

Thanks!
Shawn

-- 
Shawn Wells
Director, Innovation Programs
shawn@redhat.com | 443.534.0130
@shawndwells
````

**Comment by shawndwells** [comment]
@steelwraith - thanks for your time earlier. Can you provide guidance on how to interpret this? Auditing every successful/unsuccessful file access would be untenable for most.

**Comment by rprice** [comment]
@shawndwells Have we gotten any response?
