### ISSUE TITLE
Audit remediation scripts have an extra quote

### ISSUE THREAD

**Issue by MollyJoBault** [OpenSCAP/scap-security-guide#1930]
For the FULL_RULE assignment line there is an extra quote on many of the audit remediation scripts.  

This causes a  " script error:line 177: unexpected EOF while looking for matching `"' "

eg. shared/templates/static/bash/audit_rules_execution_chcon.sh
FULL_RULE="-a always,exit -F path=/usr/bin/chcon -F perm=x -F auid>=1000 -F auid!=4294967295 -F key=privileged""

Searching the repository for "FULL_RULE" shows this.

**Comment by shawndwells** [comment]
Crap. Crap crap crap. I introduced this. 

PR https://github.com/OpenSCAP/scap-security-guide/pull/1932/files submitted to fix. Thanks for reporting this!

**Comment by shawndwells** [comment]
@MollyJoBault - Thanks for reporting this. Patch merged upstream and will be picked up in next rebase.
