### ISSUE TITLE
IFS variable is not correctly reset

### ISSUE THREAD

**Issue by silvermangb** [OpenSCAP/scap-security-guide#1941]
The generated scripts use this idiom

IFS= something
...
unset $IFS

The last statement does not restore IFS to its previous value, as $IFS is not a variable. The statement should be

unset IFS

**Comment by mpreisler** [comment]
Thanks for reporting this, should be an easy fix.

**Comment by silvermangb** [comment]
Reported by me on behalf of Jay Vasa (jay.vasa@veritas.com)
