### ISSUE TITLE
password_minlen_login_defs

### ISSUE THREAD

**Issue by linuxdan** [OpenSCAP/scap-security-guide#1943]
OpenSCAP Error: Attempt to get non-existent selector "15" from variable "xccdf_org.ssgproject.content_value_var_accounts_password_minlen_login_defs" [xccdf_policy.c:463]
Invalid selector '15' for xccdf:value/@id='xccdf_org.ssgproject.content_value_var_accounts_password_minlen_login_defs'. Using null value instead. [xccdf_policy.c:2114]

This is from ssg-rhel6-ds.xml

**Comment by mpreisler** [comment]
Which version of SSG? I think this has been fixed a long time ago but I could be wrong.

**Comment by linuxdan** [comment]
0.1.31-2.el7.noarch

"Sometimes I think the surest sign that intelligent life exists elsewhere in the universe is that none of it has tried to contact us."
Bill Waterson (Calvin & Hobbes)

**Comment by mpreisler** [comment]
https://github.com/OpenSCAP/scap-security-guide/issues/1654

https://github.com/OpenSCAP/scap-security-guide/issues/1655
