### ISSUE TITLE
McAfee virus scan

### ISSUE THREAD

**Issue by autonomicpilot** [OpenSCAP/scap-security-guide#1950]
Why is there a check for "McAfee Endpoint Security Software" in the RHEL7 STIG? I am using the CentOS variation.

Shouldn't this only be checking the compliance of the OS and (maybe) doing a variety of checks for a variety of antivirus packages?

**Frankly, something smells about the explicit check for McAfee...**

I vote that this check is removed and changed to a generic requirement for antivirus. One that simply can't be verified and will need to be done so manually, just as it was before.

**Comment by shawndwells** [comment]
On 4/18/17 2:12 PM, autonomicpilot wrote:
>
> Why is there a check for McAfee virus scan in the RHEL7 STIG? I am
> using the CentOS variation.
>
> Shouldn't this only be checking the compliance of the OS and (maybe)
> doing a variety of checks for a variety of antivirus packages, but
> something smells about the explicit check for McAfee.
>
> I vote that this check is remove to a generic requirement for
> antivirus. One that simply can't be verified and will need to be done
> so manually, just as before.
>

Extreme agreement.

After *many* rounds of talks with DISA, they decided to *mandated* 3rd
party configuration items be included in the RHEL configuration guide.
So we were forced to write those rules into the STIG profile (you'll
note the McAfee things aren't selected in any other profiles).

DISA stated this originated from CYBERCOM requiring information systems
to install anti-virus, so they wanted to enforce that in the operating
system configuration guides.

It would be great if DISA STIGs only enforced configuration checks of
the technology it's for -- e.g. native RHEL components in the RHEL STIG.
It'd also be great for DISA to have parity between vendors -- if RHEL
needs to check for McAfee, so should all other operating systems.

.... but alas, NSA, NIST, and Red Hat lost that argument with DISA.

**Comment by shawndwells** [comment]
Feedback to DISA requesting the removal of such rules would appropriately be given to 
[Disa.stig_spt@mail.mil](mailto:Disa.stig_spt@mail.mil).

**Comment by autonomicpilot** [comment]
Thanks. Sounds like another crooked wink and a nod within the USG contracting environment if I had to nail the **smell**. And people wonder why so much budget goes to defense.

**Comment by autonomicpilot** [comment]
I'm forwarding them this thread now...to that address.
