### ISSUE TITLE
sysctl ipv6 accept_ra broken

### ISSUE THREAD

**Issue by MollyJoBault** [OpenSCAP/scap-security-guide#1951]
This is broken in CentOS at least.  There are variables that somehow made it into the configuration file.

Systemctl
... systemd-sysctl[650]: Failed to write '$sysctl_net_ipv6_conf_all_accept_ra_value' to '/proc/sys/net/ipv6/conf/all/accept_ra': Invalid argument
... systemd-sysctl[650]: Failed to write '$sysctl_net_ipv6_conf_default_accept_ra_value' to '/proc/sys/net/ipv6/conf/default/accept_ra': Invalid argument

In the  /etc/sysctl.conf:
Per CCE-CCE-80180-3: Set net.ipv6.conf.all.accept_ra = $sysctl_net_ipv6_conf_aa
ll_accept_ra_value in /etc/sysctl.conf
net.ipv6.conf.all.accept_ra = $sysctl_net_ipv6_conf_all_accept_ra_value

Per CCE-CCE-80181-1: Set net.ipv6.conf.default.accept_ra = $sysctl_net_ipv6_coo
nf_default_accept_ra_value in /etc/sysctl.conf
net.ipv6.conf.default.accept_ra = $sysctl_net_ipv6_conf_default_accept_ra_value

In resultant .xml:
replace_or_append '/etc/sysctl.conf' '^net.ipv6.conf.all.accept_ra' '$sysctl_net_ipv6_conf_all_accept_ra_value' 'CCE-80180-3'

shared/templates/template_BASH_sysctl_var 
replace_or_append '/etc/sysctl.conf' '^SYSCTLVAR' '$sysctl_SYSCTLID_value' '$CCENUM'
                                                                                       ^ needs to have "" ?

Thank you again for helping make Linux more secure.

**Comment by shawndwells** [comment]
In the datastream, the fix is being transformed as:

`````
<fix id="sysctl_net_ipv6_conf_all_accept_ra" system="urn:xccdf:fix:script:sh" reboot="true" complexity="low" disruption="medium" strategy="disable">
sysctl_net_ipv6_conf_all_accept_ra_value="<sub idref="xccdf_org.ssgproject.content_value_sysctl_net_ipv6_conf_all_accept_ra_value" use="legacy"/>"

#
# Set runtime for net.ipv6.conf.all.accept_ra
#
/sbin/sysctl -q -n -w net.ipv6.conf.all.accept_ra=$sysctl_net_ipv6_conf_all_accept_ra_value

#
# If net.ipv6.conf.all.accept_ra present in /etc/sysctl.conf, change value to appropriate value
#       else, add "net.ipv6.conf.all.accept_ra = value" to /etc/sysctl.conf
#
<sub idref="xccdf_org.ssgproject.content_value_function_replace_or_append" use="legacy"/>
replace_or_append '/etc/sysctl.conf' '^net.ipv6.conf.all.accept_ra' '$sysctl_net_ipv6_conf_all_accept_ra_value' 'CCE-80180-3'
</fix>
`````
