### ISSUE TITLE
DISA STIG SRGs page reference is not available

### ISSUE THREAD

**Issue by dahaic** [OpenSCAP/scap-security-guide#1981]
SSG references page http://iase.disa.mil/stigs/srgs/Pages/index.aspx but this is not available. Unfortunately I am not sure what it should point to, thus I won't try to fix it myself.

**Comment by dahaic** [comment]
Should it point to this page instead? http://iase.disa.mil/stigs/compilations/Pages/index.aspx

**Comment by shawndwells** [comment]
On 5/2/17 3:21 PM, Marek Haičman wrote:
> SSG references page http://iase.disa.mil/stigs/srgs/Pages/index.aspx
> but this is not available. Unfortunately I am not sure what it should
> point to, thus I won't try to fix it myself.

ossrg tags should point to
http://iase.disa.mil/stigs/os/general/Pages/index.aspx/
stigid tags should point to
http://iase.disa.mil/stigs/os/unix-linux/Pages/red-hat.aspx
disa tags should point to http://iase.disa.mil/stigs/cci/Pages/index.aspx

**Comment by mpreisler** [comment]
I am trying to understand this ticket.

First I thought you meant one of the wiki pages we have but now I think you probably mean the SRG reference system attributes. Example:
```
<reference href="http://iase.disa.mil/stigs/srgs/Pages/index.aspx">SRG-OS-000480-GPOS-00227</reference>
```

This is defined in https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/transforms/shared_constants.xslt#L16

We rely on this specific value in OpenSCAP too. See https://github.com/OpenSCAP/openscap/blob/maint-1.2/xsl/xccdf-report-impl.xsl#L464

To properly fix it we should add the new URLs to OpenSCAP first. Then when it gets to the release we should change them in SSG. I think that's a reasonable compromise considering that people can't actually click the link in the reference system attribute. It's more of a namespace then a link.

@dahaic could you please confirm that this is what this ticket is about?

**Comment by dahaic** [comment]
@mpreisler Yes, these attributes are what I mean by this ticket :) sorry for not being more precise.

**Comment by dahaic** [comment]
I have asked DISA, whether they are able to create redirect, and the response I got:
```
We no longer have one central page where the SRGs are kept. They have been distributed to the sections of IASE that they correspond to. You can also find them using the A - Z list.
```
Is that ```/os/``` link correct one, or should we play safe and link to the A-Z list? (where not just SRGs are linked)

**Comment by redhatrises** [comment]
It should probably be linked here: http://iase.disa.mil/stigs/os/general/Pages/index.aspx/

**Comment by shawndwells** [comment]
On 7/25/17 8:39 AM, redhatrises wrote:
> It should probably be linked here:
> http://iase.disa.mil/stigs/os/general/Pages/index.aspx/
+1

**Comment by redhatrises** [comment]
This was actually fixed in the SSG content already when the JBoss content was added. There are now different types of SRGs instead of just OS ones. So, this now needs to be fixed in openscap.

**Comment by mpreisler** [comment]
@redhatrises are we tracking the openscap issue anywhere? we need to fix this soon because end of October we are releasing.

**Comment by redhatrises** [comment]
@mpreisler PR fixing the issue already submitted to openscap. :)

**Comment by mpreisler** [comment]
Related to https://github.com/OpenSCAP/openscap/pull/889

**Comment by jmackani** [comment]
Agree with Shawn on this.
