### ISSUE TITLE
Ansible issues? causes CentOS7 build failures

### ISSUE THREAD

**Issue by MollyJoBault** [OpenSCAP/scap-security-guide#1995]
Build is failing for centos7, ansible issues?:
.. executed from root
   cd build
   cmake ../
   make -j4 clean
   make -j4 centos7
   make -j4 package

Output:
red/templates/create_selinux_booleans.py --csv /home/omni/webCS-linux/sysapps/sc   ap-security-guide/shared/templates/csv/selinux_booleans.csv --lang puppet --inpu   t /home/omni/webCS-linux/sysapps/scap-security-guide/shared/templates --shared /   home/omni/webCS-linux/sysapps/scap-security-guide/shared --output /home/omni/web   CS-linux/sysapps/scap-security-guide/build/RHEL/6/remediations/shared build
Merged 74 remediation scripts.
[  1%] Built target generate-internal-rhel6-ansible-remediations.xml
[  1%] Built target generate-internal-rhel7-oval-unlinked.xml
[  1%] Built target generate-internal-rhel7-guide.xml
[  1%] Built target generate-internal-rhel7-anaconda-remediations.xml
[  1%] Built target generate-internal-rhel7-bash-remediations.xml
**make[2]: *** No rule to make target '../RHEL/7/templates/static/ansible/account_   disable_post_pw_expiration.yml', needed by 'RHEL/7/ansible-remediations.xml'.**  S   top.
CMakeFiles/Makefile2:16027: recipe for target 'RHEL/7/CMakeFiles/generate-intern   al-rhel7-ansible-remediations.xml.dir/all' failed
make[1]: *** [RHEL/7/CMakeFiles/generate-internal-rhel7-ansible-remediations.xml   .dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  1%] Built target generate-internal-rhel6-puppet-remediations.xml
[  1%] Built target generate-internal-rhel6-oval-unlinked.xml
[  1%] Built target generate-internal-rhel5-oval-unlinked.xml
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by shawndwells** [comment]
On 5/10/17 12:15 PM, MollyJoBault wrote:
>
> Build is failing for centos7, ansible issues?:
>
>
>   executed from root
>
> cd build
> cmake ../
> make -j4 clean
> make -j4 centos7
> make -j4 package
>

``cd build ; cmake ../ ; make -j4 package`` works for me against latest
upstream
>
> Output:
> red/templates/create_selinux_booleans.py --csv
> /home/omni/webCS-linux/sysapps/sc
> ap-security-guide/shared/templates/csv/selinux_booleans.csv --lang
> puppet --inpu t
> /home/omni/webCS-linux/sysapps/scap-security-guide/shared/templates
> --shared / home/omni/webCS-linux/sysapps/scap-security-guide/shared
> --output /home/omni/web
> CS-linux/sysapps/scap-security-guide/build/RHEL/6/remediations/shared
> build
> Merged 74 remediation scripts.
> [ 1%] Built target generate-internal-rhel6-ansible-remediations.xml
> [ 1%] Built target generate-internal-rhel7-oval-unlinked.xml
> [ 1%] Built target generate-internal-rhel7-guide.xml
> [ 1%] Built target generate-internal-rhel7-anaconda-remediations.xml
> [ 1%] Built target generate-internal-rhel7-bash-remediations.xml
> *make[2]: *** No rule to make target
> '../RHEL/7/templates/static/ansible/account_
> disable_post_pw_expiration.yml', needed by
> 'RHEL/7/ansible-remediations.xml'.* S top.
> CMakeFiles/Makefile2:16027: recipe for target
> 'RHEL/7/CMakeFiles/generate-intern
> al-rhel7-ansible-remediations.xml.dir/all' failed
> make[1]: ***
> [RHEL/7/CMakeFiles/generate-internal-rhel7-ansible-remediations.xml
> .dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> [ 1%] Built target generate-internal-rhel6-puppet-remediations.xml
> [ 1%] Built target generate-internal-rhel6-oval-unlinked.xml
> [ 1%] Built target generate-internal-rhel5-oval-unlinked.xml
> Makefile:138: recipe for target 'all' failed
> make: *** [all] Error 2
>

**Comment by MollyJoBault** [comment]
Looks like I needed to do a git clean -fd.  Sorry folks.
