### ISSUE TITLE
RHEL 7 Derivative CentOS 7 doesn't have STIG References in guides

### ISSUE THREAD

**Issue by MollyJoBault** [OpenSCAP/scap-security-guide#2001]
CentOS 7 is a derivative of RHEL 7 but when comparing the guides, the STIG references are missing.

shared\transforms\shared_shorthand2xccdf.xslt checks for "prodtype" and these are only tagged as "rhel7" so "centos7" doesn't match.

Is there a plan to have these references on CentOS 7 guides for reference?

**Comment by shawndwells** [comment]
Oh. Crap.

Some of the ref tags that should be independent are mangled with RHEL7... e.g.:

`````
<ref prodtype="rhel7" nist="SC-8" disa="2418,2420,2421,2422"
ossrg="SRG-OS-000423-GPOS-00187,SRG-OS-000423-GPOS-00188,SRG-OS-000423-GPOS-00189,SRG-OS000423-GPOS-00190"
stigid="040300" />
`````

should be something like:
`````
<ref prodtype="rhel7" stigid="040300" />
<ref nist="SC-8" disa="2418,2420,2421,2422"
ossrg="SRG-OS-000423-GPOS-00187,SRG-OS-000423-GPOS-00188,SRG-OS-000423-GPOS-00189,SRG-OS000423-GPOS-00190"  />

`````

These should be separated out. Is this something you care enough about to take on? In theory a fancy regex could do the trick.

**Comment by MollyJoBault** [comment]
One day I will learn, it is never just a simple regex. :(
