### ISSUE TITLE
Built RPM has conflict with "filesystem" rpm

### ISSUE THREAD

**Issue by MollyJoBault** [OpenSCAP/scap-security-guide#2004]
The RPM repo check fails with current version.  This was working a week or so ago.  Did d9a24254acedd3c4c02484569cceff0b02413435 break this?

file **/usr/local** conflicts between attempted installs of scap-security-guide-doc-0.1.33-1.noarch and filesystem-3.2-21.el7.x86_64

file **/usr/local/share** conflicts between attempted installs of scap-security-guide-doc-0.1.33-1.noarch and filesystem-3.2-21.el7.x86_64

Generated spec file scap-security-guide\build\_CPack_Packages\Linux\RPM\SPECS\scap-security-guide-doc.spec has:
%files
%defattr(-,root,root,-)
%dir "/usr/local"
%dir "/usr/local/share"
...

Ran from the root directory:
cd build
cmake ../
make -j4 clean
make -j4 package

**Comment by shawndwells** [comment]
On 5/17/17 5:20 PM, MollyJoBault wrote:
>
> The RPM repo check fails with current version. This was working a week
> or so ago. Did d9a2425
> <https://github.com/OpenSCAP/scap-security-guide/commit/d9a24254acedd3c4c02484569cceff0b02413435>
> break this?
>
> file */usr/local* conflicts between attempted installs of
> scap-security-guide-doc-0.1.33-1.noarch and filesystem-3.2-21.el7.x86_64
>
> file */usr/local/share* conflicts between attempted installs of
> scap-security-guide-doc-0.1.33-1.noarch and filesystem-3.2-21.el7.x86_64
>
> Generated spec file
> scap-security-guide\build_CPack_Packages\Linux\RPM\SPECS\scap-security-guide-doc.spec
> has:
> %files
> %defattr(-,root,root,-)
> %dir "/usr/local"
> %dir "/usr/local/share"
> ...
>
> Ran from the root directory:
> cd build
> cmake ../
> make -j4 clean
> make -j4 package
>


I get the same error. Hope this didn't make its way into the latest SSG
release - could have major impact to downstream. Also noticed the RPM
got renamed (scap-security-guide now scap-security-guide-Linux??).

**Comment by MollyJoBault** [comment]
I just rolled back d9a24254acedd3c4c02484569cceff0b02413435 on my system and this now passes the rpm repo check. :(

**Comment by yuumasato** [comment]
@MollyJoBault Indeed, the roles are being installed in `/usr/local/share/doc` instead of `/usr/share/doc`. I'll take a look at it.

@shawndwells For some reason the package I get doesn't have the "Linux" suffix.

**Comment by shawndwells** [comment]
On 5/18/17 8:00 AM, Watson Yuuma Sato wrote:
>
> @shawndwells <https://github.com/shawndwells> For some reason the
> package I get doesn't have the "Linux" suffix.
>

The generated RPM is called
"scap-security-guide-0.1.33-Linux-content.rpm" when building off master

**Comment by yuumasato** [comment]
@shawndwells I know what is happening, older versions of cmake don't support new variables used in CPack to fix the naming...

CPACK_RPM_CONTENT_PACKAGE_NAME which is used to remove `content` from the name of component was introduced in https://cmake.org/cmake/help/v3.5/module/CPackRPM.html#variable:CPACK_RPM_%3Ccomponent%3E_PACKAGE_NAME

and CPACK_RPM_FILE_NAME which is used to remove `Linux` from package name was introduced in https://cmake.org/cmake/help/v3.6/module/CPackRPM.html#variable:CPACK_RPM_FILE_NAME

**Comment by shawndwells** [comment]
On 5/18/17 1:02 PM, Watson Yuuma Sato wrote:
>
> @shawndwells <https://github.com/shawndwells> I know what is
> happening, older versions of cmake don't support new variables used in
> CPack to fix the naming...
>
> CPACK_RPM_CONTENT_PACKAGE_NAME which is used to remove |content| from
> the name of component was introduced in
> https://cmake.org/cmake/help/v3.5/module/CPackRPM.html#variable:CPACK_RPM_%3Ccomponent%3E_PACKAGE_NAME
>
> and CPACK_RPM_FILE_NAME which is used to remove |Linux| from package
> name was introduced in
> https://cmake.org/cmake/help/v3.6/module/CPackRPM.html#variable:CPACK_RPM_FILE_NAME
>

Using the latest available CMake on RHEL7 (cmake-2.8.12.2-2.el7.x86_64)
this remains an issue. Should we expect developers to download and
compile their own cmake to properly build ssg? Can the build system be
rewritten against currently available cmake editions?

**Comment by MollyJoBault** [comment]
@yuumasato 
There is a mismatch between the file name and the RPM name as well: 
scap-security-guide-content.spec:
...
Name:           scap-security-guide-content
...

and the rpm name:
scap-security-guide-0.1.33-Linux-content.rpm

Are these supposed to now be new RPM names?

**Comment by yuumasato** [comment]
> Can  the build system be rewritten against currently available cmake editions?

Don't know if it is possible, but will certainly be hackish.

> Are these supposed to now be new RPM names?

No, this is a side effect of using old version of CMake/CPack to build the package. Please keep in mind that this RPM package is built with the purpose of allowing easy testing of content.

**Comment by MollyJoBault** [comment]
The RPM build not working properly makes it so I can't test the content.  I know that this is a work in progress, but if you want people (like me) to help with testing, this will need to get fixed (ideally soon).

**Comment by yuumasato** [comment]
So, I gave it a shot, and I'm starting to think that it will be impossible with CMake/CPack 2.8.

I tried hacking with the variables and configuration, but the way `CPACK_RPM_PACKAGE_COMPONENT_PART_NAME` is used in https://github.com/Kitware/CMake/blob/v2.8.12.2/Modules/CPackRPM.cmake#L903 and defined in https://github.com/Kitware/CMake/blob/v2.8.12.2/Modules/CPackRPM.cmake#L332 makes it hard to avoid "content" in package name.

Also tried using a custom spec file through variable CPACK_RPM_content_USER_BINARY_SPECFILE, and with this approach I can easily specify the package name in the specfile. But problem is that although it builds RPM correctly the build system cannot find the built package, because it still expects it to have old RPM file name, with "Linux" and "content". 
`CPACK_PACKAGE_FILE_NAME` would be the variable to define the expected RPM file name, but we cannot define two different names for each component, and also, somewhere in the code cmake appends the component name to the expected RPM file name. So actually, this variable defines a prefix in which component name is appended.

If we change CPack to build only a single RPM, with content and doc together, we can avoid this package naming problem, and RPM file name might not be exactly equal.

Or, we go back to some shell script and spec file to do this...

**Comment by yuumasato** [comment]
Most of the mess happens because we separate things into two packages, `scap-security-guide` and `scap-security-guide-doc`, having one RPM with everything would be much simpler.

@shawndwells @MollyJoBault Are you ok with putting everything into one RPM?

**Comment by MollyJoBault** [comment]
I have no preference.  But I have less stake here.    Thank you for looking at this @yuumasato !

**Comment by shawndwells** [comment]
On 5/24/17 11:49 AM, Watson Yuuma Sato wrote:
>
> Most of the mess happens because we separate things into two packages,
> |scap-security-guide| and |scap-security-guide-doc|, having one RPM
> with everything would be much simpler.
>
> @shawndwells <https://github.com/shawndwells> @MollyJoBault
> <https://github.com/mollyjobault> Are you ok with putting everything
> into one RPM?
>

I actually prefer one RPM. Less confusing.

Currently (RHEL 7.3), HTML policy tables are shipped in
scap-security-guide but HTML guides are shipped in the -doc package.

**Comment by MollyJoBault** [comment]
Thank you so much @yuumasato !  This already looks better.
