### ISSUE TITLE
Rogue quotes in generated bash remediation scripts

### ISSUE THREAD

**Issue by MollyJoBault** [OpenSCAP/scap-security-guide#2016]
I think the problem is in: shared/utils/combine-remediations.py: get_populate_replacement or there abouts.

I'm not very familiar with python.

Effected rules:
```
xccdf_org.ssgproject.content_rule_umask_for_daemons
xccdf_org.ssgproject.content_rule_account_disable_post_pw_expiration
xccdf_org.ssgproject.content_rule_accounts_password_pam_maxrepeat
xccdf_org.ssgproject.content_rule_accounts_password_pam_*
```
error       

xccdf_org.ssgproject.content_rule_account_disable_post_pw_expiration:
```
var_account_disable_post_pw_expiration="0"
0"
**^**
```
There shouldn't be a 0" here.  It is just hanging out.

xccdf_org.ssgproject.content_rule_umask_for_daemons (this one is also double inserting the remediation script ...):
```
    echo "umask $var_umask_for_daemons" &gt;&gt; /etc/init.d/functions
fi
<ns10:sub idref="xccdf_org.ssgproject.content_value_var_umask_for_daemons" use="legacy"/>"
                                                                                       **^**


grep -q ^umask /etc/init.d/functions &amp;&amp; \
```
This one shouldn't have a variable insert at all:
<ns10:sub idref="xccdf_org.ssgproject.content_value_var_umask_for_daemons" use="legacy"/>"

[devgobah-1108-ssg-report.html.txt](https://github.com/OpenSCAP/scap-security-guide/files/1023786/devgobah-1108-ssg-report.html.txt)

**Comment by mpreisler** [comment]
Could you please use github's formatting features? It's very hard to figure out what actually is the problem from the description.

Please paste what is generated and then write what you expected.

**Comment by MollyJoBault** [comment]
I was fighting that yesterday.  I can't seem to bold a quote. :(

**Comment by MollyJoBault** [comment]
This is now fixed.
