### ISSUE TITLE
DISA feels /etc/banner language being set incorrectly

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#2038]
DISA: 

> openSCAP oval sets login_banner_text which is an external dependency. Unable to verify that the required DoD login banner is being set. There was a ticket that asked for this change.

**Comment by shawndwells** [comment]
@tbrunell the banner is being set in https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/xccdf/system/accounts/banners.xml#L26#L27. Please verify with DISA this language is OK.

**Comment by tbrunell** [comment]
Spoke with DISA.  Resolved.
