### ISSUE TITLE
DISA feels package_screen_installed is not selected in DoD baselines

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#2039]

**Comment by shawndwells** [comment]
Rule clearly enabled in profile:
https://github.com/OpenSCAP/scap-security-guide/blob/master/RHEL/7/input/profiles/ospp-rhel7.xml#L68#L69

@tbrunell please verify this satisfies DISA's concerns and resolve ticket.

**Comment by tbrunell** [comment]
The rule is good.  DISA has rule ID of RHEL-07-010090 in STIG, SSG Rule ID is RHEL-07-010072.  Please change in SSG.

**Comment by redhatrises** [comment]
@tbrunell Looks like the the STIGID is set to RHEL-07-010090 since before SSG v1.31. See here https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/xccdf/system/accounts/physical.xml#L376. Is this what DISA is expecting to see?

**Comment by shawndwells** [comment]
Hah. Ted and I are on the phone *right now* going over these, and found the same thing. Resolving.
