### ISSUE TITLE
DISA feels disable_host_auth creates false negatives

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#2041]
DISA:
> STIG requires no and the expression is testing for yes

**Comment by shawndwells** [comment]
From the sshd_config manpage:

``
     HostbasedAuthentication
             Specifies whether rhosts or /etc/hosts.equiv authentication together with successful public key client host authentication is allowed (host-based
             authentication).  This option is similar to RhostsRSAAuthentication and applies to protocol version 2 only.  The default is “no”.
``

Because the default is no, having content check for such a value means ignoring the default (sysadmins have to explicitly add this line into their config files, even the default is no). The appropriate way is to check if the setting is ``yes``, which would indicate misconfiguration. 

Ref [https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/templates/static/oval/disable_host_auth.xml#L25](https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/templates/static/oval/disable_host_auth.xml#L25)

@tbrunell please explain this to DISA and resolve this ticket when done.

**Comment by tbrunell** [comment]
Spoke With DISA.  resolved.

**Comment by jflemer-ndp** [comment]
@tbrunell what does "resolved" mean in this case? This issue remains/reoccurs in DISA RHEL7 V1R2, the XCCDF requires a match on `HostbasedAuthentication no`, as opposed to prohibiting match on `HostbasedAuthentication yes` (as the RHEL6 V1R18 does).
