### ISSUE TITLE
DISA: ensure_gpgcheck_globally_activated also checks for DNF

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#2042]
DISA reports ensure_gpgcheck_globally_activated checks for yum and DNF

**Comment by shawndwells** [comment]
the underlying OVAL has conditional checks to see if the platform is fedora vs rhel

e.g. if fedora
check dnf configs
elif rhel
check yum configs

ref: [https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/templates/static/oval/ensure_gpgcheck_globally_activated.xml#L12#L18](https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/templates/static/oval/ensure_gpgcheck_globally_activated.xml#L12#L18)

@tbrunell please explain this to DISA and resolve ticket

**Comment by tbrunell** [comment]
Spoke with DISA.  resolved.
