### ISSUE TITLE
DISA: unsure if service_autofs_disabled functional

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#2043]
DISA:

> Not sure if the tests are fully functional or not. https://github.com/OpenSCAP/scap-security-guide/blob/d0af7b820664fe193195eebe498840b654bdf509/RHEL/7/input/oval/oval_5.11/service_autofs_disabled.xml

**Comment by shawndwells** [comment]
The file DISA references doesn't even exist anymore. Not sure how/why they referenced that old commit from Oct 2016.

The rule is enabled and working in latest SSG builds:
https://github.com/OpenSCAP/scap-security-guide/blob/master/RHEL/7/input/profiles/ospp-rhel7.xml#L268

@tbrunell please talk to DISA and resolve this ticket when done.

**Comment by tbrunell** [comment]
Spoke with DISA.  Resolved
