### ISSUE TITLE
DISA: installed_OS_is_certified missing from DoD profiles

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#2044]

**Comment by shawndwells** [comment]
Incorrect. This rule has been selected since July 2016. Added via https://github.com/OpenSCAP/scap-security-guide/commit/445e5f00b4f0c2888f24efef47d7cff82d4f8e1f.

ref: https://github.com/OpenSCAP/scap-security-guide/blame/master/RHEL/7/input/profiles/ospp-rhel7.xml#L31

@tbrunell please speak with DISA and resolve once done

**Comment by tbrunell** [comment]
Talked with DISA.  The check is present.  Resolved.
