### ISSUE TITLE
DISA: security_patches_up_to_date missing from DoD profiles

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#2045]

**Comment by shawndwells** [comment]
Incorrect. Has been included since Aug 27, 2015! Added via https://github.com/OpenSCAP/scap-security-guide/commit/a382ef02b573f01560a25544f3f2c25110ec6223

Included in current profile:
https://github.com/OpenSCAP/scap-security-guide/blame/master/RHEL/7/input/profiles/ospp-rhel7.xml#L256

@tbrunell please speak with DISA and resolve ticket once done

**Comment by tbrunell** [comment]
Spoke with DISA.  The rule is present.  Resolved.
