### ISSUE TITLE
DISA: sysctl_net_ipv6_conf_all_accept_source_route missing from DoD profiles

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#2046]

**Comment by shawndwells** [comment]
Incorrect. 

Ref https://github.com/OpenSCAP/scap-security-guide/blame/master/RHEL/7/input/profiles/ospp-rhel7.xml#L136

@tbrunell please speak with DISA and resolve ticket once done.

**Comment by tbrunell** [comment]
resolved.
