### ISSUE TITLE
DISA: SSG not auditing /etc/opasswd

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#2047]

**Comment by shawndwells** [comment]
Incorrect. Changes to /etc/opasswd are monitored through audit_rules_usergroup_modification_opasswd, which is selected in ospp profile:

https://github.com/OpenSCAP/scap-security-guide/blame/master/RHEL/7/input/profiles/ospp-rhel7.xml#L240

@tbrunell please review with DISA and close ticket as appropriate

**Comment by tbrunell** [comment]
Spoke with DISA.  Everything is good.  They were concerned about the rule still being a cathall rule and not broken apart.  Resolved.
