### ISSUE TITLE
DISA: SSG does not set /etc/issue content

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#2049]
> Checks for /etc/issue but does not give the external variable for the banner text

**Comment by shawndwells** [comment]
Incorrect. This is evaluated through the banner_etc_issue rule, selected in ospp profile:

https://github.com/OpenSCAP/scap-security-guide/blame/master/RHEL/7/input/profiles/ospp-rhel7.xml#L461

@tbrunell please review with DISA and close as appropriate

**Comment by tbrunell** [comment]
resolved.
