### ISSUE TITLE
OSCAP Addon marking some rules "notapplicable"

### ISSUE THREAD

**Issue by MollyJoBault** [OpenSCAP/scap-security-guide#2052]
When running the OSCAP anaconda addon some rules are being marked "notapplicable" (and are not getting applied) that I would expect would be applicable:

**content_rule_module_ ... _ disabled
content_rule_sysctl _ ...
content_rule_audit_rules_ ...**

`    

<rule-result idref="audit_rules_file_deletion_events_rename" time="2017-06-06T13:45:59" severity="medium" weight="1.000000">

      <result>notapplicable</result>

      <check system="http://oval.mitre.org/XMLSchema/oval-definitions-5">

        <check-content-ref name="oval:ssg-audit_rules_file_deletion_events_rename:def:1" href="ssg-rhel7-oval.xml"/>

      </check>

      <check system="http://scap.nist.gov/schema/ocil/2">

        <check-content-ref name="ocil:ssg-audit_rules_file_deletion_events_rename_ocil:questionnaire:1" href="ssg-rhel7-ocil.xml"/>

      </check>

    </rule-result>
`

But when run after install:
`Title   Ensure auditd Collects File Deletion Events by User - rename
Rule    xccdf_org.ssgproject.content_rule_audit_rules_file_deletion_events_rename
Result  fixed`

Here is the run after install log:
[Rules run in anaconda not fixed during install.txt](https://github.com/OpenSCAP/scap-security-guide/files/1059231/Rules.run.in.anaconda.not.fixed.during.install.txt)

**Comment by redhatrises** [comment]
This should be fixed in the latest OSCAP Anaconda Addon release. See https://github.com/OpenSCAP/oscap-anaconda-addon/pull/48

Future issues with OSCAP Anaconda Addon should be opened at https://github.com/OpenSCAP/oscap-anaconda-addon
