### ISSUE TITLE
DISA: SSG requires SSH to be NOT installed

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#2061]
DISA:
>STIG requires it to be installed, the SCAP checks for it to be removed

**Comment by shawndwells** [comment]
.... no it doesn't. SSG does not mandate the installation or removal of SSH. *If* SSH is installed, *then* it must be configured certain ways.

Ref:
https://github.com/OpenSCAP/scap-security-guide/blob/master/RHEL/7/input/profiles/ospp-rhel7.xml#L311

@tbrunell adding to your list

**Comment by tbrunell** [comment]
resolved.

**Comment by tbrunell** [comment]
reolved.

**Comment by tbrunell** [comment]
resolved.
