### ISSUE TITLE
DISA: service_firewalld_enabled does not check if service is enabled

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#2065]
DISA:
> I found the reference file in https://github.com/OpenSCAP/scap-security-guide/blob/d0af7b820664fe193195eebe498840b654bdf509/RHEL/7/input/oval/oval_5.11/service_firewalld_enabled.xml but it's looking for dependencies, not that the service is active

**Comment by shawndwells** [comment]
I suppose they're right. 

`````
    <criteria comment="package firewalld installed and service firewalld is configured to start" operator="AND">
    <extend_definition comment="firewalld installed" definition_ref="package_firewalld_installed" />
    <criteria operator="OR" comment="service firewalld is configured to start">
      <criterion comment="multi-user.target wants firewalld" test_ref="test_multi_user_wants_firewalld" />
    </criteria>
    </criteria>
`````

"If firewalld is installed, then ensure it is configured to start"

They want to ensure the firewall is currently running, not just configured to start. This one is on us.

**Comment by redhatrises** [comment]
@shawndwells @tbrunell in line with this questions from DISA, can we ask DISA to have a separate Rule/STIGID for having firewall software installed, e.g. package_firewalld_installed? Having a single rule for installing and enabling the firewall gets a little squirrelly when mapping to STIGIDs.
