### ISSUE TITLE
DISA: unsure if sysctl_net_ipv4_ip_forward runs

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#2066]
> "Found in  scap-security-guide/shared/xccdf/system/network/kernel.xml but is different from the other checks so I'm not sure if it's being evaluated at all
"

**Comment by shawndwells** [comment]
@tbrunell yet another example of DISA not actually running a scan before sending hundreds and hundreds of lines of feedback. Please have them run a scan and see if this evaluates

spoiler: it does

selected in profile:
https://github.com/OpenSCAP/scap-security-guide/blob/master/RHEL/7/input/profiles/ospp-rhel7.xml#L132

oval + remediations are generated from templates.

**Comment by tbrunell** [comment]
resolved.
