### ISSUE TITLE
Functions defined in Loops

### ISSUE THREAD

**Issue by MollyJoBault** [OpenSCAP/scap-security-guide#2072]
There are functions being defined in loops.  I'm not sure what this does to memory usage in bash ... but it definitely isn't the preferred form.  I would recommend putting the definition at the top of the file.

I suspect the code that is doing this is located in combine-remediations.py.  I'm not very familiar with python.  I'll get around to learning it eventually...

Right now running a goodly amount of the rules I'm getting ~600MB footprint in peak memory usage (CentOS 7).  I'm not sure if this is normal for oscap but it surprised me.  This might limit the usage of this tool for embedded systems.  

```
for ARCH in "${RULE_ARCHS[@]}"
do
	PATTERN="-a always,exit -F arch=$ARCH -S init_module \(-F key=\|-k \).*"
	GROUP="modules"
	FULL_RULE="-a always,exit -F arch=$ARCH -S init_module -k modules"
	# Perform the remediation for both possible tools: 'auditctl' and 'augenrules'

function fix_audit_syscall_rule {

# Load function arguments into local variables
local tool="$1"
local pattern="$2"
local group="$3"
local arch="$4"
local full_rule="$5"

# Check sanity of the input
...
done
```

**Comment by dahaic** [comment]
@MollyJoBault can you check whether the peak memory usage is lower when remediation is not used? IMHO bash does not care about this stuff - it's string to the very moment it evaluates. No preprocessing whatsoever.

In this particular case, I would leave it as it is, because it helps readability.

**Comment by redhatrises** [comment]
Closing as no further information has been provided as requested. Please re-open with requested information to work this issue further.
