### ISSUE TITLE
Typo fix

### ISSUE THREAD

**Issue by marciofoz** [OpenSCAP/scap-security-guide#2082]
oscap.scan.content: ssg-centos-7-ds.xml
oscap.scan.profile.id: xccdf_org.ssgproject.content_profile_ospp-rhel7
oscap.check.id: xccdf_org.ssgproject.content_rule_auditd_data_retention_space_left_action

Two minor corrections can be made:
-full log after scan show: These include: **ignoresyslogemailexecsuspendsinglehalt**
-change to: These include: **ignore, syslog, email, exec, suspend, single and halt**

Default value in Centos 7 after a basic installation is SYSLOG, not SUSPEND.
-full log after scan show: Set this to email (instead of the default, which is **suspend**)
-change to: Set this to email (instead of the default, which is **syslog**)

**Comment by redhatrises** [comment]
@marciofoz can you provide a report or log please?

**Comment by marciofoz** [comment]
Hi!
Attached the print screen.

![oscap](https://user-images.githubusercontent.com/10158758/27284558-a0969972-54cf-11e7-9af5-dcfcc3b62798.png)

**Comment by redhatrises** [comment]
How/where was this log file generated? It looks like it removes all XML formatting which is why the grammar is incorrect.

**Comment by mpreisler** [comment]
@marciofoz it looks like you are not using `oscap` directly but are using some sort of an SCAP integration. Can you tell us what it is? This bug should probably be reported to the openscap integration because this text is output correctly from `oscap`.

**Comment by marciofoz** [comment]
Hi, I'm using Wazuh (https://wazuh.com). But in file ssg-centos-7-ds.xml (downloaded from oscap github), line 70648, I see the html code without spaces and commas:

`<html:ul><html:li><html:code>ignore</html:code></html:li><html:li><html:code>syslog</html:code></html:li><html:li><html:code>email</html:code></html:li><html:li><html:code>exec</html:code></html:li><html:       li><html:code>suspend</html:code></html:li><html:li><html:code>single</html:code></html:li><html:li><html:code>halt</html:code></html:li></html:ul> `

output: ignoresyslogemailexecsuspendsinglehalt

The correct output after fix the html code will be:
`<html:ul xmlns:html="http://www.w3.org/1999/xhtml"><html:li><html:code>ignore, </html:code></html:li><html:li><html:code>syslog, </html:code></html:li><html:li><html:code>suspend, </html:code></html:li><html:li><html:code>rotate, </html:code></html:li><html:li><html:code>and keep_logs</html:code></html:li></html:ul>`

output: ignore, syslog, suspend, rotate, and keep_logs

Or I'm wrong ?
Tks.

**Comment by mpreisler** [comment]
> Or I'm wrong ?

Yes, I believe you are. Notice that the HTML code is a list - `ul` = unordered list. `li` = list item. Wazuh just skips all this formatting and drops it.

This is a bug in Wazuh, please open it with them.

**Comment by shawndwells** [comment]
SSG code:
https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/xccdf/system/auditing.xml#L388#L396

`````
<ul>
<li><tt>ignore</tt></li>
<li><tt>syslog</tt></li>
<li><tt>email</tt></li>
<li><tt>exec</tt></li>
<li><tt>suspend</tt></li>
<li><tt>single</tt></li>
<li><tt>halt</tt></li>
</ul>
`````

It looks like this is a tooling issue (e.g. not SSG or OpenSCAP)

**Comment by shawndwells** [comment]
..... which Martin just commented on too =P
