### ISSUE TITLE
Kickstart: Anaconda installation hangs when RPM verify is enabled

### ISSUE THREAD

**Issue by MollyJoBault** [OpenSCAP/scap-security-guide#2098]
Running the oscap add-on with a profile that has RPM verify enabled causes Anaconda to hang at the "Configuring addons" step.

I would think this rule could get skipped if called during installation time since you know the RPMs will match the repo it is pointing to (since they just got installed).

```
Installing boot loader

Performing post-installation setup tasks

Writing network configuration

Creating users

Configuring addons

_
```

```
%addon org_fedora_oscap
    content-type = scap-security-guide
    profile = <profile name>
%end
```
```
>ps -ea 
oscap
probe_system_info
probe_rpmverifyfile
probe_system_info
probe_textfilecontent54
probe_file
```
edit: previous version of this the ps was truncated

**Comment by MollyJoBault** [comment]
This issue is actually more fun than I originally thought.  I've previously had oscap running as a post-script in Anaconda and this used to work.  Now, running oscap as a post-script is also freezing the install.

**Comment by mpreisler** [comment]
@MollyJoBault you have to give us versions of what you used.

**Comment by MollyJoBault** [comment]
@mpreisler 
CentOS 7.3 Installer: 21.48.22.93-1
The SSG version is end of day Friday's 
The oscap version is: 1.2.10

**Comment by MollyJoBault** [comment]
It seems to be frozen on this line ... I think:
`if ! grep -q "/usr/sbin/aide --check" `
It looks like the file is missing that it ought to be searching ... 

PS. Debugging in anaconda is not my favorite past time

**Comment by MollyJoBault** [comment]
Submitted a pull request.  Will test tomorrow and that is the fix will close this ticket.  Sorry for the red herring above.  I had recently turned on rpm verify and was convinced that was the change that broke my test environment.

**Comment by mpreisler** [comment]
PR #2100

**Comment by MollyJoBault** [comment]
Tested.  That code was the issue.
