### ISSUE TITLE
Typo in SSG remediation description for "Add nosuid Option to /home"?

### ISSUE THREAD

**Issue by jmnielsen7** [OpenSCAP/scap-security-guide#2102]
Perhaps I am mistaken or confused on the intent of this item from the SSG scan report (read in the html report for pass/failed/error/not checked status), but it seems to randomly mention **/tmp** when it means **/home** instead:

>**Rule ID:** xccdf_org.ssgproject.content_rule_mount_option_home_nosuid	
**identifiers:**  CCE-81153-9
**references:**  CM-7, MP-2, 1.1.3, RHEL-07-021000
**Description:** The nosuid mount option can be used to prevent execution of setuid programs in /home. The SUID and SGID permissions should not be required in these user data directories. Add the nosuid option to the fourth column of /etc/fstab for the line which controls mounting of /tmp.

Aside from it switching from talking about /home to /tmp, since this check was marked "Failed" for me I checked the current state of my /etc/fstab and the /home and /tmp entries look like this:

```
/dev/mapper/VolGroup-LogVol02 /home                 xfs     nodev           0 0
/dev/mapper/VolGroup-LogVol01 /tmp                    xfs     nodev,noexec,nosuid 0 0
```

So **nosuid** is already set for **/tmp** in my case, so if _xccdf_org.ssgproject.content_rule_mount_option_home_nosuid_ was really checking for this setting on /tmp instead of /home I would have expected a "Pass" on it, unless for some reason it checks both.

**Comment by redhatrises** [comment]
It's a typo. Thanks for reporting!
