### ISSUE TITLE
Typos in remediation scripts NIST 800 171 auditd rules?

### ISSUE THREAD

**Issue by guysystems** [OpenSCAP/scap-security-guide#2123]
I think there are typos in some of the remediation scripts. I am testing the NIST 800 171 rules on CentOS 7 with OpenSCAP 1.2.14 & scap security guide 0.1.33-1.

Example: Rule ID xccdf_org.ssgproject.content_rule_audit_rules_unsuccessful_file_modification_creat
Tests for existence of lines with "exit=-EACCES" & "exit=-EPERM"
However the remediation script contains "exit=-EACCESS" & "exit=-EPRM"

Same in:
xccdf_org.ssgproject.content_rule_audit_rules_unsuccessful_file_modification_open
xccdf_org.ssgproject.content_rule_audit_rules_unsuccessful_file_modification_openat
xccdf_org.ssgproject.content_rule_audit_rules_unsuccessful_file_modification_open_by_handle_at
xccdf_org.ssgproject.content_rule_audit_rules_unsuccessful_file_modification_truncate &
xccdf_org.ssgproject.content_rule_audit_rules_unsuccessful_file_modification_ftruncate

**Comment by redhatrises** [comment]
Closing as this was fixed in the latest release.
