### ISSUE TITLE
prelinking check fails

### ISSUE THREAD

**Issue by guysystems** [OpenSCAP/scap-security-guide#2124]
On CentOS 7 machine, using NIST 800 171 profile

Rule ID xccdf_org.ssgproject.content_rule_disable_prelink fails even though prelinking is turned off:

grep  ^PRELINKING /etc/sysconfig/prelink
PRELINKING=no

Items found violating Tests whether prelinking is disabled:

Path	Content
/etc/sysconfig/prelink	PRELINKING=no

**Comment by redhatrises** [comment]
Closing as this was fixed in the latest release.
