### ISSUE TITLE
combine-ovals fails to match affected

### ISSUE THREAD

**Issue by pthierry38** [OpenSCAP/scap-security-guide#2137]
Hi all!

I've detected that the updated version of combine-ovals using python2.7 lxml (version 3.7.1) fails to match <affected> XML subelements using the updated python syntax:
```python
for affected in xml_tree.findall(".//affected"):
```
This line just never match, without failing, keeping the 'multi_platform_*. string in the generated XML file.

The previous way works well:
```python
for affected in xml_tree.findall('.//*[@family="unix"]'):
```

Test done on Debian Stretch (9.0).

**Comment by redhatrises** [comment]
@pthierry38 `combine-ovals.py` doesn't use lxml any more. Are you trying this with the latest SSG content?

**Comment by pthierry38** [comment]
Yes, with head of master

**Comment by mpreisler** [comment]
I can reproduce this.

Will fix in a moment.

**Comment by pthierry38** [comment]
Great thanks!

**Comment by mpreisler** [comment]
Just to clear this up a little bit. The combine-ovals is not using `lxml` but the same issue would be there if it was using `lxml`. It is caused by us trying to match namespaces elements with a query with no namespace. It will never match anything.
