### ISSUE TITLE
Platform reference missing in a XCCDF component.

### ISSUE THREAD

**Issue by ndiab** [OpenSCAP/scap-security-guide#2152]
In SCAP contents provided in the scap-security-guide-0.1.3.4 (the last release), several rules in the XCCDF component apply to the platform "cpe:/a:machine". But, we do not find this reference in the parent node (benchmark level).

The specification for the XCCDF 1.2 indicate that the benchmark Element SHOULD use the platform element to identify the systems or products to which the benchmark applies. Referring to the rfc2119, it means that is not an absolute requirement but the full implications must be understood and carefully weighed before choosing a different course.

I would like to know if you have a reason to the absence of this element or if it is an oversight ?

I found this issue in the following documents : ssg-centos7-ds.xml and ssg-rhel7-ds.xml. I have not checked other contents.

**Comment by yuumasato** [comment]
Hello,

checking 'ssg-rhel7-ds.xml' from [zip](https://github.com/OpenSCAP/scap-security-guide/releases/download/v0.1.34/scap-security-guide-0.1.34.zip) on release page I can find 3 'platform' under 'Benchmark' element.
```
      <platform idref="cpe:/o:redhat:enterprise_linux:7"/>
      <platform idref="cpe:/o:redhat:enterprise_linux:7::client"/>
      <platform idref="cpe:/o:redhat:enterprise_linux:7::computenode"/>
```
And the reference for 'cpe:/a:machine' can be found in another component within the data stream in the oval component 'scap_org.open-scap_comp_ssg-rhel7-oval.xml'.

All rules in 'ssg-rhel7-ds.xml' should apply to RHEL7 systems, and some Rules are refined to apply only for instances that are virtual machines or bare metal.

**Comment by ndiab** [comment]
Hello yuumasato, thank you for the answer,

I saw that these 3 platforms were referenced under the "Benchmark" element. But if we check deeply, we can find that 4 platforms are referenced under child elements "Rule". It means that this benchmark can be used in 4 differents platforms but only 3 are referenced on the "root of the benchmark".
If we comply with the SCAP 1.2 specifications, each platform used in the benchmark should be referenced at this location 

As you mentionned, the missing platform is "machine" apply for bare metal or VM,  Does that mean that is not important to reference this platform at this location because this is not the main target of this document ?

**Comment by yuumasato** [comment]
> If we comply with the SCAP 1.2 specifications, each platform used in the benchmark should be referenced at this location

Could you provide reference to this in the specification?

> As you mentionned, the missing platform is "machine" apply for bare metal or VM, Does that mean that is not important to reference this platform at this location because this is not the main target of this document ?

No, it doesn't mean that it is not important.
It is refining the platform that the item applies to. In last paragraph of section 6.2.5 of XCCDF 1.2 spec, it says that items without 'platform' element apply to the same set of platforms of nearest enclosing ancestor. 
When evaluation reaches a 'Rule' it is considered to apply to RHEL7, because its nearest enclosing ancestor is the `Benchmark`. When the 'Rule' contains a `<platform idref="cpe:/a:machine"> element it is also checked if the system is a VM or bare metal machine.

**Comment by ndiab** [comment]
> Could you provide reference to this in the specification?

In the table 4 of the XCCDF 1.2 spec, section 6.3.2 : properties of the <xccdf:Benchmark> element.

> It is refining the platform that the item applies to. In last paragraph of section 6.2.5 of XCCDF 1.2 spec, it says that items without 'platform' element apply to the same set of platforms of nearest enclosing ancestor.
When evaluation reaches a 'Rule' it is considered to apply to RHEL7, because its nearest enclosing ancestor is the Benchmark.

I agree with you, but in our case the missing is at "benchmark" level and it contains no ancestor who reference platforms. Then if an interpreter do not analyse under the child elements, it will not detect this platform and could induce a failed audit during the process or  invalidate the content. (I got this problem in other interpreters than open SCAP).

**Comment by yuumasato** [comment]
I see, I lean towards not adding `machine` and `container` platform elements to Benchmark.

As "justification", our aim is to not create separate Benchmarks or Profiles for (VMs and bare metal machines) or containers. So every profile in SSG is applicable to both `cpe:/a:machine` and `cpe:/a:container` and we fine tune some Rules for one or other platform.
Adding platform elements for `machine` and `container` in every Benchmark would just bloat content without much benefit.

Can you share what is the scanner that complains about this?

**Comment by redhatrises** [comment]
Closing as further information has not been provided on this issue. In addition, the XCCDF 1.2 spec in 6.5.2 clearly states that platform is a valid element in XCCDF Groups, Rules, Profiles, and/or Benchmarks.
