### ISSUE TITLE
Profile with Rules 'service_sshd_enabled' and 'sshd_disable_gssapi_auth' on a machine without SSH installed needs two runs of remediation for both rules to pass

### ISSUE THREAD

**Issue by yuumasato** [OpenSCAP/scap-security-guide#2154]
When the machine is scanned the first time, `service_sshd_enabled` fails, and `sshd_disable_gssapi_auth` passes. Remediation installs sshd, and nothing is done about `sshd_disable_gssapi_auth`.
On the second scan `service_sshd_enabled` passes but `sshd_disable_gssapi_auth` fails, and remediation configures GSSAPIAuthentication.

This happens because `sshd_disable_gssapi_auth` passes when SSH is not installed or SSH is configured with GSSAPIAuthentication disabled.

Some other sshd rules present the same behavior:
```
sshd_disable_kerb_auth
sshd_use_approved_macs
sshd_use_approved_ciphers
sshd_enable_warning_banner
sshd_disable_root_login
sshd_disable_empty_passwords
sshd_disable_rhosts_rsa
```
Only profile `stig-rhel7-disa`  has Rule `service_sshd_enabled` selected.

Maybe we should split `sshd_disable_gssapi_auth` into two rules one for when `service_sshd_enabled` is selected and one for when `service_sshd_disabled` is selected. But I don't like this idea.

Any suggestion how to avoid need of two scans and remediations?

**Comment by yuumasato** [comment]
Complete list of rules affected

sshd_allow_only_protocol2
sshd_disable_gssapi_auth
sshd_disable_kerb_auth
sshd_enable_strictmodes
sshd_use_priv_separation
sshd_disable_compression
sshd_print_last_log
sshd_set_idle_timeout
sshd_set_keepalive
sshd_disable_user_known_hosts
sshd_disable_rhosts_rsa
sshd_disable_root_login
sshd_disable_empty_passwords
sshd_enable_warning_banner
sshd_do_not_permit_user_env
sshd_use_approved_ciphers
sshd_use_approved_macs

**Comment by redhatrises** [comment]
@yuumasato remediation scripts should check that ssh is enabled. See #2136 for how aide remediations where handled.

**Comment by yuumasato** [comment]
> remediation scripts should check that ssh is enabled.

@redhatrises Ok, agreed, but this is not a problem because the OVAL check passes if ssh is disabled, so remediation script is not executed.

Looking further:
I see that only `C2S`Profile for RHEL6 selects `service_sshd_disabled`, and 
Profiles `stig-rhel7-disa` and `ospp-rhel7` for RHEL7 selects `service_sshd_enabled`, and 
there are lots of other Profiles that doesn't select neither enabled nor disabled but selects some of the Rules mentioned above.

```
[wsato@coruscant scap-security-guide]$ grep -R --exclude-dir=build sshd_set_idle_timeout | grep profile
Debian/8/input/profiles/common.xml:<select idref="sshd_set_idle_timeout" selected="true"/>
Debian/8/input/profiles/anssi_np_nt28_average.xml:<select idref="sshd_set_idle_timeout" selected="true"/>
Ubuntu/14.04/input/profiles/common.xml:<select idref="sshd_set_idle_timeout" selected="true"/>
Ubuntu/14.04/input/profiles/anssi_np_nt28_average.xml:<select idref="sshd_set_idle_timeout" selected="true"/>
Ubuntu/16.04/input/profiles/common.xml:<select idref="sshd_set_idle_timeout" selected="true"/>
Ubuntu/16.04/input/profiles/anssi_np_nt28_average.xml:<select idref="sshd_set_idle_timeout" selected="true"/>
Fedora/input/profiles/common.xml:  <select idref="sshd_set_idle_timeout" selected="true"/>
RHEL/7/input/profiles/rht-ccp.xml:<select idref="sshd_set_idle_timeout" selected="true"/>
RHEL/7/input/profiles/stig-rhel7-disa.xml:<select idref="sshd_set_idle_timeout" selected="true" />
RHEL/7/input/profiles/pci-dss.xml:<select idref="sshd_set_idle_timeout" selected="true"/>
RHEL/7/input/profiles/cjis-rhel7-server.xml:<select idref="sshd_set_idle_timeout" selected="true"/>
RHEL/7/input/profiles/ospp-rhel7.xml:<select idref="sshd_set_idle_timeout" selected="true" />
RHEL/7/input/profiles/C2S.xml:<select idref="sshd_set_idle_timeout" selected="true" />
RHEL/6/input/profiles/rht-ccp.xml:<select idref="sshd_set_idle_timeout" selected="true"/>
RHEL/6/input/profiles/pci-dss.xml:<select idref="sshd_set_idle_timeout" selected="true"/>
RHEL/6/input/profiles/common.xml:<select idref="sshd_set_idle_timeout" selected="true"/>
RHEL/6/input/profiles/usgcb-rhel6-server.xml:<select idref="sshd_set_idle_timeout" selected="true" />
RHEL/6/input/profiles/C2S.xml:<select idref="sshd_set_idle_timeout" selected="true" />
```

I don't know whether these Profiles want SSH enabled or not.
But the way I read this is that these Profile don't care if SSH is enabled or not, just that, if it is enabled, it is configured like the selected Rules demand.
@redhatrises and @shawndwells Maybe you can tell if my understanding above is correct?

I would propose to remove this OR criteria that makes the check pass if SSH is not enabled and unselect sshd rules from RHEL6 C2S Profile, since it requires sshd_disabled.
But it will not work if the Profiles which don't explicitly require SSH enabled or disabled are expected to work as described above.
