### ISSUE TITLE
Rule: xccdf_org.ssgproject.content_rule_ldap_client_start_tls - Doesn't check if USELDAPAUTH is set before checking

### ISSUE THREAD

**Issue by OnceUponALoop** [OpenSCAP/scap-security-guide#2159]
Tested on 
RHEL = 7.1
scap-security-guide = 0.1.34

The rule should verify that LDAP is configured to use TLS **_iff_** `USELDAPAUTH=yes` is defined in `/etc/sysconfig/authconfig`. 

The rule doesn't check if the USELDAPAUTH is set to yes before checking that `start_tls` is present in `/etc/nslcd.conf` thereby failing on systems that don't have ldapauth configured.

**Comment by redhatrises** [comment]
Duplicate of #1851. Closing.
