### ISSUE TITLE
Set Password Minimum Age - Definition does not reference variable value

### ISSUE THREAD

**Issue by OnceUponALoop** [OpenSCAP/scap-security-guide#2161]
Rule                            |OS           | scap-security-guide | Profile
--------------------------------|------------ | ------------------- | --------
accounts_minimum_age_login_defs |RHEL 7.1     | 0.1.34              | USGCB

The description of the rule states:

> To specify password minimum age for new accounts, edit the file /etc/login.defs and add or correct the following line, replacing DAYS appropriately:
> 
> PASS_MIN_DAYS DAYS
> 
> A value of 1 day is considered sufficient for many environments. The DoD requirement is 1. 

I set the value in `/etc/login.defs` to `1` but the check kept failing. 
Looking into it some more it seems the check is checking that `PASS_MIN_DAYS <VALUE>` against `oval:ssg-variable_last_pass_min_days_instance_value:var:1` which defaults to `7`

I'm not sure which value is the correct one here, the `1` in the description or the `7` in the variable.

**Comment by redhatrises** [comment]
What profile are you running and how did you set the variable?

**Comment by OnceUponALoop** [comment]
Sorry i should have probably referenced that in the bug report. I'm using the USGCB profile and I'm not changing the variable (yet).

To clarify, "I set my value to 1" meant i changed the PASS_MIN_DAYS value to 1 in `/etc/login.defs`.

**Comment by redhatrises** [comment]
Which USGCB profile are you using for RHEL7?

**Comment by OnceUponALoop** [comment]
I'm sorry, I didn't realize there were multiple under the RHEL7 USGCB. 

Is this the info you're looking for?

```
Benchmark URL   | /root/scap-security-guide-0.1.34-oval-5.10/ssg-rhel7-ds.xml
Benchmark ID    | xccdf_org.ssgproject.content_benchmark_RHEL-7
Profile ID      | xccdf_org.ssgproject.content_profile_ospp-rhel7
```

**Comment by redhatrises** [comment]
@OnceUponALoop depending on which profile you select and use will depend on what PASS_MIN_DAYS setting value is expected. For example in the stig-rhel7-disa profile, it is set to 1 in other profiles such as rht-cpp and ospp profiles it is set to 7.

**Comment by OnceUponALoop** [comment]
@redhatrises my apologies for the confusion - I should have been clearer in initial bug report.

The issue is in description which doesn't reference the checked variable value but instead has a hard coded value of 1. 

Please reference the screenshot below. The statement at `(1)`  _A value of 1 day is considered sufficient for many environments. The DoD requirement is 1_ uses hardcoded values instead of referencing the checked variable like `(2)`.

Shouldn't it reference the variable to make things clearer? This is already done in other checks, ex "Set Password Minimum Length" where the value displayed in the description references the variable value used by the check.

![image](https://user-images.githubusercontent.com/3958336/28198617-13549712-6825-11e7-9db4-1c133c8109bd.png)
