### ISSUE TITLE
selinux_all_devicefiles_labeled finds /dev/vmci and /dev/vsock as unlabeled

### ISSUE THREAD

**Issue by GaryGapinski** [OpenSCAP/scap-security-guide#2173]
The subject rule (Ensure No Device Files are Unlabeled by SELinux) flags ```/dev/vmci``` and ```/dev/vsock``` as unlabeled.

Should I report this as a bug against open-vm-tools?

**Comment by redhatrises** [comment]
For the sake of documentation, can you provide the OS, SSG version, and output of `ls -lZ /dev/vmci /dev/vsock`

**Comment by OnceUponALoop** [comment]
It's a known issue in RHEL7. 

Reference: 
- [RHEL KB 3062591 ](https://access.redhat.com/solutions/3062591)
- [Bugzilla 1451358](https://bugzilla.redhat.com/show_bug.cgi?id=1451358)

**Comment by redhatrises** [comment]
@GaryGapinski you should open a bug against open-vm-tools.

**Comment by redhatrises** [comment]
Closing as this is not an SSG issue and is being worked in the BZ mentioned above.
