### ISSUE TITLE
aide_use_fips_hashes remediation works, but oval check fails

### ISSUE THREAD

**Issue by MollyJoBault** [OpenSCAP/scap-security-guide#2193]
Running xccdf_org.ssgproject.content_rule_aide_use_fips_hashes the remediation works on CentOS 7.3

`Fix execution completed and returned: 0`

Also confirmed in the configuration file.  But the oval check fails:

`Failed to verify applied fix: Checking engine returns: fail`

**Comment by redhatrises** [comment]
@MollyJoBault this is because CentOS is not a certified FIPS system, so this check will always fail.

**Comment by MollyJoBault** [comment]
Awesome thanks.
