### ISSUE TITLE
SSG does not open port 22

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#2202]
When hardening the default firewall rules, SSG does not open port 22. This makes default installations of RHEL 7.4 unusable.

**Comment by dahaic** [comment]
Ah, you are right, Shawn - there is a rule to enable this, `xccdf_org.ssgproject.content_rule_firewalld_sshd_port_enabled` Unfortunately not used in any of the profiles. We should probably enable it for every profile where `rule_service_sshd_enabled` is set.

**Comment by linux-modder** [comment]
Still getting used to the format of the repo, those changes are only needed on the xccdf files or also oval?

**Comment by yuumasato** [comment]
The only changes required should be to select the rule in the Profiles. Take a look at  `RHEL/7/input/profiles` directory.

**Comment by redhatrises** [comment]
For the STIG, it would be correct to add ssh port in OVAL for #1850 and not adding `xccdf_org.ssgproject.content_rule_firewalld_sshd_port_enabled` as a separate item to the STIG profile.
