### ISSUE TITLE
RHEL 7.3 error: rpm_verify_permissions remediation error

### ISSUE THREAD

**Issue by VadimDor** [OpenSCAP/scap-security-guide#2205]
**In the remediation script [scap-security-guide/shared/templates/static/bash/rpm_verify_permissions.sh](https://github.com/OpenSCAP/scap-security-guide/blob/568d1aa3f45f6f8ba8e7287e5ff16adb0b62112f/shared/templates/static/bash/rpm_verify_permissions.sh)  line 12** 
FILES_WITH_INCORRECT_PERMS=($(rpm -Va --nofiledigest | grep '^.M'))
**returns e.g**. 
_SM.....T.  c /etc/profile
.M.....T.  c /etc/firewalld/firewalld.conf
SM.....T.  c /etc/ssh/sshd_config_
**where the attributes before file names are not wanted.**

**The following returns file names only:**
_FILES_WITH_INCORRECT_PERMS=($(rpm -Va --nofiledigest | grep '^.M' | cut -d ' ' -f4-))_

**- returns:** 
_/etc/profile
/etc/firewalld/firewalld.conf
/etc/ssh/sshd_config
 /etc/rc.local_

**Tested with  centos-release-7-3.1611.el7.centos.x86_64**

**Comment by dahaic** [comment]
Good catch! Can you submit a patch?
