### ISSUE TITLE
Configure NTP Maxpoll Interval not applicable to chronyd

### ISSUE THREAD

**Issue by david-paige-ctr** [OpenSCAP/scap-security-guide#2224]
The ntp_set_maxpoll is not applicable to systems running chronyd.  The chronyd service is the default for rhel 7, and packages are available for rhel 6, so this check should determine if ntpd is being used.

Rule ID ntp_set_maxpoll

**Comment by redhatrises** [comment]
As `maxpoll` can also be configured in `/etc/chrony.conf`, how does this rule not apply to chrony? Seems like the rule/oval should be expanded to make sure it is configured in `chrony.conf` as well.

**Comment by david-paige-ctr** [comment]
You are correct.  It does apply to Chrony.  I was not able to find any reference to maxpoll in the man or info pages, and the Rhel 7 System Administration Guide mentions it only under ntpd.

**Comment by cpellitt** [comment]
This rule is not particularly applicable to ntpd actually. It requires a value of 17 or lower for maxpoll. 17 is the highest value you can set, so there is no valid configuration that does not meet this requirement.

**Comment by david-paige-ctr** [comment]
It would be nice to not have the rule trigger as a FAIL though on chrony.  It sounds like the absence of this option meets the requirement of this rule.  Still, it might be prudent to check that, if present, maxpoll is not set greater than 17?

**Comment by david-paige-ctr** [comment]
As far as I can tell, maxpoll should only be used as an option on the server line.  I discovered today that by running the command below, I can satisfy the test.

echo "maxpoll 17" > /etc/ntp.conf
