### ISSUE TITLE
file_permissions_grub2_cfg fails on EFI-booted system (RHEL7)

### ISSUE THREAD

**Issue by GaryGapinski** [OpenSCAP/scap-security-guide#2229]
Since all files in ```/boot/efi/EFI/redhat/``` have execute bit set (vfat file system).

I'll have a fix that ignores [uexec](https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/templates/static/oval/file_permissions_grub2_cfg.xml#L36).

The prose section of the Rule is also misleading.

**Comment by redhatrises** [comment]
This needs to be broken out into new Rule/OVAL/remediation content.
