### ISSUE TITLE
CIS/C2S alignment: Set Deny For Failed Password Attempts method

### ISSUE THREAD

**Issue by rybal06** [OpenSCAP/scap-security-guide#2259]
CIS 2.1.1 suggests the following configuration for pam_faillock:

```
auth required pam_faillock.so preauth audit silent deny=5 unlock_time=900 
auth [success=1 default=bad] pam_unix.so
auth [default=die] pam_faillock.so authfail audit deny=5 unlock_time=900 
auth sufficient pam_faillock.so authsucc audit deny=5 unlock_time=900
```

The check in C2S fails that configuration.

```
testoval.py accounts_passwords_pam_faillock_deny_root.xml
.... text omitted....
      <tests>
        <test test_id="oval:scap-security-guide.testing-test_pam_faillock_authfail_deny_root_password-auth:tst:1" version="1" check_existence="all_exist" check="all" result="false"/>
        <test test_id="oval:scap-security-guide.testing-test_pam_faillock_authfail_deny_root_system-auth:tst:1" version="1" check_existence="all_exist" check="all" result="false"/>
        <test test_id="oval:scap-security-guide.testing-test_pam_faillock_preauth_silent_password-auth:tst:1" version="1" check_existence="all_exist" check="all" result="false"/>
        <test test_id="oval:scap-security-guide.testing-test_pam_faillock_preauth_silent_system-auth:tst:1" version="1" check_existence="all_exist" check="all" result="false"/>
      </tests>
```

**Comment by redhatrises** [comment]
@rybal06 can you add the results file that was generated (should be in `/tmp`) with `testoval.py` to this ticket?

**Comment by redhatrises** [comment]
@rybal06 this check expects that faillock locks failed root attempts which is used in the STIG profiles. This check is not configured in C2S or PCI profiles. Why is this an issue?

**Comment by rybal06** [comment]
@redhatrises My apologies, I thought it was in C2S by default, but I was actually using a custom profile (RH Satellite does not yet support tailoring files). It seems like the approach suggested in the DSS may be better than what the CIS suggests, although CIS also requires disabling root logons, so having the lockout for root might not make a difference since it cannot logon anyway. 

CIS does require pam fail lock to be configured, but I am guessing that because a directly equivalent check does not exist in the scap-security-guide, it was left disabled?  Maybe a future version of CIS will change the suggested pam configuration.
