### ISSUE TITLE
add checks and fixes in rule_rpm_verify_permissions" 

### ISSUE THREAD

**Issue by notanothername** [OpenSCAP/scap-security-guide#2261]
rule_rpm_verify_permissions runs 3 tests, and there are 2 possible remediations, but only 1 test and 1 remediation are shown to users.  Can these tests be included in the help text: 
 rpm -Va | grep '^.....U'     (5 dots)
 rpm -Va | grep '^......G'    (6 dots)
and this remediation added (which does appear in the DISA STIG):
 rpm --setugids <packagename>  

thanks,
Ed

**Comment by redhatrises** [comment]
This should be fixed with #2431
