### ISSUE TITLE
false positive for accounts have homedir login.defs

### ISSUE THREAD

**Issue by notanothername** [OpenSCAP/scap-security-guide#2262]
rule_accounts_have_homedir_login_defs failing when the required line exists:
CREATE_HOME    yes

It appears that the regex is actually looking for "no" instead of "yes", and taking the missing "no" as a fail.  Change regex to look for "yes"?

thank you,
Ed

**Comment by redhatrises** [comment]
Hi Ed,

Can you provide the version of SSG that you are using? The regex in the text is looking for `yes`.

```<ind:pattern operation="pattern match">^[\s]*(?i)CREATE_HOME(?-i)[\s]+yes[\s]*(?:|(?:#.*))?$</ind:pattern>```

**Comment by notanothername** [comment]
Hi,


I'm away from the office till Monday so I can't say for certain, but it would be the version that came with RHEL-7.4 (0.1.33-5.el7?), or possibly, if the full update to 7.4 didn't replace it, the version that came with the beta release of 7.4, as we deployed that rpm by itself when it came out, to take advantage of the "DISA-aligned" profile right away.   For sure though the regex that was displayed in the html report when using "--oval-results" had "no" in it, not "yes".


thank you,

Ed




________________________________

**Comment by notanothername** [comment]
On 08/16/2017 05:07 PM, redhatrises wrote:
> Hi Ed,
> 
> Can you provide the version of SSG that you are using? The regex in the 
> text is looking for |yes|.
> 
> |<ind:pattern operation="pattern 
> match">^[\s]*(?i)CREATE_HOME(?-i)[\s]+yes[\s]*(?:|(?:#.*))?$</ind:pattern>|


Hello,

The RHEL7 systems have scap-security-guide-0.1.33-5.el7.  Here is a 
copy-n-paste from an html report with --oval-results (the pattern has 
"no" rather than "yes"):

OVAL details
Items not found violating Check value of CREATE_HOME in /etc/login.defs:
Object oval:ssg-obj_accounts_have_homedir_login_defs:obj:1 of type 
textfilecontent54_object
Filepath	Pattern	    Instance
/etc/login.defs	^[\s]*(?i)CREATE_HOME(?-i)[\s]+no[\s]*(?:|(?:#.*))?$	1

I'm confused by the "Items not found violating Check" phrasing, perhaps 
the check is meant to succeed if "no" is not found, but it is failing. 
Thanks for looking into this.

Ed

**Comment by dahaic** [comment]
Hello Ed,
in upstream, it has been reported ( #1983 ) and fixed already (See #1984 )
For RHEL systems, RHBZ is open: https://bugzilla.redhat.com/show_bug.cgi?id=1465683

Thanks for report, and sorry for confusion :)
