### ISSUE TITLE
Missing CNSSI 1253 profile for RHEL7

### ISSUE THREAD

**Issue by enjaygee** [OpenSCAP/scap-security-guide#2266]
The "CNSSI 1253 Low/Low/Low Control Baseline for Red Hat Enterprise Linux 7" appears to have been available as of v0.1.32 (https://github.com/OpenSCAP/scap-security-guide/blob/v0.1.32/RHEL/7/input/profiles/nist-CL-IL-AL.xml) but is not in v0.1.33 (https://github.com/OpenSCAP/scap-security-guide/tree/v0.1.33/RHEL/7/input/profiles) up through master (https://github.com/OpenSCAP/scap-security-guide/tree/master/RHEL/7/profiles).

I do not see the removal of this profile referenced in the v0.1.33 release notes (https://github.com/OpenSCAP/scap-security-guide/releases/tag/v0.1.33) so wonder if the removal is a regression.

**Comment by shawndwells** [comment]
Hey @enjaygee - This was rolled into the USGCB profile.

Ref:
https://github.com/OpenSCAP/scap-security-guide/blob/master/RHEL/7/profiles/ospp-rhel7.xml#L11

**Comment by enjaygee** [comment]
Thank you @shawndwells for the information and quick feedback.
