### ISSUE TITLE
NIST-800-171 SELinux Booleans false negative

### ISSUE THREAD

**Issue by guysystems** [OpenSCAP/scap-security-guide#2276]
The following SELinux booleans are set as directed in the profile, but fail when testing. They all say "Disable" and have the setting of "false", but report as a violation

abrt_upload_watch_anon_write
guest_exec_content
selinuxuser_execstack
selinuxuser_rw_noexattrfile
xguest_connect_network
xguest_exec_content
xguest_mount_media
xguest_use_bluetooth

**Comment by shawndwells** [comment]
@redhatrises is this something you could take a look at?

**Comment by shawndwells** [comment]
p.s. @mpreisler all the sebool OVAL's now error. Is this a known issue of the YAML conversion?

**Comment by redhatrises** [comment]
@guysystems for each of the selinux booleans can you provide the output of `getsebool`?

**Comment by redhatrises** [comment]
Ran the latest from master, and all these pass. Without any more information to go on, closing this issue. Please reopen if the issue persists.
