### ISSUE TITLE
need new rule: CtrlAltDelBurstAction

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#2277]
As identified by @bgjoseluis

----
Hello,

just trying to help.

According to this tech note "https://cgit.freedesktop.org/systemd/systemd/commit/?id=2e5c94b9aa" if you press 7x in less than 2s the fix doesn't work.

In RHEL7.4 there is also a new option in systemd configuration "CtrlAltDelBurstAction" that needs to be configured:

CtrlAltDelBurstAction=none

So for RHEL7.4 you need to run (to work properly):

( ln -sf /dev/null /etc/systemd/system/ctrl-alt-del.target or systemctl mask ctrl-alt-del.target)
and
cp -p /etc/systemd/system.conf /etc/systemd/system.conf.ori
sed -i 's/#CtrlAltDelBurstAction=reboot-force/CtrlAltDelBurstAction=none/' /etc/systemd/system.conf

RHEL7.4 release notes: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html-single/7.4_Release_Notes/index.html

Thanks in advance.

**Comment by redhatrises** [comment]
To fully close this issue, an OVAL file needs to be written.

**Comment by shawndwells** [comment]
and rule to be selected in a profile
