### ISSUE TITLE
Maxpoll rule uses incorrect syntax

### ISSUE THREAD

**Issue by cpellitt** [OpenSCAP/scap-security-guide#2287]
xccdf_org.ssgproject.content_rule_chronyd_or_ntpd_set_maxpoll

This rule uses maxpoll as a standalone option, which is not a valid configuration. It can only be used with the "server" or "peer" directives.
Reference: [https://access.redhat.com/solutions/39194](https://access.redhat.com/solutions/39194)

Using maxpoll as suggested results in an error, similar to the following:
ntpd[54121]: line 63 column 1 syntax error, unexpected T_Maxpoll, expecting $end

**Comment by herrin** [comment]
Agree.

In ssg-rhel7-oval.xml:
     <ns3:pattern operation="pattern match">^[\s]*maxpoll[\s]+(\d+)$</ns3:pattern>

is 100% wrong for both ntp.conf and chrony.conf. Ntpd reports an error but starts anyway. Chronyd fails to start at all.

A correct configuration line in both looks like:

server ntp.server.com minpoll 4 maxpoll 10

Maybe something like this?
     <ns3:pattern operation="pattern match">^server[\s]+.*maxpoll[\s]+(\d+)</ns3:pattern>

but the rule must accept anything 10 or less, not just 10.
