### ISSUE TITLE
Leading and trailing whitespace in profile titles

### ISSUE THREAD

**Issue by xprazak2** [OpenSCAP/scap-security-guide#2300]
There are leading and trailing whitespace characters in profile titles for 'Upstream STIG for Red Hat Enterprise Linux 6 Workstation' and 'Upstream STIG for Red Hat Enterprise Linux 6 Server Running GUIs' which weren't there before. 

Affected versions: We found this in scap-security-guide 0.1.34 and 0.1.33, 0.1.30 is without whitespace

Steps to reproduce: 
1) `grep -B 1 -A 1 'Upstream STIG for Red Hat Enterprise Linux 6' /usr/share/xml/scap/ssg/content/ssg-rhel6-ds.xml`
2) notice the whitespace within tags for the profiles mentioned above as opposed to 'Upstream STIG for Red Hat Enterprise Linux 6 Server'

**Comment by matusmarhefka** [comment]
This is already fixed by PR https://github.com/OpenSCAP/scap-security-guide/pull/2215

**Comment by xprazak2** [comment]
Thanks!
