### ISSUE TITLE
RHEL6 RHEL7 dod_banners /etc/issue bash remediation broken & text changed

### ISSUE THREAD

**Issue by sradigan** [OpenSCAP/scap-security-guide#2327]
Bash remediation:
With the change of ```login_banner_text``` from ```dod_default``` to ```dod_banners``` in commit fb9a1f7; The [bash remediation's expansion function](https://github.com/OpenSCAP/scap-security-guide/blob/e93f9ccd924c576c5289bd6307e5235bee683217/RHEL/7/templates/static/bash/banner_etc_issue.sh#L6) was broken given the addition of the ^(regex1|regex2)$ syntax.

Updating the sed regex to the following will properly cut out the regex1 block, and it should work on strings such as ```dod_default``` which don't have that text (prepend: 's/\^(\(.*\)|.*$/\1/g;'):
```bash
sed 's/\^(\(.*\)|.*$/\1/g;s/\[\\s\\n\][+*]/ /g;s/\\//g;s/[^-]- /\n\n-/g'
```

Banner text:
In the same commit fb9a1f7, the banner text changed very slightly in  [shared/xccdf/system/accounts/banners.xml](https://github.com/OpenSCAP/scap-security-guide/blob/fb9a1f7ba4477f72926ba588339daea84c220cc3/shared/xccdf/system/accounts/banners.xml#L29), I don't know if this is by design.
```interests[\s\n]+--[\s\n]+not``` became ```interests--not``` in both ```dod_banners``` and ```dod_default```.

**Comment by cyberpear** [comment]
I have the same issue.
