### ISSUE TITLE
systemd service tests broken

### ISSUE THREAD

**Issue by sradigan** [OpenSCAP/scap-security-guide#2332]
Issue #2157 was resolved in commit e8498ec, however it broke all of the other systemd service unit tests. I believe commit should be reverted; It seems like it was appropriate to have the hard substitution of .service into all the service checks.

I believe the ideal fix is complementing the [scap-security-guide/RHEL/7/templates/template_socket_disabled](https://github.com/OpenSCAP/scap-security-guide/blob/master/RHEL/7/templates/template_socket_disabled) file with a socket_enabled template and placing the pcscd.socket requirement in another csv to generate a new test. I couldn't find the template_socket_disabled linked into the build system though.

**Comment by sradigan** [comment]
I have some code written for this, but it is still going through an internal review process so it can be contributed. I don't know how long it will take.

Essentially I reverted the e8498ec commit, removed the pcscd.socket entry from the csv, and created a sockets_enabled pipeline that would generate rules for .socket entries. I then had to change the [references to the pcscd.socket](https://github.com/OpenSCAP/scap-security-guide/blob/0dc16250ba25c751591622688fac0c7d716d76fe/RHEL/7/templates/static/oval/oval_5.11/smartcard_auth.xml#L12) to reflect the new socket naming scheme.

**Comment by redhatrises** [comment]
On Wednesday, September 20, 2017, Sean Radigan <notifications@github.com>
wrote:

> I have some code written for this, but it is still going through an
> internal review process so it can be contributed. I don't know how long it
> will take.
>
> Essentially I reverted the e8498ec
> <https://github.com/OpenSCAP/scap-security-guide/commit/e8498ec051ce1ce709dc6f51049fc3e4b7c35ec9>
> commit, removed the pcscd.socket entry from the csv, and created a
> sockets_enabled pipeline that would generate rules for .socket entries. I
> then had to change the references to the pcscd.socket
> <https://github.com/OpenSCAP/scap-security-guide/blob/0dc16250ba25c751591622688fac0c7d716d76fe/RHEL/7/templates/static/oval/oval_5.11/smartcard_auth.xml#L12>
> to reflect the new socket naming scheme.
>

Unfortunately, my WIP branch was merged before I was done, but keeping the
commit would be preferred as the sockets and services were being planned to
be put in one file that contain both .service and .socket. This would be
preferred for your PR.

**Comment by sradigan** [comment]
@redhatrises Ah ok, that makes much more sense for the commit message then. I'll hold off on getting any of my code into a PR.

What was the plan to have both services and sockets (and possibly others?) contained/generated in the same files? The CSV would contain .socket/.service extensions I assume, the generator logic would stay basically the same, the template files would stay mostly the same maybe with the exception of the [definition id](https://github.com/OpenSCAP/scap-security-guide/blob/ba7929be9fb7b91ed6ed3dabafdc0ffc350a0b2d/RHEL/7/templates/oval_5.11_templates/template_OVAL_service_enabled#L2), and then all the references to the definition id would need to be modified to accommodate the new id?
