### ISSUE TITLE
Add oval version to <def-group /> or keep oval version directories

### ISSUE THREAD

**Issue by redhatrises** [OpenSCAP/scap-security-guide#2374]
Should we add an attribute such as `oval_version="5.10"` to the <def-group /> element in our oval files and get rid of the oval versioned directories such as `oval_5.11`? Or, should we keep the oval versioned directories such as `oval_5.11` and expand to `oval_5.10`?

**Comment by yuumasato** [comment]
I'm in favor of using attributes, it will ease OVAL versioning in the long run.
And it will make possible to have OVAL 5.10 and 5.11 definitions in the same file, when making changes, it will be easier to keep them in sync.

**Comment by redhatrises** [comment]
Closing as this was fixed in #2409
