### ISSUE TITLE
build system: Changing files may not get noticed in rebuilds.

### ISSUE THREAD

**Issue by matejak** [OpenSCAP/scap-security-guide#2389]
#### Description of problem:

Changes in XCCDF files are not noticed.

#### Operating System Version:

Fedora 26, cmake 3.9.1

#### Steps to Reproduce:

1. Build ssg (e.g. `cd build && cmake .. && make rhel6).
2. Save the datastream.
3. Change an XCCDF that the `rhel6` targets depends upon (e.g. `../RHEL/6/xccdf/system/software/gnome.xml`).
4. Run `make rhel6` again - it seems that nothing happens.
5. Compare the two datastreams - they will be identical.
6. Run `make clean && make` - the produced datastream will reflect the modified XCCDF file.

**Comment by redhatrises** [comment]
I believe that this is expected behaviour as the content built successfully in the first place.

**Comment by konstruktoid** [comment]
`make clean` och `docker build --no-cache` is required because, as @redhatrises said, it was built successfully.

**Comment by jan-cerny** [comment]
I don't think that it's expected behavior. I expect that if I change anything, the change is detected by cmake and everything related is rebuild again. That's how cmake usually works. It shouldn't be related to the fact that previous build was successful.

**Comment by matejak** [comment]
Just for reference - modifying `rhel6/guide.xslt` is noticed by the build system and running `make` after a successful build results in rebuild of affected files. Conversely, modifying e.g. `shared/xccdf/system/software/gnome.xml` is another story - one has to run `make clean && make` in order to get a DS that is consistent with the source.

**Comment by yuumasato** [comment]
Maybe [glob](https://github.com/OpenSCAP/scap-security-guide/blob/master/cmake/SSGCommon.cmake#L110) for product XCCDF Rules is not working correctly.

For shared XCCDF Rules, we don't set them as dependency anywhere. And marking it all as dependency doesn't seem correct to me.

**Comment by redhatrises** [comment]
As the XCCDF and OVAL rules are merged with scripts external to CMake, is CMake still able to detect a change when really it is the script/executable doing the work, or is GLOB checking to see what changes if any occur in files.

**Comment by redhatrises** [comment]
According to CMake documentation, and unless I am reading this wrong, `glob` doesn't support regenerating files, so some other mechanism would have to be put into place to detect and regenerate the XCCDF on changes.

GLOB will generate a list of all files that match the globbing expressions and store it into the variable. Globbing expressions are similar to regular expressions, but much simpler. If RELATIVE flag is specified for an expression, the results will be returned as a relative path to the given path. (We do not recommend using GLOB to collect a list of source files from your source tree. If no CMakeLists.txt file changes when a source is added or removed then the generated build system cannot know when to ask CMake to regenerate.)

**Comment by mpreisler** [comment]
This is definitely a bug and this should be handled by the glob @yuumasato referenced.

It's expected for cmake to figure out changes to the files on disk. If you add new files or remove existing files you need to rerun configure because tracking that would be too expensive.
