### ISSUE TITLE
auditd rules and config checks "notapplicable" on RHEL 7.4 with DISA STIG content

### ISSUE THREAD

**Issue by sshimko** [OpenSCAP/scap-security-guide#2419]
#### Description of problem:
Running an eval on the DISA STIG results in the auditd rules and configuration file checks returning "notapplicable". This means the audit files are not modified as expected during remediation. This was shown when manually running the eval and when using the Anaconda component to apply the DISA STIG security profile.

This might be the result of the DISA alignment, I'm not really sure, but I know the content flagged failures and the remediation content addressed the identified issues in RHEL 7.2. If it is the intentional result of realignment, let me know if there is an alternative profile to use (if possible). If not, I'll figure something else out.

#### SCAP Security Guide Version:
0.1.33
RPM version:
scap-security-guide-0.1.33-5.el7.noarch.rpm

#### Operating System Version:
RHEL 7.4

#### Steps to Reproduce:
1. Using a stock RHEL 7.4 ISO, install, and select the DISA STIG security profile.
2. Continue with installation.
3. Upon boot, check the contents in /etc/audit (both the rules and config file).

#### Actual Results:
The rule file in particular is noticeably lacking the expected rules.

#### Expected Results:
The rule file has the correct configuration present indicating, e.g. the correct syscall watches are in-place.

#### Addition Information/Debugging Steps:
None. Ask for more in comments if needed.

**Comment by yuumasato** [comment]
Hello @sshimko,

Did you eval manually using the XCCDF file? If so, could you try again with the Data Stream file? 

SCAP Security Guide started to use CPE definitions that are not included in OpenSCAP's bundled dictionary, and this causes the scanner to not know how to eval them. Solution is to either use Data Stream file, or specify SSG CPE dictionary to use with `--cpe` option.

The problem with Anaconda is fixed upstream already, see https://bugzilla.redhat.com/show_bug.cgi?id=1465402.

**Comment by sshimko** [comment]
@yuumasato yes I was manually using the XCCDF files. Switching to the Data Streams created the correct results file and fixes. Thanks!
