### ISSUE TITLE
vlock should be preferred over screen for a locking mechanism

### ISSUE THREAD

**Issue by trevor-vaughan** [OpenSCAP/scap-security-guide#2454]
#### Description of problem:

`vlock` was specifically designed to solve the issue referenced in xccdf_org.ssgproject.content_rule_package_screen_installed and should be used over `screen` both for that reason and the `screen` vs `tmux` wars.

* 'screen' can use `vlock` by setting the `lockscreen` option.
* `tmux` can use `vlock` by setting `set-option -g lock-command vlock` in the configuration

In either case, using `vlock -a` will lock **all** virtual terminals for that user!

#### SCAP Security Guide Version:

0.1.36

#### Operating System Version:

EL 7

**Comment by redhatrises** [comment]
Adding Steve Grubb response:

```
Common Criteria requirements state that we need to have a self locking screen
after a certain number of minutes of inactivity. Screen can do it, vlock
can't.

-Steve
```

**Comment by trevor-vaughan** [comment]
@redhatrises Ah, that makes sense, but isn't `screen` a bit easy to work around? It's going to be a LONG time before it locks at the actual VT running `screen`. Or are we supposed to spawn a `screen` shell every time someone logs in?

Would using an Exit Trap with `TMOUT` to spawn `vlock` work? That should work in all cases (well, for `bash` anyway).

**Comment by trevor-vaughan** [comment]
Closing this based on [discussion on the SSG mailing list](https://lists.fedorahosted.org/archives/list/scap-security-guide@lists.fedorahosted.org/thread/NKLI3G6WERYRCTMIXSKWFO4N7IEGT2WR/).
