### ISSUE TITLE
xccdf_org.ssgproject.content_rule_ldap_client_start_tls should be checking the SSSD configuration

### ISSUE THREAD

**Issue by trevor-vaughan** [OpenSCAP/scap-security-guide#2459]
#### Description of problem:

`/etc/pam_ldap.conf` should no longer be used. SSSD should be evaluated instead.

#### SCAP Security Guide Version:

0.1.36

#### Operating System Version:

EL 7

**Comment by redhatrises** [comment]
This is a regression for which a fix is already posted. See PR #2458

**Comment by trevor-vaughan** [comment]
@redhatrises Ah, thanks!
