### ISSUE TITLE
Rules with criterion on cpe:/a:machine detected as not applicable

### ISSUE THREAD

**Issue by ptitoliv** [OpenSCAP/scap-security-guide#2462]
#### Description of problem:

Rules containing a requirement platform cpe:/a:machine  are considered as not applicable when executing the oscap eval command.

#### Steps to Reproduce:

1. Launch an oscap eval using XCCDF for CentOS 7 with DISA STIG profile
2. Check the rules considering disk partionning

#### Actual Results
The rules are considered as notapplicable.

#### Expected Results
The rules should have a pass or fail status.

#### Addition Information/Debugging Steps
If I remove the platform requirement from the XCCDF file, the rule is checked.

**Comment by redhatrises** [comment]
@ptitoliv did you apply this to a physical, virtual, or container?

**Comment by dahaic** [comment]
@ptitoliv please either consume datastream, or specify appropriate `--cpe cpe-dictionary.xml` This should do the trick.

**Comment by ptitoliv** [comment]
@redhatrises : It's on a virtual machine and I used testoval.py in order to verify that the check was okay.

**Comment by ptitoliv** [comment]
@dahaic : Oh yeah ! It did the trick ! I didn't think the cpe-dictionnary.xml was mandatory since the platform were declared in top of the XCCDF. I guess I still have oval stuff to learn. Sorry for the noise guys :(
