### ISSUE TITLE
Add requirement on ansible version needed for SSG remediations

### ISSUE THREAD

**Issue by ptitoliv** [OpenSCAP/scap-security-guide#2467]
Hello again,

I identified that some generated playbooks are not working because when we use an old ansible version. On my test machine which was a little bit outdated I had ansible 2.2 and it seems that for some playbooks we need at least ansible 2.3.

I think it could be nice to add in the documentation (Developer and User guides) the minimum ansible version needed. And maybe that could be interesting to have such a requirement directly into the specfile ?

Regards,

**Comment by dahaic** [comment]
The documentation is something I agree with. What do you suggest for specfile? Even weak dependency is too strong I would say (as we don't want ansible to be installed because of SSG).

**Comment by ptitoliv** [comment]
For SPECFILE, I was actually thinking about Requires for me since there is more and more remediations using ansible, I thought that scap-security-guide is now linked in a strong way to ansible. Today on a RHEL if you don't have ansible installed, lots of remediation won't be applied.

Anyway, if it is not wanted to create such a strong dependency, the important thing for a newcomer is to understand immediately that ansible has to be used for applying remediation. So, I think the two interesting places for saying that is of course the documentation and also in the generated guide and report introduction.

**Comment by redhatrises** [comment]
@ptitoliv all of this depends on how you are using `scap-security-guide`. `scap-security-guide` has no means of running any sort of remediation whether it be `bash`, `ansible`, `puppet`, etc. so the link to `ansible` is a weak dependency as this all depends on an operational environment.  `scap-security-guide` only provides the scripts for you to determine which ones you want to run and use. Also last time I checked, `oscap` does not run ansible and defaults to `bash`. 

Adding a `Requires` to the specfile doesn't make sense from an infrastructure architecture standpoint, because while you may use ansible, others may use `puppet`, `bash`, or some other language. Therefore, adding every script that `scap-security-guide` can support would have to be added as a `Requires` to the specfile which means all those languages would have to be installed when `scap-security-guide` is installed.

> Today on a RHEL if you don't have ansible installed, lots of remediation won't be applied.

This is not true with `oscap` defaulting to bash.

**Comment by ptitoliv** [comment]
@redhatrises. I understand your point about the fact you can't specify a strong dependency on the tool itself. However, the specific use case I had was considering the **version** of the tool. In my case, an ansible remediation failed because I had an older ansible version installed. (2.2 instead of 2.3 minimum). In that configuration, there was no fallback defaulting bash since ansible was installed but without the correct version. So remediation failed and then the check was still failed.

For the documentation part, a FAQ item with "Why my ansible remediation is not working ?" with "Use ansible >= 2.3 in order to make it work" is already a good thing.

Another idea : Could it be possible to integrate the ansible version requirement on the openscap engine with a user warning when an incorrect anisble version is detected ?

**Comment by redhatrises** [comment]
Closing this. @ptitoliv we have a ticket open to add this to openscap which generates the playbook. See https://github.com/OpenSCAP/openscap/issues/945

**Comment by dahaic** [comment]
@redhatrises afaik we do need this information to be shipped in DS metadata somehow. `oscap` is not able to determine version of `ansible` needed. It's definitely two faces of the same problem, so if you don't mind, I'll reopen this one again.

**Comment by redhatrises** [comment]
@dahaic how do you plan on putting it into the DS? Isn't that what the OpenSCAP ticket will do as the suggested header now references the ansible version?

**Comment by mpreisler** [comment]
It's not clear to me how the OpenSCAP ticket could be solved reliably if at all. It's a very hard problem. It's probably best to test playbooks using some version of Ansible in SSG upstream and then document that we guarantee it's going to work with that version or newer.

**Comment by dahaic** [comment]
@redhatrises we don't have (non-complex) way to define which version of ansible is required or not supported. So my idea is that contributors are responsible for adjusting this version somewhere within SSG source code.

**Comment by ptitoliv** [comment]
@dahaic @mpreisler : After all your explainations, I tried to write some documentation for explaining that. I think documentation is just what I wanted for that ticket. https://github.com/ptitoliv/scap-security-guide/blob/user_guide_update/docs/manual/user_guide.adoc#troubleshooting

It's just a simple basic text in order to show the idea. Not the final version.
