### ISSUE TITLE
Update RHEL 7 DISA STIG from V1R1 to V1R3

### ISSUE THREAD

**Issue by mrabe142** [OpenSCAP/scap-security-guide#2472]
The latest revision of the DISA STIG for RHEL 7 (https://iase.disa.mil/stigs/os/unix-linux/Pages/index.aspx) came out in October.  There has been ~63 rule updates, 1 rule deletion, and 2 new rules since V1R1.

**Comment by redhatrises** [comment]
Thanks @mrabe142 for letting us know about the latest release! I don't suppose that you would be willing to provide us with a summary of the changes in the latest release?

**Comment by xmtrcv** [comment]
I had previously copied the V1-to-V2 & V2-to-V3 changes from the PDF into a spreadsheet to use for auditing the V3 changes last week.  What format would you prefer the list in?

**Comment by xmtrcv** [comment]
@redhatrises I had previously copied the V1-to-V2 & V2-to-V3 changes from
the Revision History PDF into a spreadsheet to use for auditing the V3
changes last week.

What format would you prefer the list in?

**Comment by redhatrises** [comment]
@xmtrcv if you have a spreadsheet already, that would be helpful.

**Comment by xmtrcv** [comment]
@redhatrises spreadsheet* attached.  HTH
*wording regarding the changes can be ambiguous
[20171115-RHEL7-STIG-R1-V2_V3_revision_history.xlsx](https://github.com/OpenSCAP/scap-security-guide/files/1515036/20171115-RHEL7-STIG-R1-V2_V3_revision_history.xlsx)

**Comment by mrabe142** [comment]
Another related update, DISA released the first official RHEL 7 STIG SCAP 1.2 Benchmark last week:  https://iase.disa.mil/stigs/scap/Pages/index.aspx

The benchmark contains all of the OVAL content and related checking material.

**Comment by redhatrises** [comment]
Closing as the XCCDF should be updated to the latest release. Feel free to reopen if not.
