### ISSUE TITLE
xccdf_org.ssgproject.content_rule_file_ownership_library_dirs failes because of /usr/libexec/ file.

### ISSUE THREAD

**Issue by moriwaka** [OpenSCAP/scap-security-guide#2473]
#### Description of problem:

In "xccdf_org.ssgproject.content_rule_file_ownership_library_dirs",
library_files_uid_root failes because /usr/libexec/abrt-action-install-debuginfo-to-abrt-cache is not root:root. The rule should not check /usr/libexec/* files.

#### SCAP Security Guide Version:
scap-security-guide-0.1.36-1.fc27.noarch

#### Operating System Version:
Fedora 27

#### Steps to Reproduce:

1. Install abrt-addon-ccpp on Fedora
2. enable xccdf_org.ssgproject.content_rule_file_ownership_library_dirs
3. run oscap check

#### Actual Results:

library files uid root  failed because of: /usr/libexec/abrt-action-install-debuginfo-to-abrt-cache 

#### Expected Results:

check goes well without fail.

**Comment by dahaic** [comment]
Hello @moriwaka given this abrt file is a bit of anomaly in `/usr/libexec/` (All other files on my system are owned by `root`, varying group.) I would prefer to ask `abrt` to fix it, instead.

**Comment by moriwaka** [comment]
Hello @dahaic , I think this rule should not check under /usr/libexec.
Description of this rule lists target directories as following: 

> System-wide shared library files, which are linked to executables during process load time or run time, are stored in the following directories by default:
> 
> /lib
> /lib64
> /usr/lib
> /usr/lib64

And in scap-security-guide/shared/checks/oval/file_ownership_library_dirs.xml , it has a comment about target directories.
`  <unix:file_object comment="library files" id="object_file_ownership_lib_files" version="1">`
`    <!-- Check that files within /lib, /lib64, /usr/lib, and /usr/lib64 directories belong to user with uid 0 (root) -->`
`    <unix:path operation="pattern match">^\/lib(|64)|^\/usr\/lib(|64)</unix:path>`
`    <unix:filename operation="pattern match">^.*$</unix:filename>`
`   <filter action="include">state_owner_libraries_not_root</filter>`
`  </unix:file_object>`

**Comment by shawndwells** [comment]
How are /usr/libexec/* files being picked up in the first place?

From the OVAL:
https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/checks/oval/file_ownership_library_dirs.xml#L28#L40
`````

  <unix:file_object comment="library directories" id="object_file_ownership_lib_dir" version="1">
    <!-- Check that /lib, /lib64, /usr/lib, and /usr/lib64 directories belong to user with uid 0 (root) -->
    <unix:path operation="pattern match">^\/lib(|64)\/|^\/usr\/lib(|64)\/</unix:path>
    <unix:filename xsi:nil="true" />
    <filter action="include">state_owner_libraries_not_root</filter>
  </unix:file_object>

  <unix:file_object comment="library files" id="object_file_ownership_lib_files" version="1">
    <!-- Check that files within /lib, /lib64, /usr/lib, and /usr/lib64 directories belong to user with uid 0 (root) -->
    <unix:path operation="pattern match">^\/lib(|64)|^\/usr\/lib(|64)</unix:path>
    <unix:filename operation="pattern match">^.*$</unix:filename>
   <filter action="include">state_owner_libraries_not_root</filter>
`````

Has been a long day... but it looks like the regex shouldn't be going through /usr/libexec at all.
