### ISSUE TITLE
OSCAP Setting Deprecated option RhostsRSAAuthentication

### ISSUE THREAD

**Issue by MollyJoBault** [OpenSCAP/scap-security-guide#2478]
#### Description of problem:
I get a configuration file error when I run sshd after I've run OSCAP

>sshd -T
/etc/ssh/sshd_config line 169: Deprecated option RhostsRSAAuthentication

#### SCAP Security Guide Version:
0.1.35

#### Operating System Version:
CentOS 7

#### Steps to Reproduce:

1. sshd -T
2.
3.
4.

#### Actual Results:
/etc/ssh/sshd_config line 169: Deprecated option RhostsRSAAuthentication

#### Expected Results:
No error

**Comment by redhatrises** [comment]
Thanks @MollyJoBault! I had seen this earlier in the week and forgot to open a ticket on it.
