### ISSUE TITLE
aide remediations - aide_scan_notification needs update for regular grep syntax

### ISSUE THREAD

**Issue by nathanpeters008** [OpenSCAP/scap-security-guide#2495]
#### Description of problem:
The remediation script for aide_scan_notification uses the following regular expression to determine if the remediation needs to be applied: `'^.*\/usr\/sbin\/aide\s*\-\-check.*\|.*\/bin\/mail\s*-s\s*".*"\s*root@.*$'`

This results in the following command being run in the fix script: `grep -qR '^.*\/usr\/sbin\/aide\s*\-\-check.*\|.*\/bin\/mail\s*-s\s*".*"\s*root@.*$' /etc/crontab /etc/cron.d /etc/cron.daily /etc/cron.weekly /etc/cron.monthly`

However, since the grep command line does not include the -e flag, it uses regular grep syntax, which interprets the `\|` as the OR operator, instead of the literal pipe, causing the check to pass even if everything after the `|` in the regular expression is missing.

#### SCAP Security Guide Version:
0.1.36-1.el7.centos

#### Operating System Version:
CentOS 7.4.1708

#### Steps to Reproduce:

1. Run remediations against a system using a profile that includes both aide_periodic_cron_checking and aide_scan_notification (such as NIST 800-171)

#### Actual Results:
The remediation for aide_periodic_cron_checking is applied, but the remediation for aide_scan_notification is not

#### Expected Results:
Both remediations are applied

#### Addition Information/Debugging Steps:
The remediation for aide_periodic_cron_checking adds the following line to /etc/crontab:
`0 5 * * * /usr/sbin/aide  --check`

When the aide_scan_notification remediation is run, because the pipe is escaped, it is literally interpreted as match if you find either of these values `'0 5 * * * /usr/sbin/aide  --check' OR '/bin/mail -s "$(hostname) - AIDE Integrity Check" root@localhost'`

This causes the script to not bother applying the remediation because the first half of the OR expression already exists.

The easiest fix is to just remove the `\` character before any pipe in the regular expression since basic syntax already treats the pipe as a literal and there is no need to escape it.

**Comment by yuumasato** [comment]
Hello @nathanpeters008, thank you for the detailed report.

Would you like to implement and propose the fix?
This will also fix https://github.com/OpenSCAP/scap-security-guide/issues/2112

**Comment by nathanpeters008** [comment]
I have included this in https://github.com/OpenSCAP/scap-security-guide/pull/2500/
