### ISSUE TITLE
aide_periodic_cron_checking and aide_scan_notification are not compatible

### ISSUE THREAD

**Issue by nathanpeters008** [OpenSCAP/scap-security-guide#2496]
#### Description of problem:
A system that has the aide_scan_notification remediation applied should satisfy both the aide_scan_notification check and the aide_periodic_cron_checking check; however, this is not the case due to some slight differences in syntax between the checks.

Because of this error in syntax, the /etc/crontab file ends up with 2 aide cron jobs

#### SCAP Security Guide Version:
0.1.36-1.el7.centos

#### Operating System Version:
CentOS 7.4.1708

#### Steps to Reproduce:

1. Perform remediation on a system and include both the aide_periodic_cron_checking and aide_scan_notification remediations

#### Actual Results:
The following 2 lines are added to the /etc/crontab, causing the aide scan to be run twice every day
05 4 * * * root /usr/sbin/aide --check
0 5 * * * /usr/sbin/aide  --check | /bin/mail -s "$(hostname) - AIDE Integrity Check" root@localhost

#### Expected Results:
Only the following line is added, which should satisfy both checks:
0 5 * * * /usr/sbin/aide  --check | /bin/mail -s "$(hostname) - AIDE Integrity Check" root@localhost

#### Addition Information/Debugging Steps:
The check for aide_periodic_cron_checking expects the word 'root' in /etc/crontab between the time and the command, so the line added by aide_scan_notification will not satisfy it because it does not contain the word 'root' in that location.

The check for aide_scan_notification needs mail to be sent at the end of the check and so it will not be satisfied by the remediation for aide_periodic_cron_checking.

#### Suggested Fix
1. Adjust the remediation for aide_scan_notifcation to include the word root before the command in /etc/crontab which will cause both checks to pass
or
2. Remove the requirement for the word root to appear in the aide_periodic_cron_checking check, which will allow it to recognize the remediation applied by aide_scan_notification as valid

**Comment by yuumasato** [comment]
@nathanpeters008 thanks for detailed report.

I would go with first suggested fix, would you implement the fix?
Thank you.

**Comment by nathanpeters008** [comment]
Thanks @yuumasato 

Created https://github.com/OpenSCAP/scap-security-guide/pull/2500
