### ISSUE TITLE
SL7 STIG check fails on "Ensure Red Hat GPG Key Installed", key is imported

### ISSUE THREAD

**Issue by Timothy-Pulliam** [OpenSCAP/scap-security-guide#2498]
#### Description of problem:
Scientific Linux 7.4 STIG security scan fails on "Ensure Red Hat GPG Key Installed". The supplied remediation script does not fix the issue, nor does importing the key using

    # rpmkeys --import /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release

This is the same gpg key that Red Hat uses for [product signing](https://access.redhat.com/security/team/key)

```
# gpg --import /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release 
# gpg --fingerprint
/root/.gnupg/pubring.gpg
------------------------
pub   4096R/FD431D51 2009-10-22
      Key fingerprint = 567E 347A D004 4ADE 55BA  8A5F 199E 2F91 FD43 1D51
uid                  Red Hat, Inc. (release key 2) <security@redhat.com>

pub   1024D/2FA658E0 2006-12-01
      Key fingerprint = 43A6 E49C 4A38 F4BE 9ABF  2A53 4568 9C88 2FA6 58E0
uid                  Red Hat, Inc. (auxiliary key) <security@redhat.com>

```

#### SCAP Security Guide Version:

```
Name        : scap-security-guide
Arch        : noarch
Version     : 0.1.33
Release     : 6.sl7_4
```

#### Operating System Version:
Scientific Linux 7.4
```

# uname -r
3.10.0-693.11.1.el7.x86_64
```

#### Steps to Reproduce:
This is 100% reproducible

1. yum install scap-workbench
2. Run an SL7 scan, using "STIG for Scientific Linux 7" Profile (Workstation, Server, etc. does not matter)
3. "Ensure Red Hat GPG Key Installed" will always fail, even if remediation is checked, or the provided remediation shell script is given.
4.

#### Actual Results:
 "Ensure Red Hat GPG Key Installed" will always fail

#### Expected Results:
 "Ensure Red Hat GPG Key Installed" will remediate, then provide a passing mark.

**Comment by yuumasato** [comment]
@Timothy-Pulliam Thanks for the report.

Indeed, the OVAL check `ensure_redhat_gpgkey_installed` doesn't check for SL keys.
If keys are the same for SL, fix is to add check for installed SL along with check for RHEL installed.
