### ISSUE TITLE
Replacing -k privileged with -F key=privileged in audit_rules_* fix scripts broke pattern matching

### ISSUE THREAD

**Issue by nathanpeters008** [OpenSCAP/scap-security-guide#2506]
#### Description of problem:
In the fix scripts for xccdf_org.ssgproject.content_rule_audit_rules_* the FULL_RULE variable set at the top used to use -k privileged, but at some point was changed to -F key=privileged.

This broke pattern matching in several places in the scripts.

For example:
`key=$(expr "$full_rule" : '.*-k[[:space:]]\([^[:space:]]\+\)')` now returns an empty key with the following consequences:
1. Since the file name generated in /etc/audit/rules.d/ is based on the key, all fixes will end up in a file called .rules instead of for example privileged.rules.  
2. This breaks augenrules because it is looking for *.rules scripts, and will not match .rules, so any use of augenrules actually removes the newly added rules from /etc/audit/audit.rules
3. xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands is no longer idempotent because the following line won't work: `IFS=$'\n' files_to_inspect=($(find /etc/audit/rules.d -maxdepth 1 -type f -name *.rules -print))`
Instead it won't find any files because *.rules does not match .rules and will add multiple copies of a rule because the list returned is empty.

Another example:
The fix script for xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands is now broken in a few places:
```
base_search=$(sed -e "/-a always,exit/!d" -e "/-F path=${sbinary_esc}$/!d"   \
                                  -e "/-F path=[^[:space:]]\+/!d" -e "/-F perm=.*/!d"       \
                                  -e "/-F auid>=${min_auid}/!d" -e "/-F auid!=4294967295/!d"  \
                                  -e "/-k privileged/!d" $afile)
```
1. The above will not work because the sed expression does not include an expression to find -F key=privileged
2. Also the following line will not match anything because it is also hard coded to expect -k privileged: `expected_rule="-a always,exit -F path=${sbinary} -F perm=x -F auid>=${min_auid} -F auid!=4294967295 -k privileged"`

#### SCAP Security Guide Version:
0.1.36-1.el7.centos

#### Operating System Version:
CentOS Linux release 7.4.1708 (Core)

#### Steps to Reproduce:

1. Run any of the xccdf_org.ssgproject.content_rule_audit_rules_* fix scripts

#### Actual Results:
A file called .rules is created in /etc/audit/rules.d/

#### Expected Results:
A file called privileged.rules is created in /etc/audit/rules.d/

#### Addition Information/Debugging Steps:
This change does not seem to have been thoroughly throught through and there seems to be no need for it.  The -k syntax has not been deprecated nor or there any plans to do so that I am aware of.  In addition, the -k syntax is fully compatible with keeping the existing -F commands that don't include `key=`.
It introduced multiple undesired behaviors which could actually be considered to be 3 or more separate bugs, each with their own consequences and behaviors.

Note that this applies to all keys such as `-k delete`, `-k access`, `-k perm_mod`

### Suggested Fix:
Revert all audit_rules_ fix scripts to use `-k <key>` instead of `-F key=<key>` which avoids having to fix multiple pattern matching rules.

I am willing to submit a pull request for the above suggested fix.

**Comment by redhatrises** [comment]
Closing as there are already tickets open on this issue to fix the remediations portion of this. We are moving forward with using `-F key=<key>` for audit rule keys as there are performance reasons behind using `-F key=<key>` not to mention the fact that it now considered the default and best practice.

**Comment by nathanpeters008** [comment]
@redhatrises could you reference the tickets please?  I submitted a bug fix for this that updates the remediations to recognize the `-F key=` format but I couldn't find the associated bug reports (other than this one) to link them to.
