### ISSUE TITLE
spaces not showing up in rhel7 shorthand2xccdf.xslt

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#251]
ref:

![image](https://cloud.githubusercontent.com/assets/5713754/4415986/97556786-4536-11e4-9561-0485563dfd04.png)

**Comment by redhatrises** [comment]
@shawndwells with the new report format does this ticket still apply?

**Comment by shawndwells** [comment]
still an issue:

![image](https://cloud.githubusercontent.com/assets/5713754/7097195/688d845a-dfa1-11e4-8421-8997575587ee.png)

**Comment by shawndwells** [comment]
PR https://github.com/OpenSCAP/scap-security-guide/pull/522 resolved this
