### ISSUE TITLE
xccdf_org.ssgproject.content_rule_sebool* bash fix scripts are broken

### ISSUE THREAD

**Issue by nathanpeters008** [OpenSCAP/scap-security-guide#2513]
#### Description of problem:
The generated bash fix scripts for xccdf_org.ssgproject.content_rule_sebool* produce non functional bashcode.

The error received when running these is: `setsebool: illegal value var_abrt_upload_watch_anon_write for boolean abrt_upload_watch_anon_write`

#### SCAP Security Guide Version:
0.1.36-1.el7.centos

#### Operating System Version:
CentOS Linux release 7.4.1708 (Core)

#### Steps to Reproduce:

1. Run any of the remediation scripts for xccdf_org.ssgproject.content_rule_sebool*

#### Actual Results:
`setsebool: illegal value var_auditadm_exec_content for boolean auditadm_exec_content`

#### Expected Results:
SELinux boolean is successfully set

#### Addition Information/Debugging Steps:
The generated scripts contain the following logic:
```
var_abrt_anon_write="false"

setsebool -P abrt_anon_write var_abrt_anon_write
```

The variable in the setsebool command should be prefixed with a `$` in order to be considered a variable by bash, but since it isn't, the error occurs.

#### Suggested Fix:
I think the issue is with the following script : shared/templates/template_BASH_sebool_var
Specifically line 11: `setsebool -P %SEBOOLID% var_%SEBOOLID%`

Assuming that `$` does not have any special meaning to the template mechanism that generates the remediation scripts, the fix should be as simple as replacing the line above with: `setsebool -P %SEBOOLID% $var_%SEBOOLID%`

**Comment by mpreisler** [comment]
The suggested fix makes sense to me. This is most probably a regression when the XCCDF variable bindings were refactored.
