### ISSUE TITLE
fix for xccdf_org.ssgproject.content_rule_sysctl_kernel_ipv6_disable is missing with no explanation

### ISSUE THREAD

**Issue by nathanpeters008** [OpenSCAP/scap-security-guide#2515]
#### Description of problem:
Generating the bash fix for sysctl_kernel_ipv6_disable results in the following fix:
`# FIX FOR THIS RULE IS MISSING`

#### SCAP Security Guide Version:
0.1.36-1.el7.centos

#### Operating System Version:
CentOS Linux release 7.4.1708 (Core)

#### Steps to Reproduce:

1. Generate bash fixes for NIST 800-171

#### Actual Results:
```
###############################################################################
# BEGIN fix (204 / 359) for 'xccdf_org.ssgproject.content_rule_sysctl_kernel_ipv6_disable'
###############################################################################
(>&2 echo "Remediating rule 204/359: 'xccdf_org.ssgproject.content_rule_sysctl_kernel_ipv6_disable'")
# FIX FOR THIS RULE IS MISSING
# END fix for 'xccdf_org.ssgproject.content_rule_sysctl_kernel_ipv6_disable'
```

#### Expected Results:
```
function replace_or_append {
  local config_file=$1
  local key=$2
  local value=$3
  local cce=$4
  local format=$5

  # Check sanity of the input
  if [ $# -lt "3" ] 
  then
        echo "Usage: replace_or_append 'config_file_location' 'key_to_search' 'new_value'"
        echo  
        echo "If symlinks need to be taken into account, add yes/no to the last argument"
        echo "to allow to 'follow_symlinks'."
        echo "Aborting."
        exit 1
  fi  

  # Test if the config_file is a symbolic link. If so, use --follow-symlinks with sed.
  # Otherwise, regular sed command will do.
  if test -L $config_file; then
    sed_command="sed -i --follow-symlinks"
  else  
    sed_command="sed -i"
  fi    

  # Test that the cce arg is not empty or does not equal CCENUM.
  # If CCENUM exists, it means that there is no CCE assigned.
  if ! [ "x$cce" = x ] && [ "$cce" != 'CCENUM' ]; then
    cce="CCE-${cce}"
  else  
    cce="CCE"
  fi    

  # Strip any search characters in the key arg so that the key can be replaced without
  # adding any search characters to the config file.
  stripped_key=${key//[!a-zA-Z0-9_.]/}

  # If there is no print format specified in the last arg, use the default format.
  if ! [ "x$format" = x ] ; then
    printf -v formatted_output "$format" $stripped_key $value
  else  
    formatted_output="$stripped_key = $value"
  fi    

  # If the key exists, change it. Otherwise, add it to the config_file.
  if `grep -qi $key $config_file` ; then
    $sed_command "s/$key.*/$formatted_output/g" $config_file
  else  
    echo -ne "\n# Per $cce: Set $formatted_output in $config_file" >> $config_file
    echo -ne "\n$formatted_output" >> $config_file
  fi    

}

replace_or_append '/etc/sysctl.conf' 'net.ipv6.conf.all.disable_ipv6' '1' 'CCENUM'
```

#### Addition Information/Debugging Steps:
This fix existed in a previous version of the scap-security-guide.  Usually when a fix is not enabled, there is a comment in the html results listing why.  For example, some missing fixes reference an outstanding RHEL bug (like the fix for enabling repo metadata gpg check).

Since scanning a system will list this as a fail, there should be an explanation as to why there is no fix currently available.

**Comment by yuumasato** [comment]
Remediation for Rule `sysctl_kernel_ipv6_disable` is actually generated under file name `sysctl_net_ipv6_conf_all_disable_ipv6.sh` by `create_sysctl.py`, and as the names differ from Rule ID, it is not picked up build system.

Fix is to either, change Rule to be named `sysctl_net_ipv6_conf_all_disable_ipv6`, with drawback of breaking existing tailorings, or change this to be a static fix, named `sysctl_kernel_ipv6_disable.sh`.

I'd rather change Rule ID, but as that is disruptive, moving remediation to `static` may be better solution.
