### ISSUE TITLE
Output of generated bash role is misleading regarding missing fixes

### ISSUE THREAD

**Issue by yuumasato** [OpenSCAP/scap-security-guide#2520]
#### Description of problem:

Bash roles print message about remediating certain Rule even if there is no fix for the Rule.
See following snippet from a generated bash role.
```
###############################################################################
# BEGIN fix (1 / 5) for 'xccdf_org.ssgproject.content_rule_rpm_verify_permissions'
###############################################################################
(>&2 echo "Remediating rule 1/5: 'xccdf_org.ssgproject.content_rule_rpm_verify_permissions'")
# FIX FOR THIS RULE IS MISSING
# END fix for 'xccdf_org.ssgproject.content_rule_rpm_verify_permissions'
```
This happens with both Profile and result based roles.

#### SCAP Security Guide Version:
v0.1.37

#### Operating System Version:
Fedora 26

#### Steps to Reproduce:

1. `oscap xccdf generate fix --profile standard --output profile_fixes.sh ssg-fedora-xccdf.xml `
2. Check that 
3.
4.

#### Actual Results:
Output says Rules are being remediated, but nothing is actually done.

#### Expected Results:
1. A message that fix for a Rule doesn't exist is printed, or
2. There is no mention of remediating a Rule for which there is no fix.

**Comment by nathanpeters008** [comment]
I like option 1 because it is more informative.

If option 2 is chosen, it could lead to some confusion where a user thinks that the system just failed to generate the fix with no indication why.

**Comment by mpreisler** [comment]
This needs to be fixed in openscap, not ssg. Check out https://github.com/OpenSCAP/openscap/blob/maint-1.2/src/XCCDF_POLICY/xccdf_policy_remediate.c#L578 for the related code.

The solution should be pretty simple if we decide for 1), 2) would require some refactoring but is also doable.

**Comment by redhatrises** [comment]
@mpreisler should a ticket be opened in oscap then?

**Comment by mpreisler** [comment]
> @mpreisler should a ticket be opened in oscap then?

I think somebody can even create a PR straightaway without a ticket.
