### ISSUE TITLE
Perl script for generating bash script templates

### ISSUE THREAD

**Issue by timmgleason** [OpenSCAP/scap-security-guide#2525]
Perl script for parsing the XCCDF.xml file into bash scripts

Contains no fixes, I merely used this to generate the bash template files initially.

I realize that these are not output in standard SSG naming format, the system we use works better for us using the VulnID. It may be of use to someone, or not.

[XCCDF.xml_to_script.zip](https://github.com/OpenSCAP/scap-security-guide/files/1612379/XCCDF.xml_to_script.zip)

**Comment by redhatrises** [comment]
Thanks @timmgleason. Have you seen that we already generate all the bash scripts into a single script which they get installed with the SSG rpm?

**Comment by redhatrises** [comment]
Closing as the SSG build system generates the bash scripts into one bash script based off of the profile.
