### ISSUE TITLE
xccdf_org.ssgproject.content_rule_ldap_client_start_tls fails if LDAP client not enabled

### ISSUE THREAD

**Issue by nathanpeters008** [OpenSCAP/scap-security-guide#2527]
#### Description of problem:
On standalone system that have no reason or need to be connected to LDAP, LDAP is disabled.

This causes the check, xccdf_org.ssgproject.content_rule_ldap_client_start_tls, to fail.

#### SCAP Security Guide Version:
scap-security-guide-0.1.37-1.el7.centos.noarch

#### Operating System Version:
CentOS Linux release 7.4.1708 (Core)

#### Steps to Reproduce:

1. Scan a standalone system with the NIST 800-171 profile

#### Actual Results:
xccdf_org.ssgproject.content_rule_ldap_client_start_tls fails

#### Expected Results:
xccdf_org.ssgproject.content_rule_ldap_client_start_tls passes

#### Addition Information/Debugging Steps:
The help text in the html report follows:
```
To determine if LDAP is being used for authentication, use the following command:
$ sudo grep -i useldapauth /etc/sysconfig/authconfig
If USELDAPAUTH=yes, then LDAP is being used. To check if LDAP is configured to use TLS, use the following command:
$ sudo grep -i ssl /etc/pam_ldap.conf
```
Due to the presence of the line `If USELDAPAUTH=yes, then LDAP is being used` one would assume that if USELDAP=no, then the next part should not be required.

#### Suggested Fix:
The OVAL check should be changed to read something like this, which would only enforce the use of TLS for LDAP if LDAP was actually enabled.
```
<ns3:criteria operator="OR">
<ns3:extend_definition comment="LDAP is in use" definition_ref="oval:ssg-enable_ldap_client:def:1" negate="true"/>
<ns3:criteria operator="AND">
  <ns3:extend_definition comment="LDAP is in use" definition_ref="oval:ssg-enable_ldap_client:def:1" />
  <ns3:criterion comment="look for ssl start_tls in /etc/nslcd.conf" test_ref="oval:ssg-test_ldap_client_start_tls_ssl:tst:1" />
</ns3:criteria>

```

**Comment by redhatrises** [comment]
This is actually a requirement for STIG, so changing the OVAL to match what is suggested would not necessarily be the correct fix. What is the system using if it is not LDAP?

**Comment by nathanpeters008** [comment]
Are you saying that using LDAP is a requirement and therefore standalone machines using local accounts only (defined in /etc/passwd) are not allowed?  Not all networks use centralized authentication.  Some appliance type systems use only local accounts.

**Comment by nathanpeters008** [comment]
I've also seen some networks where people use only SSH keys.

**Comment by redhatrises** [comment]
If this is the case, then really what should happen is that the profile should be tailored to remove this rule or a waiver with an explanation of why it failed while still showing a failure.

**Comment by nathanpeters008** [comment]
I would actually really love it if when a failure occurred, a specific message stating what check (or checks) failed was printed.

I have spent quite a lot of time running local checks with `oscap xccdf eval --verbose INFO` and then grepping the file for `evaluated as` to see which of several checks failed and caused the overall rule evaluation to fail. An example of this would be the failure of the ssh firewall port rule.  Since my system had the ssh allowed on all zones it was really not clear why it was failing.  Only after digging through the verbose mode and then comparing it against the xccdf datastream in a text editor did I realize that the check was specifically expecting that the ifcfg-eth0 file wanted the ZONE=drop line added.

Running firewall-cmd --list-all-zones showed the eth0 bound to that zone when it was active, so it was not immediately obvious why that check was failing.

**Comment by redhatrises** [comment]
@nathanpeters008 have you added the `--oval-results` flag? It should show in the HTML report what failed and what the OVAL is getting.

**Comment by nathanpeters008** [comment]
@redhatrises I have been using oscap-ssh to scan remote systems which unfortunately does not have the oval-results option when using xccdf eval.

After comparing the functionality of oscap vs oscap-ssh for performing evaluations, I think I will probably rewrite the testing script to manually ssh/sudo and then run the xccdf evaluation locally and then scp the results back.

It makes the script a little more heavyweight as I have to manually perform many of the steps that oscap-ssh performs, but you are right that it will vastly simplify the troubleshooting process on failed checks.

Thanks for making me aware of that option!

**Comment by nathanpeters008** [comment]
@redhatrises I know this thread is getting of the topic of the subject, but I did find an issue with the --oval-results that makes it not very useful in troubleshooting.

1. it does not show exteneded definitions.  So anything failing because RHEL7 is not installed (run on a CentOS system) is not showing that not being on RHEL is the issue.
2. It does not show AND/OR logic, so it will list all failures, some of which look quite contradictory

For example, the xccdf datastream file for the rule 'Set Booot Loader Password' has the following logic:
```
<ns3:criteria operator="OR">
  <ns3:criterion comment="Pass if /boot/grub2/grub.cfg does not exist" test_ref="oval:ssg-test_bootloader_grub_cfg:tst:1" />
   <ns3:criteria operator="AND">
    <ns3:criterion comment="make sure a password is defined in /boot/grub2/grub.cfg" test_ref="oval:ssg-test_bootloader_password:tst:1" />
    <ns3:criterion comment="make sure a superuser is defined in /boot/grub2/grub.cfg" test_ref="oval:ssg-test_bootloader_superuser:tst:1" />
    </ns3:criteria>
    </ns3:criteria>
```

In that case, if /boot/grub2/grub.cfg does not exist the test automatically passes.

However, if one was to just read the html file, it claims that 3 rules failed:
1. /boot/grub2/grub.cfg does not exist
2. make sure a password is defined in /boot/grub2/grub.cfg
3. superuser is defined in /boot/grub2/grub.cfg files. Superuser is not root, admin, or administrator

As you can see, rule 1 and rule 2 contradict each other by simultaneously requiring that the file does exist and does not exist.  Since this is not a quantum system and this is not schrodingers grub, this doesn't make sense until you actually look at the xccdf datastream manually in a text editor and realize the presence of the AND/OR logic.

Further, if there are AND/OR logic plus extended definitions (like the RHEL7 rule), you will literally have to revert to the method I mentioned earlier with running the verbose INFO flag and grepping the resulting text file.

What would be the best thing to do here?  File an RFE under issues in the openscap project? to enhance the HTML output to include AND/OR logic and extended definitions?

**Comment by redhatrises** [comment]
> What would be the best thing to do here? File an RFE under issues in the openscap project to enhance the HTML output to include AND/OR logic and extended definitions?

Yes. Please create an RFE there.

**Comment by nathanpeters008** [comment]
I think it's safe to close this issue since the STIG apparently requires the use of LDAP (and not only local accounts with password/ssh keys) for this check to pass.
