### ISSUE TITLE
account_disable_post_pw_expiration text does not match rule in cjis-rhel7-server profile

### ISSUE THREAD

**Issue by nathanpeters008** [OpenSCAP/scap-security-guide#2547]
#### Description of problem:
The description for xccdf_org.ssgproject.content_rule_account_disable_post_pw_expiration in the cjis-rhel7-server profile reads: `A value of 35 is recommended.`

However, the test will fail unless a value of 0 is used.

#### SCAP Security Guide Version:
scap-security-guide-0.1.37-1.el7.centos.noarch

#### Operating System Version:
CentOS Linux release 7.4.1708 (Core)

#### Steps to Reproduce:

1.  Ensure the following line is set in /etc/default/useradd:
`INACTIVE=35`
2. Evaluate the system against the following profile: xccdf_org.ssgproject.content_profile_cjis-rhel7-server

#### Actual Results:

xccdf_org.ssgproject.content_rule_account_disable_post_pw_expiration fails

#### Expected Results:
xccdf_org.ssgproject.content_rule_account_disable_post_pw_expiration  passes

#### Addition Information/Debugging Steps:
Although the text recommends 35 days, the example code given states 0 days also.  It is likely that 0 days is correct since the example code and remediation both use this value.  The help text is probably wrong.

**Comment by redhatrises** [comment]
@nathanpeters008 the profile setting for this is `0` which should also show up before the `A value of 35 is recommended` statement. You need to tailor the profile to change to the recommended value.

**Comment by nathanpeters008** [comment]
Oh I see.  Because this is one of those values were a var is used to allow the same rule to specify different values depending on the profile (similar to the account lockout deny rules), the text is generic across profiles?

**Comment by redhatrises** [comment]
@nathanpeters008 that is correct. However, I have submitted a PR that has been merged that hopefully will reduce confusion in the future.
