### ISSUE TITLE
rhel 7.5 beta: update DISA STIG version

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#2568]
RHEL installer says STIG profile is based off V1R1... wasn't this updated to V3?

![image](https://user-images.githubusercontent.com/5713754/35364029-09ed793c-013b-11e8-9bcb-245db1b102a7.png)

**Comment by jmackani** [comment]
V1r3 is the current version.

**Comment by ajd394** [comment]
Version V1r4 has been released.

**Comment by shawndwells** [comment]
@ajd394 just fyi, while DISA latest is V1R4 this content was last verified against V1R3. Updated the profile to reflect V1R3.

Next sprint (0.1.40) targets rebase against V1R4.
