### ISSUE TITLE
Gnome3 banner : Incorrect ansible remediation and OVAL check

### ISSUE THREAD

**Issue by ptitoliv** [OpenSCAP/scap-security-guide#2589]
When trying to add the DoD banner as login banner text on GDM, I identified the following issues : 
 - ansible remediation is not working because the login banner text is the regexp stored in the XCCDF file and GDM doesn't handle such a format. So when, the remediation is applied, the result is an ugly display like that : ![gnome_banner_ansible_remediation](https://user-images.githubusercontent.com/567505/35482115-bd1307aa-0430-11e8-9105-a64071866a95.png)
 - I wrote a bash remediation (https://gist.github.com/ptitoliv/bc7f2aff8c550edb37268cc8ecc9b6f5) taking the banner stored into the XCCDF doing a small transformation on the regexp in order to have a correct display. The display seems fine with that transformation : 
![gnome_banner_bash_remediation](https://user-images.githubusercontent.com/567505/35482133-036ec162-0431-11e8-8ca9-c723fe056a88.png). However, the thing is that the OVAL check is not working any more because of the mandatory \n we have to put in the GDM banner message text in order to have a better display. 

For the last point I have two questions : 
 - Should we have to create a specific variable with the correct regexp format in order to handle this specific use case.
 - I tried to make some tests but they were unsuccessful. The thing is that for testing the regexp, I didn't find any other solution than rebuild the XCCDF and do a check which is very long. Is there some tricks in order to validate these regexp without such a long process ?

Context : SSG master branch on CentOS 7.

**Comment by ptitoliv** [comment]
Just started some WIP on that issue on branch https://github.com/ptitoliv/scap-security-guide/tree/gnome_banner. It seems I have now a correct bash and remediation for that issue. I checked only for the dod_banners right now. What do you think ?

**Comment by redhatrises** [comment]
Duplicating the banner text is not the right way to go as it not only creates confusion but it increases maintenance costs as well as duplicates content which is not what we want to do.

**Comment by ptitoliv** [comment]
@redhatrises : Just updated the branch with a common banner usable for both checks and remediations. I had to update /etc/issue remediation in order to handle that new regexp.

**Comment by ptitoliv** [comment]
Hello team,
Any news about that review ? Would you prefer me to open a PR in WIP mode ?

**Comment by matejak** [comment]
Hello Olivier, opening a pull request is a great idea, check out [how to proceed](https://github.com/OpenSCAP/scap-security-guide/blob/master/docs/manual/developer_guide.adoc#patch-creation).

**Comment by matejak** [comment]
@redhatrises we have been evaluating @ptitoliv's contribution and we came to conclusion that although his approach works, it is really complicated. At the same time, we agree with you that repeating oneself is not a good way to go.
Therefore, we put our heads together and came with this idea:
- Change the input: Now, it is a regexp that is translated to a string. We propose to change the input to string and construct the regexp out of it.
- OVAL check needs the regexp. If you have a plaintext input, you can translate it to regexp easily by translating actual whitespaces and newlines in it to `[\s\n]+`.
- `/etc/issue` remediation requires the plaintext wrapped to the width of 80 characters plus an actual newline at the very bottom.
- GDM `dconf` remediation requires plaintext, where actual newlines are translated to `\n`.

As far as I understand, Ansible remediations of login banners will require the exact strings to be inserted into files, so it looks like that at least the `dconf` and `/etc/issue` formats of the banner message will have to be constructed at build time anyway - Ansible can insert something into a file, but it can't transform the inserted content within the same step.
Therefore, taking it one step further and generating OVAL regexp at build time seems to be a low cost of getting Ansible remediations done, simplifying Bash remediations and making the input more readable for contributors.

So what do you think of this? Do you think that it is possible to extend the build system in this way?

**Comment by redhatrises** [comment]
PR fixing this has been merged. Please reopen if this is not the case.
