### ISSUE TITLE
Syntax error in generated Ansible playbooks

### ISSUE THREAD

**Issue by GaryGapinski** [OpenSCAP/scap-security-guide#2593]
#### Description of problem:
Ansible playbook is generated with syntax error.

#### SCAP Security Guide Version:
Master branch as of e9696f954e80e79cda2c93879cf43eca1af8af45.

#### Operating System Version:
Ubuntu 17.10
OpenSCAP command line tool (oscap) 1.2.17

#### Steps to Reproduce:

1. `git clone scap-security-guide`
2. `cd scap-security-guide/build;cmake ../;make`
3. `ansible-playbook --syntax-check roles/ssg-rhel7-role-ospp-rhel7.yml`

#### Actual Results:
Receive 
``` $ ansible-playbook --syntax-check roles/ssg-rhel7-role-ospp-rhel7.yml
 [WARNING]: provided hosts list is empty, only localhost is available

ERROR! Syntax Error while loading YAML.


The error appears to have been in '/tmp/github/scap-security-guide/build/roles/ssg-rhel7-role-ospp-rhel7.yml': line 3219, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      t
    - name: XCCDF Value var_accounts_passwords_pam_faillock_fail_interval # promote to variable
    ^ here
```
The vicinity of the reported line (via `nl roles/ssg-rhel7-role-ospp-rhel7.yml`):
```
  3212      
  3213      - name: XCCDF Value var_accounts_passwords_pam_faillock_unlock_time # promote to variable
  3214        set_fact:
  3215          var_accounts_passwords_pam_faillock_unlock_time: never
  3216        t
  3217      - name: XCCDF Value var_accounts_passwords_pam_faillock_fail_interval # promote to variable
  3218        set_fact:
  3219          var_accounts_passwords_pam_faillock_fail_interval: 900
  3220        tags:
  3221          - always
  3222      
```

#### Expected Results:
No syntax error.

**Comment by matejak** [comment]
Thank you for reporting the issue!
As far as we have investigated, it looks like that the scap-security-guide content is OK, but the openscap scanner is generating invalid output for this case. We are working on a fix.
On a related note, we would like to implement checks that would validate generated Ansible roles.
