### ISSUE TITLE
Rule xccdf_org.ssgproject.content_rule_aide_scan_notification fails when email ID other than root@. is given

### ISSUE THREAD

**Issue by amitkumar50** [OpenSCAP/scap-security-guide#2594]
#### Description of problem:
        
`# yum install aide -y`
`# vim /etc/crontab        //As directed in 'scan-xccdf-report.html'`
`    05 4 * * * root /usr/sbin/aide --check | /bin/mail -s "$(hostname) -
AIDE Integrity Check" rt.yu@abc.def.ghi.jkl`
`# oscap    xccdf eval    --profile`
xccdf_org.ssgproject.content_profile_stig-rhel7-disa     ssg-rhel7-ds.xml
        Title Configure Notification of Post-AIDE Scan Details
        Rule xccdf_org.ssgproject.content_rule_aide_scan_notification
        Ident CCE-80374-2
        Result fail

/////////Fix For Same/////////////
`# vim /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml`
Replace:        [root@.]
if ! grep -qR '^.*\/usr\/sbin\/aide\s*\-\-check.*\|.*\/bin\/mail\s*-s\s*".*"\s*root@.*$' $CRONTAB $VARSPOOL $CRONDIRS; then
With               [*@.]
if ! grep -qR '^.*\/usr\/sbin\/aide\s*\-\-check.*\|.*\/bin\/mail\s*-s\s*".*"\s**@.*$' $CRONTAB $VARSPOOL $CRONDIRS; then

#### SCAP Security Guide Version:
recent

#### Operating System Version:
RHEL-7.4

#### Steps to Reproduce:
1.  Provided in description
2.
3.
4.

#### Actual Results:
Aide can only send mail to root account.

#### Expected Results:
Aide should be able to send email to any user-mail.

#### Addition Information/Debugging Steps:
1. Why Email ID of root is expected? Why cannot a normal user Email ID is used? Since a normal user can also run openscap test.
2. Why Email ID format root@something fixed?

**Comment by matejak** [comment]
Fixed by  #2599

**Comment by jan-cerny** [comment]
@matejak  Thank you very much
