### ISSUE TITLE
ssg-accounts_have_homedir_login_defs_question reports fail even CREATE_HOME yes in login.defs

### ISSUE THREAD

**Issue by amitkumar50** [OpenSCAP/scap-security-guide#2595]
#### Description of problem:
`# vim /etc/login.defs`
CREATE_HOME yes
`# oscap    xccdf eval    --profile xccdf_org.ssgproject.content_profile_stig-rhel7-disa  --report report.html --results scan-xccdf-results.xml   /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml`
  Ident   CCE-80434-4
  fail

/////////Fix for same///////////////
`# vim /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml`
Change From
<ind:pattern operation="pattern match">^[\s]*(?i)CREATE_HOME(?-i)[\s]+no[\s]*(?:|(?:#.*))?$</ind:pattern>
to
<ind:pattern operation="pattern match">^[\s]*(?i)CREATE_HOME(?-i)[\s]+yes[\s]*(?:|(?:#.*))?$</ind:pattern>

#### Operating System Version:
RHEL7.4

#### Steps to Reproduce:
1. Mentioned in description
2.
3.
4.

#### Actual Results:
`ocil:ssg-accounts_have_homedir_login_defs_question:question:1` should fails even when CREATE_HOME is set inside /etc/login.defs

#### Expected Results:
`ocil:ssg-accounts_have_homedir_login_defs_question:question:1` should not fail when CREATE_HOME is set inside /etc/login.defs

**Comment by matejak** [comment]
Hello, could you please tell us the SSG version that you can reproduce this on? When I look at `checks/oval/accounts_have_homedir_login_defs.xml` in the master branch, I see that it is fixed.

**Comment by yuumasato** [comment]
I believe this is duplicate of https://github.com/OpenSCAP/scap-security-guide/issues/1983, fixed by #1984
