### ISSUE TITLE
Unanchored regular expression patterns in SCAP

### ISSUE THREAD

**Issue by solind** [OpenSCAP/scap-security-guide#2604]
#### Description of problem:

There are unanchored regular expression patterns in the SCAP content.  Specifically in the following objects:
- oval:ssg-obj_unauthenticated_apt_conf:obj:1
- oval:ssg-obj_unauthenticated_apt_conf_d:obj:1

And in the following variables:
- oval:ssg-var_rfp_all_log_files_as_string:var:1
- oval:ssg-var_rfg_all_log_files_as_string:var:1
- oval:ssg-var_rfo_all_log_files_as_string:var:1

#### SCAP Security Guide Version:

0.1.37

#### Operating System Version:

Ubuntu 14.04 (and probably also 16.04)

**Comment by matejak** [comment]
Could you please elaborate what do you mean by unanchored? The `oval:ssg-obj_unauthenticated_apt_conf:obj` regexp (that can be found e.g. in the Ubuntu oval or datastream) is `^[\s]*APT::Get::AllowUnauthenticated(=|[\s]+)(yes|true|True);.*$`, which looks anchored to me.

**Comment by solind** [comment]
Hi, look at the pattern in the filepath entity -- this is what an SCAP scanner must interpret to find the file location, and if it's not anchored, technically the entire filesystem would have to be searched (which is very expensive and time-consuming).

**Comment by matejak** [comment]
Thank you for your feedback!
I see, it makes sense to add the beginning anchor e.g. to the `<ind:filepath operation="pattern match">/etc/apt/apt/apt.conf</ind:filepath>`, so it becomes  `<ind:filepath operation="pattern match">^/etc/apt/apt/apt.conf</ind:filepath>`, or even better `<ind:filepath operation="equals">/etc/apt/apt/apt.conf</ind:filepath>` as this one doesn't use the regex syntax.
This is altogether a little bit bizzare, as [the OVAL docs](https://oval.mitre.org/language/version5.11/ovaldefinition/documentation/independent-definitions-schema.html#textfilecontent54_object) suggest that `filepath` is the *absolute* path to a filename.
However, what about the situation with variables? The `<literal_component datatype="string">%/etc/rsyslog.conf</literal_component>` entry doesn't indicate that it is treated like a regexp (`%` seems to be just a delimiter). Do you have any indication that it actually is a regexp?

**Comment by mpreisler** [comment]
Shouldn't it rather avoid using pattern match at all? shouldn't operation be "equal"?

**Comment by solind** [comment]
Indeed, I'd use operation="equals" where possible.  I found that var_rfp_all_log_files_as_string, ssg-var_rfg_all_log_files_as_string and var_rfo_all_log_files_as_string are all used as patterns.  The '%' is used as a token delimiter.

However, in the project I attempted to modify the source files and after running make the unanchored variable expressions ended up in the datastream anyway.  Perhaps you will have better luck than I did.

**Comment by solind** [comment]
As for the OVAL docs reference -- indeed, the filepath is the absolute path to a filename.  If operation="pattern match", then the absolute path must match the specified pattern.  Therefore, if the pattern is not anchored, all possible absolute paths must be found and compared to the pattern!

**Comment by matejak** [comment]
What about refactoring the code and including the variable type (literal string/regexp) in the variable name? Hungarian notation is discouraged in modern programming languages as IDEs and compilers keep track of types for us. However, in this case, the definition is too far away from actual use of the variable, so this approach would save us some pain.

**Comment by solind** [comment]
That sounds like a fine idea to me, with the variables. Ideally there should be a check that can be automated to prevent insertion of unanchored patterns that are used as filepath values.

Incidentally, you can catch a lot of unanchored filepath patterns in this content (not encoded inside of variables) if you run the following command:
```find shared/checks/oval -type f|xargs grep 'pattern match">/'```

**Comment by matejak** [comment]
@solind I agree with you, if you take a look at #2605 , you will notice that it does exactly what you recommend.
However, I am unable to see how the variable `var_rfp_all_log_files_as_string` is used as a pattern. Could you please point me to a location where this happens? As the variable name already correctly suggests that it is a filename, would it be possible to add anchors to the place where it is used in a regular expression?

**Comment by solind** [comment]
Hi @matejak, ```var_rfp_all_log_files_as_string``` is used inside ```var_rfp_all_log_files_as_collection```, which is used as the filepath for ```object_rfp_log_files_paths```.

**Comment by matejak** [comment]
Great, your remarks have been addressed in #2605

**Comment by matejak** [comment]
The PR #2605 has been merged, so I am closing this issue.

**Comment by solind** [comment]
Thanks for fixing this!
