### ISSUE TITLE
RHEL7: audit_rules_login_events_faillock

### ISSUE THREAD

**Issue by dirtyharrycallahan** [OpenSCAP/scap-security-guide#2607]
#### Description of problem:
Test doesn't match the text.

#### SCAP Security Guide Version:
tip

#### Operating System Version:
RHEL

#### Steps to Reproduce:

1. add audit rule indicated in narrative -> -w /var/run/faillock/ -p wa -k logins
2. run eval and control is marked failed b/c the narrative includes a trailing "/" 
^\-w\s+\/var\/run\/faillock\s+\-p\s+wa\s+(-k[\s]+|-F[\s]+key=)[-\w]+\s*$

#### Actual Results:
audit_rules_login_events_faillock : fail

#### Expected Results:
audit_rules_login_events_faillock : pass

**Comment by dominiquearpin** [comment]
I got the same problem with RHEL 7.5Beta.  Anyone with a patch?

**Comment by shawndwells** [comment]
There is no audit_rules_login_events_faillock in shared/ or rhel7/checks/oval.

hallllpppp I'm going mental.

**Comment by redhatrises** [comment]
@shawndwells did you check `shared/templates/csv/audit_rules_login_events.csv`?

**Comment by shawndwells** [comment]
On 2/22/18 11:11 AM, redhatrises wrote:
> @shawndwells <https://github.com/shawndwells> did you check
> |shared/templates/csv/audit_rules_login_events.csv|?

Nope. But isn't that for audit_rules_login_events, not
audit_rules_login_events_faillock?

**Comment by redhatrises** [comment]
@shawndwells it is for all audit_rules_login_events including faillock.

**Comment by dirtyharrycallahan** [comment]
I work only with Red Hat 7 server and the DISA Red Hat 7 STIG profile and while running my scans I noticed that there is a general inconsistency between the checks, the text, and the remedies (both bash and Ansible). Other examples are the Gnome settings in the dconf ini file. Some tests will accept spaces around the key=value and some will not. I will have to get my head around how all this content comes together and review the current STIG before I can submit some pull requests.
