### ISSUE TITLE
ldap_client_start_tls fails even when ldap is not enabled

### ISSUE THREAD

**Issue by OnceUponALoop** [OpenSCAP/scap-security-guide#2620]
#### Description of problem:
Rule `xccdf_org.ssgproject.content_rule_ldap_client_start_tls` reports failure even when ldap is not being used.

#### SCAP Security Guide Version:
Git master (bb897175d0695dd6b6ec434e727f66fb6eb13eea)

#### Operating System Version:
RHEL7.4

#### Steps to Reproduce:

1. Ensure `USELDAPAUTH=no` in `/etc/sysconfig/authconfig`
2. Ensure that `ssl start_tls` is commented out in `/etc/nslcd.conf`

#### Actual Results:
Failed check. It's checking nslcd even though ldap is not enabled.

```
[root@rh-test build]# oscap oval eval --verbose INFO --id oval:ssg-ldap_client_start_tls:def:1 ssg-rhel7-oval.xml
I: oscap: Identified document type: oval_definitions
I: oscap: Created a new OVAL session from input file 'ssg-rhel7-oval.xml'.
I: oscap: No external OVAL variables provided.
I: oscap: Started new OVAL agent.
I: oscap: Querying system information.
I: oscap: Starting probe on URI 'pipe:///usr/libexec/openscap/probe_system_info'.
I: probe_system_info: Extracting item from the cache queue: cnt=1, beg=0
I: probe_system_info: cache MISS
I: probe_system_info: Extracting item from the cache queue: cnt=1, beg=1
I: oscap: Evaluating definition 'oval:ssg-ldap_client_start_tls:def:1': Configure LDAP to Use TLS for All Transactions.
I: oscap:   Criteria are extended by definition 'oval:ssg-enable_ldap_client:def:1'.
I: oscap:   Evaluating definition 'oval:ssg-enable_ldap_client:def:1': Enable the LDAP Client For Use in Authconfig.
I: oscap:     Evaluating textfilecontent54 test 'oval:ssg-test_enable_ldap_client:tst:1': LDAP client is enabled.
I: oscap:       Querying textfilecontent54 object 'oval:ssg-obj_enable_ldap_client:obj:1', flags: 0.
I: oscap:       Creating new syschar for textfilecontent54_object 'oval:ssg-obj_enable_ldap_client:obj:1'.
I: oscap:       Starting probe on URI 'pipe:///usr/libexec/openscap/probe_textfilecontent54'.
I: probe_textfilecontent54: Opening file '/etc/sysconfig/authconfig'.
I: probe_textfilecontent54: Extracting item from the cache queue: cnt=1, beg=0
I: oscap:       Test 'oval:ssg-test_enable_ldap_client:tst:1' requires that every object defined by 'oval:ssg-obj_enable_ldap_client:obj:1' exists on the system.
I: oscap:       0 objects defined by 'oval:ssg-obj_enable_ldap_client:obj:1' exist on the system.
I: oscap:       Test 'oval:ssg-test_enable_ldap_client:tst:1' does not contain any state to compare object with.
I: oscap:       No item matching object 'oval:ssg-obj_enable_ldap_client:obj:1' was found on the system. (flag=does not exist)
I: oscap:     Test 'oval:ssg-test_enable_ldap_client:tst:1' evaluated as false.
I: oscap:   Definition 'oval:ssg-enable_ldap_client:def:1' evaluated as false.
I: oscap:   Evaluating textfilecontent54 test 'oval:ssg-test_ldap_client_start_tls_ssl:tst:1': Tests the value of the ssl start_tls setting in the /etc/nslcd.conf file.
I: oscap:     Querying textfilecontent54 object 'oval:ssg-obj_ldap_client_start_tls_ssl:obj:1', flags: 0.
I: oscap:     Creating new syschar for textfilecontent54_object 'oval:ssg-obj_ldap_client_start_tls_ssl:obj:1'.
I: probe_textfilecontent54: Opening file '/etc/nslcd.conf'.
I: probe_textfilecontent54: Extracting item from the cache queue: cnt=1, beg=1
I: oscap:     Test 'oval:ssg-test_ldap_client_start_tls_ssl:tst:1' requires that at least one object defined by 'oval:ssg-obj_ldap_client_start_tls_ssl:obj:1' exists on the system.
I: oscap:     0 objects defined by 'oval:ssg-obj_ldap_client_start_tls_ssl:obj:1' exist on the system.
I: oscap:     Test 'oval:ssg-test_ldap_client_start_tls_ssl:tst:1' does not contain any state to compare object with.
I: oscap:     No item matching object 'oval:ssg-obj_ldap_client_start_tls_ssl:obj:1' was found on the system. (flag=does not exist)
I: oscap:   Test 'oval:ssg-test_ldap_client_start_tls_ssl:tst:1' evaluated as false.
I: oscap: Definition 'oval:ssg-ldap_client_start_tls:def:1' evaluated as false.
Definition oval:ssg-ldap_client_start_tls:def:1: false
Evaluation done.
```

#### Expected Results:
Should pass per the documentation the check should only fail if ldap is being used for authentication and start_tls is not enabled.

#### Addition Information/Debugging Steps:
The logic in the check seems to be incorrect, it only passes if both `useldapauth=yes` and `ssl start_tls` are defined - it should also pass if `useldapauth=no` regardless of the state of `ssl start_tls`

Should be changed from A∧B to ~A∨B to achieve the correct behavior

| useldapauth | start_tls | result | 
| -- | -- | -- | 
| F | F | T
| F | T | T
| T | F | **F**
| T | T | T

**Comment by redhatrises** [comment]
This should be tailored in the profile. Considered a finding of LDAP/TLS is not enabled.

**Comment by OnceUponALoop** [comment]
@redhatrises why would this be a tailoring option? 

If LDAP is not being used for auth why would we need to have the `ssl start_tls` option enabled in nslcd if it's never going to be used?

**Comment by OnceUponALoop** [comment]
Just saw your message on the PR - you're saying that this should be considered a finding if LDAP is not being used? Is there a requirement to use ldap that i missed somewhere, maybe there's something i'm missing.

**Comment by redhatrises** [comment]
Closing as this is a tailoring profile issue.

**Comment by OnceUponALoop** [comment]
This still bugs me. I went back and looked at the references for this rule to try and understand where the requirement for enabling LDAP comes from.

The references all indicate that encryption should be utilized to protect confidentiality and so on. Enabling TLS does that for LDAP connections, so that's valid.

The question that's still not answered:
**If LDAP authentication isn't being utilized why change the configuration at all?**

The configuration change we're making in `nslcd.conf` is only used when LDAP is enabled. If it's not being used then why alter the configuration?

## Check References ##
The check references (AC-17(2), CM-7, CCI-001453, SRG-OS-000250-GPOS-00093)

**AC-17(2)**
> REMOTE ACCESS | PROTECTION OF CONFIDENTIALITY / INTEGRITY USING ENCRYPTION
> The information system implements cryptographic mechanisms to protect the confidentiality and
> integrity of remote access sessions.
> Supplemental Guidance: The encryption strength of mechanism is selected based on the security
> categorization of the information. Related controls: SC-8, SC-12, SC-13.

**CM(7)**
> LEAST FUNCTIONALITY
> Control: The organization:
> a. Configures the information system to provide only essential capabilities; and
> b. Prohibits or restricts the use of the following functions, ports, protocols, and/or services:
> [Assignment: organization-defined prohibited or restricted functions, ports, protocols, and/or
> services].

**CCI-001453**
> The information system implements cryptographic mechanisms to protect the integrity of remote access sessions.
> References:
> NIST SP 800-53             AC-17 (2)
> NIST SP 800-53A            AC-17 (2).1
> NIST SP 800-53 Revision 4  AC-17 (2)

**SRG-OS-000250-GPOS-00093**
> The operating system must implement cryptography to protect the integrity of remote access sessions.
