### ISSUE TITLE
service_firewalld_enabled and set_firewalld_default_zone fail when firewalld is not installed.

### ISSUE THREAD

**Issue by OnceUponALoop** [OpenSCAP/scap-security-guide#2622]
#### Description of problem:
Firewalld checks fail on systems that don't have firewalld installed (legacy iptables requirements)

#### SCAP Security Guide Version:
Git master (bb897175d0695dd6b6ec434e727f66fb6eb13eea)

#### Operating System Version:
RHEL7.4

#### Steps to Reproduce:

1. Ensure firewalld is not installed
2. Evaluate `service_firewalld_enabled`
3. Evaluate `set_firewalld_default_zone`

#### Actual Results:
Both test cases fail.

#### Expected Results:
They should pass (ideally they should be tagged as not-applicable) but it seems that's restricted to platforms.

#### Addition Information/Debugging Steps:
There's already an oval check `package_firewalld_installed` we'll just need to update the failing checks to add that as a criteria unless someone wants to create iptable rules as well.

**Comment by OnceUponALoop** [comment]
Having trouble locating the oval check for `service_firewalld_enabled` - I can only find the built one, am i missing something?

**Comment by yuumasato** [comment]
Hello, 
check for `service_firewalld_enabled` is generated by templates, see [template_OVAL_service_enabled](https://github.com/OpenSCAP/scap-security-guide/blob/master/rhel7/templates/oval_5.11_templates/template_OVAL_service_enabled).

It is technically possible to implement proposed idea by adding `package_firewalld_installed` into the failing checks as `applicability_checks`, but, to me, this would change semantics of the Rules.

If you really won't have `firewalld` installed in your systems, then you should probably customize the Profile and unselect `firewalld` related rules. And add yours related to `iptables`.

**Comment by redhatrises** [comment]
agree with @yuumasato. Tailoring the profile is what is expected here with explanations to the security officers as to why that is. All profiles are moving towards using firewalld over iptables. DISA specifically calls out using firewalld.
