### ISSUE TITLE
Rule RHEL-07-040500 Failing

### ISSUE THREAD

**Issue by mrabe142** [OpenSCAP/scap-security-guide#2623]
#### Description of problem:
I am running an OpenSCAP scan with the SSG DISA STIG profile.

In my /etc/chrony.conf I have the following lines:
server 0.rhel.pool.ntp.org iburst1 maxpoll 10
server 1.rhel.pool.ntp.org iburst1 maxpoll 10
server 2.rhel.pool.ntp.org iburst1 maxpoll 10
server 3.rhel.pool.ntp.org iburst1 maxpoll 10

According to my understanding of RHEL-07-040500, this should be all that is needed

#### SCAP Security Guide Version:
SSG 0.1.37-1

#### Operating System Version:
RHEL 7.4

#### Steps to Reproduce:

1. Verify contents of file match what is expected of the STIG
2. Run OpenSCAP scan
3. Generate HTML report and look over results

#### Actual Results:
Failed test during scan

#### Expected Results:
Passed test during scan

**Comment by redhatrises** [comment]
@mrabe142 why is `iburst1` in your `chrony.conf` file?

**Comment by mrabe142** [comment]
I did not add it there, this is a fresh install of RHEL 7.4 Server from the disk (offline install so i do not have remote repo access to install OS updates) so I assume it is a default value.

**Comment by redhatrises** [comment]
If you change `iburst1` to `iburst` does the check pass?

**Comment by mrabe142** [comment]
it still fails after removing the 1 from all the iburst instances

**Comment by mrabe142** [comment]
An update on this, I was running a custom RHEL7 install via kickstart to apply remediations.  I had it running the OpenSCAP remediate during OS install.  I temporarily disabled that and am looking at things in a fresher state.  The "iburst1" value is added during the OpenSCAP --remediate.  It was just "iburst" before running the --remediate step.  After changing the order I was doing things (install then remediate rather than doing them at the same time), this test is now passing but the "iburst" value seems wrong (that is not a valid option in the man page as far as I can tell).  I am not sure why it was failing before (the config looks identical to the one that previously failed) but I am continuing to investigate other inconsistencies I am seeing with the new STIG.

**Comment by redhatrises** [comment]
This looks to be an issue with the remediation script.

iburst is a valid configuration option.

**Comment by redhatrises** [comment]
@mrabe142 does #2629 fix this issue for you?

**Comment by matejak** [comment]
I have reviewed the current upstream `bash` remediations of RHEL7 NTP rules (specify single/additional NTP servers, configure maxpoll).
Although shellcheck was complaining about them, they did not produce the `iburst1` output. The remediation script for the `...set_maxpoll` rule (which is selected by the RHEL DISA STIG profile) doesn't look like that it is the culprit of making `iburst1` out of `iburst`.
I have cleaned up those scripts in #2629 though.

**Comment by mrabe142** [comment]
I did find the issue and it looks like it is already fixed in the current unreleased code.

The culprit was in **shared/fixes/bash/chronyd_or_ntpd_set_maxpoll.sh**

In SSG 0.1.37, it had the line:
`sed -i "s/$line/&1 maxpoll $var_time_service_set_maxpoll/" "$config_file"`

There was an extra '1' in the second half of the sed statement.

**Comment by yuumasato** [comment]
This was fixed by #2552
