### ISSUE TITLE
RHEL-07-020900 content out of sync with STIG

### ISSUE THREAD

**Issue by mrabe142** [OpenSCAP/scap-security-guide#2638]
#### Description of problem:
The latest version of the STIG has updated XCCDF check content/fix text for this rule. 

#### SCAP Security Guide Version:
Current repository snapshot

#### Operating System Version:
RHEL 7.4

The current version of the rule in `https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/xccdf/system/selinux.xml ` is out of sync with the latest content.

The current version has the following:
```
Verify that all system device files are correctly labeled to prevent unauthorized modification.

List all device files on the system that are incorrectly labeled with the following commands:

Note: Device files are normally found under "/dev", but applications may place device files in other directories and may necessitate a search of the entire system.

#find /dev -context *:device_t:* \( -type c -o -type b \) -printf "%p %Z\n"

#find /dev -context *:unlabeled_t:* \( -type c -o -type b \) -printf "%p %Z\n"

Note: There are device files, such as "/dev/vmci", that are used when the operating system is a host virtual machine. They will not be owned by a user on the system and require the "device_t" label to operate. These device files are not a finding.

If there is output from either of these commands, other than already noted, this is a finding.
```
This includes a check for an additional device label and also exceptions for VM devices that were causing the scan to fail (previously tracked at https://github.com/OpenSCAP/scap-security-guide/issues/2173).

**Comment by shawndwells** [comment]
Remembering why the SSG content doesn't do the ``find /dev unlabeled_t``... because all files under /dev auto get the device_t. A sysadmin would have to manually edit this to unlabeled_t, which would be captured in audit logs. Closing this with a bump to @tbrunell to triage with DISA.
