### ISSUE TITLE
CCE-80439-3 fails even if maxpoll 10

### ISSUE THREAD

**Issue by konstruktoid** [OpenSCAP/scap-security-guide#2655]
#### Description of problem:

`xccdf_org.ssgproject.content_rule_chronyd_or_ntpd_set_maxpoll` fails even if `maxpoll 10` is present in `/etc/ntp.conf`.

#### SCAP Security Guide Version:

Docker build at 2018-03-06 10:46:56.427479706 +0100, after SCAP Security Guide 0.1.38 release.
`xccdf_org.ssgproject.content_profile_stig-rhel7-disa`

#### Operating System Version:
`Red Hat Enterprise Linux Server release 7.4 (Maipo)`

#### Steps to Reproduce:
`The maxpoll should be configured to 10 in /etc/ntp.conf or /etc/chrony.conf to continuously poll time servers.`

```
$ sudo LANG=C grep -R 'maxpoll' /etc/ntp* /etc/chrony*
/etc/ntp.conf:maxpoll 10
grep: /etc/chrony*: No such file or directory
$ rpm -qa | grep -E 'ntp|chron'
ntpdate-4.2.6p5-25.el7_3.2.x86_64
nagios-plugins-ntp-2.2.1-4git.el7.x86_64
ntp-4.2.6p5-25.el7_3.2.x86_64
nagios-plugins-ntp-perl-2.2.1-4git.el7.x86_64
```

**Comment by redhatrises** [comment]
@konstruktoid I believe that this is already reported and fixed upstream. `maxpoll 10` should be configured like:
```
server 0.centos.pool.ntp.org iburst1 maxpoll 10
```

**Comment by konstruktoid** [comment]
@redhatrises you're right, `server address [key key | autokey] [burst] [iburst] [version version] [prefer] [minpoll minpoll] [maxpoll maxpoll]`
Sorry for the time waster.
