### ISSUE TITLE
auditd_data_retention_space_left_action rule description missing elements

### ISSUE THREAD

**Issue by ndiab** [OpenSCAP/scap-security-guide#2700]
#### Description of problem:
It miss an element in the description of the xccdf_org.ssgproject.content_rule_auditd_data_retention_space_left_action rule on the file /usr/share/xml/scap/ssg/content/ssg-centos7-xccdf.xml.

The Description of this rule enumerate all the possible ACTION described in the auditd.conf man page.
The list of action given on the description is the following :
* ignore
* syslog
* email
* exec
* suspend
* single
* halt

But, in the auditd.conf man pages, it given one more possible action : rotate.
This is the corresponding portion of the man page 

> admin_space_left_action
              This  parameter  tells  the  system  what  action  to take when the system has
              detected that it is low on disk  space.   Valid  values  are  ignore,  syslog,
              rotate,  email,  exec, suspend, single, and halt.  If set to ignore, the audit
              daemon does nothing.  Syslog means that it will issue  a  warning  to  syslog.
              rotate will rotate logs, losing the oldest to free up space.

Furthermore, I think this value is also an acceptable value and must be add to the OVAL acceptance tests.

#### SCAP Security Guide Version:
0.1.30-3.el70.centos.0.3

#### Operating System Version:
CentOS 7.2 x86_34
CentOS 7.3 x86_64

#### Steps to Reproduce:

1. Build the CentOS 7 ssg.

#### Addition Information/Debugging Steps:
add the line : 
` <li><tt>rotate</tt></li>`
to the 23rd line of the scap-security-guide/shared/guide/system/auditing/configure_auditd_data_retention/ file

**Comment by mpreisler** [comment]
Hi, thank you for the bug report! Would you be interested in patching this yourself so you can get full authorship and credit for your work? The upstream accepts patches and we use the github PR workflow. Check out https://github.com/OpenSCAP/scap-security-guide/blob/master/docs/manual/developer_guide.adoc#patch-creation

**Comment by redhatrises** [comment]
@ndiab this was done purposely as the reason that rotate is not and probably should not be added is because it is handling what happens when disk space gets low. When it gets low, we don't want the logs to rotate.

**Comment by ndiab** [comment]
@redhatrises  I understand the reason why rotate is not an acceptable solution. (Alhough rotate is a better solution for systems where availability is more important than integrity).

In any case, the rotate Action should be included in the possible actions list in the description of the ssg-centos7 even it is not an acceptable Action.

**Comment by ndiab** [comment]
@mpreisler , I'm interested to patch it myself.
Furthermore I found some other mistakes on the description :)

**Comment by redhatrises** [comment]
@ndiab actually exec is a better solution for systems where availability is more important, so that you can properly handle the logs rotating as well as account for storage space. rotate shouldn't be used when we are talking low disk space, availability, and security. What happens when there is not enough storage space for the logs to rotate? In addition, not all auditd.conf options should be added into ssg which this issue is highlighting. Any reference to ignore needs to be removed as that is not an acceptable option either.

**Comment by redhatrises** [comment]
@ndiab use of rotate is also considered a finding.

**Comment by ndiab** [comment]
Thank you for the replies @redhatrises, I didn't study the benefits of the exec action and it seems a bit better than rotate (if we well control the handling).
In the same way, exec is not an acceptable value.

Is that because the verification of the secure implementation of the targeted script is hard to be done or because it's plainly considered as an insecure solution ?
