### ISSUE TITLE
audit rules: key name shouldn't matter

### ISSUE THREAD

**Issue by jamescassell** [OpenSCAP/scap-security-guide#2707]
https://github.com/OpenSCAP/scap-security-guide/blob/3398c06a4b42e4518479d5b1276b65fb2cf89125/shared/checks/oval/audit_rules_privileged_commands.xml#L78

Is there a security reason that '-k privileged' must be specified?  Some other rules are more flexible with the key:
https://github.com/OpenSCAP/scap-security-guide/blob/3398c06a4b42e4518479d5b1276b65fb2cf89125/shared/checks/oval/audit_rules_kernel_module_loading_insmod.xml#L34

**Comment by yuumasato** [comment]
@jamescassell Hello,

AFAIK there is no requirement that key should be `privileged`.
Some rules were created with flexibility in mind while others not.
Would you be willing to provide a patch to make them flexible? We would be very happy to review it.
