### ISSUE TITLE
flexibility of aide run frequency

### ISSUE THREAD

**Issue by jamescassell** [OpenSCAP/scap-security-guide#2708]
https://github.com/OpenSCAP/scap-security-guide/blob/3398c06a4b42e4518479d5b1276b65fb2cf89125/shared/checks/oval/aide_periodic_cron_checking.xml#L39

It would be nice to be able to also use special time values such as `@daily`, `@weekly`, and `@monthly` in these cron jobs.

**Comment by redhatrises** [comment]
@jamescassell feel free to submit a PR.

**Comment by jamescassell** [comment]
Which form of regex is used here, in the output content?

**Comment by redhatrises** [comment]
@jamescassell pcre I believe

**Comment by jamescassell** [comment]
Thanks. I'll try to get a PR together.  I'll use 'grep -P' to test my change.

**Comment by shawndwells** [comment]
https://www.regextester.com/ is also helpful for the regex
