### ISSUE TITLE
disable ipv6 is no longer required stig-rhel6-disa

### ISSUE THREAD

**Issue by jamescassell** [OpenSCAP/scap-security-guide#2758]
#### Description of problem:
the rule ` V-38546 Medium  The IPv6 protocol handler must not be bound to the network stack unless needed` was removed from the RHEL 6 STIG in V1R14.  Latest 0.1.38 ssg still has `Disable IPv6 Networking Support Automatic Loading - Fail`

#### SCAP Security Guide Version:
0.1.38

#### Operating System Version:
RHEL 6.9

#### Steps to Reproduce:

1. remediate manually per STIG
2. run oscap
3. see failure of `kernel_module_ipv6_option_disabled`

#### Actual Results:
failed
```
Disable IPv6 Networking Support Automatic Loading - Fail
```

#### Expected Results:
rule not present

**Comment by jamescassell** [comment]
https://access.redhat.com/support/cases/#/case/02079384

**Comment by shawndwells** [comment]
@tbrunell another for you.

**Comment by tedbrunell** [comment]
DoD no longer sees IPv6 as a risk and the enablement of IPv6 is underway.  This rule can be removed.

**Comment by shawndwells** [comment]
Thanks @tedbrunell.

Surprised DISA did not want to add sysctl checks for securing IPv6.

**Comment by aurelien-git** [comment]
@jamescassell your link is broken ... why remove IPv6 does the DISA mean it is not secure?

**Comment by jamescassell** [comment]
@aurelien-git the link is only useful to Red Hat Support folks
