### ISSUE TITLE
Refactor Bash Remedation Functions

### ISSUE THREAD

**Issue by redhatrises** [OpenSCAP/scap-security-guide#2811]
1. Refactor Bash Remedation Function code to be less error prone e.g. #2794 
2. Refactor Bash Remedation Function code to use jinja2 templating
3. Refactor Bash Remedation Function code to not need include functions like #2810

**Comment by matejak** [comment]
I have verified that it is possible to use macro substitutions in shared remediation functions on up-to-date `master`.

**Comment by matejak** [comment]
Postponing to 0.1.41, as the fix is not trivial.
