### ISSUE TITLE
xccdf_org.ssgproject.content_profile_docker-host is missing from ssg-centos7-ds.xml

### ISSUE THREAD

**Issue by michaeldayCA** [OpenSCAP/scap-security-guide#2831]
#### Description of problem:

xccdf_org.ssgproject.content_profile_docker-host is missing from ssg-centos7-ds.xml

#### SCAP Security Guide Version:

0.1.39

#### Operating System Version:

CentOS Linux release 7.4.1708 (Core)

#### Steps to Reproduce:

1. oscap info /usr/share/xml/scap/ssg/content/ssg-centos7-ds.xml

#### Actual Results:
xccdf_org.ssgproject.content_profile_docker-host is not listed

#### Expected Results:
xccdf_org.ssgproject.content_profile_docker-host is listed

#### Addition Information/Debugging Steps:

Maybe this was just missed in the release notes, but given that the release notes specifically list an OVAL enhancement that is specific to the docker-host profile, I would expect that the profile would be there, otherwise why even bother fixing an issue in a deprecated profile.
```
[Enhancement] Add Docker SELinux check in daemon.json
```

**Comment by redhatrises** [comment]
@michaeldayCA the docker-host profile was marked as Draft as there is a lot more to be done with it. When a profile is marked as draft now, it is no longer built. Do you use the docker-host profile?

**Comment by michaeldayCA** [comment]
@redhatrises it was one of the profiles we scan for, but given that there were only 6 tests in it, it wasn't too useful.  I'll close this issue.  Thanks for the information.
