### ISSUE TITLE
sshd_set_keepalive misleading description

### ISSUE THREAD

**Issue by pes-soft** [OpenSCAP/scap-security-guide#2937]
#### Description of problem:
Description of the rule is misleading with incorrect name of dependent sshd setting. Rule recommends to set ClientAliveCountMax so timeout occurs when interval has been reached. Name of the setting for interval ( ClientAliveInterval ) is however not mentioned and ClientAliveCountMax is used instead, which is misleading. For example in following file: [scap-security-guide/linux_os/guide/services/ssh/ssh_server/sshd_set_keepalive.rule](https://github.com/OpenSCAP/scap-security-guide/blob/master/linux_os/guide/services/ssh/ssh_server/sshd_set_keepalive.rule) the description states:
```
To ensure the SSH idle timeout occurs precisely when the <tt>ClientAliveCountMax</tt> is set,
edit <tt>/etc/ssh/sshd_config</tt> as follows:
<pre>ClientAliveCountMax 0</pre>
```
Instead it should say:
```
To ensure the SSH idle timeout occurs precisely when the <tt>ClientAliveInterval</tt> is set,
edit <tt>/etc/ssh/sshd_config</tt> as follows:
<pre>ClientAliveCountMax 0</pre>
```

Similarly it should get fixed in rationale section and ocil section.

#### SCAP Security Guide Version:
Detected on fedora in scap-security-guide-0.1.39-2.fc28.noarch

#### Operating System Version:
Fedora 28

#### Steps to Reproduce:

1. oscap xccdf eval --profile "xccdf_org.ssgproject.content_profile_standard" --report report.html "/usr/share/xml/scap/ssg/content/ssg-fedora-ds.xml"
2. See description, reational and ocil section of sshd_set_keepalive rule in report.html

#### Actual Results:
To ensure the SSH idle timeout occurs precisely when the <tt>ClientAliveCountMax</tt> is set

#### Expected Results:
To ensure the SSH idle timeout occurs precisely when the <tt>ClientAliveInterval</tt> is set

#### Addition Information/Debugging Steps:
This is probably not related only to Fedora, but to other systems as well.

**Comment by cipherboy** [comment]
@pes-soft Good catch! Are you interested in opening a pull request to fix this? :)

It looks like there's a bit of duplication here:
- [RHEL6](rhel6/guide/services/ssh/ssh_server/sshd_set_keepalive.rule)
- [Debian 8](ubuntu1604/guide/services/ssh/ssh_server/sshd_set_keepalive.rule), [Ubuntu 14.04](ubuntu1404/guide/services/ssh/ssh_server/sshd_set_keepalive.rule), and [Ubuntu 16.04](ubuntu1604/guide/services/ssh/ssh_server/sshd_set_keepalive.rule)
- [linux_os](linux_os/guide/services/ssh/ssh_server/sshd_set_keepalive.rule) -- which you found

Also:
- [XCCDF Manual](https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/references/disa-stig-rhel6-v1r18-xccdf-manual.xml#L2037-L2039)

**Comment by redhatrises** [comment]
One thing to note on this is that files in `shared/references` should never be changed or updated as part of bugfixes. These are official files that come from the reference source themselves, and the only update to those reference files should be when a new release/version is released from the reference source.

**Comment by cipherboy** [comment]
@redhatrises Thanks! :) I updated my comment to reflect that.

**Comment by pes-soft** [comment]
Thanks for your response. I've opened a PR #2946. As Ubuntus switched to debian8 guide few days ago, change has been required just in rhel6, debian8 and linux_os.

**Comment by cipherboy** [comment]
@pes-soft Yep -- those changes were merged after I made the comment. :) Thanks for the PR!
