### ISSUE TITLE
xccdf_org.ssgproject.content_rule_accounts_password_pam_maxrepeat selector="2". DISA STIG RHEL-07-010180 = 3 

### ISSUE THREAD

**Issue by amitkumar50** [OpenSCAP/scap-security-guide#2962]
#### Description of problem:
Rule ID xccdf_org.ssgproject.content_rule_accounts_password_pam_maxrepeat for DISA STIG RHEL-07-010180 has an incorrect value. The description, oval check, and remediation all have maxrepeat = 2, but the DISA STIG says that this should be maxrepeat = 3

#### SCAP Security Guide Version:
scap-security-guide-0.1.36-7.el7.noarch

#### Operating System Version:
rhel-7

#### Steps to Reproduce:
From http://iase.disa.mil/stigs/os/unix-linux/Pages/index.aspx/Red Hat Enterprise Linux 7 STIG - Ver 1, Rel 4/U_Red_Hat_Enterprise_Linux_7_STIG_V1R4_Manual-xccdf.xml
Add the following line to "/etc/security/pwquality.conf conf" (or modify the line to have the required value):^M
^M
maxrepeat = 3The "maxrepeat" option sets the maximum number of allowed same consecutive characters in a new password.

From /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml
Profile id="xccdf_org.ssgproject.content_profile_common"
Profile id="xccdf_org.ssgproject.content_profile_stig-rhevh-upstream"
Profile id="xccdf_org.ssgproject.content_profile_ospp-rhel7"
Profile id="xccdf_org.ssgproject.content_profile_nist-800-171-cui"
refine-value idref="xccdf_org.ssgproject.content_value_var_password_pam_maxrepeat" selector="2"/

**Comment by cipherboy** [comment]
This one is an easy fix if you want to open a PR:

- [rhel7/profiles/ospp.profile line 368](https://github.com/OpenSCAP/scap-security-guide/blob/master/rhel7/profiles/ospp.profile#L368)
- [linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_maxrepeat.rule line 28](https://github.com/OpenSCAP/scap-security-guide/blob/master/linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_maxrepeat.rule#L28)

Thanks!
