### ISSUE TITLE
xccdf_org.ssgproject.content_rule_configure_firewalld_ports for DISA STIG RHEL-07-040100 automatically fails as it has no check

### ISSUE THREAD

**Issue by amitkumar50** [OpenSCAP/scap-security-guide#2963]
#### Description of problem:
Rule ID xccdf_org.ssgproject.content_rule_configure_firewalld_ports for DISA STIG RHEL-07-040100 automatically fails as it has no check. This almost needs to be manual , or notchecked, as the DISA STIG is asking for the firewall rules to meet the PPSM CLSA which would be different for every system.

#### SCAP Security Guide Version:
scap-security-guide-0.1.36-7.el7.noarch

#### Operating System Version:
rhel-7

#### Steps to Reproduce:
/usr/share/xml/scap/ssg/content/.ssg-rhel7-ds.xml xccdf_org.ssgproject.content_rule_configure_firewalld_ports for DISA STIG RHEL-07-040100 automatically fails as it has no check.

As per: http://iase.disa.mil/stigs/os/unix-linux/Pages/index.aspx
U_Red_Hat_Enterprise_Linux_7_V1R4_Manual_STIG/U_Red_Hat_Enterprise_Linux_7_STIG_V1R4_Manual-xccdf.xml
This almost needs to be manual , or notchecked, as the DISA STIG is asking for the firewall rules to meet the PPSM CLSA which would be different for every system

**Comment by redhatrises** [comment]
Sorry but nack. There are others who use this, and the goal is to fully automate hardening a box end-to-end. In addition, this is a preference, so the recommendation is to tailor out the rule from the profile and track elsewhere. If anything, the check and remediation need to be expanded to take in a comma separated list of ports and protocols and check/remediate based off of that list.
