### ISSUE TITLE
Enhancement: use faster grep

### ISSUE THREAD

**Issue by mykaul** [OpenSCAP/scap-security-guide#3031]
#### Description of problem:
In some cases, we should use fgrep and LC_ALL=C (with fgrep or grep) to speed up grep.
From a random example:
https://github.com/OpenSCAP/scap-security-guide/blob/c83eb1ebe5504025d2e198ba72cb5611b25aa3b5/rhel6/fixes/bash/sshd_do_not_permit_user_env.sh#L2

```
grep -q ^PermitUserEnvironment /etc/ssh/sshd_config
```

it's always going to be in ASCII, so we could probably use:
```
LC_ALL=C grep -q -m 1 PermitUserEnvironment /etc/ssh/sshd_config
```

#### SCAP Security Guide Version:
Doesn't matter

#### Operating System Version:
Doesn't matter

**Comment by matejak** [comment]
This is an interesting idea, we will explore this possibility. Do you, by any chance, have some kind of a benchmark?

**Comment by mykaul** [comment]
https://www.inmotionhosting.com/support/website/ssh/speed-up-grep-searches-with-lc-all

**Comment by mykaul** [comment]
@matejak : there are hundreds of grep invocations here.
For example:
https://github.com/OpenSCAP/scap-security-guide/blob/4625a97bcb949855fd425a9eda03d10ffe63a8de/rhel7/fixes/bash/snmpd_not_default_password.sh#L3  : 
```
if grep -s "public\|private" /etc/snmp/snmpd.conf | grep -qv "^#"; then
```

Two invocations already, both could benefit from this.
Just fixing it for few probably won't make a difference...
