### ISSUE TITLE
Benchmark descriptions contain formatting tags

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/scap-security-guide#3053]
#### Description of problem:
Benchmark descriptions contain formatting tags, which are not translated to HTML tags, therefore they are visible in HTML guides and reports.

See https://static.open-scap.org/ssg-guides/ssg-rhel7-guide-index.html

You will find:

```
The SCAP content is is available in the config_item="scap-security-guide" package
```
```
This guide is a italics="catalog, not a checklist," and 
```
```
 italics="Profiles",
```
I think it doesn't look well.

#### SCAP Security Guide Version:
scap-security-guide-0.1.39-2.fc27.noarch
The problem still appears on current upstream (as of HEAD a907571118793ed917b4bf7d85bc17388c98cb8f).

#### Operating System Version:
Fedora 27

#### Steps to Reproduce:

1. Open some HTML guide, eg. for RHEL 7 or Fedora, eg. https://static.open-scap.org/ssg-guides/ssg-rhel7-guide-index.html
2. Read Description
3.
4.

#### Actual Results:
Benchmark descriptions contain formatting tags

#### Expected Results:
Benchmark descriptions are normally readable

**Comment by dahaic** [comment]
Comment test

**Comment by jan-cerny** [comment]
Hi, this is great that it is fixed.
