### ISSUE TITLE
CCEs are not identified in xccdf:ident or xccdf:reference tags in CentOS content

### ISSUE THREAD

**Issue by solind** [OpenSCAP/scap-security-guide#3104]
#### Description of problem:

The ssg-centos6-ds.xml and ssg-centos7-ds.xml documents contain <xccdf:reference/> tags with CCI identifiers, but CCE identifiers are only noted in freeform text within <xccdf:fix/> tags.  I am guessing that the failure to include CCE references as structured data is unintentional.

#### SCAP Security Guide Version:

0.1.39

#### Operating System Version:

CentOS6, CentOS7

**Comment by redhatrises** [comment]
Thanks @solind! It is actually quite intentional. The RHEL CCEs should not show up in CentOS at all. Unfortunately, it seems like the CCEs are showing up in the fix tags which should not be the case.

**Comment by redhatrises** [comment]
CCEs are provided by os or application that apply to that os/application corresponding rules. In other words, the CCEs you see are RHEL CCEs which do not apply to CentOS.

**Comment by shawndwells** [comment]
On 7/9/18 1:48 PM, redhatrises wrote:
>
> CCEs are provided by os or application that apply to that 
> os/application corresponding rules. In other words, the CCEs you see 
> are RHEL CCEs which do not apply to CentOS.
>

+1

CentOS does not have any corporate entity supporting it who would 
receive authoritative CCEs from NIST.

Someone from the CentOS core team could request CCEs from NIST and 
assign them. Patches adding those CCE mappings would definitely be 
welcome if they wanted to take that on.

**Comment by solind** [comment]
I understand.  What if those mappings were to borrow CCE IDs from RHEL -- particularly where the underlying configuration issue is actually identical (e.g., most cases)?

**Comment by redhatrises** [comment]
CCEs are assigned to a platform (1:1), so how would CentOS "borrow" CCE IDs that are for the RHEL platform?

**Comment by solind** [comment]
Well, I mean it in the same sense that CentOS "borrows" everything else from RHEL. Take for example CCE-26435-8: "Ensure /tmp Located On Separate Partition".

In both ssg-rhel6-ds.xml and ssg-centos6-ds, there is a common XCCDF rule ID: xccdf_org.ssgproject.content_rule_partition_for_tmp.

In the RHEL6 content, there is an xccdf:ident tag referencing the CCE, but there is no corresponding CCE ID in the CentOS6 content.

Indeed, this identifier was assigned by NIST to RedHat.  The assertion: "RHEL and CentOS are different operating systems" is factually correct, of course, but it belies the fact that apart from the names of a few RPMs and digital signatures, they are virtually identical by CentOS's very design.  It's not like I'm talking about "borrowing" a CCE ID to use with an OS that really is vastly different, like AIX or Windows.

In light of the obvious similarities, I don't see why it wouldn't make sense to include these CCE IDs via, say, xccdf:reference tags in the CentOS version of the content (as opposed to xccdf:ident tags, which is the context in which they appear in the RHEL version of the content).

If you guys don't want to include them, that's fine.  I had originally assumed it was just an oversight.

**Comment by shawndwells** [comment]
On 7/10/18 1:38 PM, David Solin wrote:
>
> Well, I mean it in the same sense that CentOS "borrows" everything 
> else from RHEL. Take for example CCE-26435-8: "Ensure /tmp Located On 
> Separate Partition".
>
> In both ssg-rhel6-ds.xml and ssg-centos6-ds, there is a common XCCDF 
> rule ID: xccdf_org.ssgproject.content_rule_partition_for_tmp.
>
> In the RHEL6 content, there is an xccdf:ident tag referencing the CCE, 
> but there is no corresponding CCE ID in the CentOS6 content.
>
> Indeed, this identifier was assigned by NIST to RedHat. The assertion: 
> "RHEL and CentOS are different operating systems" is factually 
> correct, of course, but it belies the fact that apart from the names 
> of a few RPMs and digital signatures, they are virtually identical by 
> CentOS's very design. It's not like I'm talking about "borrowing" a 
> CCE ID to use with an OS that really is vastly different, like AIX or 
> Windows.
>

Differences extend beyond frivolity of branding and logos.

CentOS has different compilation systems including different compilation 
flags. Things like FORTIFY_SOURCE, fstack-protector-strong are present 
in RHEL but there is no assurance of CentOS being compiled with them. 
There are reasons their binaries have different digital signatures (even 
beyond differences created when binaries are compiled on different 
physical hardware).


> In light of the obvious similarities, I don't see why it wouldn't make 
> sense to include these CCE IDs via, say, xccdf:reference tags in the 
> CentOS version of the content (as opposed to xccdf:ident tags, which 
> is the context in which they appear in the RHEL version of the content).
>
> If you guys don't want to include them, that's fine. I had originally 
> assumed it was just an oversight.
>


CentOS is an operating system with no government certifications, no 
support, no OVAL for CVEs, etc. CentOS is simply not an operating system 
intended to be used in regulated environments who would care about SCAP 
and CCEs to begin with.

IMHO nobody would actively stop or prevent another individual from 
adding CentOS CCEs. It's more that no one has stepped up and offered to 
hold the bag for maintenance. CentOS doesn't have any maintainers 
focusing on security, nobody whose job it would be to manage the CCEs. 
An external party would have to do this or the CentOS maintainers would 
have to be convinced it's worth their time.

**Comment by redhatrises** [comment]
CentOS CCEs have been removed to comply with NIST CCE specifications.
