### ISSUE TITLE
oval eval considers existence of older installed kernel versions when doing package version checks

### ISSUE THREAD

**Issue by nycoe** [OpenSCAP/scap-security-guide#3142]
#### Description of problem:
With the RHEL oval definitions https://www.redhat.com/security/data/oval/Red_Hat_Enterprise_Linux_7.xml an oscap oval eval will consider older installed kernels as being vulnerable to an RHSA, even though the latest installed kernel that the machine is currently running is not vulnerable.  I would like to not delete all old kernels and keep at least one revision back available in case of an issue with the latest kernel.  There should be an option to force the check of rpms to the latest versions available on the system, instead of all versions installed.

#### SCAP Security Guide Version:
scap-security-guide-0.1.36-9.el7_5.noarch

#### Operating System Version:
RHEL 7.5

#### Steps to Reproduce:
1.   Download https://www.redhat.com/security/data/oval/Red_Hat_Enterprise_Linux_7.xml 
2.  oscap oval eval --id oval:com.redhat.rhsa:def:20181852 Red_Hat_Enterprise_Linux_7.xml
Definition oval:com.redhat.rhsa:def:20181852: true
Evaluation done.
3. uname -r
3.10.0-862.6.3.el7.x86_64
4. According to https://access.redhat.com/errata/RHSA-2018:1852  this kernel is newer than the fix for the RHSA which was available in 3.10.0-862.3.3.el7.x86_64
5. rpm -q kernel
kernel-3.10.0-693.17.1.el7.x86_64
kernel-3.10.0-693.21.1.el7.x86_64
kernel-3.10.0-862.6.3.el7.x86_64

#### Actual Results:
Definition oval:com.redhat.rhsa:def:20181852: true

#### Expected Results:
Definition oval:com.redhat.rhsa:def:20181852: false

but because I still have 2 kernels for which this RHSA applies technically installed, but not currently running, the eval shows a match.  

A flag to oval eval should allow it to only look at the latest version of an rpm (possibly only for "kernel") when doing the rpm version checks.

Workaround is to 
package-cleanup --oldkernels --count=1

which I would prefer not to do, as it would limit any rollback capability if a new issue was discovered with the latest kernel, that prevented a proper system boot.

**Comment by redhatrises** [comment]
@nycoe thanks for raising this issue. 

This is aactually a valid failure as the older kernel can be started on reboot, so the system is still technically vulnerable. In addition, this project does not deal with or work on the official Red Hat errata and OVAL. Closing.
