### ISSUE TITLE
CentOS 7 install via kickstart fails when using the COPR repos

### ISSUE THREAD

**Issue by jszakmeister** [OpenSCAP/scap-security-guide#3175]
#### Description of problem:

There are some bugs in the latest CentOS 7 packages that come with the distro, so I decided to try the COPR EPEL 7 repos to get the latest version of the package.  I'm using kickstart's oscap addon:

```
%addon org_fedora_oscap
content-type = scap-security-guide
profile = xccdf_org.ssgproject.content_profile_stig-rhel7-disa
%end
```

#### SCAP Security Guide Version:

The latest published in the COPR repos.

#### Operating System Version:

CentOS 7.5 build 1804 x86_64 (running in a VM)

#### Steps to Reproduce:

Create a new VM and use a kickstart script containing:

```
repo --name=openscap-latest --baseurl=https://copr-be.cloud.fedoraproject.org/results/openscapmaint/openscap-latest/epel-7-x86_64/

%addon org_fedora_oscap
content-type = scap-security-guide
profile = xccdf_org.ssgproject.content_profile_stig-rhel7-disa
%end
```
I can provide a config, if necessary, but I'd rather not post it here.

#### Actual Results:

Anaconda fails because the add-on cannot find ssg-centos7-ds.xml.

#### Expected Results:

I'd expect the packaged RPM to contain the CentOS derivatives, especially since it claims to support CentOS 7.

**Comment by yuumasato** [comment]
Thanks for reporting this. 
It looks like the COPR package was built supporting only a few products.
A re-spin should be coming soon.

**Comment by jszakmeister** [comment]
Awesome!  Thank you!

**Comment by matejak** [comment]
Should be fixed by now, thank you for the report!

**Comment by jszakmeister** [comment]
@matejak Thank you for fixing the issue!  I'll give it a spin soon...
