### ISSUE TITLE
[RHEL/6, RHEL/7] Fix selinux_all_devicefiles_labeled XCCDF description to use 'device_t' rather than 'unlabeled_t'

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-security-guide#328]
As pointed out in:
  [1] https://lists.fedorahosted.org/pipermail/scap-security-guide/2014-October/006257.html

the default SELinux type when SELinux knows nothing about the particular device in question isn't ```unlabeled_t```, but rather ```device_t```. This can be verified by running e.g. the following commands:
```
[root@localhost ~]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 6.6 (Santiago)
[root@localhost ~]# matchpathcon /dev
/dev	system_u:object_r:device_t:s0
[root@localhost ~]# touch /dev/mydevice
[root@localhost ~]# ls -Z /dev/mydevice 
-rw-------. root root unconfined_u:object_r:device_t:s0 /dev/mydevice
[root@localhost ~]# ln -s /dev/zero /dev/my_custom_zero
[root@localhost ~]# ls -Z /dev/my_custom_zero 
lrwxrwxrwx. root root unconfined_u:object_r:device_t:s0 /dev/my_custom_zero -> /dev/zero
```

Therefore we should modify selinux_all_devicefiles_labeled XCCDF rule's ```<description>``` & ```<rationale>``` elements (for both of RHEL-6 & RHEL-7) to read ```device_t``` instead of (current) ```unlabeled_t```.

**Comment by redhatrises** [comment]
Running `grep -rni unlabeled_t *` on the latest master does not return any results for XCCDF or OVAL content. Therefore, it looks like this issue can be closed.
