### ISSUE TITLE
Port DISA STIG's SCAP Content submission by Trey Henefield to current 'master' branch & make a PR

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-security-guide#347]
Trey Henefield provided DISA STIG content enhancements:
  [1] https://lists.fedorahosted.org/pipermail/scap-security-guide/2014-December/006296.html
  [2] https://lists.fedorahosted.org/pipermail/scap-security-guide/2014-December/006296.html

but these are not directly mergeable into current 'master' branch. Port them against current code & make a PR.

**Comment by redhatrises** [comment]
I believe that this was already done by Trey as the content exists now in git. Closing this ticket.

**Comment by iankko** [comment]
Yes. Thanks for handling this.
