### ISSUE TITLE
use applicability_check to make SSG more friendly to derivative OS'?

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#374]
certain checks -- such as the use of FIPS or certified crypto -- simply aren't possible on RHEL derivatives. Should we use the optional applicability check to auto fail such rules (e.g. only pass on RHEL, which is FIPS 140-2'd), and start dropping the CPE checks for other rules?

from https://oval.mitre.org/language/version5.11/ovaldefinition/documentation/oval-definitions-schema.html#CriteriaType:

```
The optional applicability_check attribute provides a Boolean flag that when true indicates that the criteria is being used to determine whether the OVAL Definition applies to a given system.
```

The user community has expressed interest in getting CentOS support in here, perhaps this is a good starting point.... @gregelin ?

**Comment by redhatrises** [comment]
Should Scientific Linux be included in this as well?

**Comment by shawndwells** [comment]
@redhatrises, sure

**Comment by bmx0r** [comment]
Hi guys, i want to add support for centos 7 but i'm wondering where to start...
i thought about : 
- creating a "installed_OS_is_centos7.xml" in /shared/oval/
- link that in the RHEL7 dir and add the cpe to ./RHEL/7/dist/content/ssg-rhel7-cpe-dictionary.xml
- in every check applicable to the rhel7 platteform adding the centos7

Is this the right way to do it?

**Comment by shawndwells** [comment]
Derivative OS' are now supported. Closing.

**Comment by D3vil0p3r** [comment]
> Derivative OS' are now supported. Closing.

Hello @shawndwells for a Fedora derivative, when running `oscap` command like:
```
sudo oscap xccdf eval \
                             --profile xccdf_org.ssgproject.content_profile_standard \
                             --results scan-results.xml \
                             --report scan-report.html \
                             /usr/share/xml/scap/ssg/content/ssg-fedora-ds.xml
```
is there a way to specify on the tool the specific Fedora derivative to prevent the "Not applicable" output?
