### ISSUE TITLE
NIST 800-53 AC-3: ftp_restrict_to_anon, disable_host_auth, no_netrc_files, disable_xwindows_with_runlevel

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#400]
@lukek1

**Comment by lukek1** [comment]
see pull request #422

**Comment by iankko** [comment]
All four rules fixed via PR: https://github.com/OpenSCAP/scap-security-guide/pull/422 (for both RHEL-6 & RHEL-7). Closing
