### ISSUE TITLE
runlevel_test - value of check_existence attribute

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/scap-security-guide#435]
In ssg-rhel6-oval.xml, all runlevel tests have check_existence attribute set to "any_exist". This is probably wrong. The specification (http://oval.mitre.org/language/version5.4/ovaldefinition/documentation/oval-common-schema.html) says that "A value of 'any_exist' means that zero or more objects defined by the description exist on the system.". This means that those tests pass even if referred objects don't exist. I think we expect them to fail in such case. I suggest setting check_existence to at_least_one_exists.

If you run the following content on Fedora where is systemd, you get this test pass, but no object has been collected:

```
<tests>
  <unix:runlevel_test check="all" check_existence="any_exist" comment="Runlevel test" id="oval:x:tst:1" version="1">
    <unix:object object_ref="oval:ssg:obj:1313"/>
    <unix:state state_ref="oval:ssg:ste:1314"/>
  </unix:runlevel_test>
</tests>
<objects>
  <unix:runlevel_object id="oval:ssg:obj:1313" version="1">
    <unix:service_name>smartd</unix:service_name>
    <unix:runlevel operation="equals">0</unix:runlevel>
  </unix:runlevel_object>
</objects>
<states>
  <unix:runlevel_state comment="configured to start" id="oval:ssg:ste:1314" version="1">
    <unix:start datatype="boolean">true</unix:start>
    <unix:kill datatype="boolean">false</unix:kill>
    </unix:runlevel_state>
 </states>
```

In OVAL results you can find these information:

```
<tests>
      <test test_id="oval:x:tst:1" version="1" check_existence="any_exist" check="all" result="true"/>
</tests>

<collected_objects>
      <object id="oval:ssg:obj:1313" version="1" flag="does not exist"/>
</collected_objects>
```

**Comment by iankko** [comment]
Thank you for the report, Jan.

While the recommendation s/any_exist/at_least_one_exists/g for runlevel OVAL checks looks generally safe, would it be possible you to provide an example of an environment where the current implementation isn't working properly?

This way we could ensure we will fix the issue there & not to introduce regressions in the environments, where it's currently working properly.

Thank you && Regards, Jan.

**Comment by redhatrises** [comment]
This hasn't really been an issue, so closing. Feel free to reopen if you want it fixed. PRs welcome. :D
