### ISSUE TITLE
/etc/pam.d/system-auth not updating from pwquality.conf

### ISSUE THREAD

**Issue by BisuDagger** [OpenSCAP/scap-security-guide#445]
I need RHEL7 password help please!
First I edit pwquality.conf because its updated values should affect /etc/pam.d/system-auth. Next I'm running [code]authconfig --updateall[/code]
The update call is not reading from pwquality.conf and is setting system-auth to different values. Any help on this would be amazing. Thank you!

**Comment by redhatrises** [comment]
@BisuDagger can you provide some before and after output? When using `pwquality.conf`, the password settings such as `difok` or `minlen` do not get added to `system-auth`. `pam_pwquality.so` checks `pwquality.conf`, so the line in `system-auth` should look like somthing similar to the following:

```password    required    pam_pwquality.so try_first_pass local_users_only retry=3 authtok_type=```

**Comment by BisuDagger** [comment]
This is how my pwquality.conf file looks currently.
![pwquality conf](https://cloud.githubusercontent.com/assets/8884283/6188347/33540fee-b35e-11e4-925b-e2eab62b060c.PNG)

I then call [code]authconfig --updateall[/code] and this is what system-auth and system-auth-ac look like. (password-auth also looks the same as system-auth in regards to pam_pwquality).
![system-auth-ac](https://cloud.githubusercontent.com/assets/8884283/6188369/36c8b94a-b35e-11e4-8d1c-772ee1fcc975.PNG)

**Comment by redhatrises** [comment]
@BisuDagger this is expected behavior. The password settings from `pwquality.conf` do not get updated in `system-auth`. Password settings are still enforced because of the following line in `system-auth`:

`password required pam_pwquality.so try_first_pass local_users_only retry=3 authtok_type=`

**Comment by BisuDagger** [comment]
@redhatrises Is there a reason this doesn't pass the scap test then? All credit checks result in errors.

**Comment by redhatrises** [comment]
My guess is that it is because there are two spaces before the settings.

**Comment by redhatrises** [comment]
@BisuDagger you can fix it by doing the following:

```sed -i -e 's/^[ \t]*//' /etc/security/pwquality.conf

**Comment by BisuDagger** [comment]
@redhatrises 
Okay. So I ran the command line and have the current setup now.
![pwquality conf2](https://cloud.githubusercontent.com/assets/8884283/6188940/7b99c2d4-b364-11e4-8e96-f2a26a8b4fa8.PNG)

The SCAP results are now sitting at FALSE. 
![scappw](https://cloud.githubusercontent.com/assets/8884283/6188946/893dacde-b364-11e4-8498-6f8d4a78a7c6.PNG)

Are the values I am passing through wrong? I could not find documentation to inform me of the correct ones other then here: https://benchmarks.cisecurity.org/downloads/show-single/?file=rhel7.100

**Comment by redhatrises** [comment]
What version of scap-security-guide are you running? Also, go ahead and add a space between the `=` and the assigned value i.e. `-1`

**Comment by BisuDagger** [comment]
@redhatrises 
/scap/ssg/content/ssg-rhel7-oval.xml

**Comment by redhatrises** [comment]
@BisuDagger rpm -qa | grep scap-security-guide

**Comment by BisuDagger** [comment]
@redhatrises 
scap-security-guide-0.1.19-2.el7.noarch

**Comment by redhatrises** [comment]
What SCAP profile are you running and are you running centos7?

**Comment by BisuDagger** [comment]
Is there a command I can enter to give you the exact answer for the SCAP profile? I'm new to SCAP/Linux so I want to give you the most correct information. I am running Red Hat Enterprise 7.

**Comment by redhatrises** [comment]
@BisuDagger `scap-security-guide-0.1.19-2.el7.noarch` is in BETA for RHEL7.1 and does not check `/etc/security/pwquality.conf`. It actually checks `/etc/pam.d/{system-auth, password-auth}` which means the content checks those files, and you will have to edit those files for the check to pass. Also, the only SCAP profile that Red Hat is currently shipping is a *draft* version of the Red Hat Corporate Profile for Certified Cloud Providers (RH CCP). This can be checked by running the following:

`oscap info /usr/share/xml/scap/content/ssg-rhel7-xccdf.xml`

For further help or to request that the RHEL7 content be updated to check `/etc/security/pwquality.conf`, I would strongly recommend opening a support case with Red Hat. Also, check out this guide to learn more about using OpenSCAP: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Security_Guide/sect-Using_oscap.html

**Comment by BisuDagger** [comment]
@redhatrises Thank you for all your help! It is very much appreciated!
