### ISSUE TITLE
RHEL7: check /etc/security/pwquality.conf instead of PAM

### ISSUE THREAD

**Issue by isimluk** [OpenSCAP/scap-security-guide#446]
Previously reported by @BisuDagger at OpenSCAP/openscap#52.

Quotation:
```
First issue:
-Basically, all password SCAP checks (lcredit/ocredit/reuse etc.) result in errors or false. The issue is that RHEL7 O-SCAP needs to check /etc/security/pwquality.conf instead of /etc/pam.d/{system-auth, password-auth}. Is there any way this fix can be added in?

Additional Issues on this Topic:
-Password Parameters (such as minimum age/min length etc.) do not pass SCAP. this issue is harder to identify and lies within /etc/login.defs
```

**Comment by redhatrises** [comment]
> First issue:
-Basically, all password SCAP checks (lcredit/ocredit/reuse etc.) result in errors or false. The issue is that RHEL7 O-SCAP needs to check /etc/security/pwquality.conf instead of /etc/pam.d/{system-auth, password-auth}. Is there any way this fix can be added in?

@isimluk this is already fixed in v0.1.20. See PR #299.

**Comment by redhatrises** [comment]
@isimluk looks like everything works correctly for v0.1.20 or newer. The only pam_pwquality check that still has to be in system-auth-ac is retry, but this is a limitation of libpwquality itself as it appears that adding ```retry=3``` to ```/etc/security/pwquality.conf``` does not work.

@BisuDagger Can you provide more information about the issues with ```/etc/login.defs```?

**Comment by isimluk** [comment]
Looks good to me. We can close this unless @BisuDagger gives us any feedback.

**Comment by redhatrises** [comment]
Closing as no more information/feedback was provided. Re-open this if the issues reported are still happening in the latest master branch.
