### ISSUE TITLE
files unowned by group improvements

### ISSUE THREAD

**Issue by isimluk** [OpenSCAP/scap-security-guide#460]
@jan-cerny has improved this check by #459, but still the check looks weird.

The state reads:
```
    <unix:file_state comment="Executables with suid set" id="oval:ssg:ste:1711" version="1">
      <unix:group_id datatype="int">0</unix:group_id>
    </unix:file_state>
```

Firstly, the comment is confusing. Secondly, it does not look for `unowned`, rather it looks for `not owned by root group`. At least it looks like that.

I guess the more correct oval should look like:
```
     <file_state>
        <group_id datatype="int" var_ref="VAR_LIST_OF_GROUPS" var_check="at least one"/>
      </file_state>
```
And then we need:
```
      <local_variable id="VAR_LIST_OF_GROUPS" datatype="int">
        <object_component object_ref="OBJ_LIST_OF_GROUPS" item_field="subexpression"/>
      </local_variable>
```
and
```
      <textfilecontent54_object id="OBJ_LIST_OF_GROUPS">
        <filepath>/etc/group</filepath>
        <pattern operation="pattern match">^[^:]+:[^:]*:([\d]+):[^:]*$<pattern>
        <instance operation="greater than or equal" datatype="int">1<instance>
      </textfilecontent54_object>
```

Thoughts?

**Comment by isimluk** [comment]
@jan-cerny, can you please prototype this and test? Thanks!

**Comment by jan-cerny** [comment]
I add something new to the pull request https://github.com/OpenSCAP/scap-security-guide/pull/459

**Comment by shawndwells** [comment]
resolved in https://github.com/OpenSCAP/scap-security-guide/blob/483038f1c6a2ae3f44b7b629fa4f4ecc23b702cd/RHEL/6/input/checks/file_permissions_ungroupowned.xml

closing
