### ISSUE TITLE
RHEL6 FIPS: Need MACs in sshd_config

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#480]
Current content does not check MACs settings for SSHD (needed for configuring FIPs mode)

e.g.
````echo "MACs hmac-sha2-512,hmac-sha2-256,hmac-sha1" >> /etc/ssh/sshd_config````

thanks to @fcaviggia for reporting!

**Comment by pcactr** [comment]
I'll take care of this.

**Comment by redhatrises** [comment]
Fixed. Please re-open this ticket if the fix does not work.
