### ISSUE TITLE
aide_periodic_cron_checking explicitly looking for "root"

### ISSUE THREAD

**Issue by dokuhebi** [OpenSCAP/scap-security-guide#493]
I've got an issue, and I'm not quite sure where it should be fixed.  According to RHEL-06-000302, there is a requirement that a cron job be created running aide.  While there are a number of implementations that would technically meet this requirement, the verification step says specifically to look for: 

`05 4 * * * root /usr/sbin/aide --check`

I'm using puppet to create the cron, and even though I have the cron config to use the "root" user, it seems that puppet is "smart", and removes the unnecessary reference root.  It doesn't seem like there's any way to force puppet to include the root user in the generated cron insert, so I'm stuck with the following:

`5 4 * * * /usr/sbin/aide --check`

Can I make a change to the check regex to look for "root" or nothing so my configuration passes the test?

**Comment by dokuhebi** [comment]
```
diff --git a/shared/oval/aide_periodic_cron_checking.xml b/shared/oval/aide_periodic_cron_checking.xml
index 20c5381..218cdad 100644
--- a/shared/oval/aide_periodic_cron_checking.xml
+++ b/shared/oval/aide_periodic_cron_checking.xml
@@ -33,7 +33,7 @@
   <ind:textfilecontent54_object comment="run aide daily with cron" id="object_test_aide_crond_checking" version="1">
     <ind:path>/etc/cron.d</ind:path>
     <ind:filename operation="pattern match">^.*$</ind:filename>
-    <ind:pattern operation="pattern match">^[0-9]*[\s]*[0-9]*[\s]*\*[\s]*\*[\s]*\*[\s]*root[\s]*/usr/sbin/aide[\s]*\-\-check+$</ind:pattern>
+    <ind:pattern operation="pattern match">^[0-9]*[\s]*[0-9]*[\s]*\*[\s]*\*[\s]*\*[\s]*(root|)[\s]*/usr/sbin/aide[\s]*\-\-check+$</ind:pattern>
     <ind:instance datatype="int" operation="greater than or equal">1</ind:instance>
   </ind:textfilecontent54_object>
 </def-group>
```

**Comment by dirtyharrycallahan** [comment]
This is really a puppet question. Manage the entire crontab file as a single file, a concat, a define or via Augeas.

**Comment by dokuhebi** [comment]
Even though the remediation example gives a very specific example, the check itself really just looks to see that it's run once a day.  If the check can have leeway as to when it's run (which does have a slight impact), I don't see why it can't pass whether or not root is explicitly entered (which has no impact).

**Comment by redhatrises** [comment]
> I'm using puppet to create the cron, and even though I have the cron config to use the "root" user

Where is the cron job being configured?

> I don't see why it can't pass whether or not root is explicitly entered (which has no impact).

Because depending on where/how the cron job is configured, the cron will not run without a user specified. Since the check is looking at `/etc/crontab` and any file in the `/etc/cron.d` directory, a user is required or the cron will not run with an error `(CRON) bad username` in `/var/log/cron`

**Comment by dirtyharrycallahan** [comment]
I think the opening comment is wrong. I believe that your puppet cron module is probably writing to /var/spool/cron. Cron entries in /etc/crontab (file) and /etc/cron.d (directory) have a different format than the files in /var/spool/cron. There are three ways to solve this problem:
1. Don't use the puppet cron module
2. Modify the aide check to also check /var/spool/cron/root for the aide entry.
3. Override the check

**Comment by dokuhebi** [comment]
@dirtyharrycallahan I'm not an expert, but it looks as though the scan is looking at both locations in the code.

https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/oval/aide_periodic_cron_checking.xml

**Comment by dokuhebi** [comment]
@redhatrises The file being edited by puppet is /var/spool/cron/root
```
# HEADER: This file was autogenerated at Fri Mar 20 09:50:33 -0400 2015 by puppet.
# HEADER: While it can still be managed manually, it is definitely not recommended.
# HEADER: Note particularly that the comments starting with 'Puppet Name' should
# HEADER: not be deleted, as doing so could cause duplicate cron jobs.
# Puppet Name: aide
5 4 * * * /usr/sbin/aide --check
```

However, as recommended by @dirtyharrycallahan, I'll probably use augeus to write a line to /etc/crontab.  I think the check should be looking at the /var/spool/cron/root as well.

**Comment by redhatrises** [comment]
@dokuhebi the AIDE periodic checking is looking at ```/etc/crontab``` and ```/etc/cron.d```. It is not looking at ```/var/spool/cron/root``` which is probably the main reason that you are seeing the check fail.

**Comment by redhatrises** [comment]
Closing this issue and opened #511 to accurately reflect what needs to be fixed. Referenced this PR as well.
