### ISSUE TITLE
Notification of duplicate IDs when running 'make' for Fedora and RHEL 6 & 7.

### ISSUE THREAD

**Issue by redhatrises** [OpenSCAP/scap-security-guide#50]
Output of duplicate ID usage notification below when running `make` for Fedora and RHEL 6 & 7. Should be investigated, and if necessary, patch created.

Notification: this ID is used more than once and should represent equivalent elements: login_banner_text
Notification: this ID is used more than once and should represent equivalent elements: test_unix_family
Notification: this ID is used more than once and should represent equivalent elements: state_unix_family
Notification: this ID is used more than once and should represent equivalent elements: obj_unix_family
Notification: this ID is used more than once and should represent equivalent elements: test_rhel_workstation
Notification: this ID is used more than once and should represent equivalent elements: state_rhel_workstation
Notification: this ID is used more than once and should represent equivalent elements: obj_rhel_workstation
Notification: this ID is used more than once and should represent equivalent elements: test_rhel_server
Notification: this ID is used more than once and should represent equivalent elements: state_rhel_server
Notification: this ID is used more than once and should represent equivalent elements: obj_rhel_server
Notification: this ID is used more than once and should represent equivalent elements: var_accounts_user_umask
Notification: this ID is used more than once and should represent equivalent elements: var_accounts_user_umask
Notification: this ID is used more than once and should represent equivalent elements: var_accounts_user_umask

**Comment by yuumasato** [comment]
Notification messages have changed in ce5dbab78a162c5d2676a50d8967aae90a36513c, below is a sample of how they look now:

WARNING: OVAL ID 'object_multi_user_target_for_sssd' is used multiple times and should represent the same elements.
Rewrite the OVAL checks. Place the identical IDs into their own definition and extend this definition by it.
WARNING: OVAL ID 'test_screensaver_lock_delay' is used multiple times and should represent the same elements.
Rewrite the OVAL checks. Place the identical IDs into their own definition and extend this definition by it.
WARNING: OVAL ID 'obj_screensaver_lock_delay' is used multiple times and should represent the same elements.
Rewrite the OVAL checks. Place the identical IDs into their own definition and extend this definition by it.
