### ISSUE TITLE
Modprobe is better disabled by using /bin/true (not /bin/false)

### ISSUE THREAD

**Issue by isimluk** [OpenSCAP/scap-security-guide#539]
There are rules to disable particular kernel modules (like usb-storage). This is achieved by running following remediation:
```
echo "install usb-storage /bin/false" > /etc/modprobe.d/usb-storage.conf
````
The `/bin/false` command returns non-zero, hence the loader may log this event as an error. To avoid log errors, we should advise users to use `/bin/true` instead.

The OVAL should remain unchanged. Only remediation instruction and the prose needs to be amended.

**Comment by shawndwells** [comment]
>From kmod.c:
`````
        setenv("MODPROBE_MODULE", modname, 1);
        ret = system(cmd);
        unsetenv("MODPROBE_MODULE");
        if (ret == -1 || WEXITSTATUS(ret)) {
                LOG("Error running %s command for %s\n", type, modname);
`````
(thanks to steve grubb for code snippet)

**Comment by shawndwells** [comment]
will take this - in the code right now anyway

**Comment by redhatrises** [comment]
@shawndwells what about the changes to `fixes/bash` for this as well (referenced in the ticket)?

**Comment by shawndwells** [comment]
hah, good catch. PR updated!
