### ISSUE TITLE
Since the latest commits, scap-security-guide won't build

### ISSUE THREAD

**Issue by autonomicpilot** [OpenSCAP/scap-security-guide#569]
[weiss@buildhost oscap_content]$ git clone https://github.com/OpenSCAP/scap-security-guide.git
Initialized empty Git repository in /home/weiss/scan_scripts/oscap_content/scap-security-guide/.git/
remote: Counting objects: 35474, done.
remote: Compressing objects: 100% (61/61), done.
remote: Total 35474 (delta 35), reused 2 (delta 2), pack-reused 35411
Receiving objects: 100% (35474/35474), 10.30 MiB | 3.17 MiB/s, done.
Resolving deltas: 100% (26000/26000), done.
[weiss@buildhost oscap_content]$ cd scap-security-guide/
[weiss@buildhost scap-security-guide]$ make rhel5 rhel6 rhel7
cd RHEL/5/ && make
make[1]: Entering directory `/home/weiss/scan_scripts/oscap_content/scap-security-guide/RHEL/5'
xsltproc -o output/rhel5-shorthand.xml input/guide.xslt input/guide.xml
xmllint --format --output output/rhel5-shorthand.xml output/rhel5-shorthand.xml
xsltproc -o output/unlinked-unresolved-rhel5-xccdf.xml transforms/shorthand2xccdf.xslt output/rhel5-shorthand.xml
oscap xccdf resolve -o output/unlinked-rhel5-xccdf.xml output/unlinked-unresolved-rhel5-xccdf.xml
xsltproc -o output/unlinked-rhel5-ocil.xml transforms/xccdf-create-ocil.xslt output/unlinked-rhel5-xccdf.xml
xmllint --format --output output/unlinked-rhel5-ocil.xml output/unlinked-rhel5-ocil.xml
xsltproc -o output/unlinked-ocilrefs-rhel5-xccdf.xml transforms/xccdf-ocilcheck2ref.xslt output/unlinked-rhel5-xccdf.xml
../../shared/transforms/combinefixes.py input/fixes/bash/ output/bash-remediations.xml
xsltproc -stringparam fixes "../output/bash-remediations.xml" -o output/unlinked-rhel5-xccdf.xml transforms/xccdf-addfixes.xslt output/unlinked-rhel5-xccdf.xml
xmllint --format --output output/unlinked-rhel5-xccdf.xml output/unlinked-rhel5-xccdf.xml
xsltproc -stringparam ref "nist" -o output/table-rhel5-nistrefs.html transforms/xccdf2table-byref.xslt output/unlinked-rhel5-xccdf.xml
xsltproc -stringparam profile "common" -o output/table-rhel5-nistrefs-common.html \
		transforms/xccdf2table-profilenistrefs.xslt output/unlinked-rhel5-xccdf.xml
xsltproc -o output/table-rhel5-cces.html transforms/xccdf2table-cce.xslt output/unlinked-rhel5-xccdf.xml
xsltproc -stringparam map-to-items "../output/unlinked-rhel5-xccdf.xml" -o output/table-rhel5-srgmap.html \
		transforms/table-srgmap.xslt ../../shared/references/disa-os-srg-v1r1.xml
xsltproc -stringparam flat "y" -stringparam map-to-items "../output/unlinked-rhel5-xccdf.xml" -o output/table-rhel5-srgmap-flat.html \
		transforms/table-srgmap.xslt ../../shared/references/disa-os-srg-v1r1.xml
xmllint --xmlout --html --output output/table-rhel5-srgmap-flat.xhtml output/table-rhel5-srgmap-flat.html
xmlwf input/checks/*.xml
../../shared/transforms/combinechecks.py ../../config rhel5 input/checks > output/unlinked-rhel5-oval.xml

Notification: Merged 518 OVAL checks into OVAL document.
Notification: this ID is used more than once and should represent equivalent elements: object_systemauthac_not_included
xmllint --format --output output/unlinked-rhel5-oval.xml output/unlinked-rhel5-oval.xml
xsltproc -o output/table-rhel5-stig.html transforms/xccdf2table-stig.xslt ../../shared/references/disa-stig-rhel5-v1r0.6-xccdf.xml
xsltproc -o output/table-rhel5-stig-manual.html transforms/xccdf2table-stig.xslt ../../shared/references/disa-stig-rhel5-v1r0.6-xccdf-manual.xml
xsltproc -stringparam profile "stig-rhel5-server-upstream" -stringparam testinfo "y" -o output/table-stig-rhel5-testinfo.html \
		transforms/xccdf2table-profileccirefs.xslt \
		output/unlinked-rhel5-xccdf.xml
xsltproc -stringparam overlay "../input/auxiliary/stig_overlay.xml" -o output/unlinked-stig-rhel5-xccdf.xml \
		transforms/xccdf-apply-overlay-stig.xslt \
		output/unlinked-rhel5-xccdf.xml
xsltproc -o output/table-rhel5-stig.html transforms/xccdf2table-stig.xslt output/unlinked-stig-rhel5-xccdf.xml
xsltproc -o output/unlinked-rhel5-xccdf-guide.xml transforms/xccdf-removeaux.xslt output/unlinked-rhel5-xccdf.xml
xsltproc -o output/unlinked-notest-rhel5-xccdf-guide.xml transforms/xccdf-removetested.xslt output/unlinked-rhel5-xccdf-guide.xml
oscap xccdf generate guide --profile allrules output/unlinked-notest-rhel5-xccdf-guide.xml > output/rhel5-guide.html
xsltproc -o output/rhel5-guide-custom.html transforms/xccdf2html.xslt output/unlinked-notest-rhel5-xccdf-guide.xml
../../shared/transforms/cpe_generate.py output/unlinked-rhel5-oval.xml input/checks/platform/rhel5-cpe-dictionary.xml ssg
../../shared/transforms/cpe_generate.py:89: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
  if variables:
../../shared/transforms/relabelids.py unlinked-rhel5-xccdf.xml ssg
../../shared/transforms/relabelids.py unlinked-ocilrefs-rhel5-xccdf.xml ssg
xsltproc /usr/share/openscap/xsl/xccdf_1.1_remove_dangling_sub.xsl output/ssg-rhel5-xccdf.xml \
		> output/ssg-rhel5-xccdf-nodangles.xml
xsltproc --stringparam reverse_DNS org.ssgproject.content /usr/share/openscap/xsl/xccdf_1.1_to_1.2.xsl \
		output/ssg-rhel5-xccdf-nodangles.xml > output/ssg-rhel5-xccdf-1.2.xml
sed -i '/idref="dangling reference to /d' output/ssg-rhel5-xccdf-1.2.xml
oscap ds sds-compose output/ssg-rhel5-xccdf-1.2.xml output/ssg-rhel5-ds.xml
oscap ds sds-add output/ssg-rhel5-cpe-dictionary.xml output/ssg-rhel5-ds.xml
oscap ds sds-add output/ssg-rhel5-oval.xml output/ssg-rhel5-ds.xml
../../shared/utils/enable-centos.py output/ssg-rhel5-xccdf.xml output/ssg-centos5-xccdf.xml
Traceback (most recent call last):
  File "../../shared/utils/enable-centos.py", line 170, in <module>
    main()
  File "../../shared/utils/enable-centos.py", line 148, in main
    for elem in list(tree.iter("{%s}Benchmark" % (XCCDF11_NS)))
AttributeError: ElementTree instance has no attribute 'iter'
make[1]: *** [content] Error 1
make[1]: Leaving directory `/home/weiss/scan_scripts/oscap_content/scap-security-guide/RHEL/5'
make: *** [rhel5] Error 2

**Comment by shawndwells** [comment]
@mpreisler found this, should be resolved with PR https://github.com/OpenSCAP/scap-security-guide/pull/568. Affects when building with legacy versions of python.

**Comment by shawndwells** [comment]
merged https://github.com/OpenSCAP/scap-security-guide/pull/568, appears to resolve this. Please reopen if still having issues!
