### ISSUE TITLE
Remediations rely on the functions script absolute path

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/scap-security-guide#590]
The remediations only work if the functions script is installed system-wide at a fixed location.

This breaks a lot of use-cases where the tools will push content to remote locations, such as `oscap-ssh` and `foreman scap integration`.

Fix proposal:
Add <xccdf:Value> that holds the source code of the functions script and possibly more such scripts and then use <xccdf:sub> in the <fix> elements themselves. I haven't tested it but I don't see why it shouldn't work.

**Comment by fcaviggia** [comment]
Martin,

Some code that I've used in my bash scripts to determine where they're at...

# Determine the Path
function realpath() {
    local r=$1; local t=$(readlink $r)
    while [ $t ]; do
        r=$(cd $(dirname $r) && cd $(dirname $t) && pwd -P)/$(basename $t)
        t=$(readlink $r)
    done
    echo $r
}

BASE_DIR=`dirname $(realpath $0)`

**Comment by mpreisler** [comment]
Hi @fcaviggia !

I now realize I didn't do a good job explaining the issue. The issue isn't in figuring out the real path, it is in relying on a file installed in any particular path. This means that tools such as SCAP Workbench, oscap-ssh, Satellite 6, etc... cannot push local content to remote machine and then use it. The remediations on the remote machine will only work if the remote machine has the bash script installed at the expected location.

**Comment by isimluk** [comment]
FYI: not related to foreman. Foreman is not allowed to do remediation ATM.

**Comment by shawndwells** [comment]
On 7/1/15 8:52 AM, Martin Preisler wrote:
>
> Hi @fcaviggia <https://github.com/fcaviggia> !
>
> I now realize I didn't do a good job explaining the issue. The issue 
> isn't in figuring out the real path, it is in relying on a file 
> installed in any particular path. This means that tools such as SCAP 
> Workbench, oscap-ssh, Satellite 6, etc... cannot push local content to 
> remote machine and then use it. The remediations on the remote machine 
> will only work if the remote machine has the bash script installed at 
> the expected location.
>

Took me a minute to remember that SCAP Workbench and associated tools 
move only the SCAP files around. While certain XCCDF rules have <fix> 
tag elements, the "helper scripts" are installed on the system 
separately during the RPM installation. Having things placed into an 
xccdf:Value makes a lot of sense.

**Comment by mpreisler** [comment]
Moved this to 0.1.25

It's too late to get this done for 0.1.24 and it's a big change with potential to break all remediation scripts. It's better to do it early in the 0.1.25 cycle IMO.

**Comment by mpreisler** [comment]
This has been fixed with PR #1270
