### ISSUE TITLE
accounts_passwords_pam_faillock_unlock_time OVAL incomplete

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#6]
Check returns a fail when it should pass showing an unlock time of 604800
Check looks for “auth sufficient” rather than the “auth [default=die]” listed in the STIG.  
It does detect “auth sufficient” properly it just is the wrong system variable to be checking.

**Comment by redhatrises** [comment]
This should be fixed with the merging of #555.
