### ISSUE TITLE
Remove "documentation" rules

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/scap-security-guide#617]
Scap security guide contains some rules that are not useful for security compliance. They are there only for documentation purposes. For example rules with IDs: met_inherently_generic, met_inherently_auditing, met_inherently_nonselected, unmet_nonfinding_nonselected_scope, ...
I think we should remove these rules from the content.

**Comment by shawndwells** [comment]
They're used in building the various policy mapping tables, which are the spreadsheet-esque style that our government partners work from. We (even now) need them.

With that said, they don't show up in the HTML report anymore. Is this still an issue?

**Comment by redhatrises** [comment]
Closing. These don't show up in the HTML report but are used in mapping tables.
