### ISSUE TITLE
scap-security-guide release version 0.1.24 zip content may be corrupted

### ISSUE THREAD

**Issue by redhatrises** [OpenSCAP/scap-security-guide#620]
@cliffbdf opened a ticket as this is more visible and better than commenting on a closed pull request.

New to scap - tried running the profile for Centos7

(from https://github.com/OpenSCAP/scap-security-guide/releases/download/v0.1.24/scap-security-guide-0.1.24.zip)

and it fails with lots of errors similar to,
File 'scap/scap-security-guide-0.1.24/ssg-centos7-ds.xml' line 34925: Element '{http://oval.mitre.org/XMLSchema/oval-definitions-5}object_component': No match found for key-sequence ['oval:ssg:obj:1231'] of keyref '{http://oval.mitre.org/XMLSchema/oval-definitions-5}objectKeyRef'.

Any ideas on what I am doing wrong? I ran with --cpe /usr/share/openscap/cpe/openscap-cpe-dict.xml

I also ran a "oscap xccdf validate on the ssg-centos7-ds.xml" file and it said that http://scap.nist.gov/schema/scap/source/1.2 is not a known XCCDF namespace, and indeed that URL does not exist.

**Comment by redhatrises** [comment]
@cliffbdf will you provide what version of openscap you are using in centos7 as well as the exact command that you are running?

**Comment by cliffbdf** [comment]
Hi -

I had installed it using yum just the other day. I just ran oscap —version and this is what it gave me:

[vagrant@localhost vagrant]$ oscap --version
OpenSCAP command line tool (oscap) 1.1.1
Copyright 2009--2014 Red Hat Inc., Durham, North Carolina.

==== Supported specifications ====
XCCDF Version: 1.2
OVAL Version: 5.10.1
CPE Version: 2.3
CVSS Version: 2.0
CVE Version: 2.0
Asset Identification Version: 1.1
Asset Reporting Format Version: 1.1

==== Capabilities added by auto-loaded plugins ====
No plugins have been auto-loaded...

==== Paths ====
Schema files: /usr/share/openscap/schemas
Default CPE files: /usr/share/openscap/cpe
Probes: /usr/libexec/openscap

==== Inbuilt CPE names ====
Red Hat Enterprise Linux - cpe:/o:redhat:enterprise_linux
Red Hat Enterprise Linux 5 - cpe:/o:redhat:enterprise_linux:5
Red Hat Enterprise Linux 6 - cpe:/o:redhat:enterprise_linux:6
Red Hat Enterprise Linux 7 - cpe:/o:redhat:enterprise_linux:7
Community Enterprise Operating System 5 - cpe:/o:centos:centos:5
Community Enterprise Operating System 6 - cpe:/o:centos:centos:6
Community Enterprise Operating System 7 - cpe:/o:centos:centos:7
Fedora 16 - cpe:/o:fedoraproject:fedora:16
Fedora 17 - cpe:/o:fedoraproject:fedora:17
Fedora 18 - cpe:/o:fedoraproject:fedora:18
Fedora 19 - cpe:/o:fedoraproject:fedora:19
Fedora 20 - cpe:/o:fedoraproject:fedora:20
Fedora 21 - cpe:/o:fedoraproject:fedora:21
Fedora 22 - cpe:/o:fedoraproject:fedora:22
Red Hat Enterprise Linux Optional Productivity Applications - cpe:/a:redhat:rhel_productivity
Red Hat Enterprise Linux Optional Productivity Applications 5 - cpe:/a:redhat:rhel_productivity:5

==== Supported OVAL objects and associated OpenSCAP probes ====
system_info                  probe_system_info           
family                       probe_family                
filehash                     probe_filehash              
environmentvariable          probe_environmentvariable   
textfilecontent54            probe_textfilecontent54     
textfilecontent              probe_textfilecontent       
variable                     probe_variable              
xmlfilecontent               probe_xmlfilecontent        
environmentvariable58        probe_environmentvariable58 
filehash58                   probe_filehash58            
inetlisteningservers         probe_inetlisteningservers  
rpminfo                      probe_rpminfo               
partition                    probe_partition             
iflisteners                  probe_iflisteners           
rpmverify                    probe_rpmverify             
rpmverifyfile                probe_rpmverifyfile         
rpmverifypackage             probe_rpmverifypackage      
selinuxboolean               probe_selinuxboolean        
selinuxsecuritycontext       probe_selinuxsecuritycontext
systemdunitproperty          probe_systemdunitproperty   
systemdunitdependency        probe_systemdunitdependency 
file                         probe_file                  
interface                    probe_interface             
password                     probe_password              
process                      probe_process               
runlevel                     probe_runlevel              
shadow                       probe_shadow                
uname                        probe_uname                 
xinetd                       probe_xinetd                
sysctl                       probe_sysctl                
process58                    probe_process58             
fileextendedattribute        probe_fileextendedattribute 
routingtable                 probe_routingtable          
[vagrant@localhost vagrant]$ 


Best regards,

Cliff

**Comment by redhatrises** [comment]
@cliffbdf how did you run your scan? For example: 
```
oscap xccdf eval --profile rht-cpp --cpe /usr/share/xml/scap/ssg/content/ssg-rhel7-cpe-dictionary.xml /usr/share/xml/scap/ssg/content/ssg-rhel7-xccdf.xml
```

**Comment by cliffbdf** [comment]
oscap xccdf eval --results xccdf-results.xml --cpe /usr/share/openscap/cpe/openscap-cpe-dict.xml scap/scap-security-guide-0.1.24/ssg-centos7-ds.xml

**Comment by redhatrises** [comment]
@cliffbdf you need to select a profile. 

To view a set of profiles associated with a datastream, run ```oscap info scap/scap-security-guide-0.1.24/ssg-centos7-ds.xml``` which will display a set of profiles to check the system against. Then run, for example, ```oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_stig-rhel7-server-upstream --results xccdf-results.xml scap/scap-security-guide-0.1.24/ssg-centos7-ds.xml```

Or if you are wanting to run the the check against the XCCDF xml content, run ```oscap info scap/scap-security-guide-0.1.24/ssg-centos7-xccdf.xml``` which will display a set of profiles to check the system against. Then run, for example, ```oscap xccdf eval --profile stig-rhel7-server-upstream --results xccdf-results.xml --cpe /usr/share/openscap/cpe/openscap-cpe-dict.xml  scap/scap-security-guide-0.1.24/ssg-centos7-xccdf.xml```

Add the ```--report``` option for a nice human readable html results file (if so desired). Also are you wanting to run the scan off of a datastream (*-ds.xml files)?

**Comment by cliffbdf** [comment]
This looks promising. I actually did a grep for profiles but found none because my grep did not account for the namespace before “Profile” (!)  I have to jump on a call now but I will try this asap! Thanks!!!

**Comment by cliffbdf** [comment]
Hi -

I tried this and the same errors persist. Here is the first few lines of stderr:

OpenSCAP Error: File 'scap/scap-security-guide-0.1.24/ssg-centos7-ds.xml' line 3953: Element '{http://oval.mitre.org/XMLSchema/ova
l-definitions-5#linux}systemdunitdependency_test': This element is not expected.
 [xccdf_session.c:342]
File 'scap/scap-security-guide-0.1.24/ssg-centos7-ds.xml' line 5339: Element '{http://oval.mitre.org/XMLSchema/oval-definitions-5#
linux}systemdunitdependency_object': This element is not expected.
 [xccdf_session.c:342]

I listed the profiles and used “xccdf_org.ssgproject.content_profile_common”

Please note that the oscap validate fails, with this error:

[vagrant@localhost vagrant]$ oscap xccdf validate scap/scap-security-guide-0.1.24/ssg-centos7-ds.xml
OpenSCAP Error: This is not known XCCDF namespace: http://scap.nist.gov/schema/scap/source/1.2. [elements.c:101]

Does this give a clue?

Cliff

**Comment by redhatrises** [comment]
> I tried this and the same errors persist.
What did you try?

The validate command that you are using is not for datastream files which is what you are testing  against. To validate datastream files, run ```oscap ds sds-validate ssg-centos7-ds.xml``` To validate XCCDF content, run ```oscap xccdf validate ssg-centos7-xccdf.xml```.

**Comment by cliffbdf** [comment]
Ah, ok.

I ran the validate on the data stream and this is the first few lines of the output:

[vagrant@localhost vagrant]$ oscap ds sds-validate scap/scap-security-guide-0.1.24/ssg-centos7-ds.xml
File 'scap/scap-security-guide-0.1.24/ssg-centos7-ds.xml' line 3953: Element '{http://oval.mitre.org/XMLSchema/oval-definitions-5#linux}systemdunitdependency_test': This element is not expected.
File 'scap/scap-security-guide-0.1.24/ssg-centos7-ds.xml' line 5339: Element '{http://oval.mitre.org/XMLSchema/oval-definitions-5#linux}systemdunitdependency_object': This element is not expected.
File 'scap/scap-security-guide-0.1.24/ssg-centos7-ds.xml' line 7248: Element '{http://oval.mitre.org/XMLSchema/oval-definitions-5#


- Cliff

**Comment by redhatrises** [comment]
If you run ```oscap xccdf eval --profile common --results xccdf-results.xml --cpe /usr/share/openscap/cpe/openscap-cpe-dict.xml scap/scap-security-guide-0.1.24/ssg-centos7-xccdf.xml``` do you get the same thing?

**Comment by cliffbdf** [comment]
I am actually not sure where to get ssg-centos7-xccdf.xml. It was not in the scap-security-guide-0.1.24 archive that I downloaded from https://github.com/OpenSCAP/scap-security-guide/releases <https://github.com/OpenSCAP/scap-security-guide/releases>

**Comment by redhatrises** [comment]
Thanks. Just tried that content as well and it appears corrupted. Thanks for reporting! @iankko @mpreisler thoughts? Also, why is there only datastream content?

**Comment by cliffbdf** [comment]
My pleasure. I am very anxious to be able to run a scap test. Please keep me in the loop so that I know when it has been fixed. Thanks!!!!!!!

**Comment by redhatrises** [comment]
@cliffbdf you can also build from source if you want to be able to test sooner.

**Comment by cliffbdf** [comment]
Thanks but I’ll wait for the “binary” - even though the makefile looks straightforward, I am new to scap and so I will likely misunderstand some of the flags/switches/env settings.

**Comment by redhatrises** [comment]
```make rpm``` will get you that binary rpm without having to set flags/switches.

**Comment by cliffbdf** [comment]
Ok I built it (on Centos), and it ran for a long time and ended with process status 0, and it created a directory called “rpmbuild”, but I did a recursive search in there and did not find a ssg-centos7-xccdf.xml, or even a ssg-centos7-ds.xml. An rpm was also generated so I installed that. Please forgive me for being a newbie with openscap - am I missing something here? Is the ssg-centos7-xccdf.xml right in front of me and I am not seeing it?

Cliff

**Comment by redhatrises** [comment]
No worries. When you install the rpm, the xml content exists under ```/usr/share/xml/scap/ssg/content```, so now, just use the path like so ```/usr/share/xml/scap/ssg/content/ssg-centos7-xccdf.xml```

**Comment by cliffbdf** [comment]
Well here is the situation:

There is no ssg-centos-xccdf.xml in /usr/share/xml/scap/ssg/content/. All I see there is:

ssg-rhel6-ds.xml
ssg-rhel7-cpe-dictionary.xml
ssg-rhel7-cpe-oval.xml
ssg-rhel7-ds.xml
ssg-rhel7-oval.xml
ssg-rhel7-xccdf.xml

And when I run oscap info on ssg-rhel7-xccdf.xml this is what I see:

[vagrant@localhost SRPMS]$ oscap info /usr/share/xml/scap/ssg/content/ssg-rhel7-xccdf.xml
Document type: XCCDF Checklist
Checklist version: 1.1
Status: draft
Generated: 2015-03-06
Imported: 2015-03-06T05:30:32
Resolved: true
Profiles:
	rht-ccp
Referenced check files:
	ssg-rhel7-oval.xml
		system: http://oval.mitre.org/XMLSchema/oval-definitions-5

So the only profile seems to be "rht-ccp”.

Nevertheless, when I run it, using —cpe ssg-rhel7-cpe-dictionary.xml,

oscap xccdf eval --profile rht-ccp --results xccdf-results.xml --report report.xml --cpe /usr/share/xml/scap/ssg/content/ssg-rhel7-cpe-dictionary.xml /usr/share/xml/scap/ssg/content/ssg-rhel7-xccdf.xml

it appears to work.

But it is not a centos xccdf and I am not sure what the profile “rht-ccp” is and whether it is appropriate for my system.

Cliff

**Comment by cliffbdf** [comment]
Please ignore my last email. I had installed the wrong rpm - I just noticed that after building from source I installed the rpm with “src” in its name. I removed it and installed,

scap-security-guide-0.1.24-1.el7.centos.noarch.rpm

and now I have these files in /usr/share/xml/scap/ssg/content,

eap5-cpe-dictionary.xml  ssg-firefox-cpe-dictionary.xml  ssg-jre-xccdf.xml             ssg-rhel7-oval.xml
eap5-cpe-oval.xml        ssg-firefox-cpe-oval.xml        ssg-rhel6-cpe-dictionary.xml  ssg-rhel7-xccdf.xml
eap5-ocil.xml            ssg-firefox-ds.xml              ssg-rhel6-cpe-oval.xml        ssg-sl6-ds.xml
eap5-oval.xml            ssg-firefox-oval.xml            ssg-rhel6-ds.xml              ssg-sl6-xccdf.xml
eap5-xccdf.xml           ssg-firefox-xccdf.xml           ssg-rhel6-oval.xml            ssg-sl7-ds.xml
ssg-centos6-ds.xml       ssg-jre-cpe-dictionary.xml      ssg-rhel6-xccdf.xml           ssg-sl7-xccdf.xml
ssg-centos6-xccdf.xml    ssg-jre-cpe-oval.xml            ssg-rhel7-cpe-dictionary.xml
ssg-centos7-ds.xml       ssg-jre-ds.xml                  ssg-rhel7-cpe-oval.xml
ssg-centos7-xccdf.xml    ssg-jre-oval.xml                ssg-rhel7-ds.xml

So I ran oscap with,

oscap xccdf eval --profile rht-ccp --results xccdf-results.xml --report report.xml --cpe /usr/share/xml/scap/ssg/content/eap5-cpe-dictionary.xml /usr/share/xml/scap/ssg/content/ssg-centos7-xccdf.xml

and it looks like it worked!

Thanks!

Very best regards,

Cliff

PS - I am not sure that I used the right dictionary file however, in the —cpe option.

**Comment by cliffbdf** [comment]
I see now that eap5-cpe-dictionary.xml is for jboss boxes. So I re-ran with —cpe ssg-rhel7-cpe-dictionary.xml. All of the results are “notapplicable”. I looked at the dictionary file and there is an entry for centos7, but it references "http://oval.mitre.org/XMLSchema/oval-definitions-5”, but if I go to that URL it redirects me to a MITRE web page - not an XML resource. I am sure I don’t know what is going on here, being new to this, but it looks strange to me. Probably my ignorance.

- Cliff

**Comment by mpreisler** [comment]
Hi. Let me go back to the release ZIP. I downloaded it, extracted, ran `oscap ds sds-validate` on all the datastreams. No issues encountered. Tested with OpenSCAP 1.2.4. Keep in mind that the files extracted are datastreams, not XCCDFs!

You do not need to pass `--cpe` with datastreams, this is handled for you automatically :-) All CPEs inside the datastream are registered when the datastream is loaded.

**Comment by cliffbdf** [comment]
Thank you Martin. I will try it again. - Cliff

**Comment by redhatrises** [comment]
@mpreisler @iankko looks like the issue can be reproduced if generating the content on a Fedora box and then trying to run that content on a RHEL/CentOS box with OpenSCAP 1.1.1 installed. OVAL 5.11 vs OVAL 5.10.1 issue?

**Comment by mpreisler** [comment]
> @mpreisler @iankko looks like the issue can be reproduced if generating the content on a Fedora box and then trying to run that content on a RHEL/CentOS box with OpenSCAP 1.1.1 installed. OVAL 5.11 vs OVAL 5.10.1 issue?

Confirmed. You need `OpenSCAP 1.2.4` or newer to use the datastreams in the ZIP because they were generated to use `OVAL 5.11`.

Either build OpenSCAP yourself or use Simon's COPR - https://copr.fedoraproject.org/coprs/isimluk/OpenSCAP/

**Comment by cliffbdf** [comment]
Guys - where do I get version 1.2.4? I just did a yum update oscap-utils and it says it is up to date and I have version 1.1.1.

**Comment by mpreisler** [comment]
> Either build OpenSCAP yourself or use Simon's COPR - https://copr.fedoraproject.org/coprs/isimluk/OpenSCAP/

**Comment by cliffbdf** [comment]
Guys - a question - why is version 1.2.4 unofficial, especially if one needs it to run the current user guide profiles? (I want to make sure that I use the appropriate stuff.)

Also, thanks greatly for your help in this.

Cliff

**Comment by mpreisler** [comment]
> Guys - a question - why is version 1.2.4 unofficial, especially if one needs it to run the current user guide profiles? (I want to make sure that I use the appropriate stuff.) Also, thanks greatly for your help in this. Cliff

`OpenSCAP 1.2.4` is an official upstream release. There is even one release newer than that, `1.2.5`. You probably mean why isn't it packaged everywhere right now. That is a complicated question that I won't answer here. Usually upstream releases the updates first, then downstreams pick it up and package it for the distributions. Downstream versions always lag behind because there are extra steps involved.

You can read about this if you search for "upstream downstream relationship open source".

**Comment by cliffbdf** [comment]
Thanks. This is good stuff - just trying to understand what’s what! - Cliff
