### ISSUE TITLE
[RFE] Fix and document usage of the pre-built SSG Zip archive

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-security-guide#622]
As pointed out in:
  https://github.com/OpenSCAP/scap-security-guide/issues/620#issuecomment-124450492

users are experiencing issue trying to use the pre-built / Zip SCAP Security Guide content:
  https://github.com/OpenSCAP/scap-security-guide/releases/download/v0.1.24/scap-security-guide-0.1.24.zip

While the Zip archive contains all the datastreams, and even a README.md file, it doesn't contain information how the datastream files are expected to be used.

Therefore enhance currently existing README.md file in the Zip archive with the information, how to run the system scans e.g. using the OpenSCAP scanner.

Giving to Martin, since he produced the 0.1.24 Zip archive && is aware of the tools used to generate it (=> the new guide to be included into that workflow).

**Comment by mpreisler** [comment]
I broke this with the cmake build system change. I will fix this for 0.1.32 and mention the zip archives in README.md.
