### ISSUE TITLE
Wrong NIST reference in rule root_path_no_groupother_writable

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/scap-security-guide#626]
The reference in rule "root_path_no_groupother_writable" is empty, which causes displaying URL "http://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-53r4.pdf" in HTML report. 
I think we should either put an ID there or remove the <reference> tag.

**Comment by shawndwells** [comment]
Now has NIST ref via commit 608ab239. Resolving.
