### ISSUE TITLE
Start producing two versions of SSG Zip archive -- one for OVAL-5.10.1 and one for OVAL-5.11

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-security-guide#655]
As reported in:
&nbsp; &nbsp; [1] https://lists.fedorahosted.org/pipermail/scap-security-guide/2015-August/006576.html

the currently produced version of SSG Zip archive is built with most recent openscap version from Simon's COP repo (therefore producing OVAL-5.11 as final OVAL document version). This leads (between others) into impossibility to load the produced DataStream documents in former (OVAL-5.10.1 supporting only) ```oscap / scap-workbench``` versions.

But SSG supports building of all content with both OVAL versions. It depends solely on the version of the underlying ```oscap``` command (more exactly on the OVAL version that ```oscap``` command supports). In case only OVAL-5.10.1 is supported, final OVAL document is of OVAL-5.10 version (and OVAL-5.11 checks simply aren't included). If underlying ```oscap``` supports OVAL-5.11 already, the final produced OVAL document is of OVAL-5.11 version already (and all checks, including the 5.11 specific ones are included in the content).

Therefore for now, when producing the SSG Zip archive we should consider producing DataStreams for both use cases / scenarios. E.g. having something like:

```unzip scap-security-guide-0.1.26.zip```
```ls scap-security-guide-0.1.26/```
```oval-5.10.1/ oval-5.11/```

And those two ```oval-5.10.1``` and oval-5.11``` folders would contain all benchmarks in DS format produced with corresponding ```oscap``` version (=> benchmark consumers could choose which version to use).

**Comment by mpreisler** [comment]
I have already fixed this and forgot to close this ticket. This has been fixed since `0.1.26` which unfortunately has no upstream milestone.
