### ISSUE TITLE
[Fedora] make validate currently fails on Fedora 22 system

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-security-guide#661]
```make validate``` target currently fails on Fedora 22 system:
```
$ make validate
oscap xccdf validate-xml output/ssg-fedora-xccdf.xml
oscap oval validate-xml --schematron output/ssg-fedora-oval.xml
oscap ds sds-validate output/ssg-fedora-ds.xml
cd input/fixes/bash; shellcheck -s bash *.sh
cd output; ../utils/verify-references.py --rules-with-invalid-checks --ovaldefs-unused ssg-fedora-xccdf.xml
Invalid OVAL definition referenced by XCCDF Rule: package_rsyslog_installed
Invalid OVAL definition referenced by XCCDF Rule: service_rsyslog_enabled
Invalid OVAL definition referenced by XCCDF Rule: rsyslog_send_messages_to_logserver
Invalid OVAL definition referenced by XCCDF Rule: rsyslog_accept_remote_messages_none
Invalid OVAL definition referenced by XCCDF Rule: ensure_logrotate_activated
Invalid OVAL definition referenced by XCCDF Rule: configure_logwatch_hostlimit
Invalid OVAL definition referenced by XCCDF Rule: configure_logwatch_splithosts
Makefile:89: recipe for target 'validate' failed
make: *** [validate] Error 1
```

All of the OVAL checks above are referenced by Fedora's ```input/system/logging.xml``` XML file, and the regression was introduced by the following mine change:

https://github.com/iankko/scap-security-guide/commit/010c81a3804e120111ac24ed63a6a828ff770412

Besides other changes, this change is switching on inclusion of ```Fedora/input/system/logging.xml``` file into ```Fedora/input/guide.xslt``` transformation (requesting the rsyslog section to be added for Fedora).

Since not all of the referenced OVAL checks are defined in Fedora yet, ```make validate``` fails.

I will fix this.

**Comment by redhatrises** [comment]
Ran `make validate`, and it passes. Re-open this issue if `make validate` in Fedora does not pass.
