### ISSUE TITLE
Remediation for RHEL7 disable_xinetd

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#715]

**Comment by redhatrises** [comment]
Looks like this is done already. Closing.

**Comment by shawndwells** [comment]
On 9/23/15 3:32 PM, redhatrises wrote:
>
> Looks like this is done already. Closing.
>

Many of these have remediation scripts (e.g. 
RHEL/7/input/fixes/bash/service_xinetd_disabled.sh does exist) but for 
whatever reason it isn't being linked into build.... could be XCCDF 
naming mismatch

**Comment by shawndwells** [comment]
On 9/23/15 3:36 PM, Shawn Wells wrote:
>
>
> On 9/23/15 3:32 PM, redhatrises wrote:
>>
>> Looks like this is done already. Closing.
>>
>
> Many of these have remediation scripts (e.g. 
> RHEL/7/input/fixes/bash/service_xinetd_disabled.sh does exist) but for 
> whatever reason it isn't being linked into build.... could be XCCDF 
> naming mismatch

for example, on this...

<Rule id="disable_xinetd" severity="medium">
<title>Disable xinetd Service</title>
<description>
<service-disable-macro service="xinetd" />
</description>
<ocil>
If network services are using the xinetd service, this is not applicable.
<br /><br />
<service-disable-check-macro service="xinetd" /></ocil>
<rationale>
The xinetd service provides a dedicated listener service for some programs,
which is no longer necessary for commonly-used network services. Disabling
it ensures that these uncommon services are not running, and also prevents
attacks against xinetd itself.
</rationale>
<ident cce="27443-1" />
<oval id="service_xinetd_disabled" />
<ref nist="AC-17(8),CM-7" disa="305"/>
<tested by="DS" on="20121026"/>
</Rule>


The remediation correctly matches the OVAL name, but the XCCDF is 
misaligned so the remediation isn't pulled in

**Comment by redhatrises** [comment]
Is it pulled in by the Rule or the oval id?

**Comment by shawndwells** [comment]
On 9/23/15 3:41 PM, redhatrises wrote:
> Is it pulled in by the Rule or the oval id?

XCCDF rule ID

https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/transforms/combinefixes.py#L43#L44

Takes the remediation script name (some-rule.sh), strips the .sh, and 
creates a <fix> tag for an XCCDF rule by the same name (some-rule)

In certain cases, like the xinetd, we'd want to rename the XCCDF rule to 
the service_blah_enabled/disabled vs changing OVAL/remediation names
