### ISSUE TITLE
Remediation for RHEL7 chronyd_or_ntpd_specify_remote_server

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#744]

**Comment by redhatrises** [comment]
@iankko @shawndwells Can a remediation script really be provided to specify remote time servers? This assumes that all users would have configured their ntpd or chronyd configurations that same way with the same server names no matter what type of operating environment. I am not sure that we can provide a remediation script for this. Thoughts?

**Comment by iankko** [comment]
@redhatrises 
> @iankko @shawndwells Can a remediation script really be provided to specify remote time servers? This assumes that all users would have configured their ntpd or chronyd configurations that same way with the same server names no matter what type of operating environment. I am not sure that we can provide a remediation script for this. Thoughts?

IMHO it's actually expected many / multiple systems from the same cluster to share the same (possibly vendor default) NTP servers. More details e.g. from v3.1 of the PCI DSS standard (https://www.pcisecuritystandards.org/documents/PCI_DSS_v3-1.pdf ) More from subsection ```10.4.1.a:```:

```
10.4.1.a
Examine the process for acquiring, distributing and storing the correct time within the organization to verify that: 
* Only the designated central time server(s)  receives time signals from external sources, and time signals from external sources are based on International Atomic Time or UTC.
* Where there is more than one designated time server, the  time servers peer with 
one another to keep accurate time, 
* Systems receive time information only from designated central time server(s)
```

To me the above implies what's important not being just time servers are configured, but that they also need to be standardized / vendor approved time servers. Of course there might be custom modification (for the case organization having their own particular time servers). But IMHO we can't do anything wrong in the case would the remediation script configure the ```ntp.conf``` / ```chrony.conf``` to time server values as provided by Red Hat (IOW use concrete ```*.rhel.pool.ntp.org``` for RHEL and ```*.fedora.pool.ntp.org``` as corresponding values for RHEL and Fedora servers respectively).

We might even consider adding a new rule checking if at least two of the configured NTP servers (either in ```ntp.conf``` or ```chrony.conf```) are those as provided by vendors (to satisfy that ```designated time servers``` requirement above).
