### ISSUE TITLE
[Enhancement] Unify OVAL directory naming convention

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-security-guide#771]
Currently SSG is using two different naming conventions for OVAL directories:
* ```shared/oval``` in shared/ directory, and
* ```input/checks``` name in per product directory (under ```Chromium```, ```Fedora```, ```Firefox```,  ```JRE```, ```OpenStack```, ```RHEL/5```, ```RHEL/6```, ```RHEL/7```,  ```RHEVM3```, and ```Webmin```).

This approach is causing confusion to possible contributors. Therefore the various OVAL directories naming scheme should be consistent (the same across all the different products).

The proposal is to rename all of the ```input/cheks``` directories (under products listed above) into ```input/oval``` directory.

But since additional functionality currently depends on these paths, it will not be sufficient just to rename these directories. Other changes like:
* modify main ```Makefile``` and per product ```Makefiles``` to properly cope with new ```input/oval``` directory will be required,
* also there's the ```combinechecsk.py``` Python script merging all particular OVAL scripts applicable to some product into one resulting OVAL file. It would make sense to rename this script to ```combineovals.py``` for the future (and change it that way everywhere it's used),
* couple of additional changes might be necessary too (to get the repository content work properly with the new ```input/oval``` directory per product like it is doing now).

**Comment by iankko** [comment]
@msrubar

Michal, can you possibly look at this issue && take it if interested?

Thanks, Jan.

**Comment by msrubar** [comment]
When working on this issue I found out that there are two files:
1. `Chromium/utils/verify-input-sanity.py`
2. `shared/utils/verify-input-sanity.py`
which have exactly the same content. What's the purpose behind this?

**Comment by iankko** [comment]
@msrubar 
> When working on this issue I found out that there are two files:
1. Chromium/utils/verify-input-sanity.py
2. shared/utils/verify-input-sanity.py
which have exactly the same content. What's the purpose behind this?

No purpose behind that. Just remainder of previous layout / content (in the past every product contained its own copies of every transformation script / utillity). We have tried to merge them & use ```shared/``` version where possible / discovered, but this one might fallen unnoticed.

If ```diff -s``` on those two files tells you they are truly identical, should be safe to remove the ```Chromium``` version, and keep just the ```shared/version``` (forwarding / pointing the former ```Chromium``` path to the ```shared/``` one).

Thanks, Jan.
