### ISSUE TITLE
[Bug] Using platform tag in the form of "# platform = Red Hat Enterprise Linux 7, multi_platform_fedora" does not include the remediation scripts into the final XCCDF

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-security-guide#778]
Description of problem:
------------------------------

This change is related with recent adding platform remediation script tag performed within:
&nbsp; &nbsp; [1] https://github.com/OpenSCAP/scap-security-guide/pull/768

The change works fine in general cases, but doesn't work (FWICT) when the following platform tag remediation script tag is used:
``` # platform = Red Hat Enterprise Linux 7, multi_platform_fedora```

and the particular remediation script is placed under the ```shared/fixes/bash``` location.

How reproducible:
------------------------
Always

Affected version:
---------------------
Current SSG master (as of 2015-10-06).

Steps to Reproduce:
--------------------------
1) Place some remediation script (intended for RHEL-7 and Fedora) products into ```shared/fixes/bash``` location,
2) Use / specify " # platform = Red Hat Enterprise Linux 7, multi_platform_fedora" as a platform tag for that remediation script (instructing the SSG build system to use that remediation script for both:
* RHEL-7 system,
* and currently supported Fedora systems.

Current result:
-------------------
Such a remediation script is NOT included into the produced ```ssg-rhel7-xccdf.xml``` XCCDF file (didn't check if it's included in ```ssg-fedora-xccdf.xml```).

Expected result:
---------------------
Such a remediation script IS included into the produced ```ssg-rhel7-xccdf.xml``` file.

**Comment by iankko** [comment]
@redhatrises 

Gabe, could you hopefully look at this issue and see what's happening here? (also double check the platform combination of:
```# platform = Red Hat Enterprise Linux 6, multi_platform_fedora```
would work too)

Thank you, Jan.

**Comment by redhatrises** [comment]
@iankko looking at it now.
