### ISSUE TITLE
The PCI-DSS kickstart shouldn't explicitly install openscap-scanner

### ISSUE THREAD

**Issue by vpodzime** [OpenSCAP/scap-security-guide#785]
Right now the PCI-DSS example kickstart includes this in the ``%packages`` section:

```
# Install openscap-scanner so it's possible to perform remediation once the
# installation is complete
openscap-scanner
```

This is:
1. not necessary
2. a bad example

The OSCAP Anaconda addon makes sure the ``openscap-scanner`` gets installed if any content+profile is used. In future, it may require some more packages which would make this even more confusing.

**Comment by msrubar** [comment]
I verified that the it's really not necessary.

**Comment by iankko** [comment]
@msrubar 

Michal, this looks like candidate for easy fix. Would you want to have a further look?

Thanks, Jan.
