### ISSUE TITLE
[RHEL/6] CCE-27596-6, DISA FSO RHEL-06-000275 - HTTP 404

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-security-guide#806]
CCE-27596-6, DISA FSO RHEL-06-000275. The URL is 404'ed:
https://docs.redhat.com/docs/en-US/Red_Hat_Enterprise_Linux/6/html/Security_Guide/sect-Security_Guide-LUKS_Disk_Encryption.html. Needs updating. Also, do we want to recommend a
cipher? Like aes-xts? And a key size like 256?

**Comment by iankko** [comment]
The "invalid URL" part of this one has been corrected within:
&nbsp; &nbsp; [1] https://github.com/OpenSCAP/scap-security-guide/commit/687b026bd8a60d5cf6ca5422e5817cb2f17a6554

**Comment by redhatrises** [comment]
Fixed per iankko's comment.

**Comment by iankko** [comment]
The HTTP 404 issue is fixed. But the second part: "Also, do we want to recommend a
cipher? Like aes-xts? And a key size like 256?" is not yet.

Re-opening this one.
