### ISSUE TITLE
[RHEL/6] CCE-26774-0, DISA FSO RHEL-06-000025, the check for unlabeled devices is wrong. It needs to check for device_t.

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-security-guide#811]
CCE-26774-0, DISA FSO RHEL-06-000025, the check for unlabeled devices is wrong. It needs to check for ```device_t```.

**Comment by redhatrises** [comment]
@iankko looks like in `shared/oval/selinux_all_devicefiles_labeled.xml` that `device_t` is checked for. Do you agree?

**Comment by iankko** [comment]
Correct! This has been corrected within https://github.com/OpenSCAP/scap-security-guide/commit/c3132c48ebca4e3943038ee1d7973da513ca976c Failed to close this one.

Thanks!
