### ISSUE TITLE
[RHEL/6] CCE-27550-3, DISA FSO RHEL-06-000160, are we sure 6 Mb is enough?

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-security-guide#814]
CCE-27550-3, DISA FSO RHEL-06-000160, are we sure 6 Mb is enough?

I'd think we'd be recommending much more space for logs. Is the OVAL checks for 5 or more? Or 6 and more respectively? I'd think that back on the partitioning portion we'd recommend at least 200Mb /var/log/audit and then set these numbers to match.

**Comment by shawndwells** [comment]
This is now an artifact of the C2S profile and not mapped anywhere else. We mirror CIS' recommendations on this one. Resolving.

(but no... that is likely not enough)
