### ISSUE TITLE
[RHEL/6] CCE-26242-8, DISA FSO RHEL-06-000165, The rules for time checking are weird.

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-security-guide#816]
CCE-26242-8, DISA FSO RHEL-06-000165, The rules for time checking are weird.

We need to recommend to combine the syscall rules when they have the same key and are otherwise identical. This is actually preferred.

**Comment by shawndwells** [comment]
most xccdf has been updated to show combined syscalls, while the OVAL checks for the individual syscall
