### ISSUE TITLE
[RHEL/6]  CCE-26712-0, DISA FSO RHEL-06-000197, does ftruncate make sense?

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-security-guide#820]
CCE-26712-0, DISA FSO RHEL-06-000197, does ftruncate make sense?

You would have to open a file with write. If that is successful, why would ftruncate come into play?

**Comment by redhatrises** [comment]
Closing as this using ftruncate does make sense. From an auditing perspective, being able to track who/when a file was successfully opened can be important especially if the file was not supposed to opened by the user in the first place.
