### ISSUE TITLE
[RHEL/6] CCE-26651-0, DISA FSO RHEL-06-000200, why would we recommend collecting all file deletions when we don't ask for all file creations?

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-security-guide#821]
CCE-26651-0, DISA FSO RHEL-06-000200, why would we recommend collecting all file deletions when we don't ask for all file creations?

(Not that we should do that either.) I really do not recommend this. If we are concerned about log
files, then lets put rules limited to /var/log.

**Comment by shawndwells** [comment]
we now have:
``
<select idref="audit_rules_unsuccessful_file_modification_creat" selected="true" />
<select idref="audit_rules_unsuccessful_file_modification_ftruncate" selected="true" />
<select idref="audit_rules_unsuccessful_file_modification_openat" selected="true" />
<select idref="audit_rules_unsuccessful_file_modification_open_by_handle_at" selected="true" />
<select idref="audit_rules_unsuccessful_file_modification_open" selected="true" />
<select idref="audit_rules_unsuccessful_file_modification_truncate" selected="true" />
``
