### ISSUE TITLE
[RHEL/6] CCE-26555-3, DISA FSO RHEL-06-000243, allow only approved ciphers...

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-security-guide#822]
CCE-26555-3, DISA FSO RHEL-06-000243, allow only approved ciphers...

we should sync this with FIPS140. Also, we have to add a check for MAC option as specified in FIPS Security Policy

**Comment by pcactr** [comment]
The forwarded email from Shawn (Fwd: AWS GovCloud (US) Updates for FIPS 140-2 Compliance) to the mailing list reminded me of this bug, so I am going to double-up this issue with another bugfix.

Systems that are more compliant (e.g. no 3DES ciphers, only counter-mode ciphers, and no SHA-1 usage) return false-positives:

```
[------@rhel67839 ~]$ sudo oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_common_customized --tailoring-file ssg-rhel6-ds-tailoring.xml /usr/share/xml/scap/ssg/content/ssg-rhel6-ds.xml 
Title   Use Only Approved Ciphers
Rule    xccdf_org.ssgproject.content_rule_sshd_use_approved_ciphers
Ident   CCE-26555-3
Ident   DISA FSO RHEL-06-000243
Result  fail

Title   Use Only Approved MACs
Rule    xccdf_org.ssgproject.content_rule_sshd_use_approved_macs
Result  fail
```
```
[------@rhel67839 ~]$ sudo grep -iE '^(ciphers|macs)' /etc/ssh/sshd_config 
Ciphers aes128-ctr,aes192-ctr,aes256-ctr
MACs hmac-sha2-256,hmac-sha2-512
```

Refs: NIST SP800-131A; CNSSP 15 as amended.

**Comment by shawndwells** [comment]
ciphers updated in 7bb9127f
