### ISSUE TITLE
[RHEL/6] /etc/hushlogins file needs to be created so that logins look correct

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-security-guide#825]
/etc/hushlogins file needs to be created so that logins look correct. See bz 696731  (touch  /etc/hushlogins)

**Comment by yuumasato** [comment]
There is no rule, check or fix regarding `/etc/hushlogins` in SSG. And it doesn't seem to be required in any policy.
Please, reopen if you see benefit in checking this.
