### ISSUE TITLE
Adding Debian

### ISSUE THREAD

**Issue by electrosenpai** [OpenSCAP/scap-security-guide#867]
Hi,

I would like to contribute by adding Debian in your project, but I don't know how to start. I create a local branch name "Debian_Integration".

I just want start at the begging with few test and after put as much as I can.

I have see there is lot of test in share folder , the first good step will be make a "clean" makefile that only take the share and create. To understand how it works I just look into the Fedora files and it seem pretty simple to understand the architecture of the project , but starting from scratch it's a little bit harder :-)  , if you could give me a "clean" makefile or just some help it will be wonderful !

**Comment by redhatrises** [comment]
@electrosenpai I would probably create a toplevel folder with the version that you are targeting subfolder e.g.
- `Debian/7`
- `Debian/8`

You can copy the directory structure under the `Fedora` directory from there.

> the first good step will be make a "clean" makefile

For the `Makefile`, go ahead and use the Fedora one as a starting point and modify it for Debian needs.

>  I have see there is lot of test in share folder

For any tests that work with both Debian and Red Hat, use the `share` locations. We want to element as many duplicate tests/remediations as possible unless it is required for that specific OS and/or OS version.

**Comment by iankko** [comment]
@electrosenpai 
Did I actually get it correctly you are searching for a guidance how to contribute new product into SSG?

If that's the case here is an example of a upstream commit (pretty outdated now):
&nbsp; &nbsp; [1] https://git.fedorahosted.org/cgit/scap-security-guide.git/commit/?id=b3a67cbadfa4d7574cc46bc00f3a2ae55f28bf0a

which was used to create a new ```Fedora``` product in SSG. It's pretty outdated commit already (meaning couple of paths have changed in between => you would need to modify them), but basically can provided you an idea how to create minimal SSG skeleton for the Debian products.

Should you need any other help, let me know.

Thanks, Jan.

**Comment by pthierry38** [comment]
@iankko 

That is effectively what electrosenpai and I try to do. We have duplicated the current content of the Fedora dir but your proposal seems easier. We also have updated the shared oval files to add "installed_OS_is_debian8.xml" OVAL file to add support for Debian Jessie in inventory, based on what exist for Fedora/CentOS, but also what exists in CISecurity OVALRepo, where Debian inventory are already part of the project.

It is still not functional, we will try one or two tricks (such as the one you propose) and go back to you if needed.

Thanks for your support. Phil.

**Comment by electrosenpai** [comment]
@redhatrises @iankko : we are actually working for a Debian 8 and we create the correct folder Debian/8. It took the old version of fedora (thank's for this great idea)  and I'm working on it. I'll let you know soon as I can.

Thank's for support :)

JB

**Comment by electrosenpai** [comment]
I just init the Debian 8 and i would like to push to save my work, should I push my branch (Debian_8) or you prefer I fork this repository and work on my "own "repository to let your repository clean ?

**Comment by iankko** [comment]
@electrosenpai 

The common workflow is:
* 1) You create your own fork of the official SSG repo (using the web UI),
* 2) Then create the feature branch in that forked repo (using the web UI),
* 3) (git) Clone the feature branch of that forked repo to your system,
* 4) Implement, test & commit the changes into that cloned git repo,
* 5) Push those changes into the feature branch of the forked repo,
* 6) Once all expected changes are done, you create a Pull Request against official SSG repository 

Majority of the aforementioned tasks is covered (including screenshots / images) in the Git Hub help pages / index.

Hope this helps.

**Comment by electrosenpai** [comment]
Ok , thank's

**Comment by shawndwells** [comment]
On 12/1/15 5:55 AM, Jean-Baptiste wrote:
> Ok , thank's

The SSG on GitHub primer might be useful:

https://github.com/OpenSCAP/scap-security-guide/wiki/SSG-on-GitHub-Primer

**Comment by electrosenpai** [comment]
@shawndwells thank's.

We are currently working, we took the old Fedora and apply if for Debian and it work, we test with only oval and it work !

Now I'm trying use the "new" makefile to use all the resources from the shared directory (the common test ssh, grub ...)  there is file that I should add Debian 

```
shared/transforms/combineremediations.py
```

Now my main problem is : 

```
Notification: Merged 0 remediation scripts into XML document.
[...]
Notification: Merged 0 OVAL checks into OVAL document.
[...]
```

As you can see I don't have any xml or OVAL merged, I'm working on it to know why

Can you tell me if there is other file that need to add debian too ?

**Comment by redhatrises** [comment]
> ```
> Notification: Merged 0 remediation scripts into XML document.
> [...]
> Notification: Merged 0 OVAL checks into OVAL document.
> [...]
> ```

@electrosenpai does the `make` complete successfully or with errors? 
I have seen something similar to this that is not always reproducible. Try adding `'` around the `*.xml` and `*.sh` in the `find` commands in the `make` file e.g. 

`find $(SHARED_REMEDIATIONS) $(IN)/remediations/bash -maxdepth 1 -type f -name '*.sh' -exec cp {} $(PROD_REMEDIATIONS) ';'`

**Comment by electrosenpai** [comment]
Nop :

```
/bin/sh: 1: Syntax error: Bad fd number
xsltproc -o output/guide.xml ../../shared/transforms/includelogo.xslt input/guide.xml
xsltproc -o output/ssg-debian8-shorthand.xml input/guide.xslt output/guide.xml
xmllint --format --output output/ssg-debian8-shorthand.xml output/ssg-debian8-shorthand.xml
xsltproc --stringparam ssg_version "0.1.26" -o output/unlinked-unresolved-debian8-xccdf.xml transforms/shorthand2xccdf.xslt output/ssg-debian8-shorthand.xml
oscap xccdf resolve -o output/unlinked-debian8-empty-groups-xccdf.xml output/unlinked-unresolved-debian8-xccdf.xml
../../shared/utils/unselect-empty-xccdf-groups.py --input output/unlinked-debian8-empty-groups-xccdf.xml --output output/unlinked-debian8-xccdf.xml
Unselected empty groups in 'common'.
oscap xccdf resolve -o output/unlinked-debian8-xccdf.xml output/unlinked-debian8-xccdf.xml
# Make intermediate build/debian8_remediations directory to hold final list of remediation scripts for debian8
mkdir -p build/debian8_remediations
# Search ../../shared/remediations/bash and input/remediations directories to find all product specific remediation scripts,
# which are regular files (not symlinks). Merge the final list into build/debian8_remediations directory
find ../../shared/remediations/bash input/remediations/bash -maxdepth 1 -type f -name *.sh -exec cp {} build/debian8_remediations ';'
../../shared/transforms/combineremediations.py ../../config debian8 build/debian8_remediations output/bash-remediations.xml

Notification: Merged 0 remediation scripts into XML document.
xsltproc -stringparam remediations "../output/bash-remediations.xml" -o output/unlinked-debian8-xccdf.xml transforms/xccdf-addremediations.xslt output/unlinked-debian8-xccdf.xml
xmllint --format --output output/unlinked-debian8-xccdf.xml output/unlinked-debian8-xccdf.xml
make: Dépendance circulaire content <- guide abandonnée.
# Make intermediate build/debian8_oval directory to hold final list of OVAL checks for debian8
mkdir -p build/debian8_oval
# Search ../../shared/oval and input/oval directories to find all product specific OVAL checks,
# which are regular files (not symlinks). Merge the final list into build/debian8_oval directory
find ../../shared/oval input/oval -maxdepth 1 -type f -name *.xml -exec cp {} build/debian8_oval ';'
# If openscap on the system supports OVAL-5.11 language version, include also OVAL-5.11 checks
# into final list of OVAL checks
find input/oval/oval_5.11 -maxdepth 1 -type f -name *.xml -exec cp {} build/debian8_oval ';'
# Update requested Debian OVAL version in ../../config/oval.config to be the 5.11 OVAL language version
sed -i "s/^\(debian_oval_version = \).*/\15.11/" ../../config/oval\.config
xmlwf build/debian8_oval/*.xml
../../shared/transforms/combineovals.py ../../config debian8 build/debian8_oval > output/unlinked-debian8-oval.xml

Notification: Merged 0 OVAL checks into OVAL document.
xmllint --format --output output/unlinked-debian8-oval.xml output/unlinked-debian8-oval.xml
xsltproc -o output/unlinked-debian8-xccdf-guide.xml transforms/xccdf-removeaux.xslt output/unlinked-debian8-xccdf.xml
../../shared/transforms/relabelids.py unlinked-debian8-xccdf.xml ssg
The OVAL ID does not match the XCCDF Rule ID!

  OVAL ID:       'file_permissions_etc_group'
  XCCDF Rule ID: 'rule_file_permissions_etc_group'

Both OVAL and XCCDF Rule IDs must match!
Makefile:70: recipe for target 'content' failed
make: *** [content] Error 1
```

I try the add ' but the problem still here, If you want to look I push my actual version on my fork repository and check the branch "deb_error"

**Comment by pthierry38** [comment]
J’ai corrigé ça aussi ☺ mais j’avais pas cette erreur, ça veut dire qu’il doit me manquer une ligne ds mon makefile

Philippe Thierry - PhD
SIX/DT/TAI/ROCS
Cristal – 4 ave des Louvresses
92622 Gennevilliers Cedex
Tel : 01 41 30 30 53

De : Jean-Baptiste [mailto:notifications@github.com]
Envoyé : jeudi 3 décembre 2015 16:03
À : OpenSCAP/scap-security-guide
Cc : THIERRY Philippe
Objet : Re: [scap-security-guide] Adding Debian (#867)


Nop :

/bin/sh: 1: Syntax error: Bad fd number

xsltproc -o output/guide.xml ../../shared/transforms/includelogo.xslt input/guide.xml

xsltproc -o output/ssg-debian8-shorthand.xml input/guide.xslt output/guide.xml

xmllint --format --output output/ssg-debian8-shorthand.xml output/ssg-debian8-shorthand.xml

xsltproc --stringparam ssg_version "0.1.26" -o output/unlinked-unresolved-debian8-xccdf.xml transforms/shorthand2xccdf.xslt output/ssg-debian8-shorthand.xml

oscap xccdf resolve -o output/unlinked-debian8-empty-groups-xccdf.xml output/unlinked-unresolved-debian8-xccdf.xml

../../shared/utils/unselect-empty-xccdf-groups.py --input output/unlinked-debian8-empty-groups-xccdf.xml --output output/unlinked-debian8-xccdf.xml

Unselected empty groups in 'common'.

oscap xccdf resolve -o output/unlinked-debian8-xccdf.xml output/unlinked-debian8-xccdf.xml

# Make intermediate build/debian8_remediations directory to hold final list of remediation scripts for debian8

mkdir -p build/debian8_remediations

# Search ../../shared/remediations/bash and input/remediations directories to find all product specific remediation scripts,

# which are regular files (not symlinks). Merge the final list into build/debian8_remediations directory

find ../../shared/remediations/bash input/remediations/bash -maxdepth 1 -type f -name *.sh -exec cp {} build/debian8_remediations ';'

../../shared/transforms/combineremediations.py ../../config debian8 build/debian8_remediations output/bash-remediations.xml



Notification: Merged 0 remediation scripts into XML document.

xsltproc -stringparam remediations "../output/bash-remediations.xml" -o output/unlinked-debian8-xccdf.xml transforms/xccdf-addremediations.xslt output/unlinked-debian8-xccdf.xml

xmllint --format --output output/unlinked-debian8-xccdf.xml output/unlinked-debian8-xccdf.xml

make: Dépendance circulaire content <- guide abandonnée.

# Make intermediate build/debian8_oval directory to hold final list of OVAL checks for debian8

mkdir -p build/debian8_oval

# Search ../../shared/oval and input/oval directories to find all product specific OVAL checks,

# which are regular files (not symlinks). Merge the final list into build/debian8_oval directory

find ../../shared/oval input/oval -maxdepth 1 -type f -name *.xml -exec cp {} build/debian8_oval ';'

# If openscap on the system supports OVAL-5.11 language version, include also OVAL-5.11 checks

# into final list of OVAL checks

find input/oval/oval_5.11 -maxdepth 1 -type f -name *.xml -exec cp {} build/debian8_oval ';'

# Update requested Debian OVAL version in ../../config/oval.config to be the 5.11 OVAL language version

sed -i "s/^\(debian_oval_version = \).*/\15.11/" ../../config/oval\.config

xmlwf build/debian8_oval/*.xml

../../shared/transforms/combineovals.py ../../config debian8 build/debian8_oval > output/unlinked-debian8-oval.xml



Notification: Merged 0 OVAL checks into OVAL document.

xmllint --format --output output/unlinked-debian8-oval.xml output/unlinked-debian8-oval.xml

xsltproc -o output/unlinked-debian8-xccdf-guide.xml transforms/xccdf-removeaux.xslt output/unlinked-debian8-xccdf.xml

../../shared/transforms/relabelids.py unlinked-debian8-xccdf.xml ssg

The OVAL ID does not match the XCCDF Rule ID!



  OVAL ID:       'file_permissions_etc_group'

  XCCDF Rule ID: 'rule_file_permissions_etc_group'



Both OVAL and XCCDF Rule IDs must match!

Makefile:70: recipe for target 'content' failed

make: *** [content] Error 1

I try the add ' but the problem still here, If you want to look I push my actual version on my fork repository and check the branch "deb_error"

**Comment by electrosenpai** [comment]
thank's @pthierry38 

The error was simple : "rule_" in system.xml , software.xml and common.xml :)

But i still have 0 merge on both

**Comment by redhatrises** [comment]
@electrosenpai looks like some folders are missing or are in the incorrect places. For example:

- `Debian/8/input/remediations/bash` is missing
- `Debian/8/input/checks` should be `Debian/8/input/oval`
- `Debian/8/input/system` should be a directory under `Debian/8/input/xccdf` so `Debian/8/input/xccdf/system`

**Comment by iankko** [comment]
@electrosenpai 

Here's the patch to get the ```Debian/8``` content from:
&nbsp; &nbsp; https://github.com/electrosenpai/scap-security-guide

building properly.
[0001-Enhancement-Debian-8-Various-changes-to-get-the-Debi.txt](https://github.com/OpenSCAP/scap-security-guide/files/51097/0001-Enhancement-Debian-8-Various-changes-to-get-the-Debi.txt)

To get it applied (on top of the ```Debian/8``` branch from:
&nbsp; &nbsp; [1] https://github.com/electrosenpai/scap-security-guide

Perform the following:
```
mv 0001-Enhancement-Debian-8-Various-changes-to-get-the-Debi.txt 0001-Enhancement-Debian-8-Various-changes-to-get-the-Debi.patch
```
(needed to change the suffix of the file GitHub workflow to allow me to include it into this comment). Then apply it like (in the CWD of cloned ```Debian/8``` branch of that fork):
```
$ pwd
../scap-security-guide
$ git am folder_containing/ 0001-Enhancement-Debian-8-Various-changes-to-get-the-Debi.patch
```

This change should get that content into the state, when calling:
```make``` in ```Debian/8``` folder will succeed (return 0) [didn't actually check if those OVAL checks are actually checking something).

HTH, Jan.

P.S.: Note for myself -- we really need to add set of tools that will simplify adding of a new product to SSG.

**Comment by electrosenpai** [comment]
I patch and push on Debian_8 , now we have:

```
Notification: Merged 9 OVAL checks into OVAL document.
```

Sounds good , only left to link the shared directory and it will be perfect !

**Comment by iankko** [comment]
Good. If you want to link the ```shared/``` directory too, be sure to modify the ```Makefile``` to include also checks from the ```shared``` directory (IOW have a look at some other product how ```make checks``` are implemented now). The situation (directories layout) has changed a bit since I have created that Fedora product patch.

Also, be sure to provide correct relative path to the ```shared/``` directory (IIRC from testing yesterday it was something like ```../../shared``` due to having two subdirs in the product).

**Comment by electrosenpai** [comment]
Yep , I take as example the RHEL 7 Makefile and now my build/ countain all the .xml from shared/ but they don't get merge, I'm working on it

**Comment by electrosenpai** [comment]
Debian integration #897 

Thank's for your support :)
