### ISSUE TITLE
[Enhancement]  Port C2S profile from RHEL-6 to RHEL-7

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-security-guide#869]
From C2S profile specification:

```
$ cat RHEL/6/input/profiles/C2S.xml | head -13
<Profile id="C2S">
<title>C2S for Red Hat Enterprise Linux 6</title>
<description>This profile demonstrates compliance against the 
U.S. Government Commercial Cloud Services (C2S) baseline.

This baseline was inspired by the Center for Internet Security
(CIS) Red Hat Enterprise Linux 6 Benchmark, v1.2.0 - 06-25-2013.
For the SCAP Security Guide project to remain in compliance with
CIS' terms and conditions, specifically Restrictions(8), note 
there is no representation or claim that the C2S profile will
ensure a system is in compliance or consistency with the CIS
baseline. 
</description>
```

We need to have this profile ported / available also to ```RHEL/7``` product.

**Comment by shawndwells** [comment]
Working on an initial commit now:
https://github.com/shawndwells/scap-security-guide/tree/rhel7cis

**Comment by shawndwells** [comment]
PR https://github.com/OpenSCAP/scap-security-guide/pull/880 submitted

**Comment by iankko** [comment]
Thanks. Will check that one.

**Comment by isimluk** [comment]
#880 has been merged, so this is perhaps fixed?

**Comment by iankko** [comment]
@isimluk 
> #880 has been merged, so this is perhaps fixed?

Correct catch (```C2S``` profile is available upstream for ```RHEL/7``` product already) => initial port is done. There are couple of rules to be implemented yet (see all those commented out sections, but those are enhancements for the future stage -- to be tracked under different ticket to be opened shortly).

Closing this one.
