### ISSUE TITLE
Confusing templates infrastructure

### ISSUE THREAD

**Issue by mmsrubar** [OpenSCAP/scap-security-guide#873]
When I was trying to add a new template I didn't know where exactly put it and which `makefile` should I modified. There are `product/input/oval/templates` and `product/input/remediations/bash/templates` which should contain oval and remediation templates but content of those folders is mixed up. For example in `RHEL/7/input/oval/templates` there are templates like `template_BASH_package_installed` which should be in the `RHEL/7/input/remediations/bash/templates` dir.

After a discussion with @iankko we propose to introduce a new forder **templates** in `product/input/`. The structure of the templates directory could look like:
`procudct/input/templates/oval/ - oval templates`
`procudct/input/templates/oval/remediations/ -  remediations templates`
`procudct/input/templates/oval/Makefile`

This is just an idea for now. I'll take a look at it and I opened this issue for discussion and your ideas.

**Comment by shawndwells** [comment]
this has been done. resolving.
