### ISSUE TITLE
Reference ID urls point to the project Contributors page

### ISSUE THREAD

**Issue by pkbarbiedoll** [OpenSCAP/scap-security-guide#886]
On a fresh RHEL 7 system with OpenSCAP 1.2.5, the report output contains links to references as expected, but every link points to the same definition reference url (the project Contributors page).    

Ex: 

`<a class="Hover" target="_blank" href="https://github.com/OpenSCAP/scap-security-guide/wiki/Contributors">RHEL6_20141130</a>`

Command used to generate report: 

`# oscap oval eval --report scan-oval-report.html --results scan-oval-results.xml /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml`

Version: 

> OpenSCAP command line tool (oscap) 1.2.5

**Expected behavior:**
Reference ID url points to documentation explaining the definition ID.

**Comment by iankko** [comment]
Hello, thank you for your report.

The example you quoted:
```
<a class="Hover" target="_blank" href="https://github.com/OpenSCAP/scap-security-guide/wiki
/Contributors">RHEL6_20141130</a>
```

Is there to say that particular rule has been verified to be working on Red Hat Enterprise Linux 6 system on November the 30-th 2014.

Can you clarify further, what you mean under:
> <b>Expected behavior:</b>
Reference ID url points to documentation explaining the definition ID. 

What kind of explanation of definition ID you are missing currently?

Thank you && Regards, Jan.

**Comment by pkbarbiedoll** [comment]
Thanks for the prompt response and explanation of the link anchor text (ie, RHEL6_20141130).  

In an older report generated by oscap, each row anchored the rule to a full description included at the bottom of the report.    (unfortunately I don't have details of the oscap version or arguments passed to generate the report)

In the report generated on the current oscap version at the top of this post ( `oscap oval eval --report scan-oval-report.html --results scan-oval-results.xml /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml` ), the descriptions were not included in the html output.

Is there a way of configuring `--report` to include descriptions found in the ssg*.xml files?  

Many thanks, 
pkbarbiedoll

**Comment by redhatrises** [comment]
This looks to have been fixed. Please re-open if not.
