### ISSUE TITLE
[Enhancement] [RHEL/6] Provide a granular PCI DSS mapping for RHEL-6 product

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-security-guide#892]
Same request for granular PCI DSS ID mapping like for `RHEL/7` product, but now for RHEL-6.

Giving to Zbynek (since he already has experience with that).

Thanks, Jan.

**Comment by mpreisler** [comment]
Is this ticket about the PCI-DSS centered benchmark? Can you provide more details?

**Comment by iankko** [comment]
Hi Martin,

  at the time this ticket was filed the situation was as follows (there have been granular PCI-DSS mapping available for RHEL-7 rules, but not for RHEL-6 product).

Granular = not just mapping to e.g. PCI DSS rule #11, but e.g. to rule #11, section 2, subsection 3 etc.
AFAIK this was done solely on RHEL-7 (just RHEL-7 rules got the related "pci_dss" attribute into the corresponding elements) till the moment, how we settle down / agree on the way how the final PCI-DSS referencing should look like (e.g. referencing subsections instead of main rules, regenerating PCI-DSS benchmark layout etc.).

Not sure if in current ```master``` the RHEL-6 PCI-DSS rules have been equipped with the PCI-DSS links already (basically AFAICT it should be 1:1 mapping to RHEL-7 ones, where same rule exists).

If this adding of attributes wasn't performed yet, this ticket is still valid.

Thanks, Jan
