### ISSUE TITLE
[Enhancement] [RHEL/6] Provide PCI DSS kickstart for RHEL-6

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-security-guide#893]
Currently for ```RHEL/6``` product we are shipping couple of kickstart files to install a compliant system / get a compliant system right after first boot / login.

Status quo:
```
$ tree -L 1 RHEL/6/kickstart/
RHEL/6/kickstart/
├── ssg-rhel6-stig-ks.cfg
└── ssg-rhel6-usgcb-server-with-gui-ks.cfg

0 directories, 2 files
```

As can be seen above we are currently missing ```RHEL/6``` kickstart for the PCI DSS profile yet.

Michal, could you hopefully have a look at this one? (the format of that file would be similar like in already existing ones, you would just change the profile id the final installed system would be remediated against).

Should you have further questions (encounter some issues), just ask.

Thank you, Jan.

**Comment by msrubar** [comment]
Yes, I'll take a look at it.

**Comment by iankko** [comment]
Thanks! Much appreciated.
