### ISSUE TITLE
Cleanup OVAL tempaltes

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#911]
At some point, we should cleanup the OVAL template generation:

- Duplicate files between RHEL6/7/shared (e.g. package_removed)
- Document the various template directories (oval/templates, oval/oval_5.11/templates, etc)

**Comment by msrubar** [comment]
I actually have this in my TODO and already discuss this with @iankko.

Also see: https://github.com/OpenSCAP/scap-security-guide/issues/873

**Comment by shawndwells** [comment]
thanks @msrubar! Closing this issue.
