### ISSUE TITLE
XCCDF values associated with "sysctl_net_ipv4_conf_*" not used.

### ISSUE THREAD

**Issue by GautamSatish** [OpenSCAP/scap-security-guide#932]
Some of the OVAL checks and remediation scripts for network-kernel parameters seem to ignore the XCCDF input variable. For example, the rule "sysctl_net_ipv4_conf_all_accept_source_route" has an associated XCCDF variable "sysctl_net_ipv4_conf_all_accept_source_route_value" which it seems to be passing to the OVAL check:

    <oval id="sysctl_net_ipv4_conf_all_accept_source_route" value="sysctl_net_ipv4_conf_all_accept_source_route_value" />

However, the OVAL check and remediation script seem to be ignoring it:

      <unix:sysctl_state id="state_runtime_net_ipv4_conf_all_accept_source_route" version="1">
        <unix:value datatype="int" operation="equals">0</unix:value>
      </unix:sysctl_state>

Fix: 
    /sbin/sysctl -q -n -w net.ipv4.conf.all.accept_source_route=0

**Comment by GautamSatish** [comment]
I had discussed this issue in the mailing list and would like to work on it. Please assign this to me. Thank you!

**Comment by shawndwells** [comment]
Hi @GautamSatish, invited you to the SSG Community group, which will give you rights to assign tickets to yourself once you accept. Thanks for taking this on -- let us know how we can help!

**Comment by GautamSatish** [comment]
All code changes are complete. Closing this issue. Thanking everyone for all the support!
