### ISSUE TITLE
[Wiki / Doc] Document the expected test expectations when making a PR

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-security-guide#937]
See:
&nbsp; &nbsp; [1] https://github.com/OpenSCAP/scap-security-guide/pull/936#issuecomment-164729612
and

&nbsp; &nbsp; [2] https://github.com/OpenSCAP/scap-security-guide/pull/936#issuecomment-164731215

for details. For now it's enough the PR to pass the expectations to pass the conditions expressed in [2]. As more products will get `make validate` target passing, we will add them to these expectations (maybe we could even add `Debian/8` now already?)

**Comment by iankko** [comment]
Easy fix. Giving to Michal to have a look.

**Comment by mpreisler** [comment]
Isn't it just `make jenkins` since #921 ?

**Comment by isimluk** [comment]
Indeed. The jenkins bot should just run
```
make jenkins
mkdir install_test
make DESTDIR=`pwd`/install_test install
```

I think having the `make jenkins` requirement is enough for the contribution.

**Comment by isimluk** [comment]
I mean, the `make install` can still fail, however chances of `make jenkins` passing and `make install` failing are fairly low.

**Comment by iankko** [comment]
> I think having the make jenkins requirement is enough for the contribution.

Correct me if wrong, but ```make jenkins``` checks the content builds && validates. But doesn't actually test the corrected feature is working. I agree that ```make jenkins``` is a shorthand for running those ```make validates``` manually.

But wouldn't like to set the expectations the way if content builds && validates, it's OK to push it (since the issue in question described like fixed might not be fixed at all).

**Comment by isimluk** [comment]
Ah, agreed.

The `test expectations` should be to
* run `make jenkins`
* test the newly contributed feature (something else for remediation, something else for the oval...)

**Comment by mpreisler** [comment]
Mentioned Jenkins and `make validate` on https://github.com/OpenSCAP/scap-security-guide/wiki/SSG-on-GitHub-Primer

**Comment by mpreisler** [comment]
Mentioned that automated testing cannot catch logic issues in OVAL or remediations https://github.com/OpenSCAP/scap-security-guide/wiki/SSG-on-GitHub-Primer
