### ISSUE TITLE
Add support for shared XCCDF rules

### ISSUE THREAD

**Issue by pthierry38** [OpenSCAP/scap-security-guide#942]
I've seen that there is a lot of duplicated content in xccdf files between RHEL, Fedora & now Debian, mostly for shared oval files.
oval id, descriptions and rationales are the same, and the only difference is the ref and test part, depending on the distro.
Is there a way to share a some of the xccdf content in shared/xccdf for shared/oval files to avoid too much duplication, using for example <xi:include > to add shared content ?
The goal is to reduce the cost of xccdf writing for shared oval. Maybe the usage of a variable would help for differenciate the ref and test part of each rule.

What do you think of that idea ?

**Comment by redhatrises** [comment]
I like the idea and have thought of it myself. I just wonder if it would be too confusing. Also, the `cce` identifiers are for specific OS and that adds complexity to this as the `cce` for rhel7 does not apply to debain.

**Comment by pthierry38** [comment]
Yes it was the difficulty of sharing rules content. Globally, ident (and refs ?) diverge.
Maybe something like : 
```xml
<rule id="shared_oval_id">
    <xi:include href="../../../shared/xccdf/shared_oval_id.xml"/>
    <ident cce="cce_id"/>
    <ref disa="disa_ref" cis="cis_ref"/>
</rule>
```
would be easier than integrating the whole rule block in the shared file. This leaves the ident and ref usage back to the distribution but keep the title, rationale, oval inclusion and ocil shared (I'm not sure that last one can always be shared, but maybe for multi_platform_all oval files it can).

**Comment by radzy** [comment]
I'm in favor.  The current situation is very confusing as-is.  I doubt that it will be more confusing to have shared rule contents as discussed here than the way things are without this change.

**Comment by radzy** [comment]
A simple-minded way to share files might be with direct inclusion, without xi:include : 

diff --git a/Fedora/input/xccdf/system/permissions/files.xml b/Fedora/input/xccdf/system/permissions/files.xml
index b08922752a67..a49247daa5a7 100644
--- a/Fedora/input/xccdf/system/permissions/files.xml
+++ b/Fedora/input/xccdf/system/permissions/files.xml
@@ -159,39 +159,8 @@ configured correctly and restrictively.
 </description>
 
 <Rule id="file_permissions_library_dirs" severity="medium">
-<title>Verify that Shared Library Files Have Restrictive Permissions</title>
-<description>System-wide shared library files, which are linked to executables
-during process load time or run time, are stored in the following directories
-by default:
-<pre>/lib
-/lib64
-/usr/lib
-/usr/lib64
-</pre>
-Kernel modules, which can be added to the kernel during runtime, are
-stored in <tt>/lib/modules</tt>. All files in these directories
-should not be group-writable or world-writable. If any file in these
-directories is found to be group-writable or world-writable, correct
-its permission with the following command:
-<pre>$ sudo chmod go-w <i>FILE</i></pre>
-</description>
-<ocil clause="any of these files are group-writable or world-writable">
-Shared libraries are stored in the following directories:
-<pre>/lib
-/lib64
-/usr/lib
-/usr/lib64
-</pre>
-To find shared libraries that are group-writable or world-writable,
-run the following command for each directory <i>DIR</i> which contains shared libraries:
-<pre>$ sudo find -L <i>DIR</i> -perm /022 -type f</pre>
-</ocil>
-<rationale>Files from shared library directories are loaded into the address
-space of processes (including privileged ones) or of the kernel itself at
-runtime. Restrictive permissions are necessary to protect the integrity of the system.
-</rationale>
-<ref nist="AC-6" disa=""/>
-<oval id="file_permissions_library_dirs" />
+  &../../../../../shared/xccdf/system/file_permissions_library_dirs.xmlfragment"
+  <ref nist="AC-6" disa=""/>
 </Rule>
 
 <Rule id="file_ownership_library_dirs" severity="medium">
diff --git a/shared/xccdf/system/file_permissions_library_dirs.xmlfragment b/shared/xccdf/system/file_permissions_library_dirs.xmlfragment
new file mode 100644
index 000000000000..25e30486edbb
--- /dev/null
+++ b/shared/xccdf/system/file_permissions_library_dirs.xmlfragment
@@ -0,0 +1,32 @@
+<title>Verify that Shared Library Files Have Restrictive Permissions</title>
+<description>System-wide shared library files, which are linked to executables
+during process load time or run time, are stored in the following directories
+by default:
+<pre>/lib
+/lib64
+/usr/lib
+/usr/lib64
+</pre>
+Kernel modules, which can be added to the kernel during runtime, are
+stored in <tt>/lib/modules</tt>. All files in these directories
+should not be group-writable or world-writable. If any file in these
+directories is found to be group-writable or world-writable, correct
+its permission with the following command:
+<pre>$ sudo chmod go-w <i>FILE</i></pre>
+</description>
+<ocil clause="any of these files are group-writable or world-writable">
+Shared libraries are stored in the following directories:
+<pre>/lib
+/lib64
+/usr/lib
+/usr/lib64
+</pre>
+To find shared libraries that are group-writable or world-writable,
+run the following command for each directory <i>DIR</i> which contains shared libraries:
+<pre>$ sudo find -L <i>DIR</i> -perm /022 -type f</pre>
+</ocil>
+<rationale>Files from shared library directories are loaded into the address
+space of processes (including privileged ones) or of the kernel itself at
+runtime. Restrictive permissions are necessary to protect the integrity of the system.
+</rationale>
+<oval id="file_permissions_library_dirs" />
-- 
1.9.1

**Comment by redhatrises** [comment]
Taking this one and self-assigning.

**Comment by shawndwells** [comment]
Considering this resolved @redhatrises @PThierry
