### ISSUE TITLE
RHEL7 (ssg-0.1.25) missing docs

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#958]
Current RPM is only shipping limited set of HTML tables:

$ pwd
/usr/share/doc/scap-security-guide-0.1.25
[shawnw@devbox-rhel7 scap-security-guide-0.1.25]$ ls -l
total 3032
-rw-r--r--. 1 root root   1028 Aug 19 11:54 DISCLAIMER
-rw-r--r--. 1 root root   1597 Aug 19 11:54 LICENSE
-rw-r--r--. 1 root root 194552 Oct  2 06:17 table-rhel6-cces.html
-rw-r--r--. 1 root root 133483 Oct  2 06:17 table-rhel6-nistrefs-common.html
-rw-r--r--. 1 root root 569920 Oct  2 06:17 table-rhel6-nistrefs.html
-rw-r--r--. 1 root root 590432 Oct  2 06:17 table-rhel6-srgmap-flat.html
-rw-r--r--. 1 root root 590269 Oct  2 06:17 table-rhel6-srgmap-flat.xhtml
-rw-r--r--. 1 root root 379696 Oct  2 06:17 table-rhel6-srgmap.html
-rw-r--r--. 1 root root 406368 Oct  2 06:17 table-rhel6-stig.html
-rw-r--r--. 1 root root 212941 Oct  2 06:17 table-rhel7-cces.html

Need to update RPM to ship full HTML tables for RHEL7

**Comment by shawndwells** [comment]
@mpreisler believe the cmake system now takes care of this. can you confirm?

**Comment by mpreisler** [comment]
@shawndwells yes, cmake will install all tables.
