### ISSUE TITLE
CentOS 7 ssg kickstart.

### ISSUE THREAD

**Issue by darrynza** [OpenSCAP/scap-security-guide#963]
does the latest version with the working CentOS 7  work with kickstart ?

**Comment by iankko** [comment]
@darrynza 
> does the latest version with the working CentOS 7 work with kickstart ?

Can you clarify what you understand under 'latest version'? Current 'master' git content or SSG-0.1.27 release?

Also, can you elaborate on the issue you are experiencing?

Thank you && Regards, Jan.

**Comment by redhatrises** [comment]
Closing as no clarification has been provided as requested. Please re-open if needed.
