### ISSUE TITLE
auditd.conf action ignore case, but the rule check with case

### ISSUE THREAD

**Issue by moriwaka** [OpenSCAP/scap-security-guide#982]
environment: Fedora 23, RHEL7

I have /etc/audit/auditd.conf with UPPER CASE actions like following. auditd actions ignore case. 

space_left_action = SYSLOG
admin_space_left_action = SUSPEND

These lines are detected as violation with rules:
xccdf_org.ssgproject.content_rule_auditd_data_retention_space_left_action
xccdf_org.ssgproject.content_rule_auditd_data_retention_admin_space_left_action

Prease update rules to ignore action's case.
Thanks,

**Comment by redhatrises** [comment]
Tested with the latest SSG release. This has already been fixed.
